### ISSUE TITLE
Group Member adding problem

### ISSUE THREAD

**Issue by Nisutec** [mumble-voip/mumble#4453] opened 2020-09-03 19:00 UTC
**Describe the bug**
When I try to add a new user to a group, I can’t use the user search bar at the bottom of the user list the text input is too small. When I make the window bigger the search bar has the same size. It is not possible to make it bigger.

**Steps to Reproduce**
1. Click on "Root" and open the "edit" window
2. Go to the "Group" tab
3. Select a group
4. Try to add a user to the group
5. See the problem

**Expected behavior**
A user search bar that I can normally use to add users to groups. At the moment it is unusable.

**Screenshots**
![problem](https://p52.p0.n0.cdn.getcloudapp.com/items/8LuPl2Dr/Image%202020-09-03%20at%208.39.27%20PM.png?source=viewer&v=dddf6b55047541f7679253e9a7115575)

**Desktop (please complete the following information):**
- OS: WIndows 10
- Screen Resolution: 3840x2160
- Version: Mumble 1.3.2
- Software Language: German

**Comment by Krzmbrzl** [comment] 2020-09-04 06:47
I am running current master (more or less; aka 1.4.0) on KDE Neon (Linux) on 1920x1080 and this is how it looks for me:
![image](https://user-images.githubusercontent.com/12751591/92208265-219ca400-ee8b-11ea-8252-8b8c5cb81727.png)

Could you try to temporarily decrease your screen's resolution to 1920x1080 (or something in that region) to check whether the issue is related to the high resolution, please?

**Comment by Krzmbrzl** [comment] 2020-09-04 08:04
Now that I have put some more thought into this, I don't think that the screen resolution has something to do with this. I think the problem is that the UI as a whole as a totally weird grow-behavior (the left 2 parts not really growing at all).
And since you're using the German locale, the add-buttons take a lot more space (since `Hinzufügen` has a lot more characters than `Add`) and thereby shrinking the ComboBoxes to an unusable size.

In order to verify this, could you please switch Mumble's language to English, restart it and then check whether the fields are still rendered so tiny?

**Comment by Nisutec** [comment] 2020-09-04 11:36
When I change the language to English and open the group tab it looks like this.
![group 1](https://p52.p0.n0.cdn.getcloudapp.com/items/2Nuy9zZ8/Image%202020-09-04%20at%201.30.09%20PM.png?source=viewer&v=08aef13fff821edfba2917027259a072)

But when I resize the window only the right column will be increased.
![group 2](https://p52.p0.n0.cdn.getcloudapp.com/items/YEuoJr01/Image%202020-09-04%20at%201.29.42%20PM.png?source=viewer&v=9e01b07ffb843bf62d1302789af2368d)

**Comment by Krzmbrzl** [comment] 2020-09-04 14:18
Alright - the resize issue is fixed with #4455 and once that's in I think that it should be easy enough for you to resize the window to your needs :)

**Closed** 2020-09-04 14:20 UTC
Labels: bug, client, ui

**Comment by Nisutec** [comment] 2020-09-04 16:27
@Krzmbrzl Thank you for the fast help

**Comment by Krzmbrzl** [comment] 2020-09-04 16:30
You're welcome. The fix will be rolled out with 1.3.3 which shouldn't take too long from now to be released. Therefore you should be able to benefit from it (somewhat) soon :)
