### ISSUE TITLE
Mumble-server immediately crashes when launched

### ISSUE THREAD

**Issue by FireZtreaM** [mumble-voip/mumble#6617] opened 2024-10-25 03:02 UTC
### Description

I'm running Arch Linux ARM on my Raspberry Pi 2. It just keeps crashing and when run manually I'm getting an error message that I don't know what to do with. I've tried reinstalling Arch Linux, but I'm getting the same problem even on a fresh install.

### Steps to reproduce

1. Run "sudo systemctl start mumble-server"
2. Watch it crash over and over again

Alternativly

1. Run "sudo -u _mumble-server /usr/bin/mumble-server -ini /etc/mumble/mumble-server.ini" to start the server manually
2. Watch it crash immediately

### Mumble version

1.5.634

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Relevant log output

```shell
sudo -u _mumble-server /usr/bin/mumble-server -ini /etc/mumble/mumble-server.ini
<W>2024-10-24 20:18:13.195 ServerDB: Opened SQLite database /var/lib/mumble-server/mumble-server.sqlite
<W>2024-10-24 20:18:13.195 ServerDB: Using SQLite's default rollback journal.
<W>2024-10-24 20:18:13.209 MumbleServerIce: Endpoint "tcp -h 127.0.0.1 -p 6502 -t 60000" running
<W>2024-10-24 20:18:13.210 Murmur 1.5.634 running on Linux: Arch Linux ARM [arm]: Booting servers
mumble-server: /build/mumble/src/mumble-1.5.634/src/MumbleProtocol.cpp:375: void Mumble::Protocol::UDPAudioEncoder<role>::preparePreEncodedSnippets() [with Mumble::Protocol::Role role = Mumble::Protocol::Role::Server]: Assertion `successful' failed.
Aborted
```

**Comment by Krzmbrzl** [comment] 2024-10-25 11:47
Duplicate of #6202

**Closed** 2024-10-25 11:47 UTC
Labels: bug, triage
