### ISSUE TITLE
pulseaudio: close Mic/Input sink on mute+deafen // Headphones bluetooth profile switching

### ISSUE THREAD

**Issue by afics** [mumble-voip/mumble#5379] opened 2021-12-21 08:59 UTC
### Context

To my knowledge this only applies to Linux systems that use pulseaudio or pipewire.

### Description

Close Mic/Input sink on mute+deafen so headphones connected via bluetooth can switch from their input+output profile to the higher quality output only profile.

### Mumble component

Client

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment] 2021-12-21 09:29
Duplicate of #5314 (which itself was closed as being redundant/duplicate - see https://github.com/mumble-voip/mumble/issues/5314#issuecomment-966064031)

**Closed by Krzmbrzl** 2021-12-21 09:29 UTC
Labels: feature-request, triage

**Comment by afics** [comment] 2021-12-21 09:35
@Krzmbrzl which of the issues mentioned in #5314 is supposed to include my request? just asking so I can watch the issue.

**Comment by Krzmbrzl** [comment] 2021-12-21 10:11
We currently use #1089 to track the general "stop using the mic once muted/deafened" thing. While the issue itself is not a duplicate of this one (topic-wise), the underlying requirements are almost the same and thus it isn't really worth it to have two separate issues imo.

However, I guess we could create a new one that combines your request with the already open ones :thinking: 
Thoughts?

**Comment by afics** [comment] 2021-12-22 09:04
> However, I guess we could create a new one that combines your request with the already open ones thinking
> Thoughts?

Maybe a pinned summary issue, something like "Audio Architecture Rewrite" could be created which is a parent to all subtasks?
I think it would be good if it mentions all points it addresses (like this pulseaudio sink closing thing), even if there are no sub-issues for them, just so it does not get asked over and over again.

**Comment by Krzmbrzl** [comment] 2022-01-08 09:08
Good point -  see https://github.com/mumble-voip/mumble/issues/5408
