### ISSUE TITLE
Link all settings per user name

### ISSUE THREAD

**Issue by pierremestrez1976** [mumble-voip/mumble#4134] opened 2020-05-05 18:42 UTC
**Context**
When using "-m" option to run multiple client per OS.

**Describe the feature you have in mind**
Being able to store all settings (Registry in windows) per user name

This allows audio drivers, shortcuts etc... to be set by user & per mumble instance

Thanks in advance

**Comment by Krzmbrzl** [comment] 2020-05-06 05:24
I think this is an duplicate of #1613 and/or #1292

**Closed by Krzmbrzl** 2020-05-06 05:24 UTC
