### ISSUE TITLE
Push-to-talk getting stuck down since 1.4

### ISSUE THREAD

**Issue by lukefor** [mumble-voip/mumble#5758] opened 2022-07-23 20:58 UTC
### Description

Within my friend group of Mumble users, everyone that has updated to 1.4 is affected with a bug where 1-10% of PTT activations result in PTT getting 'stuck down'. Specifically, mic remains on even though button is not being physically pressed (cue embarrassment), and turns off when button is next pressed and released.

We all use a side mouse button for PTT (mouse 4/5) on 1000hz polling gaming mice. All on Windows 10 x64. DoublePush Time disabled. Never experienced anything like this on previous 1.2.x or 1.3.x versions

As an aside, we all sorely miss the Suppress hotkey option https://github.com/mumble-voip/mumble/issues/5472 - if there is a chance the old hotkey code would also resolve this issue then would be fantastic to have an option to switch back to it

### Steps to reproduce

Update to 1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment] 2022-07-24 07:55
The shortcut system on Windows has been completely rewritten as the old API caused massive issues with decreasing polling rates or something like that.
The new API foes not have this issue but unfortunately doesn't support suppressing key events anymore. So no, there is no chance to get this feature back unless you can convince Microsoft to somehow add this feature to that particular API.

As for the problem at hand, I am 90% sure that this is a duplicate of #5706 which just recently got fixed via #5739.
Thus, the next release should fix this issue.

**Closed by Krzmbrzl** 2022-07-24 07:55 UTC
Labels: bug, triage

**Comment by lukefor** [comment] 2022-07-24 10:13
That is great news! It does sound like it may be the cause, anecdotally have noticed the issue happens more often while in-game (lots of other clicking going on)
