### ISSUE TITLE
Unable to 'Send Message' to Users/Channels

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#994] opened 2013-06-06 06:52 UTC
When selecting a user or channel name in the currently active server, you are unable to type a message to any individual or channel using the text input bar. Users still on 1.2.3 connected to the same server do not have the same issue, and are free to text message whomever they wish or whatever channel they wish. 

The only way to get around this issue is to right-click a user or channel and use the "Send Message" function. 

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/994/ ._

**Comment by davidebeatrici** [comment] 2018-07-17 05:40
#3465

**Comment by Hartmnt** [comment] 2023-01-31 17:40
I think this was either fixed by #5917 or not a bug after all in case OP just forgot to enable the “Use selected item as chat bar target” (Hard to tell because the usernames are missing). Anyway, if I somehow missed something here feel free to comment.

**Closed by Hartmnt** 2023-01-31 17:40 UTC
Labels: client, bug
