### ISSUE TITLE
Suppress shortcut no longer available

### ISSUE THREAD

**Issue by FlyveHest** [mumble-voip/mumble#5529] opened 2022-01-27 13:28 UTC
### Description

After upgrading, I noticed that using my PTT key, which is mouse-key-5, results in odd behaviour depending on which window is active at the time of clicking. (Mouse key is bound to normal functionality in driver)

For instance, clicking over the client window makes channels move about.

I can't find anything in the changelog about this feature being removed.

### Steps to reproduce

1. Create new shortcut
2. `Suppress` column is missing

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment] 2022-01-27 13:58
Duplicate of https://github.com/mumble-voip/mumble/issues/5472

**Closed by Krzmbrzl** 2022-01-27 13:58 UTC
Labels: bug, triage
