### ISSUE TITLE
New icons problem.

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#3504] opened 2018-08-26 16:49 UTC
These new icons have one problem which didn't exist with the old ones: when you mute or deafen yourself, the icon in the system tray doesn't look identifiable as Mumble at all, rather it looks like some generic system icon representing "muted microphone" or "muted system volume", leading to confusion. With the old icons, it was identifiable as Mumble, with its recognizable mouth.

Just take a look at this:

![capture](https://user-images.githubusercontent.com/42674312/44630656-74205d00-a961-11e8-96af-49e593ea63f1.PNG)

Is my system volume muted? It sure looks like that at first sight -- in fact, I've oddly got two "system volume" icons! Except one of them is not actually the system volume, but rather Mumble -- in which I have enabled "deafening".

It was also a bad idea, in my opinion, to replace the mouth by a "person" icon.

Also, I don't see any option to switch to the old icons (switching to "None" theme seems to keep the "New" ones), should there be one?

None of this is meant to belittle the work that went into producing or selecting the new icons, I think that work was a good contribution.

**Comment by davidebeatrici** [comment] 2018-08-26 20:30
We replaced the old icons for the system theme in #3475.

> It was also a bad idea, in my opinion, to replace the mouth by a "person" icon.

Could you explain why, please? We would like to make the theme as good as possible for the users.

**Comment by trudnorx** [comment] 2018-08-26 20:43
> Could you explain why, please? We would like to make the theme as good as possible for the users.

It's too generic, bland. It doesn't feel distinctly like "Mumble", it feels like it could represent just about anything. The mouth represents talking and represents a voice chat application, and it feels distinctive of Mumble with which the mouth icon can be mentally associated.

Some generic "person", by itself, represents just about nothing, it doesn't immediately seem to represent voice chat or speaking; it doesn't feel connected to Mumble, either, there's a million applications using icons like that.

The meaning of the mouth lighting up as red, is very obvious to the user, and there is an obvious connection with the act of speaking and intuitively feeling as if everything is working properly.

**Comment by trudnorx** [comment] 2018-08-27 19:45
But maybe it would be ok to use person icon for other users in the main window but mouth icon for system tray

**Comment by edm7707** [comment] 2018-08-27 19:54
I haven't really looked into themes and UI customization very much ... but can you change system tray icons if you make your own theme? .... If not, maybe a feature worth looking into?

**Comment by davidebeatrici** [comment] 2018-08-27 23:36
> But maybe it would be ok to use person icon for other users in the main window but mouth icon for system tray. When you're in the main window you already know it's Mumble and a person icon is good for representing people, but in system tray person icon is meaningless and not immediately associated to your own speaking

I agree.

> I haven't really looked into themes and UI customization very much ... but can you change system tray icons if you make your own theme? .... If not, maybe a feature worth looking into?

Custom themes load resources from the Mumble theme, unless they are overridden, meaning that you just have to include the icons you want to replace.

The classic icons are there: https://github.com/mumble-voip/mumble/tree/master/icons/classic

**Comment by davidebeatrici** [comment] 2019-03-21 06:29
> But shouldn't there be a 'classic' option in case users want the classic icons and like them more? Many apps do this.

#3641

**Comment by davidebeatrici** [comment] 2019-03-21 18:52
#3641 has been merged. There's now a theme called "Classic - Old Style".

**Comment by Krzmbrzl** [comment] 2020-06-06 16:34
I guess this issue can be closed now? (I'll assume "yes" until proven otherwise)

**Closed by Krzmbrzl** 2020-06-06 16:34 UTC
Labels: client, theme

**Comment by streaps** [comment] 2020-06-07 08:07
The original issue has not been solved. Adding Classic style is not really a solution.

What to prove, if we don't know the reason why the issue has been closed?

**Comment by Krzmbrzl** [comment] 2020-06-07 08:53
Well I think it kinda is solved. The issue basically is "I think the old icons are better" and for anyone that thinks so, you can use the Classic theme. No problems there :shrug:

**Comment by streaps** [comment] 2020-06-07 09:58
The issue is with the new icon set. Classic theme is only a workaround for people who are able to cope with these horrible icons (or for some reasons prefer them) _and_ already know the problem. It doesn't help any user who is not aware of the old icon set or is new to Mumble.

**Comment by Krzmbrzl** [comment] 2020-06-07 10:01
Feel free to open an issue at https://github.com/mumble-voip/mumble-theme and explain what exactly is the issue and how you would improve on that.
I guess we can have a look at what we could do there.

Personally I don't have any problems with the icons :shrug: 

In any case this issue is OT in this repository as the icons are part of the theme and the theme is not part of the main repo.

**Comment by streaps** [comment] 2020-06-07 10:02
whatever

**Comment by toby63** [comment] 2020-06-08 16:51
While I don't agree on changing the icons theme, I would like to see an option, where only the mumble icon is shown in system tray (so no state icons).
And this is certainly related to this repo.

**Comment by Krzmbrzl** [comment] 2020-06-08 16:56
> I would like to see an option, where only the mumble icon is shown in system tray (so no state icons).

That's already possible. Go to Settings > User interface > Tray icon and uncheck "Show talking state in tray icon"

**Comment by cedarmax** [comment] 2024-05-06 02:29
Just updated from Ubuntu 22.04 LTS to 24.04 LTS.  The new Mumble package in this release is missing the classic icons.  I can't find the old ones anywhere only.  I am currently stuck with the new Fisher Price icons, please fix ASAP.

**Comment by Krzmbrzl** [comment] 2024-05-06 08:44
The classic theme has been removed due to the reasons given in https://github.com/mumble-voip/mumble/pull/4969

**Comment by cedarmax** [comment] 2024-05-07 05:18
> The classic theme has been removed due to the reasons given in #4969

Can the old icons be brought back with a custom user installed theme?  I am trying to find the icons in my old mumble install folder, but I cannot find them

**Comment by Krzmbrzl** [comment] 2024-05-07 11:16
You can find the old icons in the git history. Creating a custom theme from it should be possible.

**Comment by davidebeatrici** [comment] 2024-05-07 15:15
Yes, you can just copy the default theme and replace the icons.

**Comment by cedarmax** [comment] 2024-09-23 21:41
> You can find the old icons in the git history. Creating a custom theme from it should be possible.

How?

**Comment by davidebeatrici** [comment] 2024-09-23 21:47
https://github.com/Krzmbrzl/mumble/tree/490579bd275a6e30e7ad1ffb1e4a3cf489804edb/themes/Classic

**Comment by cedarmax** [comment] 2024-09-23 22:22
> https://github.com/mumble-voip/mumble/tree/490579bd275a6e30e7ad1ffb1e4a3cf489804edb/themes/Classic

@davidebeatrici Thank you for your reply, I was able to get this installed and working.  However, a few icons didn't revert to their old versions, such as the World icon to select a server and the Mute button icon.  Any idea how to fix this?
