### ISSUE TITLE
Connect to multiple servers at the same time

### ISSUE THREAD

**Issue by e00E** [mumble-voip/mumble#5629] opened 2022-04-20 22:38 UTC
### Description

I would like to to join multiple servers at the same time. I am aware of a workaround using the command line switch to allow multiple instances of the client but it would be nicer if a single client natively supported this.

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment] 2022-04-21 05:45
Duplicate of #2091

**Closed** 2022-04-21 05:45 UTC
Labels: feature-request, triage
