### ISSUE TITLE
Push-to-Talk key hangs on Wayland

### ISSUE THREAD

**Issue by promi** [mumble-voip/mumble#4073] opened 2020-04-17 10:48 UTC
OS: Ubuntu 20.04 (problem also exists on other distros)

When you use Push-to-Talk on a Desktop Environment that is running on Wayland the Push-to-Talk status is not updated when switching to a different application while holding the Push-to-Talk key.

If another window is in the foreground, pressing the Push-To-Talk button does not even work, so Mumble has to be the current active window.

**Comment by Reikion** [comment] 2020-04-17 12:05
It's security feature of Wayland. If release of 1.4.0 version will be ready, then you will be able to set up Push-To-Talk in your Desktop Environment's hotkey manager. See: #3243.

**Comment by Krzmbrzl** [comment] 2020-04-17 12:17
I'll close this as a duplicate of #3243

**Closed by Krzmbrzl** 2020-04-17 12:17 UTC
