### ISSUE TITLE
IPv6 addresses no longer visible

### ISSUE THREAD

**Issue by TredwellGit** [mumble-voip/mumble#4021] opened 2020-03-30 20:52 UTC
**Describe the bug**
On master, IPv6 addresses are no longer visible. Connecting via IPv6 still works, but the addresses are not visible in the user interface. IPv6 addresses are visible in 1.3.0.

**Steps to Reproduce**
Hover over a server with IPv6 support in Mumble Server Connect or while connected to a server look at an IPv6 connected user's Connection Information IP Address.

**Screenshots**
![Connection Information IP Address](https://user-images.githubusercontent.com/61860346/77959663-f642d700-72a4-11ea-8d64-93ab0c978607.png)
![Mumble Server Connect](https://user-images.githubusercontent.com/61860346/77959665-f6db6d80-72a4-11ea-8cfa-7a162553cc8c.png)
Notice how the IPv6 address is not visible but the port is.
IPv4 address whited out for privacy.

**Desktop:**
- OS: Arch Linux
- Version: Mumble b5500df55eac47ddae19987811b29097da62c48e

**Additional context**
This issue is present on the current master, but I am unsure what commit introduced the issue.

**Comment by Krzmbrzl** [comment] 2020-03-31 06:22
Do you have the address of a server using IPv6 at hand so I can try it out for myself? :)

**Comment by TredwellGit** [comment] 2020-04-01 21:43
If you run a server on localhost (I assume that you do since you work on Murmur), then it will support IPv6 and IPv4.

**Comment by Krzmbrzl** [comment] 2020-04-02 08:20
> I assume that you do since you work on Murmur

I do indeed.

> it will support IPv6 and IPv4.

But I'm still shown the IPv4 address. Do you happen to know a way to force it to only use/show IPv6?

**Comment by bendem** [comment] 2020-04-02 18:32
> Do you happen to know a way to force it to only use/show IPv6?

You can set the host to '[::1]' which is the ipv6 version of 127.0.0.1.

**Comment by Krzmbrzl** [comment] 2020-04-02 18:56
Okay thanks. Will try that :)

**Comment by TredwellGit** [comment] 2020-04-02 19:22
Hovering over the server in Mumble Server Connect shows both IPv6 and IPv4, but you will only be able to see the port portion of the IPv6. Here is a better image of what it looks like in 1.3.0.
![Grimshot 2020-04-02 15-17-41](https://user-images.githubusercontent.com/61860346/78292821-a27afc80-74f5-11ea-80fc-67838e0ed889.png)

**Comment by TredwellGit** [comment] 2020-04-02 23:48
To clarify even further, in 1.3.0 it correctly shows `Addresses 127.0.0.1:64738, [0::1]:64738` but in recent versions incorrectly shows `Addresses 127.0.0.1:64738, :64738`.

**Comment by Krzmbrzl** [comment] 2020-04-04 18:00
I just bisected the commits between the state of 1.3.0 and current master and b263b91340fb8b359e34626de880f606cfd9c116 turned out to be the cause of this.

**Comment by Krzmbrzl** [comment] 2020-04-04 18:18
Okay I messed that commit up. This is what you get for blindly replacing deprecated functions without checking the docs for the replacement :man_facepalming:
`QString::asprintf` is a static function and thus it only works if I assign its return value to a variable. Which I didn't...

**Closed** 2020-04-06 07:22 UTC
Labels: bug, mumble, ui
