### ISSUE TITLE
Client high CPU usage 

### ISSUE THREAD

**Issue by Avamander** [mumble-voip/mumble#3041] opened 2017-04-20 14:15 UTC
Version: 1.3.0\~2310\~g9e834cb\~snapshot-1\~ppa1\~yakkety1
OS: Ubuntu 16.10

I have noticed that when Mumble is connected to the server and even when there's no voice being transmitted (push-to-talk) and no one is speaking, it's utilising about 10% of my CPU, that'd a tad high. When there are other people speaking it rises to about 13%.

**Comment by mkrautz** [comment] 2017-04-21 21:48
This is a long standing issue.

Mumble, on all OSes, will keep recording input and feeding it to the preprocessor pipeline, in order to make the automatic gain control, work well, among other things...

When using the PulseAudio backend, Mumble can use quite a bit of CPU when doing this. I believe the other backends are a little better in that regard.

There are other issues, someone should probably merge this into them.

**Comment by Avamander** [comment] 2017-04-22 10:33
Though would it be possible to stop the input recording, even more so when push-to-talk is used and even more so when mic is muted to just not waste CPU?

**Comment by Kissaki** [comment] 2017-04-22 11:33
It’s so sound/volume amplification and noise suppression or whatnot works as intended when you do press the PTT. It has been discussed in the other issue tickets. #1092

**Comment by Avamander** [comment] 2017-04-22 12:24
Okay, but at least when the mic is muted then it shouldn't listen.

**Comment by davidebeatrici** [comment] 2017-12-03 11:40
Closing in favor of #1089.

**Closed by davidebeatrici** 2017-12-03 11:40 UTC
Labels: mumble, priority/P2 - Important
