### ISSUE TITLE
MumbleTheme: Menu highlights are different from all other highlights

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2435] opened 2016-07-17 19:53 UTC
![image](https://cloud.githubusercontent.com/assets/36527/16902769/c2fd1de4-4c68-11e6-8118-79a3645e0b49.png)

vs

![image](https://cloud.githubusercontent.com/assets/36527/16902773/dd69535a-4c68-11e6-84e2-6a05ef0d1253.png)

**Comment by mkrautz** [comment] 2016-07-18 20:14
But maybe it's intentional.

Clicked state:

![image](https://cloud.githubusercontent.com/assets/36527/16928804/f487b564-4d34-11e6-92df-66ebdec849df.png)

Non-clicked state:

![image](https://cloud.githubusercontent.com/assets/36527/16928817/016c0f0a-4d35-11e6-9af0-4d0bcd651349.png)

**Comment by Krzmbrzl** [comment] 2020-03-04 09:46
@xPoke do you have any idea about this one? :thinking:

**Comment by xpoke** [comment] 2020-03-17 16:26
Hey - 
In general for the dark theme I went with high contrast and strong hue on a clicked element ("strong intention") and a lighter contrast and shade on a selection/mouse-over ("weak intention"). 

However I agree the first example breaks that logic, and I don't remember the reason, but I believe it could be a QT limitation - they might not have different QSS selectors for a highlight event or click event. And even if they did, I'm not sure it would look right (try this in almost any app - no app will have different UI elements for clicking vs. hovering in the top menu)
Either way, these days there is very little visual consistency for top menus on Win10+ (and everywhere else), and other operating systems use their own conventions. But still if this looks wrong in your opinion, please change it.

**Comment by Krzmbrzl** [comment] 2020-03-17 16:38
Thanks for the feedback :+1:

Personally I don't mind this at all and I wouldn't even have noticed it if I hadn't stumbled upon this issue.

I just wanted to make sure that this currently is the intended behavior and not a bug that we'd have to track down.

Therefore I'll close this issue as "intended behavior" :)

**Closed by Krzmbrzl** 2020-03-17 16:38 UTC
Labels: mumble, needs-more-input, theme, ui
