### ISSUE TITLE
Add Raise Hand feature

### ISSUE THREAD

**Issue by JustGitting** [mumble-voip/mumble#4258] opened 2020-06-07 01:45 UTC
**Context**
Using voice-only chat software is always a little tricky given you cannot always read the visual cues as to when is a good time to raise a question or new topic.

A friend asked if mumble has  a "raise hand" feature with some sort of queue so you know who was next to speak. I don't believe mumble has this feature, happy to be corrected though.   

**Describe the feature you have in mind**
Like the mute button, a raise-hand (waving hand) button could be added to the top of the Mumble application. This would highlight the users avatar / username that they wish to speak. This could also include a number so other users know who wishes to speak next.
During or after the user has gotten the opportunity to speak, they (or a moderator) could press their raise-hand button again to remove them from the speaking list. This updates their icon and reduces the queue numbers by 1. 

**Describe alternatives you've considered**
I've read else where that users could use the chat channel to ask to speak next. Whilst is a simple solution, not everyone is following the chat. It's hard to keep track of who is wanting to speak next if there are multiple conversations/topics being discussed via chat. 

**Additional context**
The FOSS video conference software, Jitsi, along with Zoom, etc,  have a "raise hand" feature, so users are accustomed to the function.

**Comment by Krzmbrzl** [comment] 2020-06-07 06:43
Duplicate of #4102

**Closed by Krzmbrzl** 2020-06-07 06:43 UTC
