### ISSUE TITLE
Registration server requires specific set of cipher suites

### ISSUE THREAD

**Issue by oplehtinen** [mumble-voip/mumble#2597] opened 2016-10-25 00:46 UTC
```
<W>2016-10-25 03:13:59.096 1 => <5:(-1)> New connection: 52.201.18.254:46579
<W>2016-10-25 03:13:59.100 1 => <5:(-1)> Connection closed: Error during SSL handshake: error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher [13]
<W>2016-10-25 03:13:59.211 1 => Registration: DNS name callback voip.astraalivankila.net=>185.20.139.180 failed: Source-based callback failed. Server not reachable.
```

Not sure if related to #2252 ?

I finally have my server running with PFS and such - I really shouldn't need to enable SSL3 just to get registered.

A records and such are in order, and everything worked fine before using stricter SSL ciphers.

**Comment by mkrautz** [comment] 2016-10-25 09:26
No, the registration server doesn't require SSLv3. It should work with TLS 1.2 just fine.
The error message is OpenSSL internals leaking out.

I believe we use the same cipher preference as recent Mumble/Murmur, so https://github.com/mumble-voip/mumble/blob/master/scripts/murmur.ini#L195.

What cipher suites have you enabled for your server?

See also the SSL Labs check for mumble.hive.no and mumble.info for a list of support cipher suites:
https://www.ssllabs.com/ssltest/analyze.html?d=mumble.info (used in Mumble 1.2.x)
https://www.ssllabs.com/ssltest/analyze.html?d=mumble.info (used in Mumble 1.3.x, still)

**Comment by dimits** [comment] 2016-10-25 11:21
`sslCiphers=EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH`

I had these, but changed the preference to your recommendation. Registration now works and so does PFS. :)

**Comment by mkrautz** [comment] 2016-10-26 19:13
@dimits What version of Murmur was this on? And what distro?

I can't reproduce the failure to connect with the cipher suites you provide (I've only tested with openssl s_client, though):

    openssl s_client -cipher "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH" -connect mumble.hive.no:443

and

    openssl s_client -cipher "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH" -connect mumble.info:443

both connect just fine...

**Comment by dimits** [comment] 2016-10-26 19:37
@mkrautz Using those settings in the openssl s_client connect just fine for me, too. (Just tried)

Mumble running on Ubuntu 16.04.1, using the snapshot PPA of murmur, right now: 1.3.0~1623~g0556b6c~snapshot-1~ppa1~xenial1

**Comment by mkrautz** [comment] 2016-10-26 19:41
Thanks, I'll try to reproduce with the Murmur in xenial.

**Comment by davidebeatrici** [comment] 2020-11-17 01:24
Duplicate of #4569.

**Closed by davidebeatrici** 2020-11-17 01:24 UTC
Labels: bug, public-server-registration, server
