### ISSUE TITLE
Removing ACL rule containing a no longer existing member results in an error

### ISSUE THREAD

**Issue by kvdheijden** [mumble-voip/mumble#1733] opened 2015-06-29 14:16 UTC
When removing a rule from ACL which contains a member that no longer exists in the database the following error will be put in the logfile, and you can no longer connect to the server: 

> SQL Error [INSERT INTO `murmur_group_members` (`group_id`, `server_id`, `user_id`, `addit`) VALUES (?, ?, ?, ?)]: Cannot add or update a child row: a foreign key constraint fails (`murmur`.`murmur_group_members`, CONSTRAINT `murmur_group_members_del_user` FOREIGN KEY (`server_id`, `user_id`) REFERENCES `murmur_users` (`server_id`, `user_id`) ON DELETE CASCADE) QMYSQL3: Unable to execute statement

I am using MySQL as database for murmur.
After restarting the server, you can log back in as normal.

**Comment by mkrautz** [comment] 2015-06-29 20:25
When a user in unregistered, we remove all the ACLs referring to that user.

Is your bug report that:

 - It is possible using Murmur's RPC API to remove a user, to get in a state where the ACLs still refer to the removed user.

?

I suppose it's also possible there is a race somewhere regarding setting ACLs and unregistering

**Comment by Hallelujahh** [comment] 2015-06-30 08:55
There was a username which was removed in my ACL, and the moment I removed that user, my server stopped working. I'm not sure how the user did not end up being deleted if that's the case. The removal of the ACL and the user was quite some time apart tho.

**Comment by mkrautz** [comment] 2015-06-30 09:46
Thanks, I pretty much just wanted to know whether you modified the MySQL data yourself, or an external program did it on your behalf.

We don't support directly modifying the SQL. All changes must be made through Murmur's RPC interface.

However, from your reply, it does not sound like any manual editing took place!

We still don't know what caused this, so I'm marking this as up-for-grabs so someone can pick it up and investigate.

Thanks for the report!

**Comment by Hallelujahh** [comment] 2015-06-30 16:15
Ahh.. I did actual edit the database manually. I removed the user from the users table because I was at a location where I had no access to mumble, but I did have access to MySQL. Thus the cause to the error is found.

Anyway, did you specifically design murmur to crash/halt whenever an SQL error happens? Or should this maybe be caught? and show some error in the client?

**Closed** 2020-01-25 18:00 UTC
Labels: help wanted, murmur
