### ISSUE TITLE
1.3.1-rc1 tries to "update" to 1.3.0 every time it's launched

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#4089] opened 2020-04-21 07:12 UTC
![image](https://user-images.githubusercontent.com/42674312/79836224-26ffc300-83b0-11ea-904a-747f25415fb2.png)

**Comment by Krzmbrzl** [comment] 2020-04-21 07:21
You can disable the version check in the settings.

I *think* this issue should be resolved once the auto-update-backend has been informed that there is a new version 1.3.1 :thinking:

**Comment by Krzmbrzl** [comment] 2020-04-21 07:36
The problem should be fixed now. If not, please let me know

**Comment by trudnorx** [comment] 2020-04-21 12:55
@Krzmbrzl still happening

**Comment by MartB** [comment] 2020-04-23 16:39
Still happening indeed.

**Comment by Krzmbrzl** [comment] 2020-04-23 16:43
Yes the problem is that we "fixed" the issue for snapshot releases, but we obviously the RC is not a snapshot release.
The issue won't exist in the released 1.3.1 though as then we can update the mainline update backend logic accordingly (which we can't do right now as otherwise everyone with 1.3.0 would get an update prompt for 1.3.1 which doesn't exist yet).

If I have the time though I'll rewrite the logic in the backend to do a proper version comparison in order to avoid this issue in the future :)

**Comment by Krzmbrzl** [comment] 2020-06-10 05:56
Now that 1.3.1 is released, the update checker should works as expected. Let me know if it doesn't

**Comment by Techassi** [comment] 2020-06-11 00:05
@Krzmbrzl yes it seems to be resolved. There is no note when connection and "Check for update" reports I am on the latest version.

**Comment by Krzmbrzl** [comment] 2020-06-11 06:06
Great. Thanks for reporting back :)

**Closed by Krzmbrzl** 2020-06-11 06:06 UTC
Labels: release-management
