### ISSUE TITLE
Quick-Chatbar starts minimized on new installs

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#1455] opened 2014-11-01 14:06 UTC
In the current 1.3.0 snapshots, the quick chatbar starts minimized for new installs.

Reproduction steps:
- remove HKEY_CURRENT_USER\Software\Mumble\Mumble\ui (window geometry data)
- Start Mumble

The chatbar can still be resized, making it visible again.

Probably an issue created through the transition to Qt5.

```
<hacst> Kissaki: Mew. I think this is a Qt 5 thing. I already looked at the code and tried a few things to beat it into submission but it didn't really work.
<hacst> Kissaki: Interested in taking a look? We really need to fix this (obviously) ;)
<Kissaki> sure
<hacst> Kissaki: To save you a few seconds: https://github.com/mumble-voip/mumble/blob/master/src/mumble/CustomElements.h#L63
<hacst> That's the control. We override several functions to have our custom sizing behavior like sizeHint and minimumSizeHint
<hacst> I think I tried setting a minimum size in the constructor but that didn't quite work.
<hacst> Setting a min size in QTCreator did work but that's not exactly helpful ;)
<hacst> I'd maybe start by checking if our minimum size calculations actually always return what we want and whether the callbacks are everything we should do and return the right thing on every call.
<Kissaki> there is no bug ticket for it yet?
<hacst> Kissaki: No. Probably should create one.
<hacst> Kissaki: I was working on another issue when I noticed it (annoyingly enough it had to do with layout so I kept thinking I broke it with what I was doing at the time)
<hacst> (I was trying to fix the "scale the log not the tree view" issue by making everything a dockwidget. Turns out that works better but still sucks in terms of control over scaling)
<hacst> setMinimumHeight(0); << That looks suspicious
<hacst> Wonder if I missed that...anyways ;) Have fun.
```

**Comment by hacst** [comment] 2015-06-11 00:00
Still occurring with 1.3.0~658 :( Hoped the last Qt update might've fixed it.

**Comment by mkrautz** [comment] 2015-12-26 19:55
Still happens now.

**Comment by dstensnes** [comment] 2019-12-30 15:28
@Kissaki May I suggest a small UI clean up containing a fix for this, as well as #1391 (https://github.com/mumble-voip/mumble/issues/1391)? That should at least make the current UI behave way better, and might remove some complaints about the mumble chat. that people are using as an excuse to move to discord

**Comment by dstensnes** [comment] 2019-12-30 15:29
This one in particular makes it so new users do not think there is a chat at all, which is quite bad

**Comment by Kissaki** [comment] 2019-12-30 23:13
@dstensnes It is already marked with priority P2.

**Comment by Krzmbrzl** [comment] 2020-04-28 16:33
I think this is a duplicate of #3701 (or rather the other way around given the age of this issue. However the other issue has some nice screenshots in there, so I'd say we'll keep that one instead).
I'll transfer all milestones and labels to it as well...

**Closed** 2020-04-28 16:34 UTC
Labels: client, priority/P2 - Important, ui
