### ISSUE TITLE
Debug build immediately crashing with HEAP CORRUPTION error

### ISSUE THREAD

**Issue by Skewjo** [mumble-voip/mumble#4842] opened 2021-03-08 20:18 UTC
**Describe the bug**
Debug build is immediately crashing with HEAP CORRUPTION error.
Generator command (from: ```D:\Users\Skewb\Documents\repos\mumble2\build\debug>```):
```
cmake -G "NMake Makefiles" "-DVCPKG_TARGET_TRIPLET=x64-windows-static-md" "-Dstatic=ON" "-DCMAKE_TOOLCHAIN_FILE=D:\Users\Skewb\Documents\repos\vcpkg\scripts\buildsystems\vcpkg.cmake" "-DIce_HOME=D:\Users\Skewb\Documents\repos\vcpkg\installed\x64-windows-static-md" "-DCMAKE_BUILD_TYPE=Debug" ../..
```

Error: 
```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: D:\Users\Skewb\Documents\repos\mumble2\build\debug\mumble.exe

HEAP CORRUPTION DETECTED: after Normal block (#3828194) at 0x000001A66A4D6980.
CRT detected that the application wrote to memory after end of heap buffer.


(Press Retry to debug the application)

---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Steps to Reproduce**
Clone and build repo in debug mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/4118039/110376233-8f7f7f00-8018-11eb-94ef-bccae7dc9f8f.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: Occurs when building master branch

**Additional context**
I decided to do a debug build so that I could do some additional troubleshooting on my feature branch, but it immediately failed with the above error. I was curious whether this was because of my changes or not, so I attempted to build the master branch without my changes present and ran into the same issue.

Is this something you guys are aware of, or have I built something incorrectly? 
Can provide full generator and build output if necessary.

**Comment by davidebeatrici** [comment] 2021-03-08 20:55
@Kissaki encountered the issue as soon as we switched to CMake, however our old environment didn't contain debug libraries and as a result we always used the release + symbols preset with qmake.

Have you tried running the application through Visual Studio? It should indicate more or less where the heap corruption occurs.

If I recall correctly, though, the corruption was coming from one of Qt's modules.

**Comment by Skewjo** [comment] 2021-03-08 22:23
@davidebeatrici, got it, thanks for the info. If you guys don't usually build the debug version how do you attach the debugger? 

I can debug the release version of my Windows app without issue, but when I try to attach the visual studio debugger to Mumble I get a bunch of errors telling me about Visual Studio's inability to load symbols. Similar issue in Qt.

**Comment by davidebeatrici** [comment] 2021-03-09 00:31
`-DCMAKE_BUILD_TYPE=Release -Dsymbols=ON`

**Comment by Krzmbrzl** [comment] 2021-03-09 07:26
> got it, thanks for the info.

"Got it" as in "I have found where the corruption occurs" or as in "understood"? In the former case: Where did the corruption occur? Was it in one of Qt's modules?

**Comment by Skewjo** [comment] 2021-03-09 12:09
Sorry... "Got it" as in "understood". Haven't had the chance to troubleshoot it yet, and likely won't make it very far if I do...

**Comment by Krzmbrzl** [comment] 2021-03-09 12:47
Please let us know, if you find anything

**Comment by Skewjo** [comment] 2021-03-10 14:52
Got the debug button to work in Qt (which I believe is just using a release build with debug symbols on) and it gives me  the following output: 
```
HEAP[mumble.exe]: Invalid address specified to RtlFreeHeap( 00000243C0C90000, 00000243C60ED070 )
```

![image](https://user-images.githubusercontent.com/4118039/110647748-bb684500-817d-11eb-9ca8-1f0b3e1697cf.png)

**Comment by davidebeatrici** [comment] 2021-03-10 19:32
I'm pretty sure the error is due to mumble-voip/rnnoise@b30f2bb8049601c3b7253d47f75dc6a68c5f32fd, line 467:
```c
opus_val16 *yy_lookup = malloc(sizeof(*yy_lookup) * maxperiod+1);
```

The correct line is:
```c
opus_val16 *yy_lookup = malloc(sizeof(*yy_lookup) * (maxperiod+1));
```

The issue is fixed in mumble-voip/rnnoise@a9afcccb3c4f01e6e76a1ef67ccb58b7799856bf, but I forgot to update the submodule...

**Comment by Skewjo** [comment] 2021-03-10 23:04
@davidebeatrici, yep! That seemed to resolve the issue.

**Comment by Skewjo** [comment] 2021-03-11 20:12
Looks like I've got a couple of other memory issues occurring in the debug build, but I'm guessing they are completely unrelated(not sure if I should open up another issue).

Both have occurred an unknown amount of time after launching the program, and both appear to involve ```Opus.dll":

\#1:
![image](https://user-images.githubusercontent.com/4118039/110848477-c2717f00-8273-11eb-82ca-48729f1d495d.png)

\#2
![image](https://user-images.githubusercontent.com/4118039/110848488-c7cec980-8273-11eb-855e-ebf2cbe0a083.png)

**Comment by Krzmbrzl** [comment] 2021-03-11 20:20
A separate issue would probably be best.

**Closed** 2021-03-11 23:56 UTC
Labels: support
