### ISSUE TITLE
RFC: Should IP+Certificate ban really be the default ban?

### ISSUE THREAD

**Issue by Githlar** [mumble-voip/mumble#1655] opened 2015-05-07 00:04 UTC
There seem to be some conflicting views regarding the default ban policy in Mumble. Currently the default is to both certificate ban and IP ban a user. However, after some discussion in IRC we throwing around the idea of making the default ban a certificate ban with the option of adding IP as well when it's created.

So, I will list the pros and cons that we've covered for both options and let whoever wants to chime in on this do so.
### Certificate + IP Ban (default behavior)
1. Strongest ban -- most likely to deal with trolls more easily
2. Possibility of banning a whole NAT network without the admin realizing
3. Can be downgraded to Certificate ban (assuming the administrator is able to be notified of an accidental NAT block, for example).
### Certificate Ban (proposed behavior)
1. No possibility of accidentally banning a NAT
2. Not as heavy-handed as Certificate + IP -- not as efficient against trolls out-the gate
3. Can easily be upgraded to Certificate + IP

They both have their pros and cons. Some say that the certificate + IP is easier and more effective therefore should be preferred. I'm of the mentality that the possibility of banning an entire NAT with a single click is unacceptable -- after all, the administrator might not fully understand that he's doing this. This goes even more since Mumble itself doesn't give you any hint about what it's actually doing unless you happen to carefully examine the (new) ban list after the fact. Ultimately, no matter how you look at it, even the strongest ban we have can be trivially bypassed by a sufficiently resourceful individual.

Personally, I think that the average Mumble user probably doesn't know anything about the certificate. Indeed, in my experience many of my users don't even know what a certificate is or that they have one. So, for the majority of cases I think a certificate ban would be adequate.

What I propose is to change the default behavior to be a certificate-only ban. However, with the ability to upgrade it to a certificate+IP ban right from the ban user dialog via a checkbox. This would provide the desired flexibility to do what needs to be done without having to re-visit the ban dialog to, say, remove or add an IP restriction.

**Comment by Kissaki** [comment] 2015-05-12 07:16
When you’re being attacked/trolled not being able to quickly and simply react with a working ban is problematic.
An IP ban that bans more than wanted is easily discovered by the person that can not connect, and can be handled after the fact, which is probably also after the attacker/troll gave up.

I would argue in favour or being able to quickly resolve the situation, and cleaning up afterwards. When you’re in a match, playing, or in a discussion, you don’t want to take too much time with the hassle of banning a nuisance. I’ve never had an issue where a specific IP ban lead to another user not being able to connect (my server is not really high volume though …).

Are there use-cases for NAT which handles entire user networks rather than small, living-together networks?

What would you do with someone who connects without a user certificate?

**Comment by jumpandspintowin** [comment] 2015-05-14 03:43
@Kissaki, NAT is routinely used in IPv4 world for expanding a large number of internal hosts to one or few external IP addresses. It's deployed at nearly every home, public WiFi, office, and even cellular providers. So, it's everywhere.

**Comment by hacst** [comment] 2015-05-14 09:12
Does anyone know someone running bigger mumble servers? They'll surely have an opinion on such defaults.

In general I don't think that an IP ban is a big problem even in the face of NAT. The probability one of your valid users is behind the same one as a troll is small. If it happens chances are they know each other and can resolve the issue IRL. As our connection is encrypted we shouldn't generally have the "my ISP is sending me through a proxy so a gazillion ppl. have the same IP" issues.

I guess what we could do is make the dialog retain whatever you configured last time which the current behavior staying the initial default. But it doesn't sound like that's the underlying issue you are concerned about.

**Comment by mkrautz** [comment] 2015-05-14 09:42
The problem with ISP's isn't just proxies. It's carrier grade NAT, which using TLS won't combat.

Banning a troll on a carrier-grade NAT IP could ban a whole slew of other users.  However, the problem is minimal for Mumble servers, I reckon.

It's worse for websites, because there are free-for-all.  Mumble servers are often more private and have a smaller audience.

But it's still a very real problem.

**Comment by SteffanLong** [comment] 2015-05-17 03:51
Simply banning the certificate only keeps the troll/unwanted user gone for a few seconds while they get a new certificate.

Unless of course you have your ACLs set up to only allow non-registered users in the Root channel with self-register off, but this is not the default behavior.

Like others have said, if you unintentionally ban an entire NAT network then you'd be made aware of it when someone is unable to connect, and you could resolve it then.

**Comment by Githlar** [comment] 2015-05-18 06:09
I don't necessarily agree with the fact that the server owner would know it. Personally, I don't give out my personal contact detail to people on my (small) Mumble server. So, if something were to go wrong, they wouldn't necessarily be able to contact me. Then again, since Mumble is gaming-oriented I suppose there is a case to be made that the accidentally affected party could contact the owner via the game. Point taken.

In a normal circumstance, banning the home IP of a user is a perfectly valid scenario. However, like mkrautz stated, there are more environments that they are in that could potentially cause issues for other users. Whether or not it's a realistic concern hasn't really been determined. That said though, as I stated before, you can't necessarily expect an average server operator to understand nuances of the 'net like NAT.

Yes, there would be an issue with certificateless users, and that'll have to be something to look into when/if there's a consensus to actually implement this. I was going to make the argument that everybody should already have a certificate by default, but that's not the case in at least some mobile clients.

I agree that we need some input from large server operators in order to determine if this is a real concern. That said, would my proposal of adding a checkbox to the ban dialog that says "Also ban IP" and defaults to checked (possibly saving its setting) be something worth doing? As of now, Mumble doesn't give any hint about what it's actually doing when a user is banned (cert+IP ban) which I think is possibly misleading to a degree.

**Comment by Kissaki** [comment] 2015-05-19 21:18
> adding a checkbox to the ban dialog that says "Also ban IP" and defaults to checked (possibly saving its setting) be something worth doing?

Sure, yes.

**Comment by mkrautz** [comment] 2015-05-20 08:48
Agreed, we'd certainly welcome a checkbox for that.

**Comment by Kissaki** [comment] 2015-10-31 21:46
I did some work on this.
Unfortunately, our code seems to expect an address to always be part of the ban. Changing this seems to span various places, which is why I couldn’t finish it yet …

**Comment by Krzmbrzl** [comment] 2020-12-09 09:58
Closing in favor of #4621

**Closed by Krzmbrzl** 2020-12-09 09:58 UTC
Labels: client, discussion, enhancement

**Comment by mk-pmb** [comment] 2021-01-11 04:11
Might a compromise be an even better solution? Instead of banning on/off, we could use a severely restricted mode as default, e.g. from that IP we only accept one new connection every 3 minutes, and we accept only chat messages, no voice.

Possible feature creep:
* Finding a nicer name for that name.
* Ban subnets by custom prefix length. (default = 24 bits?)
* Pick a less restrictive mode if (or as soon as) there are more than (number) clients with voice privilege currently connected from that IP.
* Confine the restricted users to a certain room, or possibly auto-create a room with a default name if none is configured for this purpose.
* Check if users may need help managing their notifications to minimize potential annoyances from restricted users, but still be notified enough in case they might want to review their chat messages.

**Comment by Krzmbrzl** [comment] 2021-01-11 08:03
@mk-pmb please continue discussions in #4621. Otherwise it has the potential to get lost :point_up:
(Maybe just copy&paste your comment there as well)
