### ISSUE TITLE
Missing tray icon for Mumble server on Windows

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#4930] opened 2021-04-13 08:52 UTC
**Describe the bug**
When running the Mumble server (Murmur) on Windows there used to be a tray icon indicating that the server is running.
That tray icon has stopped showing since 1.4.0 (since our change to cmake).

**Steps to Reproduce**
1. Start server on Windows
2. Observe that there is no tray icon

**Expected behavior**
The tray icon to be shown

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble server 1.4.0

**Additional context**
The issue was reported to us by @cjunekim
The issue was already mentioned in https://github.com/mumble-voip/mumble/pull/4252#issuecomment-642899986. That comment actually indicates that the expected behavior would be for the server to minimize to tray but this step doesn't seem to happen.

Besides the minimize/tray icon issue, the server seems to be running fine though.

**Comment by Kissaki** [comment] 2021-05-08 11:40
So the server keeps running but is invisible to the user? There is no way for the user to shut down the server via standard UI? They will have to find and kill the process in the task manager?

Seems like a pretty critical issue that should be fixed for release.

**Comment by Krzmbrzl** [comment] 2021-05-09 07:07
It think the issue is that nobody has a clue as to why this happens.

Besides: I don't expect Windows _servers_ to be that widely used anyways and using the task manager is also not that big of a deal. Thus idk if I wanted to turn this into a blocker 🤷

**Comment by trudnorx** [comment] 2021-05-27 03:54
Windows servers are actually going to be used a pretty significant amount for multiple reasons, including users who want to setup a server for just them and their friends, etc. Task manager could be a big deal because 1) it forces Murmur to shutdown without doing a 'clean' procedure, 2) even if Murmur does not require such a clean procedure, it fosters bad practice. (that could result in data corruption, etc. with other server programs _or_ if Murmur also suffers from this in a newer version). Another disadvantage of this problem is the user can't see the server log for the currently running session from the tray icon anymore.

**Comment by Krzmbrzl** [comment] 2021-05-27 06:15
The issue that nobody has the slightest clue about why this happens still remains 🤷

**Comment by trudnorx** [comment] 2021-05-27 14:03
If the issue emerged purely from a change in the build system, could it be because it's not properly setting flags related to building on Windows, thus Windows-specific code like the tray icon isn't being compiled?

**Comment by Krzmbrzl** [comment] 2021-05-27 14:24
Good thought but as far as I can tell there are no flags involved in this that are unset.

We include the respective source files here
https://github.com/mumble-voip/mumble/blob/a5439965e3608df1a6811078a4d9b68067eaff20/src/murmur/CMakeLists.txt#L108-L114
and the actual tray icon should get created at
https://github.com/mumble-voip/mumble/blob/a5439965e3608df1a6811078a4d9b68067eaff20/src/murmur/main.cpp#L296-L298
`Q_OS_WIN` should be set by Qt (where and how I don't even know) but I am somewhat confident that this is indeed set as we are using this macro in quite a few places and it doesn't seem to cause trouble.

Thus to me it seems as it _should_ work xD

**Comment by trudnorx** [comment] 2021-05-27 14:30
You are sure that it changed only due to cmake or could there have been code changes in between?

**Comment by Krzmbrzl** [comment] 2021-05-27 14:42
Unless @davidebeatrici has managed to hide some code changes unlreated to the cmake switch in his cmake PR back then, it was only the cmake switch :thinking:

**Comment by davidebeatrici** [comment] 2021-05-27 17:43
CMake switch + Qt update.

**Comment by trudnorx** [comment] 2021-05-28 00:23
Did the Qt update change something about how tray icon should be coded?

**Comment by Krzmbrzl** [comment] 2021-05-28 06:15
Could be but that is usually not Qt's style (to change the behavior of existing programs like this with a Qt update).
I have not checked our implementation with the latest docs though (would probably be `QSystemTrayIcon`).

I can't even tell you what Qt version we were using prior to the cmake switch. Only that it was probably quite old. So maybe 5.6 or something like that :thinking:

**Comment by davidebeatrici** [comment] 2021-05-28 06:19
5.6, yes.

**Comment by Kissaki** [comment] 2021-06-03 15:10
I looked into this. And was not able to identify the problem yet. Everything seems to be fine, but it does not show, without issues being reported.

We use QSystemTrayIcon in the client, where we convert svgs to pixmaps and set those as icons. On activation we clear and fill the menu with menu items (reverse order between top and bottom of screen). This all works fine. The try icon shows, and the icon is updated according to the users state.

On the server side we create the QSystemTrayIcon and set the icon to the app icon, which seems to be embedded in the exe just fine, as it shows on QMessageBoxes. Even passing a QIcon explicitly does not change anything. We set a QMenu without dynamic behavior.

Using QSystemTrayIcon::showMessage to try and show a message does not work either.

The QSystemTrayIcon is created, a context menu is set, and show() is called as per QSystemTrayIncon documentation. So it *should* work.

I also tried moving up the initialization and working with it directly, without the Tray class. It does not show.

In the client we create a QApplication subclass MumbleApplication. The QSystemTrayIcon resides in MainWindow.
MainWindow and in turn QSystemTrayIcon is created after QApplication but before QApplication::exec(). Just like the server side.

**Comment by Kissaki** [comment] 2021-06-03 15:12
If it were easier to set up a Qt5 test project I would do that now to verify the behaviour and try and reproduce the issue…

**Comment by Krzmbrzl** [comment] 2021-06-03 16:05
> If it were easier to set up a Qt5 test project I would do that now to verify the behaviour and try and reproduce the issue…

You could use https://github.com/mumble-voip/qt_unicode_test as a start in order to not have to write the boilerplate yourself... :shrug:

**Comment by Krzmbrzl** [comment] 2021-07-11 16:45
Okay I figured out _what_ causes the issue. It seems that the icon used for the tray icon is in fact not available (for some reason) and if a tray icon is created with an empty or invalid (non-existent) icon, it will not be shown at all in the tray.

Using a dummy icon (created programmatically) causes the tray icon to be shown as expected.

Now I only have to figure out why the original icon doesn't work...

**Comment by Krzmbrzl** [comment] 2021-07-11 17:25
I figured it out - see #5172 :rocket:

**Closed** 2021-07-11 17:57 UTC
Labels: bug, help wanted, server
