### ISSUE TITLE
New UI uses red icons to indicate lack of activity

### ISSUE THREAD

**Issue by tmseiler** [mumble-voip/mumble#1858] opened 2015-10-25 18:24 UTC
In the newer QT-based interface, a red icon is used to designate a user who isn't talking. This contradicts expectations from previous versions, as well as the convention of red lights indicating a traditional recording device is "hot", or actively recording. Thus, I am constantly startled by the idle icon, wondering if the mic is hot.

**Comment by mkrautz** [comment] 2016-01-06 18:33
Sounds sensible to me.

@xPoke WDYT?

**Comment by xPoke** [comment] 2016-01-06 18:39
This is a very common concern with the red icons, but turning them simply gray really mutes the visual appeal of the design, and makes users not stand out in the UI (and they should).
I will experiment with new ideas and report back.

**Comment by hacst** [comment] 2016-01-06 22:49
Regarding the discussion on IRC:
* I liked the red ones. Fit very well visually.
* Against gray. Totally mushes users and channels together and looks kinda depressing.
* The pantone "human" imho doesn't fit the scheme if you ask me.
* Orange looked a bit to aggressive to my taste.

Maybe swapping red/green with red being recording and green being nothing imho might work better? Red is well established for "recording" so that would be ok. Not sure if that specific green works as a "default" color though.

**Comment by xPoke** [comment] 2016-01-07 05:03
My main issue with swapping the colors is the inconsistency with the even
more general notion that says red light - off, green light - on. I think it
ends up just as confusing.

**Comment by idontusenumbers** [comment] 2016-01-07 18:19
> Against gray. Totally mushes users and channels together and looks kinda depressing.

Why would you want to bring attention to a user that isn't broadcasting? Grey is exactly the color that non-broadcasters should be. Also consider red/green colorblindness, the most common kind.

**Comment by idontusenumbers** [comment] 2016-01-07 18:23
> I liked the red/green ones. Fit very well visually. Can understand the concerns though.
> The pantone "human" imho doesn't fit the scheme if you ask me.
> Orange looked a bit to aggressive to my taste.

Your personal preference should not trump usability.

https://www.google.com/search?q=recording+light&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi-pIjjqJjKAhUI3CwKHVSQAfIQ_AUICCgC&biw=1920&bih=995

Where are the green lights? I see a single green light, everything else is red.

**Comment by xPoke** [comment] 2016-01-07 18:36
Regarding both comments
- We want to bring attention to users as opposed to channels. This is to indicate to users where people are and where they are not when looking at the server. This is especially relevant for big crowded servers with lots of rooms.
- Red/Green colorblindness is common, which is why we also added the visual talking indicators. It should also be noted that the red and green colors are of different shade and intensity, but could be tweaked further. For reference, the pantone "human" color is slightly better for them, but not enough to be compliant with distinction standards.
- For non-colorblind people, which is the majority of users, red/green provides great contrast.
- There are speaking colors which are not green - such as for whisper / broadcast (purple / blue), though these are probably rare.
- I don't mean light for recording, but rather as in electrical appliances - green means on, red means off. Consider traffic lights or LEDs on speakers / chargers. You could argue that red also means "alert" and green means "normal", which could make sense for swapping the colors.
- However, inside mumble, both in the theme and before, red also means "muted / deafened". 
- Usability is important, but aesthetics also play into creating visual theme. The pantone "human" color simply looks ugly :)

Would love more info for/against swapping the red/green for users, and other suggestions.

**Comment by xPoke** [comment] 2016-01-07 18:58
Let me know what you think about this solution https://github.com/mumble-voip/mumble-theme/commit/ed8e090018e6e468bca981087935aee5fcb0f0b7 as the logical conclusion from what I wrote above.

**Comment by idontusenumbers** [comment] 2016-01-08 06:17
* Bringing attention to every leaf of a tree doesnt bring attention to the leaves, it loses them in a sea of visual noise
* I don't get the reference to speakers and chargers. I would say my own devices are split pretty evenly between green being on, red being on, blue being on, white being on... I can tell you one thing that *is* consistent is the color used for recording. That's red.
* The core feature of the application is audio chat. If users are confused about how the core functionality of the application works because it's been confounded by design choices intended to create a visual theme, something has gone terribly wrong.
* If anything, the application should fade into the background and let the user focus on what they are trying to accomplish. With mumble, they are trying to talk over the internet. If the mumble UI is causing anxiety and shock, that is Not Good (tm)

**Comment by xPoke** [comment] 2016-01-08 07:36
Regarding point no. 2, I don't think we want to convey that the user is "recording" (that's an actual different feature in mumble that IS indicated by a red circle), we want to convey "speaking".

All other point are not relevant to the discussion.
Please keep the issue tracker for actual suggestions and feedback about proposed solutions. The goals of a good UI design are obvious to us all, but getting there requires more than just nay-saying. I have implemented a change for this issue, please provide constructive criticism about it.

**Comment by idontusenumbers** [comment] 2016-01-10 08:55
The issue tracker seems like a great place to discuss these options.

How about non-color ways to indicate these states? It seems like the proposed changes just shuffle the colors around to avoid one unintended conveyance for another. Making red the disabled indicator still leaves users who think 'red means recording' left in the same situation as the OP.

I still dong understand the goal of drawing attention to user icons. I feel like 'normal users' (non broadcasting, non recording, unmuted etc etc should 'blend into the background'. Any list in any non-customized operating system within the last 20 years would show just black text with a simple low contrast icon. Disabled would show grey text with a dotted outline or greyscale icon. I have no problem changing the shape of the icon to indicate speaking or recording. I would be totally into having a badge for recording or muted etc. Currently muted and deafened are indicated on the opposite side of the screen using confusing x's (does x mean an action was taken on them or they are incapable because their mic int connected; maybe the distinction doesn't matter)

**Comment by xPoke** [comment] 2016-01-10 21:58
Drawing attention to users should be very clear when seen on large, complicated mumble servers, which is a very common scenario (so common, we implemented the filter feature for it).
Compare [colored users](https://i.imgur.com/FaAipVK.png0) with [grayscale users](https://i.imgur.com/lq0PApD.png) on such servers. It's very clear that there is a usability case to be made to help the eye see what is going on. A user should be visually distinct from a server in more than just a small icon, but obviously not too much.

About using colors for indications - we use both colors and icon shape for everything possible. The problem is that mumble has many similar meaning states. For example, a user can be muted in many different ways (self-muted, locally muted, channel muted or admin muted) and while all these states mean "muted", which is indicated by a crossed microphone, we have to indicate the specific state type, and this is where we use colors. I made an attempt to keep consistency between different icons, though obviously some artistic license is required. Making a different icon for each of these states is obviously not feasible, especially with tiny 16x16 icons.

As far as speaking indications go, we do slightly change the icon shape along with the color - we add small lines around the icon's head to indicate sound.

As in graying out users - currently mumble does not allow coloring the user's text according to state, only the icon can indicate the state. Furthermore, Idle users are not "disabled", they are idle. Muted users aren't disabled either, they are just muted. The only common state (in common messenger applications) that shows users as gray is an offline state, which doesn't exist in mumble.

Moving the icons from the right side is something I would be for - but this requires a deeper change than a simple theme allows. Also we need to decide how exactly users should look (I agree the current method is not the best).

I would agree that there are [many states](https://i.imgur.com/OFwZuiD.png) to indicate and very little indication to the user what each of these indications mean (as far as colors go anyway. I think the new icons are actually pretty descriptive). However, if you can figure out a way to have 4 different 16x16 icons to indicate different types of the same state, which doesn't rely on color or previous knowledge, I would gladly design such icons. Sometimes you have to rely on some user prerequisite knowledge (just like how you know [this text](https://en.wikipedia.org/wiki/Mystery_meat_navigation) is a clickable link).

**Comment by Sophira** [comment] 2016-03-05 21:25
I came here after seeing that the colours for idling/speaking were changed in the newest dev version of Mumble.

I personally am not a huge fan of the change, but I can understand why it was done. However, one of the reasons why I love the new theme over the pre-1.3.0 look is that it was a *lot* easier to distinguish idling/speaking users. For me (as a non-colourblind user, admittedly), having the whole user icon change colour between two highly contrasting colours was much preferable to the old greyscale/red lips icon in which only part of the icon actually changed. However, with this change, the green/blue aren't nearly so contrasting.

(Also, the "red for muted/deafened" isn't actually working for me; even when I'm muted/deafened/suppressed, my icon is still green.)

I understand the need for colour even for idling users, and I'm trying hard not to be all "I don't like change!" (although I *do* believe that the red/green from before made perfect sense and I actually prefer those as the green for idle users throws me off), but maybe a more contrasting colour for speaking users would be better.

I know I wasn't at the IRC meeting so I may have missed some context, but I think it would make more sense to have a muted blue for idle users, a nice saturated green for speaking users, and instead of a different colour for muted users, have their user icon and name show up at 50% alpha. In other words, something like this mockup that I made from the example pictures given above:

https://imgur.com/XgTvqc2

(it's inaccurate since of course you wouldn't see anyone speaking in a room you weren't in, but I wanted to illustrate how it might look)

To me, green for idle users gives the wrong impression, whereas blue is a "neutral" colour. If I'm just rehashing stuff that was already discussed at the IRC session, though, I apologise!

**Comment by hacst** [comment] 2016-03-12 03:29
Related new FR on sf: "#1193 Tray icon voice activity colour changes." - https://sourceforge.net/p/mumble/feature-requests/1193/

**Comment by netinetwalker** [comment] 2016-05-01 19:26
GREEN FOR DEFAULT AND BLUE FOR SPEEKING IS VERY WRONG. Bring the old color theme back!   Make a theme for someone with colorblindness is ok but don't fuck every user up! red/blue or red/green ok! but not green/blue!

**Comment by netinetwalker** [comment] 2016-05-01 21:58
![image](https://cloud.githubusercontent.com/assets/6934484/14944611/7ca9761e-0ff8-11e6-8c62-9454a925b2c0.png)

I think red for nothing and blue for speaking is a better solution if you want todo something for colorblind ...

**Comment by mkrautz** [comment] 2016-05-01 22:10
Note that the original reason for changing the colors wasn't colorblindedness. It was @tmseiler's confusion in the context of audio, where "red" typically means "recording".

**Comment by netinetwalker** [comment] 2016-05-02 02:05
But green for inactive is not a solution because green is speaking ... *g*
Ok what about light gray in dark theme and dark gray in light theme for inactive users. And blue or green or red for activity... Hmm Icon subthemes is what is needed...

**Comment by Sophira** [comment] 2016-05-02 04:11
What do you think about the mockup image I posted above, with a muted blue for inactive, green for speaking, and 50% alpha for muted?

https://imgur.com/XgTvqc2

**Comment by mkrautz** [comment] 2016-05-08 23:26
@Sophira I like that better than what we have in master right now.

Added my 2¢ at https://github.com/mumble-voip/mumble-theme/pull/7#issuecomment-217752472

**Comment by Krzmbrzl** [comment] 2020-01-25 18:52
I assume this discussion to be over and the "new" UI is released now anyways (in whichever state). Thus I'll close this issue...

**Closed by Krzmbrzl** 2020-01-25 18:52 UTC
Labels: ui
