### ISSUE TITLE
Add temporary/alternative server passwords

### ISSUE THREAD

**Issue by steven-joruk** [mumble-voip/mumble#1443] opened 2014-10-23 09:46 UTC
I use Mumble as a gaming chat server. It's common to want people to join the server just for an hour or day, but it isn't ideal to give them the server password. It's also not ideal to change the server password very often.

It would be great to be able to manage temporary or alternative server passwords, one is enough for my needs but I'm sure it's a use case for people to use several. It would also be good to automatically add people connecting with a certain password to a certain ACL group so they can't enter regular users channels and cause trouble.

**Comment by bontibon** [comment] 2015-11-19 13:43
Some other thoughts:

- Have a permission that gives a user the ability to create a temporary access code for the server
- Users can generate and give out access codes that guests can use to join the server
- Invited users can only stay in the server as long as the person who invited them is connected
- Invited users can be kicked by the person who invited them to the server (in the case where the inviter does not have kick permissions)

**Comment by ZeroAbility** [comment] 2023-02-14 00:31
Have you looked at the features here? 

https://wiki.mumble.info/wiki/Mumble_PHP_Interface

It might be a better to submit a feature request there. There will probably need to be better handling of time based access on something with high availability.

**Comment by Krzmbrzl** [comment] 2023-02-15 07:14
We can close this as a duplicate of #6061

**Closed by Krzmbrzl** 2023-02-15 07:14 UTC
Labels: feature-request
