### ISSUE TITLE
Echo Cancellation on macOS cause no Audio Input

### ISSUE THREAD

**Issue by krishukr** [mumble-voip/mumble#5733] opened 2022-07-01 23:42 UTC
### Description

then I have to disabled the echo cancellation, and the channel becomes noisy
hope to fix it soon :)

### Steps to reproduce

1. go to Configuration menu
2. Audio Input -> Audio Processing -> Echo Cancellation
3. select EXPERIMENTAL: Acoustic echo cancellation (Apple)
4. apply it

### Mumble version

1.4.230

### Mumble component

Client

### OS

macOS

### Reproducible?

Yes

### Additional information

macOS 12.4
using the built-in microphone and speaker

**Comment by Krzmbrzl** [comment] 2022-07-02 08:13
Duplicate of #4912

**Closed** 2022-07-02 08:14 UTC
Labels: bug, triage
