### ISSUE TITLE
Windows installer doesn't respect not creating shortcuts

### ISSUE THREAD

**Issue by ElPumpo** [mumble-voip/mumble#3087] opened 2017-05-10 20:13 UTC
The installer creates shortcutrs to the executables even when un-checked from the installer..?

- Windows 10 v1703
- Latest snapshot

**Comment by mkrautz** [comment] 2017-07-20 13:01
I cannot reproduce this with the latest snapshot, mumble-1.3.0-2505-g346702f-snapshot.msi.

Unchecking the desktop shortcut option does not create a desktop shortcut for me.
Neither for Mumble, nor Murmur. (Nor if I only install Mumble, or Murmur).

Closing... If you still encounter this problem, please let us know.

**Comment by mkrautz** [comment] 2017-07-20 13:02
Note that the option in the installer is for desktop shortcuts only. Are you talking about other shortcuts, i.e. start menu entries, etc.?

**Closed by mkrautz** 2017-07-20 13:01 UTC
Labels: installer

**Comment by ElPumpo** [comment] 2017-07-20 13:35
I'm on VACation atm, and yes I'm talking about desktop shortcuts

**Comment by ElPumpo** [comment] 2017-08-03 16:55
Weird, but this issue fixed itself

**Comment by mkrautz** [comment] 2017-08-03 17:12
:+1: Well, at least it's fixed. :-)
