### ISSUE TITLE
carriage return not working anymore in the chat

### ISSUE THREAD

**Issue by W0rmsy** [mumble-voip/mumble#4899] opened 2021-04-03 01:01 UTC
**Describe the bug**
This has been introduced in the snapshot. 
When copy/pasting text containing carriage return or manually adding some with ctrl + enter and send the message, the carriage return is removed and everything is concatenated
Example: https://eof.li/wma

**Steps to Reproduce**
copy multiple lines and send them from the quick chat 
or
add multiple carriage return by pressing ctrl + enter in the quick chat and send

**Expected behavior**
Carriage return should be sent like it was before the snapshot and in the advanced send message popup (right click-> send message)

**Screenshots**
https://eof.li/wma

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version:  `Mumble (1.4.0~2021-03-20~gf8dc8b0~snapshot)`

**Additional context**

**Comment by Krzmbrzl** [comment] 2021-04-03 06:48
Have you been using another snapshot before that? If so: Was this working in the other snapshots?

**Comment by Krzmbrzl** [comment] 2021-04-03 06:54
Okay I can reproduce this. I'll have a look :eyes:

**Comment by Krzmbrzl** [comment] 2021-04-03 07:21
Turns out the issue was that I did not know how to HTML anymore, when I implemented Markdown support :sweat_smile: 

The issue is fixed in #4902 though and thus in the next snapshot it should be gone. Thanks for reporting this :+1:

**Closed** 2021-04-03 12:24 UTC
Labels: bug, client

**Comment by W0rmsy** [comment] 2021-04-03 14:00
Thanks :) 👍
