### ISSUE TITLE
Chat message textbox isn't displayed on start

### ISSUE THREAD

**Issue by charlesg99** [mumble-voip/mumble#3701] opened 2019-06-04 01:29 UTC
Linux, Mumble 1.3.0rc1-3, the bottom left textbox to send messages to channel isn't displayed when first starting:

![Screenshot from 2019-06-03 21-25-22](https://user-images.githubusercontent.com/33044886/58844654-2b12dd00-8646-11e9-9ad5-bd8bd77d9309.png)

If I go to the Configure --> Settings... menu and then click Apply, the textbox reappears:

![Screenshot from 2019-06-03 21-26-54](https://user-images.githubusercontent.com/33044886/58844684-539ad700-8646-11e9-90a4-2d6b97f00d73.png)

**Comment by trustable-code** [comment] 2019-06-04 05:42
Same issue for me. On each start I use the splitter to increase the height of the text box.

**Comment by LinuxOnTheDesktop** [comment] 2020-04-19 09:19
Same problem, I think, on Mint 19.3 Cinnamon: the text box needs pulling up to be visible.

**Comment by Krzmbrzl** [comment] 2020-04-19 09:25
What resolution does your screen have?

**Comment by LinuxOnTheDesktop** [comment] 2020-04-19 09:31
2560x1440. *But* I am running Hi-DPI scaling at x2, effectively halving the resolution. The next version of Mint will have fractional scaling (so called) which should increase the effective resolution.

I hadn't thought of that when I commented.

**Comment by toby63** [comment] 2020-04-20 20:28
I also have this bug.

OS: Debian Testing
Resolution: 1920x1080
Mumble Version: 1.3.0

**Comment by streaps** [comment] 2020-04-22 11:50
Same problem. Raspbian Buster, Mumble 1.3.0 from testing. 1280x1024 screen, LXDE.

**Comment by Krzmbrzl** [comment] 2020-04-22 12:15
Is there someone affected by this bug who'd be capable of compiling Mumble from source on their machine? I have an idea what might be the problem but as I am not affected by the problem, I can't test my theory...

**Comment by streaps** [comment] 2020-04-22 12:35
Qt 5.12.5

**Comment by toby63** [comment] 2020-04-22 15:15
@Krzmbrzl: 
> Is there someone affected by this bug who'd be capable of compiling Mumble from source on their machine?

I want to compile it anyway (for testing 1.3.1 client and building a new server, because of outdated openssl version in static server builds #4001 ).
Just point me to the patch, when it is ready (no stress though, is just a minor problem).
Could take a while though, I am busy with some other stuff and have never compiled mumble.

* Are the Docs (https://wiki.mumble.info/wiki/BuildingLinux) still recent?
Especially this part:
> qmake -recursive main.pro
make
* (question for when patch is ready) What version should I compile 1.3.0, 1.3.1, master or some special commit?

**Comment by Krzmbrzl** [comment] 2020-04-22 16:29
The patch will be against master, so you'd have to build the patch PR (which will be based on the master branch). As I wrote above though I think the patch I had in mind doesn't make much sense after all.
However once you set up a build environment we could potentially search for the bug together by adding debug-statements as needed :)

Yes the docs should still be up to date.

**Comment by toby63** [comment] 2020-04-22 17:07
> The patch will be against master, so you'd have to build the patch PR
> As I wrote above though I think the patch I had in mind doesn't make much sense after all.

Ok, a different patch then? Or for now, no patch?

> once you set up a build environment

Well, I always have an lxd container ready for compiling.
I guess that's sufficient?

I guess the requirements shown in the [travis file](https://github.com/mumble-voip/mumble/blob/master/scripts/travis-ci/before_install.bash) are the most recent?

> we could potentially search for the bug together by adding debug-statements as needed :)

Whats the plan?
I set debug options, compile it and then we can see special logs?
Never really used debug flags to be honest :smile: .
I hope I don't have to rebuild stuff a thousand times :stuck_out_tongue: ?
What are the debug options? (haven't seen them in the install doc)
And what about usability? Can we build a version that can run alongside the already installed versions?
I would have suggested to use a Virtual machine (which I would need to set up first), but that would maybe taint the result.

Regarding the bug in general, are you using a more recent version of Qt or what makes you think thats the reason?
Especially considering you don't have the bug?

**Comment by Krzmbrzl** [comment] 2020-04-22 17:15
No patch for now.

The important bit is that you can run the built client on a machine that shows the error.

Travis file should be pretty up to date yes. Maybe you need to install qt5-concurrent in addition. Depends on the packaging of your distro

The plan would be track down where and based on what the size of the chat is set. For this we can add print statements into the code.
I think this will require a few compiles but only minor changes between them so they should be really fast (after the first one that is).

Yeah you don't have to install the compiled version. You can run it from the source dir. It will use your settings but as long as you don't change them, that should be fine.

I'll probably try to reproduce the bug in a VM first. If that works, you are spared the effort :P

Yes im running qt 5.14. From what I have read, dock widgets in qt (which the Chat is) adapt the size according to their content widgets. However we do set the minimum height for the widget to be as high as a single character. Thus it should never disappear completely. But as it does I was thinking that maybe there is a bug in the layout of these widgets.

**Comment by toby63** [comment] 2020-04-22 19:13
@Krzmbrzl 
Ok, thanks for the information.

> I'll probably try to reproduce the bug in a VM first. If that works, you are spared the effort :P

Good luck :+1: .

By the way, it also goes back to normal (chatlog visible) when I activate the "minimal view" (Configure->Minimal View).
So it seems that the layout needs some kind of reset. 

The bug appears in the snap version as well.
Snap version has implemented Qt v.5.9.5

Some information on my **settings** in mumble:
* layout: "classic"
* theme: mumble dark
Other options don't seem to be relevant.

More **information for the debian version** (changes they applied) (though irrelevant, because the bug appears for others as well, including the snap version):
Note: Those seem unsuspicious to me.
* included patches: https://salsa.debian.org/pkg-voip-team/mumble/-/tree/debian/debian/patches
* build config: [rules](https://salsa.debian.org/pkg-voip-team/mumble/-/blob/debian/debian/rules)

**Comment by rkoe** [comment] 2020-04-23 14:22
To me, it looks like (a) the wrong Qt-widgets are used or (b) the widget-sizes are configured incorrectly.
Since the mouse-pointer changes into an up-down-arrow above the (hidden) textbox, *it looks like* something like a splitter/paned window is used (instead of a fixed layout) and there's no minimal size set for the textbox.
But that's just a (hopefully helping) guess, since I don't know Qt or the Mumble-code in detail. (If it would be GTK+, I could have helped. ;))

**Comment by Krzmbrzl** [comment] 2020-04-23 16:17
The cursor actually changes because it's the border between two DockWidgets. As for the size-configuration, I'd say that is done properly but then again it's always hard to tell :shrug:

**Comment by toby63** [comment] 2020-04-29 14:52
@Krzmbrzl 
You have added the milestone and the p2-label, so can we assume you could replicate the problem?

**Comment by Krzmbrzl** [comment] 2020-04-29 16:17
No sadly I still wasn't able to replicate the issue. However I found #3817 which seemingly described the same bug. I closed the old ticket and transferred its milestone and the important label to this one.

**Comment by toby63** [comment] 2020-04-29 18:59
@Krzmbrzl 
What OS(es) did you try in virtual machines (if you did that already)?

By the way, I built mumble from master some days ago (i would need to search for the exact commit) and it did appear there too.

Interesting things:
* #1455 seems to imply that the problem occurs on windows too.
* The reporter and kissaki also had qt5 (or rather the transition to qt5) in mind as a reason.
Maybe it is really a code problem, something that worked in qt4 and does not work in qt5.
But why does it work for some people then, very strange.

**Comment by Krzmbrzl** [comment] 2020-04-29 19:06
> What OS(es) did you try in virtual machines (if you did that already)?

I didn't get around trying a lot. I only checked on my dev-machine (running KDE Neon -> Linux) and there it didn't happen.

> Maybe it is really a code problem, something that worked in qt4 and does not work in qt5.

Yeah that's what my best guess atm is too (after having read the linked issue). However for the question as to why it only happens for some users, I don't have an answer :shrug:

**Comment by toby63** [comment] 2020-04-29 19:39
@Krzmbrzl 
Also interesting, the line
>setMinimumHeight(0)

@hacst suggested, seems to exist still.
My quick search shows it in:
> mumble/src/mumble/CustomElements.cpp - line 110

Maybe just change that, but I guess others have tried that already.
Maybe ask @Kissaki what he tried so far :slightly_smiling_face: .

I just checked the MainWindow.ui again (I remebered from when i looked at that some time ago).
As hacst said, the log and chat widgets are now "QDockWidgets".
> widget class="QDockWidget" name="qdwChat"

Interesting things i see are:
(remember i don't have a clue what these things do :smile: )

* x is set to zero
 property name="geometry"
 x>0

* sizeIncrement: both zero

* baseSize: both zero

* minimum expension, also zero:
property name="sizePolicy"
     sizepolicy hsizetype="Expanding" vsizetype="MinimumExpanding"
      horstretch>0</horstretch
      verstretch>0</verstretch

**Comment by dstensnes** [comment] 2020-05-07 22:55
I have had this problem for quite some time now, but I usually keep mumble open, so I has not been that bothered with it. I did however check my settings in "User Interface". I had it set to "Custom", and it seems to me the problem is only present when it is set to "Custom". Could that be the case? I have it set up to be a mirror of the "classic" layout, with the User/Channel list on the left (i guess it was an attempt at getting the chat box to resize instead of the User/Channel list, which didn't work, but I stuck with it anyway)

**Comment by Krzmbrzl** [comment] 2020-05-08 05:36
It might have something to do with this but it seems like it is not the only cause. I just switched my Mumble to a "custom" layout and the chatbox remained working as expected...

**Comment by toby63** [comment] 2020-05-08 15:09
I want to remind that I use the default layout and I guess many others do as well.
The pictures from the reporter indicate this too.

@dstensnes 
* What OS are you using?
* And what version of Qt (in case you don't know, visible in -> Help -> about Qt)?

@Krzmbrzl 
By the way, are you using X-Server or Wayland? (don't know if thats even important/related, but maybe)

**Comment by Krzmbrzl** [comment] 2020-05-08 18:48
I'm using X

**Comment by dstensnes** [comment] 2020-05-09 15:45
I'm using Xorg on Debian 10. I have compiled mumble from master branch, currently at commit bc112e56242f1a1fcefc7ce1fd70b2216c470d8f
It is using qt 5.11.3

**Comment by dstensnes** [comment] 2020-05-12 20:57
Hmm, yeah, I suppose it could be because it has been moved or something. Could it be because another element has 100% height defined as default or something like that?

**Comment by Krzmbrzl** [comment] 2020-05-13 06:06
I honestly have no idea what the cause might be. And given that I can't reproduce this error, it's very hard to debug.
Thus if someone of you (who has the problem) was able to poke around in the code (add some log statements, change some sizing values, etc) that'd be a great help :point_up:

**Comment by toby63** [comment] 2020-05-13 15:28
> Thus if someone of you (who has the problem) was able to poke around in the code (add some log statements, change some sizing values, etc) that'd be a great help point_up

Above you said you wanted to test it in a vm first.
But if we should test something, just give some instructions or hints what to do.
I guess someone will try.

**Comment by Krzmbrzl** [comment] 2020-05-13 16:22
> Above you said you wanted to test it in a vm first.

Yeah well I don't have the time to do so right now :see_no_evil: 

> But if we should test something, just give some instructions or hints what to do.

Don't have the time for this atm either. If nobody steps forward that can debug this problem more or less on their own, I think we'll have to postpone the debugging...
But thanks for the offer :)

**Comment by toby63** [comment] 2020-05-13 20:26
> Yeah well I don't have the time to do so right now :see_no_evil:

No offence meant. It just sounded like no one has offered to to something.

> Don't have the time for this atm either. If nobody steps forward that can debug this problem more or less on their own, I think we'll have to postpone the debugging...

It's only a minor bug imo, but to be honest:
Even if I got the time to dig into it, it would probably be a waste of (very much) time, because I don't have any clue :rabbit:.
I think someone "should" do it, who at least knows a little bit about where to search :superhero:.
So I guess we wait, until someone has time :slightly_smiling_face:.

**Comment by toby63** [comment] 2020-05-17 16:03
Would a Debugging build be enough?
https://wiki.mumble.info/wiki/Debugging

**Comment by Krzmbrzl** [comment] 2020-05-17 16:42
For debugging this problem? Not really, no. You'd have to add some debug print statements into the UI code in order to figure out where the size gets set to what value and why...

**Comment by felix91gr** [comment] 2020-06-09 06:06
I'm testing the snapshot of June 9th (commit `7c67ea33`), in Linux, and I'm getting this exact same thing:

> (...) the bottom left textbox to send messages to channel isn't displayed when first starting (...) If I go to the Configure --> Settings... menu and then click Apply, the textbox reappears (...)

My OS is:
- elementary OS 5.1.5 Hera
- Built on Ubuntu 18.04.4 LTS
- Linux 4.15.0-99-generic

**Comment by Krzmbrzl** [comment] 2020-06-09 08:09
@felix91gr what Qt version did fix the problem for you (which one did you compile into master)?

**Comment by felix91gr** [comment] 2020-06-09 18:22
@Krzmbrzl `5.9.5` :)

**Comment by toby63** [comment] 2020-06-09 19:03
@felix91gr  Can you give us the exact commit?
And also the exact build options you used?

**Comment by felix91gr** [comment] 2020-06-09 20:27
@toby63 I basically downloaded the 1.4.0-based fork of @davidebeatrici for `cmake`-based compilation and compiled mumble from that:

```console
git clone https://github.com/davidebeatrici/mumble.git mumble_1_4_0_testing
cd mumble_1_4_0_testing
git checkout cmake
git submodule update --init --recursive
sudo apt-get -y install build-essential ninja-build pkg-config \
       qt5-default qttools5-dev qttools5-dev-tools libqt5svg5-dev \
       libboost-dev libssl-dev libprotobuf-dev protobuf-compiler \
       libcap-dev libxi-dev \
       libasound2-dev libpulse-dev \
       libogg-dev libsndfile1-dev libspeechd-dev \
       libavahi-compat-libdnssd-dev libzeroc-ice-de
mkdir build && cd build
cmake ..
cmake --build .
./mumble
```
The commit I compiled is `1328c3898ecb`, from David's fork.
My `cmake` version is `3.17.3`

**Comment by dennisschagt** [comment] 2020-08-01 09:19
I think I found the issue.

https://github.com/mumble-voip/mumble/blob/3a07016b8fb4f902b778c1d74cbb13cab25fa93a/src/mumble/CustomElements.cpp#L137-L142

The calls to `document()->documentLayout()->documentSize().height())` return `0` as long as the window is not yet visible.
This makes the configured maximum height to be `0` in the next line.

I'm using i3wm as a window manager.
My guess is that i3wm (and some other window managers) don't configure a width and height as long as the window is not shown (or until some other step in window creation).

**Comment by Krzmbrzl** [comment] 2020-08-01 14:49
Good catch @dennisschagt! :+1:

**Closed** 2020-08-02 14:02 UTC
Labels: bug, client, help wanted, priority/P2 - Important, ui
