### ISSUE TITLE
Downgrading version without uninstalling not possible

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#4085] opened 2020-04-20 12:44 UTC
Here's what happens when I try to downgrade from 1.3.1 rc1 to 1.3.0:

![image](https://user-images.githubusercontent.com/42674312/79752984-72b15e80-8315-11ea-8668-b377379f95d1.png)

As far as I know, this did not happen when trying to downgrade a version before.

**Comment by ZeroAbility** [comment] 2020-04-20 20:05
I believe this is by design with MSI files when the version number is not increased:

https://www.advancedinstaller.com/forums/memberlist.php?mode=viewprofile&u=11838

**Comment by toby63** [comment] 2020-04-20 20:31
@ZeroAbility: Link requires login.

**Comment by ZeroAbility** [comment] 2020-04-20 20:34
> @ZeroAbility: Link requires login.

My mistake. I updated the link. In any case, the installer project for the RC needs to have the version string changed. Appears to be a bug. I am not using the older build environment so I won't be able to test it.

**Comment by Krzmbrzl** [comment] 2020-04-21 07:18
I just double-checked but I just can't find any place in which the version number hasn't been changed...

@ZeroAbility do you happen to know where the wrong version number would most likely be? In the binary or somewhere in the installer?

**Comment by trudnorx** [comment] 2020-04-21 07:25
"<Product Id="*" Name="$(var.ProductName) $(var.ProductVersion)" Language="!(loc.LANG)" Version="$(var.ProductVersion)" Manufacturer="$(var.ProductManufacturer)" UpgradeCode="$(var.ProductUpgradeCode)">" in Product.wxs

I guess this is what is producing the output "Mumble 1.3.0" in the error dialog, but apparently ProductVersion is "3.5" in MumbleInstall.wixproj? What is 3.5?

**Comment by Krzmbrzl** [comment] 2020-04-21 07:27
> What is 3.5?

I stumbled upon this version number as well and figured it might be the WiX version number this file has been created with/for? Duno though :shrug:

**Comment by Krzmbrzl** [comment] 2020-04-21 07:32
From my understanding the `ProduceVersion` variable should be the one defined here
https://github.com/mumble-voip/mumble/blob/dd9c261c521893f68bb75b1cd762aa7a6a873b56/installer/Settings.wxi#L5

but obviously it is not, given that the title says `1.3.0`

**Comment by trudnorx** [comment] 2020-04-21 07:37
> Wait a sec... @trudnorx is the screenshot you posted from the downgrade process? So is the shown installer window the actual `1.3.0` installer?

Yes. So, one confusing thing is it's saying "a later version of Mumble 1.3.0 is already installed" instead of "a later version of Mumble is already installed". But the thing is, I remember other versions letting me downgrade without uninstalling first, so this shouldn't be happening, or maybe I'm actually misremembering that...

Either way, optimal would be to make it so that it allows downgrading without uninstalling, for example because of things like uninstalling can delete some files...

**Comment by Krzmbrzl** [comment] 2020-04-21 07:43
Hm from what zeroability stated and from what is written in the linked forum, this seems to be a limitation of Windows installers in general: They just won't let you install older versions of a product as long as newer ones are installed already...

I'm not a Windows guru so I don't know if this is in fact true, but if it is, then it seems to me that the 1.3.1 install has worked just fine and now it's a limitation of Windows that prevents you from a simple downgrade :thinking:

**Comment by Krzmbrzl** [comment] 2020-04-23 16:46
As the current info seem to indicate that this is nothing we can fix, I'll close this issue.

If you find evidence of the contrary, please let me know :)

**Closed by Krzmbrzl** 2020-04-23 16:46 UTC
Labels: installer
