### ISSUE TITLE
Odd issues with users who autojoin in a channel with "deny" text message

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#968] opened 2013-03-09 23:57 UTC
If someone logs out in a channel with "Text message" - Deny set, when they log back in and move channel they can't type in the message bar if any channel is highlighted (regardless of "use selected item as chat bar target" setting)

With "use selected..." set, they can message the current channel by highlighting their name, or message other users as normal.  With it unset, they can message the current channel as long as any user is selected.

If the user has the "edit ACL" rights in the channel (specific or inherited), these bugs do not occur.

Right-clicking on a channel the user should be able to message restores normal behaviour

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/968/ ._

**Comment by davidebeatrici** [comment] 2018-07-17 05:44
#3465

**Comment by Hartmnt** [comment] 2022-10-06 12:29
Seems to be a duplicate of #1799

**Closed** 2022-10-07 12:00 UTC
Labels: client, bug
