### ISSUE TITLE
%3A

### ISSUE THREAD

**Issue by Azytheoneandonly** [mumble-voip/mumble#3371] opened 2018-03-13 07:07 UTC
**%3A** in a URL changes to  **:**  in Chrome(unsure if in any other browser) and breaks the link by making it invalid.

**Comment by davidebeatrici** [comment] 2018-03-13 08:13
**%3A** corresponds to **:** in the URL encoding.

If the link is valid, you should be able to access it by using either **%3A** or **:**, because it's converted by the browser.

**Comment by Azytheoneandonly** [comment] 2018-03-13 16:13
https://scontent.fadl1-1.fna.fbcdn.net/v/t1.0-9/29101840_10155685996324355_4591307223241588736_n.jpg?_nc_eui2=v1%3AAeEWudYE_k9G2HAcXYcJGHRCqNFte1HTS-7en5MJS9sTLR2ItmIIxDu6aM3UosYjh1Ccz9vzzG_gm1D-Y_Gmd6Jm_K04gjNnH0PRNrKt-NXAzQ&oh=1f9025678d94a4a30e8ad2bf87b899d4&oe=5B4C4564

was the link someone posted on my mumble server if you would like to test it out in mumble. anyway thanks for the response.

**Comment by mkrautz** [comment] 2018-03-13 18:30
Is this on macOS? You don't state which OS it is, and we've seen problems like this on macOS before.

**Comment by Azytheoneandonly** [comment] 2018-03-14 05:27
Windows 10 sorry.

**Comment by mkrautz** [comment] 2018-03-18 17:16
I have not been able to test 1.2.19 yet, but I couldn't reproduce with 1.3.0.

**Comment by jzelinskie** [comment] 2018-05-18 04:17
Any URL with a % in it on Windows 10 Mumble 1.2.19 cannot be opened by clicking.
The same URL on Mac works.

**Comment by Rovanion** [comment] 2022-01-30 20:37
Seems like the bug persists in Mumble 1.4.230 on Windows 10.

**Comment by Snowknight26** [comment] 2022-07-14 04:06
Was looking to fix this myself since it's an issue in 1.4.230 and.. after all this time I see that it's fixed with 727049c52681eeccca5d7dbec6997cb6fe92cea1. Would love to have the fix backported.

**Comment by Krzmbrzl** [comment] 2022-07-14 20:42
Ah nice. Thanks for letting us know :+1:

**Closed** 2022-07-14 20:42 UTC
