### ISSUE TITLE
Mumble segfaults when trying to change audio settings under PipeWire

### ISSUE THREAD

**Issue by KynikossDragonn** [mumble-voip/mumble#6105] opened 2023-04-11 20:30 UTC
### Description

When using PipeWire for all audio (both Input and Output) trying to change any setting whatsoever and hitting either "Apply"  or "OK" will cause a segfault, no settings changed or saved to config.

It crashes even if no settings were changed at all and you pressed either "Apply" or "OK" to close the window instead of "Cancel".

### Steps to reproduce

1. Open the settings window.
2. Hit either "Apply" or "OK".

### Mumble version

1.4.287

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Using PipeWire 0.3.68.

GDB backtrace:
```
[Switching to thread 1 (Thread 0x7ffff469e800 (LWP 28920))]
#0  0x000055555758dac0 in ?? ()
#0  0x000055555758dac0 in ?? ()
#1  0x00007fffea4136d2 in ?? () from /usr/lib/libpipewire-0.3.so
#2  0x00007fffea415d7e in pw_stream_destroy () from /usr/lib/libpipewire-0.3.so
#3  0x0000555555846653 in ?? ()
#4  0x0000555555846858 in ?? ()
#5  0x00005555556547f9 in ?? ()
#6  0x000055555569f102 in ?? ()
#7  0x00005555556a0a3e in ?? ()
#8  0x00007ffff5eeb8ac in ?? () from /usr/lib/libQt5Core.so.5
#9  0x00007ffff78ff678 in ?? () from /usr/lib/libQt5Widgets.so.5
#10 0x00007ffff5eeb8ac in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff7855222 in QAbstractButton::clicked(bool) () from /usr/lib/libQt5Widgets.so.5
#12 0x00007ffff785548a in ?? () from /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff7857018 in ?? () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff7857237 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff77a4cf8 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff7762fce in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#17 0x00007ffff776b562 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff5eb3ea8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#19 0x00007ffff776966e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff77bdb28 in ?? () from /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff77c0eb0 in ?? () from /usr/lib/libQt5Widgets.so.5
#22 0x00007ffff7762fce in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff5eb3ea8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#24 0x00007ffff633f8fd in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#25 0x00007ffff6312dec in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#26 0x00007ffff211a72a in ?? () from /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5
#27 0x00007ffff54e3d9d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#28 0x00007ffff54e4048 in ?? () from /usr/lib/libglib-2.0.so.0
#29 0x00007ffff54e40dc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#30 0x00007ffff5f0c0a6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#31 0x00007ffff5eb291b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#32 0x00007ffff796ca57 in QDialog::exec() () from /usr/lib/libQt5Widgets.so.5
#33 0x00005555557126b8 in ?? ()
#34 0x0000555555607063 in ?? ()
#35 0x00007ffff5eeb582 in ?? () from /usr/lib/libQt5Core.so.5
#36 0x00007ffff775c7d2 in QAction::triggered(bool) () from /usr/lib/libQt5Widgets.so.5
#37 0x00007ffff775f3fb in QAction::activate(QAction::ActionEvent) () from /usr/lib/libQt5Widgets.so.5
#38 0x00007ffff78e4a52 in ?? () from /usr/lib/libQt5Widgets.so.5
#39 0x00007ffff78ec864 in ?? () from /usr/lib/libQt5Widgets.so.5
#40 0x00007ffff77a4cf8 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#41 0x00007ffff7762fce in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#42 0x00007ffff776b562 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#43 0x00007ffff5eb3ea8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#44 0x00007ffff776966e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /usr/lib/libQt5Widgets.so.5
#45 0x00007ffff77bdf75 in ?? () from /usr/lib/libQt5Widgets.so.5
#46 0x00007ffff77c0eb0 in ?? () from /usr/lib/libQt5Widgets.so.5
#47 0x00007ffff7762fce in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#48 0x00007ffff5eb3ea8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#49 0x00007ffff633f8fd in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
#50 0x00007ffff6312dec in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
#51 0x00007ffff211a72a in ?? () from /usr/lib/qt5/plugins/platforms/../../../libQt5XcbQpa.so.5
#52 0x00007ffff54e3d9d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#53 0x00007ffff54e4048 in ?? () from /usr/lib/libglib-2.0.so.0
#54 0x00007ffff54e40dc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#55 0x00007ffff5f0c0a6 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#56 0x00007ffff5eb291b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#57 0x00007ffff5ebaa86 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#58 0x00005555555cdb1e in ?? ()
#59 0x00007ffff564120c in __libc_start_call_main (main=main@entry=0x5555555f02e0, argc=argc@entry=1, argv=argv@entry=0x7fffffffe708) at ../sysdeps/nptl/libc_start_call_main.h:58
#60 0x00007ffff56412bc in __libc_start_main_impl (main=0x5555555f02e0, argc=1, argv=0x7fffffffe708, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe6f8) at ../csu/libc-start.c:381
#61 0x00005555555f42b1 in ?? ()
```

### Relevant log output

```shell
[New Thread 0x7ffff1dff6c0 (LWP 29153)]
[New Thread 0x7ffff15fe6c0 (LWP 29154)]
[New Thread 0x7fffebc896c0 (LWP 29155)]
[New Thread 0x7fffeb4886c0 (LWP 29156)]
[New Thread 0x7fffeac876c0 (LWP 29157)]
<X>2023-04-11 15:23:39.149 PipeWire 0.3.68 from libpipewire-0.3.so
<D>2023-04-11 15:23:39.154 libopus 1.3.1 from libopus.so.0
<W>2023-04-11 15:23:39.157 CELT bitstream 8000000b from /usr/lib64/mumble/libcelt0.so.0.7.0
<W>2023-04-11 15:23:39.157 Theme: "Mumble"
<W>2023-04-11 15:23:39.157 Style: "Lite"
<W>2023-04-11 15:23:39.157 --> qss: ":themes/Mumble/Lite.qss"
<W>2023-04-11 15:23:39.158 Locale is "en_US" (System: "en_US")
[New Thread 0x7fffea3276c0 (LWP 29159)]
<W>2023-04-11 15:23:39.312 Database SQLite: "3.41.2"
<W>2023-04-11 15:23:39.752 Updating application palette
<W>2023-04-11 15:23:39.766 GlobalShortcutX: Using XI2 2.4
[New Thread 0x7fffe96df6c0 (LWP 29161)]
[New Thread 0x7fffe8ede6c0 (LWP 29162)]
<W>2023-04-11 15:23:39.853 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
[New Thread 0x7fffcde9d6c0 (LWP 29163)]
[New Thread 0x7fffcd69c6c0 (LWP 29164)]
[New Thread 0x7fffcce9b6c0 (LWP 29165)]
[New Thread 0x7fffb3fff6c0 (LWP 29166)]
[New Thread 0x7fffb37fe6c0 (LWP 29167)]
[New Thread 0x7fffb2ffd6c0 (LWP 29168)]
[New Thread 0x7fffb27fc6c0 (LWP 29169)]
[New Thread 0x7fffb1ffb6c0 (LWP 29170)]
[New Thread 0x7fffb17fa6c0 (LWP 29171)]
<W>2023-04-11 15:23:40.071 SocketRPC: Removing old socket on "/run/user/1000/MumbleSocket"
<W>2023-04-11 15:23:41.545 AudioInput: Opus encoder set for low delay
<W>2023-04-11 15:23:41.545 AudioInput: 192000 bits/s, 48000 hz, 480 sample
[New Thread 0x7fff9bfff6c0 (LWP 29173)]
<W>2023-04-11 15:23:41.582 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
[New Thread 0x7fff9b7fe6c0 (LWP 29174)]
[New Thread 0x7fff9affd6c0 (LWP 29175)]
[Thread 0x7fff9affd6c0 (LWP 29175) exited]
[New Thread 0x7fff9affd6c0 (LWP 29176)]
<W>2023-04-11 15:23:41.583 AudioOutput: Initialized 2 channel 48000 hz mixer
[New Thread 0x7fff9a7fc6c0 (LWP 29177)]
[New Thread 0x7fff99ffb6c0 (LWP 29178)]
[Thread 0x7fff99ffb6c0 (LWP 29178) exited]
[New Thread 0x7fff99ffb6c0 (LWP 29179)]
[Thread 0x7fff99ffb6c0 (LWP 29179) exited]
<W>2023-04-11 15:23:41.592 Zeroconf: Third-party browser API reports error -65537
<W>2023-04-11 15:23:41.664 AudioInput: Noise canceller disabled
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2023-04-11 15:23:45.212   OpenType support missing for "Tahoma", script 20
<W>2023-04-11 15:23:45.225   OpenType support missing for "Tahoma", script 17
<W>2023-04-11 15:23:45.419   OpenType support missing for "Segoe UI", script 20
[New Thread 0x7fff99ffb6c0 (LWP 29181)]
[New Thread 0x7fff849ff6c0 (LWP 29182)]
[New Thread 0x7fff7ffff6c0 (LWP 29183)]
[New Thread 0x7fff7f7fe6c0 (LWP 29184)]
[Thread 0x7fff9b7fe6c0 (LWP 29174) exited]

Thread 1 "mumble" received signal SIGSEGV, Segmentation fault.
```

**Comment by davidebeatrici** [comment] 2023-04-12 03:28
Duplicate of #6101.

**Closed by davidebeatrici** 2023-04-12 03:28 UTC
Labels: bug, triage
