### ISSUE TITLE
Markdown list context does not end between messages

### ISSUE THREAD

**Issue by mweinelt** [mumble-voip/mumble#4986] opened 2021-05-11 21:48 UTC
**Describe the bug**
After using `!help` from botamusique new messages to the channel are part of a markdown list.

**Steps to Reproduce**
1. Install botamusique
2. Use `!help`
3. Write to the channel
4. See how your message is part of the markdown list

**Expected behavior**
The markdown list context should end with each message

**Screenshots**
![20210511_23h45m01s_grim](https://user-images.githubusercontent.com/131599/117888933-0d7b3300-b2b3-11eb-9901-8f9d40af3406.png)

**Desktop (please complete the following information):**
 - OS: NixOS Unstable
 - Version: 8e89110025eee14ddb81e0c2acaebd6b4339dbb1

**Additional context**
n/a

**Comment by Krzmbrzl** [comment] 2021-05-12 07:11
Duplicate of #4491

**Closed by Krzmbrzl** 2021-05-12 07:11 UTC
