### ISSUE TITLE
Other users posting images causes Mumble to scroll up in chat

### ISSUE THREAD

**Issue by archer007** [mumble-voip/mumble#5630] opened 2022-04-21 01:53 UTC
### Description

Other users posting images causes Mumble to scroll up in chat, effectively hiding the image and making it so that you need to manually scroll the window down again

### Steps to reproduce

1. Connect to any Mumble server
2. Join any channel
3. Have someone fill the chat window with a mix of text and images
4. Have someone send a picture
5. The Mumble chat window snaps to a previous point in the chat when a new image is posted

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

It's very annoying when using Mumble for a mixed text, image, and voice chat to have to manually scroll the chat window down after anyone posts an image

**Comment by archer007** [comment] 2022-08-22 23:43
Current workaround is to downgrade to Mumble 1.3.4

**Comment by hashworks** [comment] 2022-10-28 13:14
I'm currently trying to bisect this – basically we know that stuff worked in b6353420f209a97bea9d2e9ea04d41554cf371e6 (1.3.4) and failed somewhere on the way to 8505df958fc16a6f3ad902d84aed415742c5bb20 (1.4.230).

@archer007 It's a bit hard to reproduce this, do you have a bulletproof way to trigger the bug?

**Comment by Krzmbrzl** [comment] 2022-10-28 15:02
@hashworks isn't the bug reproducible simply by connecting with a second client to the same server and then sending an image to the channel your first client is in? :thinking:

**Comment by hashworks** [comment] 2022-10-28 15:17
Not really - for me and others it only happens after a while. I can't really reproduce it just by others spamming some pictures.

**Comment by Krzmbrzl** [comment] 2022-10-28 15:26
For context: I asked whether this was not trivially reproducible as stated in the initial report. I then thought some more on it and deleted my question again. But apparently hashworks was too fast in answering my question, so deleting it came too late ^^

**Comment by hashworks** [comment] 2022-12-18 20:06
Maybe this is also a duplicate of #2504 / #4638 and can be resolved with upstream issue https://bugreports.qt.io/browse/QTBUG-83622 ?

**Comment by Krzmbrzl** [comment] 2022-12-19 07:02
Ah yes indeed. I would agree that this seems to be the very same bug. Unfortunately, Qt has not actually bothered fixing this yet. Maybe it's fixed with Qt6, but we'll only find out once we actually move to using it.

In any case, I'll close this as a duplicate of #2504

**Closed by Krzmbrzl** 2022-12-19 07:02 UTC
Labels: client, ui, bug

**Comment by hashworks** [comment] 2024-03-01 19:24
@Krzmbrzl Are there plans to switch to Qt6 in the future? Otherwise, I guess it might make sense to look for a workaround, I don't think anyone will fix [QTBUG-83622](https://bugreports.qt.io/browse/QTBUG-83622).

**Comment by Krzmbrzl** [comment] 2024-03-01 20:09
Yes we definitely want to migrate to Qt6 eventually. There is some maintenance work to do before that is possible though
