### ISSUE TITLE
Automatically reload SSL certificate on change

### ISSUE THREAD

**Issue by dabruh** [mumble-voip/mumble#5987] opened 2022-12-09 21:57 UTC
### Context

Seamless integration in containerized environments

### Description

We currently support [Live reload of Murmur SSL settings via SIGUSR1](https://github.com/mumble-voip/mumble/pull/2850), but I struggle to figure out how we can automatically send this SIGUSR1 signal in a scenario where we're running two Docker Compose services (containers) where one is the Mumble server, and another a container that handles the certificate renewal against a shared volume of the two containers.

I thus propose that the Mumble server does periodic checking (or listens for FS events) of the SSL certificate file and automatically tries to reload it when it's modified.

This is related to https://github.com/mumble-voip/mumble-docker/issues/28

### Mumble component

Server

### OS-specific?

No

**Comment by Krzmbrzl** [comment] 2022-12-10 07:27
Duplicate of #4544

**Closed by Krzmbrzl** 2022-12-10 07:27 UTC
Labels: feature-request, triage
