### ISSUE TITLE
Would like Mumble 1.2.8 or 1.3.0 without ASIO

### ISSUE THREAD

**Issue by jtl999** [mumble-voip/mumble#1516] opened 2015-01-06 02:08 UTC
I noticed on the 1.2.5 known issues page you had an issue open related to ASIO freezing and I kind of have similar issues with 1.3.0. Please compile Mumble without ASIO please.

**Comment by mirhl** [comment] 2015-01-07 20:09
So, you have kind of similar issues ASIO must be the reason....

You know.. it's not like if you could provide more information we couldn't help you better

**Comment by mkrautz** [comment] 2015-01-07 20:25
It's likely he actually has ASIO issues :-)

Anyway, we will provide a way to disable ASIO for 1.2.9 and 1.3.x.
We'd like to keep shipping the builds with ASIO, so we will probably have a hidden setting to disable it.

I will land this feature soon, and I'll do a 1.2.x snapshot to go along with it. Should happen this week, I hope.

**Comment by mirhl** [comment] 2015-01-07 21:59
Should I assume ASIO is always initialized even on "normal" systems then?

It's pretty lame indeed, considering this feature could interest *perhaps* less than 1% of users :p

**Comment by mkrautz** [comment] 2015-01-07 22:04
Err. Well, the binary is linked against the Steinberg ASIO SDK. It queries whether there are any ASIO devices in the system, and if so, ASIO is enabled.

We've previous received reports of capture cards that provide ASIO capabilities having issues causing freezing, which is why the entry is there in the Known Issues in the Wiki.

This could be something along those lines...

**Comment by jtl999** [comment] 2015-01-08 01:11
I have a FiiO E10K USB DAC which uses it's own ASIO driver (works quite nicely for everything, except Mumble) Also thinking of getting M-Audio mic interface.

**Comment by Boxx1e** [comment] 2015-01-25 07:07
Freezing and causing kb and mouse freeze with my HifimeDIY Sabre u2 asynchronous dac so would like a build without ASIO

**Comment by mkrautz** [comment] 2015-01-25 09:15
My current status on this is that I requested access to the Steinberg SDK a couple of weeks ago, and I haven't heard back yet.  The idea was that the ancient SDK we're using might be the cause of these problems.

I've created https://github.com/mumble-voip/mumble/pull/1542 as a workaround for these issues until we get to the bottom of this.

Should be in snapshots soon, once reviewed.  Might also backport to 1.2.x.

Sorry for the wait...

**Comment by mkrautz** [comment] 2015-01-25 09:17
Alternatively, you could use the x64 snapshot builds for 1.3.x. They are built without ASIO because we're missing an x64 SDK, still (haven't heard from Steinberg):

https://github.com/mumble-voip/mumble-releng/blob/master/buildscripts/1.3.x/mumble-win64-static.cmd#L19

Downloads are available on the main page of the Wiki: http://wiki.mumble.info/wiki/Main_Page

**Comment by mirh** [comment] 2016-05-07 15:50
Did Steinberg ever reply back?

**Comment by mkrautz** [comment] 2016-05-07 16:21
Yes, it is now. :-) Previously, you had to register.

We also just download it from their website in the build environment, now.

Builds are using the latest SDK.

1.3.0 on x64 have ASIO on.

The 'asio/enable' flag has been available for some time as well.

Are people having problems with ASIO still?

Note also blacklisting of misbehaving DACs in GlobalShortcut_win:
https://github.com/mumble-voip/mumble/commit/44fd4e6493202da98ecaf073418686fbd7451e47 (both in 1.2.x and 1.3.0)

**Comment by mirh** [comment] 2016-05-07 17:07
Yes, I'm still having both #1473 and #1113
If you hadn't noticed, I found out everybody with a Realtek DSP can now try native ASIO (which has the same problems of my Xonar)

**Comment by davidebeatrici** [comment] 2017-12-02 23:17
As pointed out by @mirh, this is resolved by #1542.

**Closed by davidebeatrici** 2017-12-02 23:17 UTC
Labels: discussion, mumble
