### ISSUE TITLE
Overlay not functioning

### ISSUE THREAD

**Issue by knight2142** [mumble-voip/mumble#4290] opened 2020-06-13 20:29 UTC
Overlay worked on perfectly with 1.3.0, updated to 1.3.1 and overlay not functioning for FFXIV.

I have tried various whitelist approaches, but nothing has shown the overlay.

**Comment by Krzmbrzl** [comment] 2020-06-14 06:38
Duplicate of #4281

**Closed by Krzmbrzl** 2020-06-14 06:38 UTC
