### ISSUE TITLE
Multiple Certificates & Certificate Switcher

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#4799] opened 2021-02-27 03:50 UTC
Please allow us to have multiple certificates imported into Mumble and be able to switch between which certificate to use. Essentially an account switcher. Obviously you will not be able to switch to another certificate when your connected to a server.

Will be nice rather than having to import the certificate every time you want to switch accounts.

**Comment by Krzmbrzl** [comment] 2021-02-27 15:01
This is a duplicate of #2107 

But nonetheless I agree that this is a desirable feature.

**Closed by Krzmbrzl** 2021-02-27 15:01 UTC
