### ISSUE TITLE
Website issue: new users download dev snapshot by mistake

### ISSUE THREAD

**Issue by trustable-code** [mumble-voip/mumble#1759] opened 2015-07-21 15:45 UTC
I have seen many people, who use Windows x64, are completely new to Mumble and download the development snapshot, without knowing that his is not recommended for new users.
Please make it more clear for newbies, that they should download the stable version.
Possible solutions:
* Remove the dev snapshot links from the table and move them to a sub page.
* Make an optical difference between links to the stable and the dev snapshot.
* In the row of Windows x64, in the column Stable, place a link to 1.2.10 or use a row-span between the table cells.

**Comment by Tarun80** [comment] 2015-07-21 18:26
If anything, a background color for the snapshots would be sufficient. It's really not their fault people can't read, though. It quite clearly says development snapshot and there's more than sufficient space

**Comment by trustable-code** [comment] 2015-07-22 09:01
The main problem: There is no stable version shown for Windows x64. Many users know, that they have a 64 bit Windows, but they don't know what it means or that they can use the 32 bit version of Mumble. When they look for "Mumble for Windows x64", they only find the dev snapshot download link. This needs to be changed!

**Comment by mkrautz** [comment] 2015-07-23 10:13
I've added the 32-bit stable build as "Windows x64" on the front page now.

Also added OS X Universal to the stable links.

**Comment by Tarun80** [comment] 2015-07-23 17:22
@mkrautz, I disagree with that as it's a misleading solution. People may look at that and expect that to be a stable x64 version and may get upset that an x86 version is in the x64 stable slot.

**Comment by mkrautz** [comment] 2015-07-23 18:57
Someone else should make a decision...

**Comment by trustable-code** [comment] 2015-07-23 22:28
@Tarun80, the normal user doesn't care if it's a x64 or x86 version, he just wants a version that runs. Therefor I think the change by mkrautz was good. I see regularly new users, who download the dev snapshot by mistake and have some problems with it, until they change the stable version.

**Comment by Tarun80** [comment] 2015-07-24 09:05
Might be able to make a few edits to the tables that exist and add a cell color via CSS. Perhaps a green for stable and a blue for snapshots. I'll look into hex codes for this though and draft something.

**Comment by hacst** [comment] 2015-07-24 20:54
/me mumbles something about "that landing page needing a serious redesign and that the download stuff should be one very big (stable client), one smaller button (stable server) and two even smaller ones (client/server snapshot) with sane settings detected from the useragent. The table should only visible as a fallback or on explicit user request." Then /me slowly fades into the background because he's to lazy to do the work

**Comment by Tarun80** [comment] 2015-07-24 21:36
Is there a way to view the <mumblelatest></mumblelatest> directly?

**Comment by Tarun80** [comment] 2015-07-27 19:17
@mkrautz, do you know how I could access and view the ```<mumblelatest>``` section to make an editable copy?

**Comment by mkrautz** [comment] 2015-07-27 19:44
Oops, thanks for the ping.

The <mumblelatest> is a Mediawiki extension that we've made. It feeds from a script that we generate on our release servers, snapshot.php. This file is then transferred to the Mediawiki instance and used for the <mumblelatest> tag.

Here's a snippet of the PHP script that's used for mumblelatest:

	function mumbleLatestData() {
	  return "{|class=\\"wikitable\\" style=\\"margin-left: 30px; margin-bottom: 30px; margin-top: 10px; min-width: 650px;\\"
	!style=\\"text-align: left;\\"|OS
	!style=\\"text-align: left;\\"|Stable Release
	!style=\\"text-align: left;\\"|Development Snapshot
	|-
	|Windows
	|[$win32r $version]
	|[http://mumble.info/snapshot/mumble-$win32.msi $win32]
	|-
	|Windows x64
	|[$winx64r $version]
	|[http://mumble.info/snapshot/mumble-$winx64.winx64.msi $winx64]
	|-
	|OS X
	|[$osxr $version]
	|[http://mumble.info/snapshot/Mumble-$osx.dmg $osx]
	|-
	|OS X (Universal, Legacy)
	|[$osxur $version]
	|[http://mumble.info/snapshot/Mumble-Universal-$osxu.dmg $osxu]
	|-
	|Ubuntu
	|[https://launchpad.net/~mumble/+archive/release Stable Release PPA]
	|[https://launchpad.net/~mumble/+archive/snapshot Snapshot PPA]
	|-
	|iOS
	|[$iosr $iosver]
	|
	|-
	|Static Linux Server
	|[$staticr $version]
	|[http://mumble.info/snapshot/murmur-static_x86-$static.tar.bz2 $static]
	|-
	|Static OS X Server
	|[$osxstaticr $version]
	|[http://mumble.info/snapshot/Murmur-OSX-Static-$osxstatic.tar.bz2 $osxstatic]
	|}
	:*<span class=\\"plainlinks\\">[[1.2.10\|What's new?]]</span>
	:*<span class=\\"plainlinks\\">[https://github.com/mumble-voip/mumble/releases/tag/1.2.10 Download Source Code]</span>
	:*<span class=\\"plainlinks\\">[http://mumble.info/gpg/gpg.txt GPG signatures]</span>
	:*<span class=\\"plainlinks\\">[https://github.com/mumble-voip/ View Git Repositories]</span>
	";
	}

**Comment by Tarun80** [comment] 2015-07-27 20:02
I'm going to see if perhaps I can draft something new that might work a bit better. It may take some time, but I'll do what I can. Thanks @mkrautz!

**Comment by Tarun80** [comment] 2015-07-27 21:06
Drafted and made a few minor changes. Colors are based off of [this template](http://wiki.mumble.info/wiki/Template:ReleaseTimeline).


![First draft of new table](http://i.imgur.com/r97i4KT.png)

**Comment by Tarun80** [comment] 2015-07-29 13:55
@mkrautz @hacst - if the above changes look good let me know and I'll get the code over to you guys. If you like, I can also work on a new main landing page for the Mumble project in my spare time. Let me know if there's any project colors to use (such as the ones in Mumble Metro) and I'll see what I can style and work up.

**Comment by JoelTroch** [comment] 2015-08-04 11:59
@Tarun80 IMO, I think it would be great to precise the "Windows" builds like this:
* Windows --> Windows x86 (32 bits)
* Windows --> Windows x64 (64 bits)

**Comment by Tarun80** [comment] 2015-08-04 16:27
Joel, I considered this but felt it would be redundant overall since the 64 bit version is very clearly specified. However, it's all according to what the Mumble Team would want as far as that goes. I personally believe the information provided in the screenshot is clear and sufficient.

**Comment by Tarun80** [comment] 2015-08-24 07:18
@mkrautz and @hacst - any feedback on this?

**Comment by hacst** [comment] 2015-08-26 20:35
Sorry for the delay. Will take a proper look this weekend.

**Comment by Tarun80** [comment] 2015-08-27 20:22
@hacst - I still have the Wiki code (and can make it PHP code if need be) saved if you like the changes I've proposed.

**Comment by hacst** [comment] 2015-08-30 18:33
While I prefer the new design to the existing one imho we should go a step further and directly offer the most likely stable version a user wants with a big button. The table should only be shown on user request or when we cannot figure out or do not support the platform.

E.g. if you go to https://www.mozilla.org/en-US/firefox/new/ they detect your platform using Javascript and only show you the download button matching yours (though I think this specific design is quite poor as there is no easy way to get to the other downloads).

To implement this we could add special handling for the landing page to the wiki's common.js which hides the table in favor of a single download button and the option to show the table again. Shouldn't be hard design or implantation wise really. If we want the detection to be robust we'll likely want to use existing 3rd party code for that (e.g. Mozillas implementation if that is open source).

Thoughts?

**Comment by trustable-code** [comment] 2015-08-30 18:48
@hacst: I totally agree, that one big download button would be the best. Because many visitors just want to download the software and nothing more. Almost all modern software download pages work this way. More examples: Chrome, LibreOffice and GitHub Desktop.

**Comment by Tarun80** [comment] 2015-08-30 19:24
@hacst - that would be more aptly suited for a proper downloading page, not so much the wiki index page. Additionally, this should be implemented once all stable builds are available for all versions of the OS'.

In this case, the table would suffice even as a temporary update to allow clarity. Speaking as an admin of a Mumble/Murmur server, I also prefer the table being there for when I need to grab a new Linux snapshot to update.

**Comment by JoelTroch** [comment] 2015-08-30 19:59
What about something like [this](http://shepard62fr.free.fr/mumble_test.html)?

It's a quick/dirty prototype I made in 5 minutes, you can click on links to get detailed description. Of course, OS would be detected and chosen by default.

**Comment by Tarun80** [comment] 2015-08-30 23:17
Here's the wikified code.

```
{|class="wikitable" style="margin-left: 30px; margin-bottom: 30px; margin-top: 10px; min-width: 650px;"
!style="text-align: left;"|Operating System
!style="text-align: left;"|Stable Release <!-- background-color: #ccffc7; -->
!style="text-align: left;"|Development Snapshot <!-- background-color: #c7e4ff; -->
|-
|Windows
|style="background-color: #ccffc7;"|[$win32r $version]
|style="background-color: #c7e4ff;"|[http://mumble.info/snapshot/mumble-$win32.msi $win32]
|-
|Windows x64
|style="background-color: #ccffc7;"|---
|style="background-color: #c7e4ff;"|[http://mumble.info/snapshot/mumble-$winx64.winx64.msi $winx64]
|-
|OS X
|style="background-color: #ccffc7;"|[$osxr $version]
|style="background-color: #c7e4ff;"|[http://mumble.info/snapshot/Mumble-$osx.dmg $osx]
|-
|OS X (Universal, Legacy)
|style="background-color: #ccffc7;"|[$osxur $version]
|style="background-color: #c7e4ff;"|[http://mumble.info/snapshot/Mumble-Universal-$osxu.dmg $osxu]
|-
|Ubuntu
|style="background-color: #ccffc7;"|[https://launchpad.net/~mumble/+archive/release Stable Release PPA]
|style="background-color: #c7e4ff;"|[https://launchpad.net/~mumble/+archive/snapshot Snapshot PPA]
|-
|iOS
|style="background-color: #ccffc7;"|[$iosr $iosver]
|style="background-color: #c7e4ff;"|---
|-
|Static Linux Server
|style="background-color: #ccffc7;"|[$staticr $version]
|style="background-color: #c7e4ff;"|[http://mumble.info/snapshot/murmur-static_x86-$static.tar.bz2 $static]
|-
|Static OS X Server
|style="background-color: #ccffc7;"|[$osxstaticr $version]
|style="background-color: #c7e4ff;"|[http://mumble.info/snapshot/Murmur-OSX-Static-$osxstatic.tar.bz2 $osxstatic]
|}
```

**Comment by Tarun80** [comment] 2015-10-09 06:39
@mkrautz and @hacst - any update on this?

**Comment by Tarun80** [comment] 2015-11-11 18:38
Checking on this again, because Guild Wars 2 now has a 64-bit beta client and people are needing to change to the 64-bit snapshot. Unfortunately because it says 1.2.10 under stable, people are downloading this thinking they are getting an actual stable 64 bit client when it does not exist.

**Comment by Tarun80** [comment] 2015-12-11 23:33
Still encountering this as a problem. Any ETA on the fix? More people are downloading what they assume is a stable 64 bit build and getting the stable 32 bit due to how it's categorized.

**Comment by hacst** [comment] 2015-12-13 21:38
@Tarun80 Applied your proposal (slightly modified it as I couldn't just copy&paste it over). Should become visible with the next snapshot. Really sorry for drawing this out so long. Kept thinking I would get to implementing the one-button-solution "next weekend". Well. That obviously never happened. Should've applied your improvements right away.

Will close this once we verified it looks as intended.

**Comment by Tarun80** [comment] 2015-12-13 21:56
Awesome! Looking forward to seeing the changes. If you needed the php code I could have taken care of that for you. Thanks again. :)

**Comment by hacst** [comment] 2015-12-20 22:15
Visible now on http://wiki.mumble.info/wiki/Main_Page . I created https://github.com/mumble-voip/mumble/issues/2001 for further improvements to the download UX. If someone wants to tackle that feel free to do so (marked it up-for-grabs). Closing this.

**Closed by hacst** 2015-12-20 22:15 UTC

**Comment by Tarun80** [comment] 2015-12-20 23:53
@hacst sorry to be so persistent, was looking to get the issue resolved for clarity sake for all. I'll see what I can do in the coming months about getting something like what you discussed with a button download for the Wiki itself.
