### ISSUE TITLE
Emoticons In Chat

### ISSUE THREAD

**Issue by KaLam1tyAC** [mumble-voip/mumble#1831] opened 2015-09-29 19:46 UTC
Hey guys,

There was a thread made about this a year back by **cr0ne**, but kind of stopped short on development. I don't think a pull request was ever made for this, nor was a suggest posted.
The thread is here: http://forums.mumble.info/viewtopic.php?f=2&t=1270

This was the development made back when Mumble was 1.2.4: 
https://github.com/TasosDhm/mumble/commit/2ab888bb079c435da2c92f393c4543c89a0cca32

I figured making a note here would be better for all the feature requests. Of course, it's not a hugely important feature, but chat with no ![Kappa](https://static-cdn.jtvnw.net/emoticons/v1/25/1.0) = ![ResidentSleeper](https://static-cdn.jtvnw.net/emoticons/v1/245/1.0) chat, right?

**Sourced From cr0ne's Post**
Type Kappa:
![Type Kappa](http://i.imgur.com/oAzghiX.png)

Get Kappa:
![Get Kappa](http://i.imgur.com/2Dakxsv.png)

My only gripe with his implementation was grabbing the keywords and then replacing it with a img-tag reference. Seems a bit iffy (bandwidth stealing, possible image deletion/modification, etc.). Of course, all of the links are delegated within the _murmur.ini_, and one can also just link to their on fileserver, but maybe just grab the image from the local server folder and convert to Base64 (like how Inserting images into chat works)? So what do you guys think?

**Comment by Tarun80** [comment] 2015-10-09 04:09
Seems rather pointless and potentially spam-promoting. This is a voice chat, not IRC.

**Comment by Xylemon** [comment] 2015-10-30 09:51
"This is a voice chat, not IRC." There's plenty of voice clients that emoticons, even TeamSpeak 3 has them from what I remember...

Anyway, if it's configurable (as in making it optional to see or have on the server) I don't see a problem with this personally.

**Comment by KaLam1tyAC** [comment] 2015-10-30 15:54
@Tarun80 Plus, what's to stop people from already posting images? This is merely a convenience factor in doing so. The onus is on mods to deal with chat related issues anyway, as there are already a lot of controls in place to prevent spamming. If someone wanted to grief, they could just spam voice as well.

And just because some people don't use the chat system, others do. It's not just for voice communication. Text can be convenient and fun.

If you look through the source, it's pretty much configurable within the server .ini, down to what images are grabbed; if the emotes are enabled at all.

**Comment by m-brian** [comment] 2015-11-04 10:43
Mumble already has a feature creep problem. The UI is difficult to understand. The kind of emoticons you suggest add clutter reminiscent of early web chats. It seems the chat supports Emoji already, let's leave it at that and let the operating system handle emoticons. 😊

**Comment by bontibon** [comment] 2018-01-30 15:55
Duplicate of #1334.

**Closed by bontibon** 2018-01-30 15:55 UTC
Labels: feature-request

**Comment by edurenye** [comment] 2020-10-14 15:24
Would be nice to have a button that unfolds a box with all the available emoji's so you can select them from there and don't have to copy paste them. Like it works for many other applications like Slack.
