### ISSUE TITLE
Placeholder texts visually identical to normal text

### ISSUE THREAD

**Issue by ian-kelling** [mumble-voip/mumble#5985] opened 2022-12-03 19:40 UTC
### Description

In the Address field of the add server dialog, there is pre-filled text, which does not respond to normal editing commands. The only way to edit it is to type new text, but that is very unintuitive.

### Steps to reproduce

1. open connect to server dialog
2. Click "Add New..."
3. try to edit the the text "127.0.0.1" by pressing delete, or clicking into a a section of the text. 

Expected: you can edit it. The text is visually the same as the port text which you can edit.

Result: You can't edit it. It is unclear how to actually enter an address.

### Mumble version

1.3.4

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment] 2022-12-03 20:06
But you can click in the field and type a new address? That's the intended behavior. The prefilled information is only a placeholder text. That is not meant to be regular text... :thinking:

**Comment by ian-kelling** [comment] 2022-12-03 21:17
You can type a new address, however as i said in the bug, the prefilled information has no visual indication it is a uneditable placeholder, so the natural behavior of any user is to edit that text, such as by pressing delete, or selecting part or all of it to edit, none of which works.

**Comment by ian-kelling** [comment] 2022-12-03 21:26
This should have the bug label re-added. To explain again: at the top of that dialog there are 2 fields, address and port, visually identical with pre-filled text. To change the port, you select the field then press delete to change the text. To change the address, you try the same thing: click the field, press delete and nothing happens, the text remains. Oh, you need to know the magic of entering text in order to change it. Now, try that same thing on the port field, and nothing happens, it won't allow you to enter new text without editing the old text.

**Comment by Krzmbrzl** [comment] 2022-12-04 07:37
This is not a bug, but intended behavior. 

The reason for the inconsistency between the different fields is that for e.g. the port we can use a reasonable default value, that will be correct in a meaningful amount of cases (in all cases where the server admin did not explicitly change the port to something else).
Therefore, we fill in a fixed value that can be changed as needed.

For the server address however, we have no way to guess what the user wants to enter there. Therefore, there is no default value. Instead, we add a placeholder text that illustrates how such an address could look like.

Using placeholder text is pretty standard in software nowadays. Therefore, for most users this will just work the way they are used to (after all the placeholder text is visually different (it usually appears a bit transparent) from regular text, which makes it possible to distinguish those cases).

For above reasons, I will close this issue as "works as intended".

**Comment by Krzmbrzl** [comment] 2022-12-04 07:39
Oh and if the placeholder text really does look exactly the same as the text for the port, please post a screenshot of this. 
In that case I think this should be a Qt bug though, which we can't really do anything about.

**Comment by ppfeufer** [comment] 2022-12-04 10:40
Ya, the placeholder text does kinda look the same

![image](https://user-images.githubusercontent.com/2989985/205486136-9003c906-bbb4-4e3d-af09-4bc509860071.png)

**Comment by Krzmbrzl** [comment] 2022-12-04 12:50
That's interesting. For me the difference is much more apparent. What Qt version are you using?

**Comment by ppfeufer** [comment] 2022-12-04 13:03
Freshly updated this morning

![image](https://user-images.githubusercontent.com/2989985/205492021-8690abfe-0486-4f84-8044-7a5c0f276125.png)

**Comment by Krzmbrzl** [comment] 2022-12-04 15:15
I just re-checked and as it turns out, the difference is no longer there for me either. It used to be obvious which of the fields were placeholder texts and which were pre-filled texts...
Changing the Mumble theme to the default one does restore the original (and desired) effect:
![image](https://user-images.githubusercontent.com/12751591/205498763-7af5c5b2-965a-45a5-b5e0-a818777cfec3.png)

My guess would have been that there was a regression in the Mumble theme, but given that it also appears in version 1.3.4, this can't be.
There must have been a change in Qt that causes our theme to cause this non-default behavior :thinking:

**Comment by ian-kelling** [comment] 2022-12-04 20:38
My qt is libqt5gui5:amd64  5.15.3+dfsg-2ubuntu0.2, my mumble is 1.3.4-1ubuntu1. This is trisquel 11, which mostly has the same packages as ubuntu 22.04

**Comment by Krzmbrzl** [comment] 2022-12-12 05:49
Yes that seems to be exactly what we're seeing here indeed.

Sadly, it seems that the Qt team doesn't care at all about this (in the issue someone even reports that Qt support told them this was intentional).

The workaround provided in the issue will almost certainly not work for us either as that uses palettes to set colors in code, but as we are using stylesheets, my experience thus far is that Qt refuses to accept color changes via palette in essentially all cases (because it always prefers the value set in stylesheets).

**Comment by Krzmbrzl** [comment] 2022-12-12 05:51
From https://doc.qt.io/qt-5/qpalette.html#placeholderText:

> Before Qt 5.12, the placeholder text color was hard-coded in the code as QPalette::text().color() where an alpha of 128 was applied. We continue to support this behavior by default, unless you set your own brush. One can get back the original placeholder color setting the special QBrush default constructor as placeholder brush.

**Comment by Krzmbrzl** [comment] 2022-12-27 15:44
Alright, I did some more digging and the "offending" operations in our stylesheets are all of those that modify the `color` property of a `QLineEdit` object. There are several instances of this in our stylsheet. However, we can't just not do this as we in fact have to change the regular text color on those widgets.

Further research confirmed that it is currently only possible to set the color for the placeholder text via `QPalette` changes, that (mostly) are ignored when using stylesheets (as our themes do).
Therefore, there is currently no way to fix this issue in a good way. I found some workarounds that allow you to set the placeholder color by setting e.g. `QLineEdit[text=""] { color: red; }`, but this has the problem that the widget doesn't update on its own, if the text changes. So once this stylesheet applies, it keeps applying even after the text is no longer empty.
This can be circumvented by causing an explicit call ensuring the widget will be "polished" every time its text changes, but this has to be wired up for every single `QLineEdit` (and `QPlainLineEdit`) individually, which is not a viable approach for us.

This issue should be fixed from Qt 6.4 onwards via https://codereview.qt-project.org/c/qt/qtbase/+/434310, but I don't expect to ever see a backport from this to Qt 5.
If I read the code correctly, this commit essentially restores the prior behavior for placeholder texts when using stylesheets (they automatically get a lower alpha value, making them semi-transparent.

All that goes to say that I don't see a way for us to fix this. It is expected to fix itself though, once we move to Qt 6.

Refs.:
- https://codereview.qt-project.org/c/qt/qtbase/+/434310
- https://bugreports.qt.io/browse/QTBUG-95297
- https://forum.qt.io/topic/131701/how-set-stylesheet-for-qlineedit-placeholdertext
- https://forum.qt.io/topic/90176/change-qlineedit-placeholder-text-color/7
- https://bugreports.qt.io/browse/QTBUG-92199

**Closed by Krzmbrzl** 2022-12-27 15:44 UTC
Labels: client, theme, upstream-bug, bug
