### ISSUE TITLE
Video Streaming Support (Screen Sharing)

### ISSUE THREAD

**Issue by edshot99** [mumble-voip/mumble#6468] opened 2024-06-15 22:34 UTC
### Context

Friends and other people in my group have been getting used to Discord's screen sharing feature which means I end up stuck with Discord for screen sharing which I do not like.

### Description

RIST is a new protocol dedicated to delivering high-quality low-latency video. To utilize RIST, I use TSDuck.
I then stream to TSDuck with OBS Studio using a RIST URL that accepts input and then give viewers a RIST URL that outputs the stream which they can open with mpc-qt (mpv/ffmpeg).

Although this set-up works nicely it requires a lot of effort compared to a 'one-click-solution' that other services out there provide.
Seeing how Mumble was planning to add video streaming support I decided to create this issue to discuss the many ways to go about it as well as have feedback of whether or not that this should be added to Mumble.

###Implementation A: Both server and client side###
There are two ways this can be implemented in the server.
A: Create a helper program that provides Mumble with a list of available URLs. Once a stream has started and stopped the helper program will remove the URL pair from the list and restart the TSDuck (tsp) process with a fresh set of secrets for the URL pair.
B: Link Mumble against libtsduck and re-create tsp functionality so that Mumble can create and destroy RIST streams easily.

RIST URL pair (streaming/viewing) needs to be re-created after using to prevent stream hijacking and viewing without permission.
It may be wondered why is it required to have this URL pair in the first place. This is because RIST by design requires a port dedicated for streaming to and receiving from.
It should be possible to only use two ports with multiple streams when using librist, but I haven't got it work and TSDuck doesn't support this as far as I know.
So two ports are required for every person wanting to stream.

Client side can then receive new network messages for requesting a stream URL, notifying other users in a room and allowing access to the view URL and other nice indicators.
Screen recording would have to rely on OBS Studio and stream playback would have to rely on mpv/ffmpeg. I will go into more detail about this later.

**Advantages of Method A**
- TSDuck with full functionality
- Easily offload video streaming to another server

**Disadvantages of Method A**
- Requires installing and configuring TSDuck and the helper adding more work for server operators
- Would require the helper program to network across servers for offloading (TSDuck1 <-> Mumble <-> TSDuck2)

**Advantages of Method B**
- Server operators can easily install Mumble and not worry about anything else besides additional firewall ports

**Disadvantages of Method B**
- Limited TSDuck functionality
- Inability to offload video streaming unless some offloading code is programmed
- Requiring TSDuck as a dependency for the Mumble Server

###Implementation B: Client side only###
Modifying the Mumble server for video support may not sit well with some people when Mumble was and is dedicated for audio in the first place.
So another way I thought about adding video support was just to leave the server code alone, but allow video streaming on any server by having users select their own streaming source and notifying other users and prompting to trust and view.

**Advantages**
- Allows video streaming on any server because not every server operator will want this (not wanting to upgrade, bandwidth limits, etc.)
- Server code left untouched

**Disadvantages**
- Requires users to find a server that allows video streaming and to trust them (as well as configure it in Mumble)
- Users being more suspicious of 'do you trust this server' for video streams

So whether implementation A or B is selected, the client would still require modification and dependence on other programs.

OBS Studio would be required because it can do Window Capture and Window Audio Capture across multiple operating systems.
Although it could be possible to use something smaller like ffmpeg it would typically be stuck to entire display and entire audio card capture which would just loopback Mumble and cause echo.
ffmpeg/mpv would be required to play back the RIST stream. Although mpv isn't necessary this would mean that GUI and other media player-like controls and functionality would have to be programmed as well.

So now comes the ultimate question. Should Mumble really integrate video support?
It would be nice, but it would require making the client (at least) very big.

I personally would choose to keep this out of Mumble or at least go with implementation B.
I think I would rather prefer a dedicated program (call it Shutter ;) to do this, but I know people prefer all-in-one programs.

### Mumble component

Both

### OS-specific?

No

### Additional information

NOTE: librist probably can be used instead of libtsduck. I just use TSDuck because I had some problem and using this fixed it.

librist: https://code.videolan.org/rist/librist
TSDuck: https://github.com/tsduck/tsduck

**Comment by Krzmbrzl** [comment] 2024-06-16 13:39
(More or less) duplicate of #4150
Things related to any kind of video stream support should be discussed there.

**Closed by Krzmbrzl** 2024-06-16 13:39 UTC
Labels: feature-request, triage
