### ISSUE TITLE
Allow Windows installer to select folder to install into

### ISSUE THREAD

**Issue by FlyveHest** [mumble-voip/mumble#5894] opened 2022-09-19 17:13 UTC
### Context

When installing the client on Windows, possible other OSes

### Description

Currently, the Mumble client always installs into `C:\Program Files\Mumble` which might be the preferred location for most users, but it would be nice if you instead could select the target install location, and possible for the installer to remember this location when updating.

### Mumble component

Client

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment] 2022-09-19 17:30
Duplicate of #4702

**Closed by Krzmbrzl** 2022-09-19 17:30 UTC
Labels: feature-request, triage
