### ISSUE TITLE
WAV audio cue sound files are playing inconsistently

### ISSUE THREAD

**Issue by Brottweiler** [mumble-voip/mumble#6359] opened 2024-03-11 20:54 UTC
### Description

When using audio cue, the sound is sometimes silent. It seems random, and happens both for ON and OFF.

### Steps to reproduce

1. Open settings
2. Enable Audio cue when using Push To talk
3. Apply
4. Keep pressing Push To Talk repeatedly and you will notice that sometimes the ON and OFF cue does not play at all.

### Mumble version

1.5.613

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Upgraded from 1.5.517 → 1.5.613. In 1.5.517 audio cue works flawlessly. 1.5.613 has problems.

**Comment by Hartmnt** [comment] 2024-03-11 23:15
Hi,

> 4\. Keep pressing Push To Talk repeatedly

What exactly do you mean with "repeatedly". The audio cue behavior was changed to first stop the currently active sound when switching to the other state. If you press and release PTT really fast, you would probably notice the samples stutter when using long samples. The change was done in #5926 and requested in #1671

Are you using audio cue samples which are longer than the original ones?

**Comment by Brottweiler** [comment] 2024-03-12 05:14
Press PTT, wait one second, release PTT, wait one second, repeat. My audio cue sound is the original Ventrilo PTT sound which is less than a second. So the sound file is short and I notice this issue when I talk with people on mumble.

**Comment by Hartmnt** [comment] 2024-03-12 10:43
I tried to reproduce this, but it works as expected for me. Is there any way for me to download the original Ventrilo samples?

**Comment by Brottweiler** [comment] 2024-03-12 17:35
Here is a video demonstrating the issue. You can notice twice that the audio is silent when using PTT.
[rec-2024-03-12_18.28.52.webm](https://github.com/mumble-voip/mumble/assets/1613137/da30d92c-7fb7-4bb1-943d-6fbb747a74e9)

You are right that I cannot seem to reproduce it using the default audio cue sounds.. unless it happens much more rarely.
I have made an archive with the PTT sounds you can download here and test with. [PTT.tar.gz](https://github.com/mumble-voip/mumble/files/14576455/PTT.tar.gz)

**Comment by Hartmnt** [comment] 2024-03-12 17:41
> Here is a video demonstrating the issue. You can notice twice that the audio is silent when using PTT. [PTT.webm](https://github.com/mumble-voip/mumble/assets/1613137/da30d92c-7fb7-4bb1-943d-6fbb747a74e9)
> 
> You seem to be right that I cannot seem to reproduce it using the default audio cue sounds.. unless it happens much more rarely. I have made an archive with the PTT sounds you can download here and test with. [PTT.tar.gz](https://github.com/mumble-voip/mumble/files/14576455/PTT.tar.gz)

Oh wow. I can reproduce your issue with the provided sound files. But using the default client audio cues and other ``.ogg`` files works just fine for me. I wonder if this is a race condition with the wav decoder, because if I remember correctly we read the sample each time it is played.

**Comment by Brottweiler** [comment] 2024-03-12 17:45
Yep, converting the file to `.ogg` solves the issue. Thanks!

**Comment by Hartmnt** [comment] 2024-03-12 17:46
Yes, but lets keep the issue open as there is clearly something wrong with the wav decoding.

**Comment by Hartmnt** [comment] 2024-12-08 19:05
Closing in favor of #6613

**Closed by Hartmnt** 2024-12-08 19:05 UTC
Labels: client, audio, bug
