### ISSUE TITLE
Lack of jack causes long startup time

### ISSUE THREAD

**Issue by Bios-Marcel** [mumble-voip/mumble#4296] opened 2020-06-15 18:14 UTC
**Describe the bug**

Starting mumble takes a lot of time, due to the fact that it searches for Jack. One could think the easy fix is to install Jack. But having Jack installed kind of messes the audio on my system up. I thought deactivating the auto-connection to jack would work with `autoconnect=false` in the config, but it appears to not be what  I thought and has no effect whatsoever in that regard.

**Steps to Reproduce**
Simply install and launch mumble-client on a machine without jack installed.
In my case, I tested this on ubuntu 20.04.

**Expected behavior**
Fast application startup, no matter whether jack is installed or not.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 KDE-Plasma
 - Version: 1.3

**Comment by Krzmbrzl** [comment] 2020-06-15 18:56
How can I check whether I have jack installed or not? 'cause I think that I don't but I didn't experience this kind of issue :thinking:

**Comment by Bios-Marcel** [comment] 2020-06-15 18:58
In case you have apt, you could just run `apt list --installed | grep jack` (there's probably a better way, but it'll suffice). Otherwise I am not sure, since I don't actually use jack myself.

**Comment by Krzmbrzl** [comment] 2020-06-16 09:32
Okay so it looks like I indeed have jack installed on my system.

How did you determine that the increase in startup time comes from looking for jack though? :thinking:

**Comment by Bios-Marcel** [comment] 2020-06-16 12:18
I just started mumble via cli and noticed that it's retrying multiple times to connect to jack. During that, there was no other output and nothing else happened. So, while I didn't trace it, I am 100% sure that's the problem.

**Comment by magnus-gross** [comment] 2020-06-16 14:08
Please update to 1.3.1, the bug is already fixed there. https://github.com/mumble-voip/mumble/commit/e1dad86336dad8dfc51b41fe99320f0dfdfe75f9

**Comment by Krzmbrzl** [comment] 2020-06-16 15:07
@magnus-gross good catch

Also it has been brought up on IRC that this issue is a duplicate of #3822 which has been fixed in #3826 (which is not part of 1.3.1 but will be part of 1.4.0 and is part of the current master branch).

So the commit magnus has linked, should cure the symptoms while the linked PR actually fixes the underlying problem (as far as I can tell).

**Closed by Krzmbrzl** 2020-06-16 15:07 UTC

**Comment by Bios-Marcel** [comment] 2020-06-16 17:19
How come the PPA isn't supported for ubuntu 20.04, but 19.10?

**Comment by Krzmbrzl** [comment] 2020-06-17 05:36
We're currently having some problems with the way we are creating the PPAs. @Kissaki looked into it but reported our current infrastructure to be a complete mess. According to him we *might* trigger a PPA for 20.04 with the next release.

I wanted to look into this issue but didn't have the time yet.

So if you know how PPAs work, then I think we can indeed use your help :)
