### ISSUE TITLE
Settings UI unusable on a 4K screen with 200% scaling

### ISSUE THREAD

**Issue by SlaterTh90** [mumble-voip/mumble#5964] opened 2022-11-17 16:40 UTC
### Description

The settings UI is larger then the screen area on a 200% scaled 4k screen. While settings can be changed, it is impossible to press the apply button. The settings window can also not be resized in any way (even full screening it is impossible).

Tested using gnome 42 and 43.

### Steps to reproduce

1. Install mumble 1.4.287 (from Flathub)
2. Open settings on a 4k gnome desktop with 200% scaling
3. Realize that the apply, cancle, ok ... buttons are all out of the visible area, with no way to resize the UI to a useable size

Workaround: Temporarily disable scaling to apply settings.

### Mumble version

1.4.287 (Flathub)

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Screenshots

![image](https://user-images.githubusercontent.com/43008743/202504301-6162974d-b7aa-4eea-a78f-b17cb7621417.png)

**Comment by Krzmbrzl** [comment] 2022-11-17 17:11
This is essentially a duplicate of #5425

**Closed by Krzmbrzl** 2022-11-17 17:11 UTC
Labels: bug, triage
