### ISSUE TITLE
[1.2.x] Typos in the message displayed when the server certificate verification fails

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#2618] opened 2016-11-04 14:34 UTC
![server_certificate_verification_failed_typos](https://cloud.githubusercontent.com/assets/5897523/20009062/4ae543fe-a2a3-11e6-840f-f89632996c1a.png)

- **Sever** instead of **Server**, in the first line
- Two points instead of one, at the end of the first line

**Comment by Kissaki** [comment] 2016-11-04 17:34
Duplicate of #1552 which was fixed in 99f3de86133b4ff0e185003ce23c1fd9eaf5e90d

`git branch --contains 99f3de86133b4ff0e185003ce23c1fd9eaf5e90d` does not list `1.2.x` so I guess it was not backported.

**Comment by Kissaki** [comment] 2016-11-04 17:36
I guess we only translate master strings, so changing text in 1.2.x is not an option!?

**Comment by mkrautz** [comment] 2016-11-06 10:17
We can't really easily backport strings fixes. We haven't done so in the past, so we don't really know the process if we were to find a way to "hack" this into 1.2.x without breaking any existing strings.

I don't think it's worth the effort. It's unfortunate, of course.
But 1.2.0 is what, 7 years old by now? And this typo has probably been there since that, or maybe even longer?

I don't think we should waste our resources on trying to backport strings. We have a 1.3.x backlog to work on. :-)

**Closed by mkrautz** 2016-11-06 10:17 UTC
Labels: mumble, ui
