### ISSUE TITLE
Mumble 1.4.287 will not launch on Windows 10

### ISSUE THREAD

**Issue by evanbishop** [mumble-voip/mumble#5966] opened 2022-11-18 03:49 UTC
### The issue

After updating from Mumble 1.3.X to 1.4.287, Mumble will no longer load. Attempting to launch Mumble results in the process immediately dying. I tried deleting files in AppData, uninstalling and reinstalling, and can't get it to launch. Launching from cmd provides no messages either; it just dies instantly. 

### Mumble version

1.4.287

### Mumble component

Client

### OS

Windows

**Comment by Krzmbrzl** [comment] 2022-11-18 05:52
Do you have the Visual C++ Redistributable installed?

**Comment by evanbishop** [comment] 2022-11-18 14:05
Yes, I have the Visual C++ Redistributable installed. I have the x86 and x64 versions of the 2008, 2010, 2012, 2013, and 2015-2022.

**Comment by Krzmbrzl** [comment] 2022-11-18 20:01
Hm... this is odd. I don't think I ever encountered a situation such as this...

@davidebeatrici any ideas?

**Comment by davidebeatrici** [comment] 2022-11-18 20:57
I would take a look at the console log (`%AppData%\Mumble\Mumble\Console.txt`), if it exists.

**Comment by evanbishop** [comment] 2022-11-18 22:24
The contents of the console log are:

```
<W>2022-11-18 15:23:53.697 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2022-11-18 15:23:53.713 libopus 1.3.1-97-g6b6035ae from C:/Program Files/Mumble/client/opus.dll
<W>2022-11-18 15:23:53.728 CELT bitstream 8000000b from C:/Program Files/Mumble/client/celt0.0.7.0.dll
```
and that's it..

**Comment by davidebeatrici** [comment] 2022-11-18 22:46
What processor does your computer have?

**Comment by evanbishop** [comment] 2022-11-18 22:50
I have a Ryzen 5 3600X. 

I may have some free time tomorrow to set up a build and debug environment for Mumble. I've never developed for or on Windows before, though (just Linux)

**Comment by davidebeatrici** [comment] 2022-11-18 23:12
Okay, we can exclude unsupported instruction sets as the cause.

Build instructions can be found here: https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_windows.md

**Comment by davidebeatrici** [comment] 2022-11-23 18:38
No problem, did you perhaps encounter microsoft/vcpkg#27758?

**Comment by evanbishop** [comment] 2022-11-23 19:08
Yes, that's the one! I was able to check out this branch https://github.com/microsoft/vcpkg/pull/27974 and get going

**Comment by evanbishop** [comment] 2022-11-24 17:23
I was able to build and debug mumble with the issue. What kills mumble is:

Exception thrown at 0x0000000069A2F26B (libjack64.dll) in mumble.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFD9681F5E.

I wonder if I've hit https://github.com/jackaudio/jack2/issues/275. I'll keep debugging maybe tomorrow, I'm going to go spend some time with my  family. Happy thanksgiving all :)

**Comment by davidebeatrici** [comment] 2022-11-24 18:35
Excellent, you indeed found the culprit!

Update JACK and the application should launch successfully.

**Comment by evanbishop** [comment] 2022-11-25 20:09
Updating JACK did indeed solve the problem. The thing is, I don't recall  ever installing JACK nor  was it listed in the list of installed programs., it must have been installed as a dependency of something else,  or maybe I had it laying around for a few years and forgot about it. 

Regardless, I'm wondering if there's any way for Mumble to detect and warn the user about this condition? I'm totally inexperienced in Windows development, but if this is something that's feasible I'd be more than willing to take a shot at it in my spare time to save someone else the trouble later of wondering why Mumble seems broken.

**Comment by davidebeatrici** [comment] 2022-11-25 21:59
In theory we can retrieve JACK's version from the DLL's metadata, allowing us to reject anything older than the first good version.

**Comment by Krzmbrzl** [comment] 2023-05-13 15:10
Closing this in favor of #6135

**Closed by Krzmbrzl** 2023-05-13 15:10 UTC
Labels: windows
