### ISSUE TITLE
Client Access Tokens Dissapear when New Server Certificate Installed?

### ISSUE THREAD

**Issue by sadsfae** [mumble-voip/mumble#4516] opened 2020-10-01 10:58 UTC
**Describe the bug**

Hi Folks.  I run a murmur server that utilizes Lets Encrypt certificates, when there's a SSL/TLS renewal for the domain I use the post-hook functionality of Certbot to restart mumble.  This of course replaces the SSL certificate but it still utilizes the same key/cert name in my `mumble.ini`.

On this server we use Access Tokens to grant certain access to some channels and clients needed to re-enter their access token as it was missing on all their Mumble clients after the SSL/TLS certificate was renewed and the Murmur server restarted.

I couldn't understand why replacing the TLS/SSL certificate and restarting murmur would cause a client side change unless Access Tokens are based on the current certificate?

There's not a lot in the murmur server logs, but I can confirm the access token for my client was also missing and needed to be re-added.

Are access tokens (from a client perspective) tied to the identity of a server + unique certificate at the time?  Is there a defacto  expiration time for tokens otherwise? (I wouldn't think so).

If so is there a way to turn this off?  Lets Encrypt renews their certificates every 60-90 days or so and it'd be a real hassle for people to re-add the same Access Token just because the certificate is changed.  

I quite like using Let's Encrypt and really don't want to issue a longer-term self-signed certificate if indeed client-side (Mumble) access tokens are somehow tied to issued Murmur Server certificates.

**Steps to Reproduce**
1. Murmur `1.3.1` on CentOS7
2. Add an access token from a client connecting to the server
3. Replace an SSL/TLS certificate configured via `sslCert=` and `sslKey=`
4. Restart Murmur
5. Client-side server access token is missing on mumble clients of various OS/version/platform connecting to it.

**Expected behavior**
Restarting murmur to pick up a new certificate that was generated should not remove any Mumble client settings for Access Tokens for that server.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Multiple:  Windows 7, Windows 10, Linux]
 - Version: [Multiple: 1.3.2, 1.3.1, 1.2.19]
- Murmur Version 1.3.1

I have not looked in the code base to see if the current certificate is tied in any way to Access Tokens set on clients (or somehow it forms part of what makes a "server" and clients see it as a new connection and drop the access tokens?).  I only ran across another thread where another user had their Access Tokens disappear but not much else.

https://sourceforge.net/p/mumble/discussion/492607/thread/156ec46c/

As I said earlier I'd hate to ditch Let's Encrypt for a long-term self-signed certificate to work around this if it's the case.

**Comment by Krzmbrzl** [comment] 2020-10-01 14:20
> Are access tokens (from a client perspective) tied to the identity of a server + unique certificate at the time?

I am quite sure of this, yes. I strongly suspect that access codes are treated in the same way as other server-specific data: They are stored in Mumble's database with the server's cert-hash as the key. As the cert-hash changes when the cert changes, the client considers this server to be completely unknown and will therefore not use any data from the old one.

That at least is what I suspect. I haven't checked the code but I think this is rather likely.

> If so is there a way to turn this off?

I don't think so. We use the certificate to prove the server's identity and therefore a new cert results in a new identity. I don't really see a way to work around this :thinking:

**Comment by sadsfae** [comment] 2020-10-01 15:02
> > Are access tokens (from a client perspective) tied to the identity of a server + unique certificate at the time?
> 
> I am quite sure of this, yes. I strongly suspect that access codes are treated in the same way as other server-specific data: They are stored in Mumble's database with the server's cert-hash as the key. As the cert-hash changes when the cert changes, the client considers this server to be completely unknown and will therefore not use any data from the old one.
> 
> That at least is what I suspect. I haven't checked the code but I think this is rather likely.
> 
> > If so is there a way to turn this off?
> 
> I don't think so. We use the certificate to prove the server's identity and therefore a new cert results in a new identity. I don't really see a way to work around this thinking

Thanks for the reply.

I can understand if it works this way as it's a way to verify server identity and can strengthen security.

It is however less useful when combined with something like Let's Encrypt which generates their free TLS/SSL certificates in a much more rapid cadence as they expire and re-issue certs every 60-90 days.

What would be useful in this case assuming cert hash is a factor that comprises a unique server identity is an RFE to supply a `mumble.ini` setting to opt out or not consider server certificate hash as a qualifying component of what defines a server.

e.g. `cert-hash-ignore=yes` 

I am sure I'm not the only person leveraging Let's Encrypt for Mumble, it's such a useful service and project and it'd keep folks from needing to self-sign certificates due to their short issuance period.

**Comment by Krzmbrzl** [comment] 2020-10-01 15:58
Having such an option would require the server admin to be able to somehow manually specify the cert-hash that gets transmitted to the client which could then be used to steal the identity of another server really easily. I don't think that is a good thing to have :thinking:

**Comment by sadsfae** [comment] 2020-10-01 16:20
> Having such an option would require the server admin to be able to somehow manually specify the cert-hash that gets transmitted to the client which could then be used to steal the identity of another server really easily. I don't think that is a good thing to have thinking

Perhaps, but you also have other ways to verify authenticity like ACME protocol (https://www.thesslstore.com/blog/acme-protocol-what-it-is-and-how-it-works/) and checking forward/reverse DNS or that what someone is accessing is the same as the server they've defined in their client albeit with what might be a different certificate than the last time they connected (just spitballing here).

I was just asking if an RFE that allows cert-hash checking to be optionally skipped in cases where someone might want to use Let's Encrypt but also use Access Tokens and not have to remake them everytime a new certificate is generated.

In any case, for our uses we've just gone back to using a longer-term self-signed certificate to avoid the disruption of folks losing their client-side access tokens when a certificate is changed.

**Comment by Krzmbrzl** [comment] 2020-10-02 05:49
Before starting to think about changing any existing procedures, we should probably first check that my assumption is actually correct :sweat_smile: 

After a certificate renewal, is there a pop-up when first connecting to the server again complaining about SSL/Cert mismatch that you have to accept for connecting to the server?

**Comment by sadsfae** [comment] 2020-10-02 11:38
> Before starting to think about changing any existing procedures, we should probably first check that my assumption is actually correct sweat_smile
> 
> After a certificate renewal, is there a pop-up when first connecting to the server again complaining about SSL/Cert mismatch that you have to accept for connecting to the server?

Right, here is the order of events:

When the certificate is renewed Murmur is still serving things off of the old one in memory, so the only prompt you receive as a client is that the current certificate has expired and do you want to still accept it.  Only when Murmur is restarted does it start using the new certificate outlined in:

```
sslCert=/home/murmur/my_cert.pem
sslKey=/home/murmur/my_key.pem
```

The certificate name(s) never change as the renewal process is automated there by `certbot` (Let's Encrypt tool).
Let's Encrypt generated certs never prompt you for anything otherwise as they are in the browser/OS trust ring already and they will always match the domain/host for which they were generated if it was successful.

Once murmur is restarted with the new certificate that had been renewed all client access tokens are missing on everyone's clients.

**Comment by Krzmbrzl** [comment] 2020-10-02 15:22
Okay.

Do you have a copy of the old certificate somewhere that could be used for testing purposes?

**Comment by sadsfae** [comment] 2020-10-02 16:18
> Okay.
> 
> Do you have a copy of the old certificate somewhere that could be used for testing purposes?

I do yeah, let me copy it off somewhere.  I can share the following if you think it's helpful, it's a full chain certificate automatically renewed via certbot ala Let's Encrypt.

```
sslCert=/etc/letsencrypt/live/domain.example.com/fullchain.pem
```

Should I attach it here or send it somewhere else?

Thanks for your help.  I am not very good at C++ and couldn't pinpoint where in the codebase exactly how Access Tokens client-side are handled, I've only looked thus far into the murmur source.  I guess this would be in the mumble client codebase portions.

**Comment by Krzmbrzl** [comment] 2020-10-03 15:04
> Should I attach it here or send it somewhere else?

I'm not sure if I can even use that for testing :thinking: 

> I also have another Murmur server that uses Let's Encrypt that's not heavily used like the other one so I'm happy performing any sort of tests that help illuminate this

Yeah that'd be great. I was thinking that perhaps you could send me a link to your murmur server. Then I can connect and read out the cert-hash. Then you could revert to the old cert and I'd do the same again. This way it should be pretty easy to obtain the hashes of the 2 certs and then that'd would either prove my theory wrong or confirm it.
Do you think that'd be possible? :)

**Comment by sadsfae** [comment] 2020-10-05 14:25
> > Should I attach it here or send it somewhere else?
> 
> I'm not sure if I can even use that for testing locally thinking
> 
> > I also have another Murmur server that uses Let's Encrypt that's not heavily used like the other one so I'm happy performing any sort of tests that help illuminate this
> 
> Yeah that'd be great. I was thinking that perhaps you could send me a link to your murmur server. Then I can connect and read out the cert-hash. Then you could revert to the old cert and I'd do the same again. This way it should be pretty easy to obtain the hashes of the 2 certs and then that'd would either prove my theory wrong or confirm it.
> Do you think that'd be possible? :)

Absolutely.  I can use another mumble server I have however that also uses LE certs, the main one I can't make any testing changes to it as it'd be too disruptive for the users - just going to leave that one self-signed.

Can you send me an email ww.foster@gmail dot com ?  I will send you the password, right now it's using an old LE cert (but if bounced will pick up the new one that's since been copied into place automatically via certbot).  I can't strip the password without bouncing murmur, which would inevitably start using the new certificate but it's pretty much in the same place as the one I filed this issue against (with access tokens missing) prior to the service restart.

**Comment by Krzmbrzl** [comment] 2020-10-06 04:45
awesome, thank you! :)

**Comment by Krzmbrzl** [comment] 2020-10-10 06:35
Hold on bot - this issue is sibject to active investigation :point_up:

**Comment by Krzmbrzl** [comment] 2020-10-23 09:32
Okay so after some testing we have found out that the issue is indeed that the server's cert hash changed (as the cert that is being used has changed due to being renewed).

A possible solution to this problem is shown in #4544.

I'll close this issue in favor of the linked one in order to have a compact issue about the problem.

**Closed by Krzmbrzl** 2020-10-23 09:32 UTC
Labels: needs-more-input
