### ISSUE TITLE
Add "Device Profiles"

### ISSUE THREAD

**Issue by teknoskillz** [mumble-voip/mumble#3353] opened 2018-03-01 14:46 UTC
"Device Profiles" 

Using the Windows platform, when plugging in different mikes and or headsets, to optimize each device,
requires sometimes adjusting different things in the settings options and advanced options.

New feature would allow profiles for each input device to be saved so that when when switching mikes
or going to headset combo mikes , the proper saved settings profile either can be selected from a saved list or loaded automatically on removing a device from the hardware through windows device manager, or likewise, as you select a device from the drop down menu, its profile , if saved and enabled, loads as the menu changes.

**Comment by bontibon** [comment] 2018-03-28 15:00
Duplicate of #1264

**Closed by bontibon** 2018-03-28 15:00 UTC
Labels: feature-request, mumble
