### ISSUE TITLE
Connecting to a server takes a long time

### ISSUE THREAD

**Issue by derlade** [mumble-voip/mumble#3882] opened 2019-11-09 10:19 UTC
I am running a mumble server (1.2.18-1+deb9u1) on my Raspberry and frequently have users complaining about the fact that it takes a fairly long time to connect to the server, up to 20 seconds after clicking connect. The CPU load is under 10% during connection, also there should be sufficient RAM available. 
Is this a problem that is connected to the old version in the Raspbian Stretch repo, and would dist-upgrading to Buster and getting the new murmur version fix the problem?

**Comment by davidebeatrici** [comment] 2019-11-09 18:50
I would update to Buster, so that you have the latest stable version of Debian and Murmur.

**Comment by ajmandourah** [comment] 2020-03-18 06:38
Having the same issue on 2 of my servers. Both if them are debian buster with the murmur 1.3
The thing even when opening the servers list it takes around 5-9 sec to display the pings. the same duration also when trying to connect to either server.
I am no expert and I dont know if its Ice thats the culprit as on both if them I implemented CVP and mumo but in theory it souldnt affects the performance of connecting as they have separate ports.

**Comment by Krzmbrzl** [comment] 2020-03-18 07:39
Is any of these 2 servers publicly available so that I could try it out myself @ajmandourah?

**Comment by ajmandourah** [comment] 2020-03-18 07:46
Yes of course. Can I privat msg you the link?

**Comment by Krzmbrzl** [comment] 2020-03-18 07:50
I think the easiest way would be if you joined our irc channel via the riot client, find me in the room's members and dm me there :)

https://riot.im/app/#/room/#mumble:matrix.org

**Comment by ajmandourah** [comment] 2020-03-18 08:13
Will do so after work today. :)

**Comment by ajmandourah** [comment] 2020-03-18 08:51
Check your riot :)

**Comment by Krzmbrzl** [comment] 2020-03-18 09:23
What version of Mumble are you using?
I tested it with the current state of the `master` branch (aka a 1.4 snapshot if you will) and it connected in no time. The server lists shows up pretty quick as well (including info about how many users are on that server) - takes about 1-2 seconds.

**Comment by ajmandourah** [comment] 2020-03-18 09:28
I use the stable 1.3

**Comment by Krzmbrzl** [comment] 2020-03-18 09:50
What OS and what hardware are you on and how good is your internet connection? How fast does loading a normal website usually take (roughly)?

**Comment by ajmandourah** [comment] 2020-03-18 10:01
Windows 10. Ethernet connection 1gb. 100mb speed download and upload. No problem in loading pages.
I must note that such issue was reported  also to me by the members in mumble which have mumble 1.3.

**Comment by Krzmbrzl** [comment] 2020-03-18 10:05
Hm maybe this is a Windows thing then. I tried it on Linux. Let me check that on Windows and report back.

Do you experience this issue only on these 2 servers or on other servers as well?

**Comment by ajmandourah** [comment] 2020-03-18 10:16
I haven't tried in other servers.
About my servers one is hosted in a server on my lan. And the other is on a VPS

**Comment by Krzmbrzl** [comment] 2020-03-18 12:03
I tried it on my Windows machine (Win7) using the released 1.3 Mumble client and the result is the same as on Linux. No problems whatsoever.

What version of Windows are you using? Windows10?

**Comment by ajmandourah** [comment] 2020-03-18 12:14
Win 10 pro 1909

**Comment by Krzmbrzl** [comment] 2020-03-18 12:18
Is this issue new or have you been experiencing it for some time?
I assume that using other means to connect to the servers (e.g. remote desktop or ssh)  isn't that slow?

**Comment by ajmandourah** [comment] 2020-03-18 12:42
Probably since 2-3 months. Ssh works fine without lagging. I tried right now from Plumble on android and it connects fine. Probably something from windows 10. Strange

**Comment by Krzmbrzl** [comment] 2020-03-18 13:37
I assume everyone that experiences this problem is running Win10 as well?

**Comment by ajmandourah** [comment] 2020-03-18 13:58
You got that right 😑

**Comment by Avatat** [comment] 2020-03-18 15:01
My colleague uses Windows 10 build 17763.1098 (1809?), and Mumble 1.3.0. He connects to Mumble 1.3.0 server without any issues and delays.
Many Linuxes and MacOS users don't have any issues with Mumble 1.3.0 client too.

**Comment by ajmandourah** [comment] 2020-03-18 16:24
I did some testing a moment ago. I disabled the "check for update on startup" on network settings and it seems that fixed it up for me. 

I failed to mention that the problem is mostly when starting up mumble and It seems it prioritize checking for update "then" pinging the servers to check for connections. Strangely though this behavior was not present in the previous builds. 

My friend changed the settings right now and It worked for them. check it out

**Comment by Krzmbrzl** [comment] 2020-03-18 16:42
@Avatat thanks for the report

@ajmandourah I'm glad you were able to figure this out. As to why this happened, I don't have a clue. I just checked the history of both the ConnectionDialog and the VersionCheck and neither seem to have gotten any significant update in the last years that could explain this behaviour.
I might also be a Qt issue as the VersionCheck is running asynchronously and thus shouldn't interfere with the rest of Mumble's startup.

Anyways I'll close this issue as resolved as you were able to fix it on your system :)

**Closed by Krzmbrzl** 2020-03-18 16:42 UTC
Labels: murmur
