### ISSUE TITLE
Depend on deprecated Qt4 in Linux

### ISSUE THREAD

**Issue by androos** [mumble-voip/mumble#3430] opened 2018-06-29 01:54 UTC
Qt4 is dead (for 3 years) and going away.
https://bugs.gentoo.org/656826

**Comment by ppfeufer** [comment] 2018-06-30 16:14
Yep, this is an important one, dear mumble team, please update!

**Comment by C0rn3j** [comment] 2018-06-30 22:41
Dupe of https://github.com/mumble-voip/mumble/issues/2728

**Comment by davidebeatrici** [comment] 2018-07-02 19:13
Closing in favor of #2728.

**Closed by davidebeatrici** 2018-07-02 19:13 UTC
