### ISSUE TITLE
Feature Request: Display a custom string next to name in the user list

### ISSUE THREAD

**Issue by jack-cole** [mumble-voip/mumble#3537] opened 2018-10-15 01:53 UTC
I would like it if we could have a feature to have a custom string next to a user.

Use case: I run a server where myself and several friends hang out on. Sometimes we leave our computers without disconnecting from the server, and go AFK for hours or sometimes days. It would be great if it showed how long a person was AFK next to their name, after they had been gone for 20 minutes. e.g. "1h27m idle", so when one of us joins we can see immediately who isn't here, without having to click on each individual and click information. I could write a script for that.

Here is a mockup example of my use case:
![text-example](https://user-images.githubusercontent.com/5460372/46925718-3a271b00-cfe2-11e8-91c9-0b927bc73091.png)

Since it could be abused, it would be also great to have changing your own, and changing others, require permissions.

**Comment by bontibon** [comment] 2018-10-15 12:13
Closing as duplicate of #2190.

**Closed by bontibon** 2018-10-15 12:13 UTC
