### ISSUE TITLE
Provide new alternative options for overlays

### ISSUE THREAD

**Issue by LTHPKBTE** [mumble-voip/mumble#6337] opened 2024-02-13 05:23 UTC
### Context

Many games have been upgraded to DX12. Without the overlay, I cannot understand the specific communication situation in full-screen games.
The current TalkingUI is not suitable for full-screen games because it will overlap with the content of the game itself, So it's not a good alternative.

### Description

Using the original overlay style as a separate borderless transparent top window can be used as an overlay replacement for some full-screen games and most games that support borderless operation.

### Mumble component

Client

### OS-specific?

No

### Additional information

I don't know how to select the OS-specific option since this looks like it will work for Linux users as well. 

It might be better if it could detect the program in focus and automatically turn this feature on or off.

Related issue: #5760 

Automatic translation. Please forgive my grammatical errors.

**Comment by LTHPKBTE** [comment] 2024-02-13 05:40
I found that I ignored a lot of discussion content (for example, the window should be able to be reduced smaller). For more discussion content, please check the discussion under the related issue.

**Comment by LTHPKBTE** [comment] 2024-02-13 06:22
> I don't think this is a good idea. The TalkingUI is absolutely not meant to be used on top of a fullscreen window. As such it is not meant as a replacement for the overlay. Trying to force it into that position seems like a bad idea.

Might it be better to create a new option as a standalone overlay alternative?

**Comment by LTHPKBTE** [comment] 2024-02-13 06:28
> I don't think this is a good idea. The TalkingUI is absolutely not meant to be used on top of a fullscreen window.

I just tried using a third-party software to pin TalkingUI, and it was really not a good experience. The issue has been modified.

**Comment by Krzmbrzl** [comment] 2024-02-13 07:32
This remains a duplicate of #5760.
I wanted to throw the overlay out into a standalone-ish kind of application that interfaces with Mumble e.g. via the plugin interface essentially since I started working on Mumble. However, the main issue is that we don't have the resources to do this properly (nor to update the overlay code to work with DirectX 12 or Metal on Apple devices). Hence the current state of affairs.

**Closed by Krzmbrzl** 2024-02-13 07:32 UTC
Labels: feature-request, needs-more-input, triage
