### ISSUE TITLE
Settings window doesn't fit to 1280x1024

### ISSUE THREAD

**Issue by TotalCaesar659** [mumble-voip/mumble#3924] opened 2019-12-23 13:14 UTC
![1](https://user-images.githubusercontent.com/14265316/71359944-453ee900-259f-11ea-9798-8cbab4cd0780.png)

**Comment by Krzmbrzl** [comment] 2020-03-02 17:26
Duplicate of #2120

**Closed by Krzmbrzl** 2020-03-02 17:26 UTC
Labels: ui
