### ISSUE TITLE
The user status icons are about half the size with Windows Scaling @150%

### ISSUE THREAD

**Issue by AriaanBruinsma** [mumble-voip/mumble#3773] opened 2019-08-29 23:09 UTC
The user status icons are about half the size with Windows Scaling @150%.

Also, perhaps a setting that would allow the user to change the scaling. (Like the Telegram chat app)

<img width="406" alt="6Y6VST1TGy" src="https://user-images.githubusercontent.com/539121/63981872-069d9400-cac1-11e9-9428-9b095ac5b0ef.png">

**Comment by Ytmndissue** [comment] 2019-08-30 14:49
I reported on this a while back with no real mention as to what it could be due to:
https://github.com/mumble-voip/mumble/issues/3412

Sort of just gave up and closed it.

**Comment by Krzmbrzl** [comment] 2022-08-05 06:42
Duplicate of #5632

**Closed** 2022-08-05 06:42 UTC
Labels: client, ui
