### ISSUE TITLE
Clicking on URI send through chat does not open.

### ISSUE THREAD

**Issue by Hizzi** [mumble-voip/mumble#5841] opened 2022-08-30 13:07 UTC
### Description

I can't click on links in the chat
The client consider it like a simple text.
I've got this issue since the 1.4.274 update.

The source text seems correct :

<a href="https://www.mumble.info/"><span style="color:#39a5dd">https://www.mumble.info/</span></a>

![image](https://user-images.githubusercontent.com/5193440/187443062-5d7d9908-1f15-47a3-98c9-692a28d7edad.png)

I tried he default theme but the problem is still there.

I'm on windows 11

### Steps to reproduce

Connect to a server.
Send e message with URI like "https://www.mumble.info/"
Try to click on it.

### Mumble version

1.4.274

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment] 2022-08-30 15:31
Duplicate of #5818

**Closed by Krzmbrzl** 2022-08-30 15:31 UTC
Labels: bug, triage
