### ISSUE TITLE
Audio input device selection in 1.5.613

### ISSUE THREAD

**Issue by zeroskull** [mumble-voip/mumble#6367] opened 2024-03-21 18:12 UTC
### Description

 When upgrading to 1.5.613, with my settings staying the same, I am unable to speak no matter what transmission type is selected. I have to switch the audio input device to **Default Device** to be able to speak. When running 1.5.517, and all previous versions of mumble, I specified my audio input device as **Microphone (Realtek(R) Audio)**.

### Steps to reproduce

Update from 1.5.517 to 1.5.613
Have Audio Input Device set to Microphone (Realtek(R) Audio)

### Mumble version

1.5.613

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

I have completely uninstalled and reinstalled mumble and the behavior is the same.

I see the error `"WASAPIInput: Mic GetService failed: hr=0x88890003"` in the developer console when the audio input device is set to Microphone (Realtek(R) Audio).

I got my mic working by just switching to Default Device, so its not a big deal, but the behavior between versions is different for me.

**Comment by Hartmnt** [comment] 2024-03-21 19:17
Duplicate of #6356

Thanks for the report though I think the part with the "Default Device" was not mentioned yet

**Closed as not planned by Hartmnt** 2024-03-21 19:17 UTC
Labels: bug, triage
