### ISSUE TITLE
Intermittent mouse stuttering

### ISSUE THREAD

**Issue by Dementei** [mumble-voip/mumble#3209] opened 2017-07-30 12:34 UTC
I have no idea why but when I have mumble running my PC just randomly stutters, makes playing shooters a real challenge that's for sure, crosshair goes way off whenever it happens. Does the same stutter on any other version as well. Running AMD 8350 and Win 8.1. Would appreciate any help on this.

Current version: 1.3.0 (2526-g36cb960-snapshot)

Was watching Task Manager CPU and Network utilization, and I see major spikes in Ethernet once the stutter occurs. So that could be something.

The spikes and stutter go away when mumble isn't running, as soon as it's closed, no spikes.

**Comment by mkrautz** [comment] 2017-07-30 17:53
We have had reports of this before, but haven't been able to reproduce the problem.

Could you try a few things to help pinpoint the culprit for us?

First, try to disable the overlay in Settings -> Overlay. Due to the way the overlay works, you'll have to reboot your PC (or at the very least log out of your Windows user, and log back in) to be 100% the overlay is fully disabled.

Does that change anything?

If not, you could also try Settings -> Shortcuts, then under "Additional Shortcut Engines", disable "Enable Windows hooks". Click Apply and restart Mumble.

Does that change anything?

Please try those two things. Thanks!

**Comment by Dementei** [comment] 2017-07-31 00:48
Thanks for the reply, I've always had the overlay off, and the disabling of Windows hooks seem to have worked. What are the downsides of not using hooks?

**Comment by mkrautz** [comment] 2017-07-31 06:34
You lose support for an upcoming feature where you can use keys such as F13-F24. You also lose the ability to suppress keys (that is, to only let Mumble see the keypress, but not other programs.)

**Comment by davidebeatrici** [comment] 2017-12-02 22:46
Closing in favor of #3275.

**Closed by davidebeatrici** 2017-12-02 22:46 UTC
Labels: mumble, support, windows
