### ISSUE TITLE
MSI: is killing 'mumble.exe' a good solution?

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#1694] opened 2015-06-05 12:18 UTC
With the recent changes to the MSI installer, we've begun using util:CloseApplication to close mumble.exe if it's already running.

I wonder if that is wise, considering MSI can also be used by sysadmins to prepare installations, etc. etc.

I assume we should try to limit the call to util:CloseApplication to interactive installations, or something like that?

Don't know.

If anyone has any input, please let your voice be heard!

**Comment by hacst** [comment] 2015-06-05 12:35
Not sure what you mean with "prepare". If the sysadmin decides to update mumble remotely then imho that should do everything needed to do that _now_ and without a reboot. It might be a security critical update. If we can we should remember if we actually ended up closing mumble and relaunch it but apart from that imho no special handling is needed.

**Comment by mkrautz** [comment] 2015-06-05 12:48
Mostly thinking of things such as administrative installations:

https://msdn.microsoft.com/en-us/library/aa367541%28v=vs.85%29.aspx

If I was an admin, and did msiexec.exe /a mumble.msi TARGETDIR=z:\mumble, I wouldn't exepct that to kill any local Mumble client I had running.

I am not sure if it actually happens now, but I can't rule it out.

**Comment by hacst** [comment] 2015-06-05 16:32
My admin experience is definitely limited. Non-existent for large windows installations. I certainly would prefer my update to actually be applied immediately but I can see how that might be a problem for some ;)

**Comment by davidebeatrici** [comment] 2017-05-30 17:06
With the snapshots installers, Mumble is never closed if connected to a server.
It's probably a bug, since after the installation it is closed instantly when clicking on the window's X button, without displaying the usual message asking if the user wants to close the message, minimize Mumble or close it.

**Comment by mkrautz** [comment] 2017-07-20 13:03
Another issue is that multiple users on the system can be using multiple copies of Mumble at the same time...

**Comment by mkrautz** [comment] 2017-07-20 13:03
But for now, our use-case is single-user machines, obviously. As that's what most installations are going to be.

**Comment by Krzmbrzl** [comment] 2020-01-25 17:48
In my opinion an installer killing running instances of the program is kinda the default and every admin should have this in mind when installing stuff.

Given that the issue is quite old now and there hasn't been much discussion, I'll close this issue for now

**Closed by Krzmbrzl** 2020-01-25 17:48 UTC
Labels: installer
