### ISSUE TITLE
Speech-dispatcher issues

### ISSUE THREAD

**Issue by xskoak** [mumble-voip/mumble#1756] opened 2015-07-16 09:23 UTC
After upgrading to 1.2.10-2 a number of Speech-Dispatcher outputs show up without doing anything in pavucontrol/pulseaudio. There is also an issue with the speech sounding static-like, the incoming speech, with static sounds being there a few seconds after disconnecting.
This was on Arch Linux x86_64 and kernel version 4.0.7-2.

**Comment by mkrautz** [comment] 2015-07-17 09:21
Possible duplicate of https://github.com/mumble-voip/mumble/issues/1324

**Closed** 2015-07-22 16:00 UTC
