### ISSUE TITLE
Possible Upcoming Mumble Compatibility Issue with XBox One Controller on Windows

### ISSUE THREAD

**Issue by laenas** [mumble-voip/mumble#2104] opened 2016-02-06 21:16 UTC
I run the Windows 10 Fast Ring previews, and there's a potential upcoming compatibility issue between Mumble and the newer Windows drivers for the XBox One Controller(driver information at bottom of post).  With the next major non-preview build landing some time this spring(probably) it may be worthwhile to identify this issue beforehand.

1.  Mumble consistently chews up an entire logical core in this situation, driving CPU usage sky-high.
2.  Mumble (possibly due to CPU usage?) does not properly identify upper mouse button inputs for PTT(or even configuring PTT) and instead seems to read them as Mouse1.  
2a.  This is identifiable by the fact that you'll get 'drag and drop' behavior in a channel list, despite the PTT key being something like Mouse4, and not being easily reproduceable.
3.  Mumble does not exist properly, closing the interface(and confirming you want Mumble to close) will leave an orphan process chewing up that entire logical core.
4. This does not appear to be an issue with other VOIP solutions such as TS3, so it seems specific to something Mumble is doing.

Have tested with Win32 1.2 latest, and Win64 1.3 snapshot latest.  Both show this issue.

Have confirmed that CPU usage correctly resolves itself both if you disconnect the gamepad while mumble is running;  and also returns if you reconnect the gamepad while mumble is running.

Improper input mapping does seem to require an entire Mumble restart - disconnecting mid-session will not resolve the issue.

Mumble started *without* the gamepad connected *WILL* exit properly if the gamepad is added mid-session.
Mumble started *with* the gamepad connected *will not* exit properly until the gamepad is disconnected.

There are 2 drivers available to me:
v10.0.14257.1000 - dated 2016-01-31:  Causes issues.
v6.2.11059 - dated 2014-05-26:  Works as intended with no side effects.

**Comment by mkrautz** [comment] 2016-02-06 21:20
Thanks!

We added XInput support in some of the more recent snapshots. It's possible the driver latest insider builds doesn't work too well with DirectInput. Right now, in 1.3.0, we drive the controller in both XInput and DirectInput, at the same time.

I should try to land the code that blacklists Xbox controllers from DirectInput -- such that it is only opened via XInput -- and see if that helps you...

**Comment by laenas** [comment] 2016-02-06 21:30
Let me know if there's any additional debug info that would be helpful to you in hunting this down.

**Comment by LazyBoot** [comment] 2016-03-02 22:34
Looks like the windows update with the issues has been pushed live. I started having issues with mumble eating cpu cycles after yesterdays update.

![mumble-cpu](https://cloud.githubusercontent.com/assets/3827482/13478021/4c5368ba-e0cf-11e5-85a6-80399f9ca75f.PNG)

**Comment by mkrautz** [comment] 2016-03-03 09:18
Also affects 1.2.x.

**Comment by mkrautz** [comment] 2016-03-03 15:18
Fix is in, at https://github.com/mumble-voip/mumble/commit/6f1331b2e6bfe0acc90dbf2b7d188acc874a5793

Will do a snapshot ASAP.

**Comment by mkrautz** [comment] 2016-03-03 19:32
Snapshot is available as Snapshot 1.3.0~963~ge174f8d~snapshot. (https://www.mumble.info)

**Comment by nheppe** [comment] 2016-03-04 03:01
I can confirm that the above issues with the xbox one controller were present when on version 1.2.14

I can also confirm that the new snapshot resolves these issues.

**Comment by mkrautz** [comment] 2016-03-05 00:43
Now in 1.2.x snapshot form:
https://dl.mumble.info/mumble-1.2.15~19~ga4d5b1e~snapshot.msi

I hope to release this as-is as 1.2.15, if nothing goes wrong. Feel free to test.

**Comment by mkrautz** [comment] 2016-05-01 13:58
It was released with 1.2.15, but wasn't closed accordingly.

Thanks @laenas for reporting this early. :-)

**Closed by mkrautz** 2016-05-01 13:58 UTC
