### ISSUE TITLE
Not possible to select custom path when installing on Windows

### ISSUE THREAD

**Issue by Rovanion** [mumble-voip/mumble#5493] opened 2022-01-21 12:48 UTC
### Description

Hi,
With the new installer for Windows in Mumble 1.4.230 it is no longer possible to select the path to which Mumble is installed. The step that used to come after accepting the license agreement [0] has seemingly been removed and the installer now installs the program at a location of its own choosing.

I have all my Windows programs installed to a separate disk to my Windows system in order to reduce disk IO contention and so that I can carry it with me through reinstalls of Windows. This is why I care.

[0]: Sidenote, the user does not need to agree to the GNU GPL in order to use the software. It is only if they are to redistribute the software that an agreement must be met. So this part of the installer could actually be removed.

### Steps to reproduce

1. Run mumble_client-1.4.230.x64.msi
2. Accept the license agreement
3. Press install
4. Wonder where exactly it is being installed

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![mumble installer](https://user-images.githubusercontent.com/632775/150529598-208da8c3-cb4d-41e6-98f6-3ea633fd6ea4.png)

**Comment by Krzmbrzl** [comment] 2022-01-21 13:07
Duplicate of #4702

**Closed by Krzmbrzl** 2022-01-21 13:07 UTC
Labels: bug, triage
