### ISSUE TITLE
Icons problem in mumble in Plasma

### ISSUE THREAD

**Issue by IlabSentuser** [mumble-voip/mumble#4863] opened 2021-03-16 15:00 UTC
I have found out today that icons are missing in mumble. I have changed no configuration of the client itself. I updated some programs 2 days ago but i don't know i any of the files could have caused this change. Among the files i suspect are more prone to be causing the trouble are: ttf-nerd-fonts-symbols and noto-fonts-emoji. However this is the only application which presents any problem at all. While i am not sure if that update caused the problem i am sure it worked before that update, so it stopped working either right after it or yesterday for some reason, since i didn't use it yesterday. I checked the logs of pacman (i use Arch by the way hahaha) and didn't find any errors. I tried removing icons cache in .cache/icon-cache.kcache and it did not work, i deleted all mumble configuration's files known to me(.local/share/Mumble and .config/Mumble). If anyone has some ideas about this or needs more info i will gladly comply.  Thanks in advance.

Archlinux, Plasma 5.21.2, Mumble 1.3.4.

This is what i mean when i say icons are gone(there is some placeholder texture in there, this same placeholder icon is in settings in every ticked checkbox too):

![Screenshot_20210316_153957](https://user-images.githubusercontent.com/71553739/111328271-62614b00-866e-11eb-9cfd-82305c4a474d.png)

In the settings window:
![Screenshot_20210316_155859](https://user-images.githubusercontent.com/71553739/111330893-a48b8c00-8670-11eb-9027-832a63222a41.png)

**Comment by Krzmbrzl** [comment] 2021-03-16 16:47
Duplicate of #4853

**Closed by Krzmbrzl** 2021-03-16 16:47 UTC
