### ISSUE TITLE
Using -m multiple instances breaks Mumble shortcuts/hotkeys

### ISSUE THREAD

**Issue by DesktopMasters** [mumble-voip/mumble#5545] opened 2022-02-02 22:27 UTC
### Description

No way to use push to talk on the second copy of mumble running.

### Steps to reproduce

1. Run Mumble
2. Run second copy of Mumble with -m
3. Use push to talk hotkey.
Only the first copy of Mumble will allow you to talk.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment] 2022-02-03 06:45
@davidebeatrici any idea as to why this might happen?

**Comment by davidebeatrici** [comment] 2022-02-03 06:54
Mumble version?

**Comment by DesktopMasters** [comment] 2022-02-03 08:18
I assumed it was a bug.
It is Mumble (1.4.230)
I use Mouse 3 also Right CTRL with Right Shift 
and both of them have the same issue.

**Comment by Snowknight26** [comment] 2022-07-29 03:56
At least in a VM, which handles mouse button/keyboard key presses differently, this seems to be fixed in a custom build from ff3d0a6ec82bb1c0228bcc2349777cb6e2326927 (1.5.x branch). Can't check with 1.4.230 at the moment due to build errors.

**Comment by Krzmbrzl** [comment] 2022-09-08 18:14
Given that this issue seems to not be reproducible on current master and considering the fact that the `-m` switch has to be regarded as a "probably works okay, but expect to encounter some hickups, because Mumble wasn't built for that", I'll close this issue (for the time being).

**Closed by Krzmbrzl** 2022-09-08 18:14 UTC
Labels: client, bug, GlobalShortcuts
