### ISSUE TITLE
Make two distinct audio notifications for microfone mute/unmute

### ISSUE THREAD

**Issue by Revertron** [mumble-voip/mumble#1547] opened 2015-01-27 17:49 UTC
In TeamSpeak there are two distinct audio notifications: "Microphone muted" and "Microphone activated".
When user pushes key combination to mute/unmute he/she is certain what the mode of microphone is.

Please, make this change in Mumble, it will be much appreciated.

**Comment by bontibon** [comment] 2015-01-27 21:16
Duplicate of #1179.

**Comment by bontibon** [comment] 2015-05-04 00:59
This issue can be closed as a duplicate, @hacst.

**Closed** 2015-05-04 09:14 UTC
