### ISSUE TITLE
Link Plugin Not Working on Mac/Don't know how to install the osxdist.py file fix

### ISSUE THREAD

**Issue by lognap** [mumble-voip/mumble#5713] opened 2022-06-02 08:07 UTC
### The issue

Hello! I've just downloaded mumble on my macOS Monterey MacBook and the link plugin is nowhere to be found. I've seen a previous forum post about this issue and I saw that there was a fix, but I'm not quite sure how to run the file or what to do once I've downloaded the osxdist.py file. I tried running it through terminal, but I wasn't sure what to put for the directory or what to do with the file. Could someone give me a detailed description of what to do with the file after I've downloaded it in order to fix the missing link plugin problem?

### Mumble version

1.4.230

### Mumble component

Client

### OS

macOS

**Comment by Krzmbrzl** [comment] 2022-06-02 10:37
Duplicate of #5571 

This will be fixed in the upcoming hotfix release for 1.4

**Closed by Krzmbrzl** 2022-06-02 10:37 UTC
Labels: support
