### ISSUE TITLE
linux overlay without opengl

### ISSUE THREAD

**Issue by treaki** [mumble-voip/mumble#1821] opened 2015-09-23 00:42 UTC
hi,

i would like to use the mumble overlay without opengl applications like:

`mumble-overlay lbreakout2`
for example (see http://lgames.sourceforge.net/index.php?project=LBreakout2)

this is an sdl game...

Could you add support for not opengl software.

Also it would be nice to enable an overlay for the the window manager without any software is running (like skype or libnotify dose for example). That could be done like GKrellM dose (which could use transparency using compiz to)

this are just some exemples with whith i try to show the right now limited usage possiblitys of the mumble overlay under linux, Hope you could do something about.

thanks and keep up the good work

**Comment by Kissaki** [comment] 2015-09-27 20:45
> [SDL is] library designed to provide […] and graphics hardware via OpenGL and Direct3D

So usually SDL actually does use OpenGL.
If the overlay does not work with that specific game, more specific technological details would be necessary for us to take a look at it.

Also, please keep a ticket to one topic, so it can be handled (discussed and closed) on-topic.

**Comment by treaki** [comment] 2015-10-07 08:06
isnt ```mumble-overlay lbreakout2``` example enough?, try it on debian...

**Comment by Krzmbrzl** [comment] 2022-11-06 07:38
I would argue that this is a duplicate of #2148

**Closed by Krzmbrzl** 2022-11-06 07:38 UTC
Labels: overlay, feature-request
