### ISSUE TITLE
Release 1.4.230 source archives do not include required 3rd party submodules

### ISSUE THREAD

**Issue by dexgs** [mumble-voip/mumble#5446] opened 2022-01-17 17:24 UTC
### The issue

Trying to build the new release using the given source archives fails because the source directories for celt, rnnoise, etc. are all empty.

### Mumble version

1.4.230

### Mumble component

Both

### OS

Linux

**Comment by Krzmbrzl** [comment] 2022-01-17 18:13
Which source archives? The ones from GitHub? These never contain submodules (as I have been told very recently) :eyes:

**Comment by dexgs** [comment] 2022-01-17 20:17
Right, sorry if I'm jumping the gun, but for previous releases, the release on GitHub was accompanied by a source archive containing submodules (like https://github.com/mumble-voip/mumble/releases/download/1.3.4/mumble-1.3.4.tar.gz) in addition to the archive GitHub produces for the associated tag.

**Comment by TerryGeng** [comment] 2022-01-17 20:24
I believe this issue can be considered as part of https://github.com/mumble-voip/mumble/issues/5434.

**Comment by Krzmbrzl** [comment] 2022-01-17 20:30
Yes, indeed. @davidebeatrici is already in the process of preparing the sources.

In the meantime the easiest way would be for you to just use git to clone the repo and check out the respective tag (and init the submodules).

Closing this as a duplicate of #5434

**Closed by Krzmbrzl** 2022-01-17 20:30 UTC
Labels: support
