### ISSUE TITLE
Feature request:Ui refresh 

### ISSUE THREAD

**Issue by ImGunter** [mumble-voip/mumble#3513] opened 2018-08-31 08:40 UTC
I think it would be really cool if mumble got some type of simplified cleaner ui now that steam is competing and teamspeak is coming out with a new ui I just think it would be cool to see a whole reimagined mumble!

**Comment by davidebeatrici** [comment] 2018-08-31 08:41
Which version are you using?

**Comment by ImGunter** [comment] 2018-08-31 08:43
I am currently using the latest snapshot of 1:3

**Comment by Ytmndissue** [comment] 2018-09-01 14:07
I'd be at the opposite end of the spectrum, I would prefer the existing 1.2/1.3 style UI (with the new icons of course.)

**Comment by ImGunter** [comment] 2019-02-18 06:44
> I'd be at the opposite end of the spectrum, I would prefer the existing 1.2/1.3 style UI (with the new icons of course.)
> 
> Although I guess that doesn't matter, the newer UI is selected by default and classic can still be applied regardless.
> 
> I wonder what the OP had in mind?

my bad for responding so late but idk just a more modern design for mumble because i feel like with a more modern ui and cleaner lookng ui it could actually compete with the likes of discord and teamspeak who is about to launch teamspeak 5 which is a complete rewrite with new technology and everything so i think it would be cool since it's an open source project to have that happen to keep mumble alive so that people will always have a very nice open source option to go to.

**Comment by toby63** [comment] 2020-03-23 19:58
For the sake of reducing the open issues, this is a duplicate of #3608 .
I would keep the newer one.

**Closed** 2020-03-23 20:04 UTC
Labels: mumble, ui
