### ISSUE TITLE
mumble-1.3.0~547~g657f9e8~snapshot crash on startup

### ISSUE THREAD

**Issue by nicolasjoly** [mumble-voip/mumble#1596] opened 2015-03-15 04:41 UTC
Both x86 and x64 version of the latest snapshot (1.3.0~547) just crash on startup. I'm on Windows 8.1 x64. I tried a fresh install for both version. Snapshot 540 is all fine and dandy

**Comment by mkrautz** [comment] 2015-03-15 10:28
Anything intersting in your log? %APPDATA%\Mumble\Console.txt

**Comment by Tarun80** [comment] 2015-03-15 16:00
Windows 7 x64. Mumble snapshot is also crashing.

Open Mumble, immediately crashes. Nothing is written to the console.txt file.

**Comment by nicolasjoly** [comment] 2015-03-15 16:00
Not really

<W>2015-03-15 11:58:40.237 DirectSound: Disabled as WASAPI is available
<W>2015-03-15 11:58:40.246 CELT bitstream 8000000b from C:/Program Files (x86)/Mumble/celt0.0.7.0.dll
<W>2015-03-15 11:58:40.256 CELT bitstream 80000010 from C:/Program Files (x86)/Mumble/celt0.0.11.0.dll
<W>2015-03-15 11:58:40.256 Locale is "en" (System: "en_CA")
<W>2015-03-15 11:58:40.356 Database SQLite: "3.8.6"
<W>2015-03-15 11:58:40.370 Overlay: Listening on "\\.\pipe\MumbleOverlayPipe"
<W>2015-03-15 11:58:40.384 Updating application palette
<W>2015-03-15 11:58:40.523 GlobalShortcutWin: No LowLevelHooksTimeout registry key found.
<W>2015-03-15 11:58:40.750 AudioInput: 96000 bits/s, 48000 hz, 480 sample
<W>2015-03-15 11:58:40.757 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Mouse Mouse:8
<W>2015-03-15 11:58:40.757 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Keyboard Keyboard:126
<W>2015-03-15 11:58:40.759 WASAPIInput: Latencies 100000 30000 => 100000
<W>2015-03-15 11:58:40.762 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2015-03-15 11:58:40.763 WASAPIOutput: Driver says no to 2 channel output. Closest format: 6 channels @ 44100 kHz
<W>2015-03-15 11:58:40.767 WASAPIInput: Mic Stream format 1
<W>2015-03-15 11:58:40.767 WASAPIInput: Stream Latency 58050 (882)
<W>2015-03-15 11:58:40.778 Adding device {c888c680-3baf-11e4-8002-444553540000} Sennheiser 3D G4ME1 Sennheiser 3D G4ME1:5
<W>2015-03-15 11:58:40.799 Adding device {a17bafc0-4be1-11e4-8002-444553540000} Gaming Mouse G502 Gaming Mouse G502:652
<W>2015-03-15 11:58:40.800 WASAPIInput: Echo Stream format 1
<W>2015-03-15 11:58:40.801 AudioInput: Initialized mixer for 2 channel 44100 hz mic and 6 channel 44100 hz echo

**Comment by Venopsis** [comment] 2015-03-15 16:53
Hello,

I have the same problem since I updated to this version. The problem is also Windows is lagging very much. My processor reach 100% of activity.

**Comment by Venopsis** [comment] 2015-03-15 17:02
I just reinstall the version 540 and it's all good ;)

The link to download it: http://mumble.info/snapshot/mumble-1.3.0~540~gedd5509~snapshot.winx64.msi

**Comment by hacst** [comment] 2015-03-15 17:21
Sorry about this. I'm looking into it right now.

**Comment by Tarun80** [comment] 2015-03-15 21:04
I'd like to add in that I'm using the 32-bit Mumble. I did not test the 64-bit version.

I also rolled back to 532 snapshot due to the overlay disappearing in those after 532 (from testing so far).

**Comment by hacst** [comment] 2015-03-15 21:11
I just pushed a patch that fixes at least one potential crasher. If the snapshot 549 (will take a while to build) still crashes please make sure to submit crash reports and explicitly mention this issue so I can find them.

**Comment by Venopsis** [comment] 2015-03-15 21:11
I try it and give you my feedback immediatly

**Comment by Tarun80** [comment] 2015-03-15 21:44
@Venopsis They are not built yet. hacst said they will take a while to build. They'll be found here, though: http://mumble.info/snapshot/

**Comment by Venopsis** [comment] 2015-03-15 21:47
@Tarun80 Okay I'll wait the built version. I already know the link to find the snapshots thx.

**Comment by hacst** [comment] 2015-03-15 23:26
@Venopsis , @Tarun80 The new snapshot is out.

**Comment by Tarun80** [comment] 2015-03-16 00:25
@hacst Installed on my Windows 7 x64 laptop, no issues so far (did this when you posted) and just now on my main computer (also Windows 7 x64). No issues loading and connecting. Perhaps this has resolved the problem.

**Comment by nicolasjoly** [comment] 2015-03-16 02:47
549 is stable here too, thanks

**Comment by Venopsis** [comment] 2015-03-16 18:27
549 is good for me too. Thx to fix the problem quickly.

**Comment by hacst** [comment] 2015-03-16 19:50
Nice. Thanks for reporting (back). I'll close this then.

**Closed by hacst** 2015-03-16 19:50 UTC

**Comment by Venopsis** [comment] 2015-03-20 18:48
Hello,

I open again this ticket because suddenly my mumble start to crash again as described in this ticket. I absolutely change nothing from the last time when it worked. I restarted my computer in case of but unfortunately it's always crashing.
I looked in the log file but for me I didn't see something special. I paste the log if you want to look too:

------- Mumble log top -------
<W>2015-03-20 19:35:00.761 DirectSound: Disabled as WASAPI is available
<W>2015-03-20 19:35:00.768 CELT bitstream 8000000b from C:/Program Files/Mumble/celt0.0.7.0.dll
<W>2015-03-20 19:35:00.774 CELT bitstream 80000010 from C:/Program Files/Mumble/celt0.0.11.0.dll
<W>2015-03-20 19:35:00.777 Locale is "fr_BE" (System: "fr_BE")
<W>2015-03-20 19:35:01.254 Database SQLite: "3.8.6"
<W>2015-03-20 19:35:01.339 Overlay: Listening on "\\.\pipe\MumbleOverlayPipe"
<W>2015-03-20 19:35:01.367 Updating application palette
<W>2015-03-20 19:35:01.472 GlobalShortcutWin: Found LowLevelHooksTimeout with value = 0x1388
<W>2015-03-20 19:35:01.692 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Souris Souris:8
<W>2015-03-20 19:35:01.714 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Clavier Clavier:126
<W>2015-03-20 19:35:01.732 AudioInput: 50077 bits/s, 48000 hz, 480 sample
<W>2015-03-20 19:35:01.734 WASAPIInput: Latencies 100000 30000 => 100000
<W>2015-03-20 19:35:01.738 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2015-03-20 19:35:01.738 WASAPIOutput: Driver says no to 2 channel output. Closest format: 6 channels @ 96000 kHz
<W>2015-03-20 19:35:01.740 WASAPIInput: Mic Stream format 1
<W>2015-03-20 19:35:01.740 WASAPIInput: Stream Latency 53333 (960)
<W>2015-03-20 19:35:01.740 Adding device {9606fd60-3215-11e4-8002-444553540000} Programmable Hotkeys Programmable Hotkeys:669
<W>2015-03-20 19:35:01.740 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2015-03-20 19:35:01.740 WASAPIOutput: Output stream format 1
<W>2015-03-20 19:35:01.741 WASAPIOutput: Stream Latency 106666 (2880)
<W>2015-03-20 19:35:01.741 WASAPIOutput: Periods 10000us 3000us (latency 10666us)
<W>2015-03-20 19:35:01.741 WASAPIOutput: Buffer is 30000us (1)
<W>2015-03-20 19:35:01.741 AudioOutput: Initialized 6 channel 96000 hz mixer
<W>2015-03-20 19:35:01.746 Adding device {048360c0-320d-11e4-8001-444553540000} G19 Gaming Keyboard G19 Gaming Keyboard:7
<W>2015-03-20 19:35:01.756 Adding device {048360c0-320d-11e4-8004-444553540000} Plantronics GameCom 780 Plantronics GameCom 780:5
<W>2015-03-20 19:35:01.994 OpenSSL Support: 1 (OpenSSL 1.0.1k 8 Jan 2015)
<W>2015-03-20 19:35:02.009 SSL: CA certificate filter applied. Filtered size: 96, original size: 96
<W>2015-03-20 19:35:02.072 ServerHandler: QOS2 loaded
<W>2015-03-20 19:35:05.243 ServerHandler: Failed to add UDP to QOS
<W>2015-03-20 19:37:32.895 DirectSound: Disabled as WASAPI is available
<W>2015-03-20 19:37:32.899 CELT bitstream 8000000b from C:/Program Files/Mumble/celt0.0.7.0.dll
<W>2015-03-20 19:37:32.902 CELT bitstream 80000010 from C:/Program Files/Mumble/celt0.0.11.0.dll
<W>2015-03-20 19:37:32.902 Locale is "fr_BE" (System: "fr_BE")
<W>2015-03-20 19:37:33.311 Database SQLite: "3.8.6"
<W>2015-03-20 19:37:33.392 Overlay: Listening on "\\.\pipe\MumbleOverlayPipe"
<W>2015-03-20 19:37:33.402 Updating application palette
<W>2015-03-20 19:37:33.500 GlobalShortcutWin: Found LowLevelHooksTimeout with value = 0x1388
<W>2015-03-20 19:37:33.700 AudioInput: 50077 bits/s, 48000 hz, 480 sample
<W>2015-03-20 19:37:33.703 WASAPIInput: Latencies 100000 30000 => 100000
<W>2015-03-20 19:37:33.707 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2015-03-20 19:37:33.707 WASAPIOutput: Driver says no to 2 channel output. Closest format: 6 channels @ 96000 kHz
<W>2015-03-20 19:37:33.710 WASAPIInput: Mic Stream format 1
<W>2015-03-20 19:37:33.710 WASAPIInput: Stream Latency 53333 (960)
<W>2015-03-20 19:37:33.710 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2015-03-20 19:37:33.710 WASAPIOutput: Output stream format 1
<W>2015-03-20 19:37:33.710 WASAPIOutput: Stream Latency 106666 (2880)
<W>2015-03-20 19:37:33.710 WASAPIOutput: Periods 10000us 3000us (latency 10666us)
<W>2015-03-20 19:37:33.710 WASAPIOutput: Buffer is 30000us (1)
<W>2015-03-20 19:37:33.711 AudioOutput: Initialized 6 channel 96000 hz mixer
<W>2015-03-20 19:37:33.718 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Souris Souris:8
<W>2015-03-20 19:37:33.719 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Clavier Clavier:126
<W>2015-03-20 19:37:33.729 Adding device {9606fd60-3215-11e4-8002-444553540000} Programmable Hotkeys Programmable Hotkeys:669
<W>2015-03-20 19:37:33.735 Adding device {048360c0-320d-11e4-8001-444553540000} G19 Gaming Keyboard G19 Gaming Keyboard:7
<W>2015-03-20 19:37:33.746 Adding device {048360c0-320d-11e4-8004-444553540000} Plantronics GameCom 780 Plantronics GameCom 780:5
<W>2015-03-20 19:37:33.833 OpenSSL Support: 1 (OpenSSL 1.0.1k 8 Jan 2015)
<W>2015-03-20 19:37:33.840 SSL: CA certificate filter applied. Filtered size: 96, original size: 96
<W>2015-03-20 19:37:33.842 ServerHandler: QOS2 loaded
<W>2015-03-20 19:37:33.988 ServerHandler: Failed to add UDP to QOS
------- Mumble log end -------

I hope it could help you.
