### ISSUE TITLE
can't make support.system handle: No such file or directory

### ISSUE THREAD

**Issue by Tcll** [mumble-voip/mumble#5899] opened 2022-09-26 18:14 UTC
### Description

when launching mumble, it shows a transparent window frame and then crashes with:
```
ws2:[tcll]:/home/tcll$ /mnt/Storage/Scripts/home.sh mumble_chd /mnt/Storage/Programs/Web/mumble/AppRun
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-tcll'
QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: Windows, Fusion
<D>2022-09-26 14:02:56.088 libopus 1.3.1 from libopus.so.0
<D>2022-09-26 14:02:56.842 JACK 1.9.21 from libjack.so
<X>2022-09-26 14:02:56.923 PipeWire 0.3.42 from libpipewire-0.3.so.0
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.surround71.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<D>2022-09-26 14:02:58.476 PortAudio V19.7.0-devel, revision unknown from libportaudio.so
<D>2022-09-26 14:02:58.476 PulseAudio 16.1.0 from libpulse.so
<W>2022-09-26 14:02:58.477 PulseAudio: Connection failure: Connection refused
<W>2022-09-26 14:02:58.571 Theme: "Mumble"
<W>2022-09-26 14:02:58.571 Style: "Lite"
<W>2022-09-26 14:02:58.571 --> qss: ":themes/Mumble/Lite.qss"
<W>2022-09-26 14:02:58.637 Locale is "en_US" (System: "en_US")
<W>2022-09-26 14:02:59.141 Database SQLite: "3.39.3"
<W>2022-09-26 14:02:59.369 Updating application palette
<W>2022-09-26 14:02:59.504 GlobalShortcutX: Using XI2 2.4
<W>2022-09-26 14:03:00.448 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<W>2022-09-26 14:03:02.451 SocketRPC: Removing old socket on "/mnt/Storage/Home/mum/.MumbleSocket"
<W>2022-09-26 14:03:03.117 AudioInput: Opus encoder set for high quality speech
<W>2022-09-26 14:03:03.117 AudioInput: 40000 bits/s, 48000 hz, 480 sample
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55d34caa6140: can't make support.system handle: No such file or directory
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55d34caa6140: can't make support.system handle: No such file or directory
<W>2022-09-26 14:03:03.291 AudioInput: Opus encoder set for high quality speech
<W>2022-09-26 14:03:03.294 AudioInput: 40000 bits/s, 48000 hz, 480 sample
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55d34cafdec0: can't make support.system handle: No such file or directory
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55d34cafdec0: can't make support.system handle: No such file or directory
pure virtual method called
terminate called without an active exception
```
I had a friend build me an appimage with arch2appimage so it included everything needed to run

### Steps to reproduce

launch mumble

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

it should be noted I'm running with no audio server:
- no pipewire
- no pulseaudio
- no jack
as well as
- no DBus

all audio is direct through ALSA
not sure if mumble can run with ALSA only like every other program I use

**Comment by davidebeatrici** [comment] 2022-09-26 19:56
You should remove unneeded libraries from the AppImage, such as the PipeWire one (it's causing the issue in this case).

**Comment by Tcll** [comment] 2022-09-26 23:41
thanks, though I don't believe my friend packed it

I did try building my own AppDir first with just these:
https://archlinux.org/packages/community/x86_64/mumble/
https://archlinux.org/packages/community/x86_64/poco/
https://archlinux.org/packages/community/x86_64/libspeechd/
https://archlinux.org/packages/extra/x86_64/protobuf/

but it had the same issue, only displaying a window frame and then crashing with the same error:
```
ws2:[tcll]:/home/tcll$ /mnt/Storage/Scripts/home.sh mumble_chd /mnt/Storage/Programs/Web/mumble/AppRun
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-tcll'

(mumble:17069): Gtk-WARNING **: 19:47:31.803: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.803: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.803: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.804: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.848: Unable to locate theme engine in module_path: "adwaita",

(mumble:17069): Gtk-WARNING **: 19:47:31.869: Unable to locate theme engine in module_path: "adwaita",

(mumble:17069): Gtk-WARNING **: 19:47:31.887: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.888: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.888: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.888: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.903: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.903: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.904: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.904: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.906: Unable to locate theme engine in module_path: "adwaita",

(mumble:17069): Gtk-WARNING **: 19:47:31.907: Unable to locate theme engine in module_path: "adwaita",

(mumble:17069): Gtk-WARNING **: 19:47:31.913: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.913: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.914: Unable to locate theme engine in module_path: "murrine",

(mumble:17069): Gtk-WARNING **: 19:47:31.914: Unable to locate theme engine in module_path: "murrine",
QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: bb10dark, bb10bright, cleanlooks, gtk2, cde, motif, plastique, Windows, Fusion
<D>2022-09-26 19:47:32.954 libopus 1.3.1 from libopus.so.0
<D>2022-09-26 19:47:33.306 JACK 1.9.21 from libjack.so
<X>2022-09-26 19:47:33.346 PipeWire 0.3.42 from libpipewire-0.3.so.0
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.surround71.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<D>2022-09-26 19:47:34.333 PortAudio V19.7.0-devel, revision unknown from libportaudio.so
<D>2022-09-26 19:47:34.334 PulseAudio 16.1.0 from libpulse.so
<W>2022-09-26 19:47:34.337 PulseAudio: Connection failure: Connection refused
<W>2022-09-26 19:47:34.402 Theme: "Mumble"
<W>2022-09-26 19:47:34.403 Style: "Lite"
<W>2022-09-26 19:47:34.403 --> qss: ":themes/Mumble/Lite.qss"
<W>2022-09-26 19:47:34.449 Locale is "en_US" (System: "en_US")
<W>2022-09-26 19:47:34.978 Database SQLite: "3.39.3"
<W>2022-09-26 19:47:35.055 Updating application palette
<W>2022-09-26 19:47:35.137 GlobalShortcutX: Using XI2 2.4
<W>2022-09-26 19:47:35.490 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<W>2022-09-26 19:47:36.062 SocketRPC: Removing old socket on "/mnt/Storage/Home/mum/.MumbleSocket"
<W>2022-09-26 19:47:36.547 AudioInput: Opus encoder set for high quality speech
<W>2022-09-26 19:47:36.547 AudioInput: 40000 bits/s, 48000 hz, 480 sample
[E] pw.loop [loop.c:86 pw_loop_new()] 0x56479817eed0: can't make support.system handle: No such file or directory
[E] pw.loop [loop.c:86 pw_loop_new()] 0x56479817eed0: can't make support.system handle: No such file or directory
<W>2022-09-26 19:47:36.655 AudioInput: Opus encoder set for high quality speech
<W>2022-09-26 19:47:36.655 AudioInput: 40000 bits/s, 48000 hz, 480 sample
[E] pw.loop [loop.c:86 pw_loop_new()] 0x5647981d0180: can't make support.system handle: No such file or directory
[E] pw.loop [loop.c:86 pw_loop_new()] 0x5647981d0180: can't make support.system handle: No such file or directory
pure virtual method called
terminate called without an active exception
```

the reason I had my friend build the appimage was to include everything needed
even stuff like libpulse which shouldn't affect anything (other programs I have run with it just fine)

any idea at all what might be causing it??

**Comment by Tcll** [comment] 2022-09-26 23:52
I guess I could be a bit more specific about my distro and such

I specifically run Artix Linux OpenRC
and am working towards making it so lightweight I can run it in RAM
while still maintaining the functionality of XFCE with stuff like FVWM
while also cutting out as many insecurities as possible
so that means no SSH or DBus, and of course no bloat like audio servers (the less I can use, the better)

I have a slight feeling the no DBus may be causing the issue as `support.system` seems like it might be a glib2 thing
though I could be wrong as idk how mumble works

**Comment by davidebeatrici** [comment] 2022-09-27 00:00
Mumble loads audio libraries at runtime (except ALSA's currently), that's why you can (and should) leave out the ones you don't use.

The reason for the crash is that there is no backend available, as also ALSA is failing to initialize:

```
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.surround71.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
```

**Comment by Tcll** [comment] 2022-09-27 03:47
ah alright thanks, and thanks for working with me
hopefully libasound.so is supported soon :D

I'll look into the ALSA issues whenever it's supported, if they happen :)

**Comment by davidebeatrici** [comment] 2022-09-27 03:51
What I meant is that ALSA is the only backend that is not loaded at runtime, of course it's supported.

**Comment by Tcll** [comment] 2022-10-17 02:02
well, I just updated mumble:
https://archlinux.org/packages/community/x86_64/mumble/
and still can't start it:
```
ws2:[tcll]:/home/tcll$ /mnt/Storage/Scripts/home.sh mumble_chd /mnt/Storage/Programs/Web/mumble/AppRun

(mumble:15542): Gtk-WARNING **: 21:58:35.476: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.477: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.477: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.477: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.538: Unable to locate theme engine in module_path: "adwaita",

(mumble:15542): Gtk-WARNING **: 21:58:35.559: Unable to locate theme engine in module_path: "adwaita",

(mumble:15542): Gtk-WARNING **: 21:58:35.585: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.585: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.586: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.586: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.605: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.605: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.606: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.606: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.610: Unable to locate theme engine in module_path: "adwaita",

(mumble:15542): Gtk-WARNING **: 21:58:35.618: Unable to locate theme engine in module_path: "adwaita",

(mumble:15542): Gtk-WARNING **: 21:58:35.638: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.638: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.639: Unable to locate theme engine in module_path: "murrine",

(mumble:15542): Gtk-WARNING **: 21:58:35.639: Unable to locate theme engine in module_path: "murrine",
QApplication: invalid style override 'gtk' passed, ignoring it.
	Available styles: bb10dark, bb10bright, cleanlooks, gtk2, cde, motif, plastique, Windows, Fusion
<D>2022-10-16 21:58:37.249 libopus 1.3.1 from libopus.so.0
<D>2022-10-16 21:58:37.717 JACK 1.9.21 from libjack.so
<X>2022-10-16 21:58:37.776 PipeWire 0.3.42 from libpipewire-0.3.so.0
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.surround71.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM surround71
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.hdmi.0:CARD=0,AES0=4,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM hdmi
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline:CARD=0,DEV=0
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
ALSA lib confmisc.c:1369:(snd_func_refer) Unable to find definition 'cards.0.pcm.modem.0:CARD=0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_a52.c:1001:(_snd_pcm_a52_open) a52 is only for playback
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<D>2022-10-16 21:58:38.903 PortAudio V19.7.0-devel, revision unknown from libportaudio.so
<D>2022-10-16 21:58:38.904 PulseAudio 16.1.0 from libpulse.so
<W>2022-10-16 21:58:38.905 PulseAudio: Connection failure: Connection refused
<W>2022-10-16 21:58:38.992 Theme: "Mumble"
<W>2022-10-16 21:58:38.992 Style: "Lite"
<W>2022-10-16 21:58:38.992 --> qss: ":themes/Mumble/Lite.qss"
<W>2022-10-16 21:58:39.040 Locale is "en_US" (System: "en_US")
<W>2022-10-16 21:58:39.668 Database SQLite: "3.39.3"
<W>2022-10-16 21:58:40.393 Updating application palette
<W>2022-10-16 21:58:40.817 GlobalShortcutX: Using XI2 2.4
<W>2022-10-16 21:58:41.804 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
<W>2022-10-16 21:58:44.654 AudioInput: Opus encoder set for high quality speech
<W>2022-10-16 21:58:44.655 AudioInput: 40000 bits/s, 48000 hz, 480 sample
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55586d2460d0: can't make support.system handle: No such file or directory
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55586d2460d0: can't make support.system handle: No such file or directory
<W>2022-10-16 21:58:44.870 AudioInput: Opus encoder set for high quality speech
<W>2022-10-16 21:58:44.870 AudioInput: 40000 bits/s, 48000 hz, 480 sample
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55586d28c660: can't make support.system handle: No such file or directory
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55586d28c660: can't make support.system handle: No such file or directory
pure virtual method called
terminate called without an active exception
```

have you added libasound.so backend init support??
if so then it's an issue on my end

**Comment by davidebeatrici** [comment] 2022-10-17 03:26
In your case it doesn't matter, as you only want ALSA.

According to the log, its library is failing to find the configuration file.

**Comment by Tcll** [comment] 2022-10-18 14:40
> In your case it doesn't matter, as you only want ALSA.

wait, I'm confused now, so it does init the alsa library??

> According to the log, its library is failing to find the configuration file.

I'll have a look, thanks
that's a bit weird since I'm using my system's libasound.so, so any reference to `/etc/` from mumble should be loading from my system's `/etc/` path to find the configs despite being run from an AppDir in a CHD
but there's a chance it could be trying to load from `mumble/etc/` if not `mumble/usr/...` or the CHD path `~/.local/...` == `.../mumble_chd/.local/...`

portability sucks on Linux :P

**Comment by Krzmbrzl** [comment] 2022-10-18 18:01
So the issue is resolved by this then?

**Comment by Tcll** [comment] 2022-10-20 22:31
sorry for the delay
but yes, all seems to be working well :+1:
the only thing I can't seem to figure out is how to get echo cancellation to be functional

I'm actually starting to wonder if that's what was causing the initial issue as well
would certainly be interesting to figure out considering the lacking ALSA init support from earlier :)

but anyways yeah I've been running it on a friend's server and it seems to work very well so far :)
thanks for working with me on this, and sorry for all the hype to just find a sus imposter library on my system XD

**Comment by Krzmbrzl** [comment] 2022-10-21 06:12
Yeah, I also struggle to get echo cancellation to work properly ^^
But apparently this is due to my audio system somehow doing weird things in terms of sample rate...

**Closed** 2022-10-21 06:11 UTC
Labels: support
