### ISSUE TITLE
Mumbe 1.3.0 - OS X 10.11 - doesn't show public servers list

### ISSUE THREAD

**Issue by krono86** [mumble-voip/mumble#4111] opened 2020-04-29 07:51 UTC
Mumbe 1.3.0, on OS X 10.11, doesn't show public servers list.

![img](https://user-images.githubusercontent.com/121834/80572817-3067db80-89ff-11ea-9380-aa5943fd3048.png)

Desktop:
 - OS: OS X 10.11.6
 - Version: Mumble 1.3.0

**Comment by Krzmbrzl** [comment] 2020-04-29 07:54
Could you please check your settings file (https://wiki.mumble.info/wiki/Client_Settings) for the entry `disablepubliclist` (or simply copy&paste the whole settings file if you don't mind sharing)?

**Comment by Krzmbrzl** [comment] 2020-04-29 07:59
Though from the screenshot the fact that you are shown the `Internet` item at all indicates that you are shown the public server list. However the fact that it doesn't seem to have any children seems very weird to me... Have you tried double-clicking the `Internet` entry?

**Comment by krono86** [comment] 2020-04-29 08:19
`disablepubliclist` is not present in the settings file.
Yes, I do, I tried double-clicking on the `Internet` entry but nothing comes out.

**Comment by Krzmbrzl** [comment] 2020-04-29 08:22
> disablepubliclist is not present in the settings file.

Okay good - that's what is expected.

> Yes, I do, I tried double-clicking on the Internet entry but nothing comes o

Weird. My best guess would be that Mumble can't actually access the internet and thus can not populate this list...
Are you able to connect to any server? Also is this a new installation or has it been working before?

**Comment by krono86** [comment] 2020-04-29 08:34
> Are you able to connect to any server? 
Yes, I can. When I add a public server found on the website to favorites, I'm able to connect.
> Also is this a new installation or has it been working before?
I upgraded from 1.2.9. I had no working problem before.

**Comment by Krzmbrzl** [comment] 2020-04-29 08:37
But the issue with the server list appeared right after the upgrade?

> Yes, I can. When I add a public server found on the website to favorites, I'm able to connect.

There goes my theory... :flying_saucer:

**Comment by krono86** [comment] 2020-04-29 08:41
> But the issue with the server list appeared right after the upgrade?

The list disappeared after upgrade.

**Comment by Krzmbrzl** [comment] 2020-04-29 08:42
Have you tried first completely uninstalling Mumble and then doing a fresh install? :thinking:

**Comment by krono86** [comment] 2020-04-29 08:48
> Have you tried first completely uninstalling Mumble and then doing a fresh install? thinking

Just tried: no results...

**Comment by Krzmbrzl** [comment] 2020-04-29 09:30
Very weird. Then I don't know what might be the cause. I'll ask on our IRC if someone has encountered something like this before...

**Comment by Avatat** [comment] 2020-04-30 08:14
I checked it, and everything seems to be ok with Mumble 1.3.0 and MacOS 10.15.4.
I want to add, that MacOS 10.11 (El Capitan) isn't supported anymore - you should upgrade to the newer one.

**Comment by Krzmbrzl** [comment] 2020-04-30 10:21
Well the OS being outdated might have something to do with, however it appears to have been working before, which is a bit weird.

Could you start Mumble from a console please and post the output of that here (after having tried to open the public server list of course)?

**Comment by krono86** [comment] 2020-05-02 00:15
This is the outuput starting Mumble from a console:

```
<W>2020-05-02 02:13:17.974 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:17.975 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:17.976 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:17.977 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:17.978 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:18.707 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:18.711 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:18.714 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:18.718 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:18.721 Error receiving trust for a CA certificate
<W>2020-05-02 02:13:18.737 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2020-05-02 02:13:18.764 libopus 1.2.1 from /Applications/Mumble.app/Contents/MacOS/../Codecs/libopus.dylib
<W>2020-05-02 02:13:18.787 CELT bitstream 8000000b from /Applications/Mumble.app/Contents/MacOS/../Codecs/libcelt0.0.7.0.dylib
<W>2020-05-02 02:13:18.821 CELT bitstream 80000010 from /Applications/Mumble.app/Contents/MacOS/../Codecs/libcelt0.0.11.0.dylib
<W>2020-05-02 02:13:18.830 Theme: "Mumble"
<W>2020-05-02 02:13:18.831 Style: "Lite"
<W>2020-05-02 02:13:18.831 --> qss: ":themes/Mumble/OSX Lite.qss"
<W>2020-05-02 02:13:18.837 Using Mac OS X system langauge as locale name
<W>2020-05-02 02:13:18.837 Locale is "it" (System: "it")
<W>2020-05-02 02:13:20.254 Database SQLite: "3.14.1"
<W>2020-05-02 02:13:20.256 Overlay: Listening on "/Users/krono/.MumbleOverlayPipe"
<W>2020-05-02 02:13:20.311 Updating application palette
<W>2020-05-02 02:13:20.553 AudioInput: Opus encoder set for VOIP
<W>2020-05-02 02:13:20.554 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2020-05-02 02:13:20.554 CoreAudioInput: Set device to 'Default Device'.
2020-05-02 02:13:20.649 Mumble[612:5070] 02:13:20.648 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
<W>2020-05-02 02:13:20.652 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2020-05-02 02:13:20.653 CoreAudioInput: BufferFrameSizeRange = (15.00, 4096.00)
<W>2020-05-02 02:13:20.654 CoreAudioOutput: Set device to 'Default Device'.
<W>2020-05-02 02:13:21.079 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2020-05-02 02:13:21.080 CoreAudioOutput: BufferFrameSizeRange = (15.00, 4096.00)
warning: The VAD has been replaced by a hack pending a complete rewrite
```

**Comment by Avatat** [comment] 2020-05-02 11:12
@krono86, could you run this command in your terminal?
```
curl --compressed https://publist.mumble.info/v1/list
```
Did you get XML-formatted list of Mumble servers as output?

**Comment by krono86** [comment] 2020-05-02 11:52
Yes, I do. I obtain an XML-formatted list of servers.

**Comment by Krzmbrzl** [comment] 2020-05-03 17:40
Okay I just did some searching and it seems like the error message you repeatedly see in your log is not emitted by Mumble directly. Instead I am rather sure that it has to do with this Qt bug: https://bugreports.qt.io/browse/QTBUG-55005

At least the error messages match up. In any case this is q Qt error message which indicates that the SSL connection could not be established which also explains why you aren't seeing the server list.

Could you try out the 1.3.1 release candidate to see if the issue remains? You can find the RC here: https://github.com/mumble-voip/mumble/releases/tag/1.3.1-rc1

**Comment by krono86** [comment] 2020-05-04 08:16
I tried the 1.3.1 rc; I have the same problem, but now there is an error message.
![Senza titolo](https://user-images.githubusercontent.com/121834/80947373-53740000-8df0-11ea-89b3-ad947c45dc5e.png)

**Comment by Krzmbrzl** [comment] 2020-05-04 08:38
Uhm could you change the language for Mumble to English (settings > user interface) and send how that message looks in english? That'd make it a lot easier to trace it in the code.

**Comment by Krzmbrzl** [comment] 2020-05-04 08:43
It is very weird though that you haven't gotten this error message before. The respective code hasn't changed in quite a while...

**Comment by krono86** [comment] 2020-05-04 09:01
> ~Uhm could you change the language for Mumble to English (settings > user interface) and send how that message looks in english? That'd make it a lot easier to trace it in the code.~
> 
> EDIT: Nvm I found the translation:
> 
> https://github.com/mumble-voip/mumble/blob/f097427c722b1644fb4bb318d721480cf5b788c2/src/mumble/mumble_it.ts#L2634-L2637
> 
> The error is coming from
> 
> https://github.com/mumble-voip/mumble/blob/f097427c722b1644fb4bb318d721480cf5b788c2/src/mumble/ConnectDialog.cpp#L1772-L1775
> 
> I guess the terminal output still looks the same?

Yes, the output from terminal is the same.

**Comment by Krzmbrzl** [comment] 2020-05-04 11:16
Hm okay then we're basically back at where we've started. My guess is that maybe another Qt version would fix the issue but I don't think that's gonna happen in the 1.3.x series...

**Comment by Krzmbrzl** [comment] 2020-05-07 09:11
@krono86 any reason why you are staying on an outdated MacOS version? If not my suggestion would be to upgrade as @Avatat reported everything to be working fine on a more recent version...

**Comment by krono86** [comment] 2020-05-07 09:53
I’m on a MacBook Pro 13” mid 2009, thus El Capitan is the last available OS major release for that machine.
What’s about Mumble system requirements?

**Comment by Krzmbrzl** [comment] 2020-05-07 09:58
Ah okay I see. I honestly have no idea what the requirements are. I also think that everything *should*  work on older MacOS releases as well (though I don't know much about MacOS so that might be wrong).
I was just thinking that if an upgrade was to solve the issue, then that would be the easiest option...

In this case though I think you'll have to wait until we release the first snapshot for 1.4 as that will probably also contain a newer Qt version...

Until then I'd close this issue due to the fact that OS X 10.11 is EOL and it seems to be working on newer versions. I'm sorry I couldn't be of greater help here :(

**Closed by Krzmbrzl** 2020-05-07 09:58 UTC
Labels: bug, macOS, ui
