### ISSUE TITLE
cant see the mumble welcome  message

### ISSUE THREAD

**Issue by DGMurdockIII** [mumble-voip/mumble#1881] opened 2015-11-10 23:00 UTC
cant see the mumble welcome  message for snapshot because backround to dark for text on new theme   http://i.imgur.com/gkCflal.png will be fixed IE the 1.3.0 Snapshot message text being so  dark

**Comment by Kissaki** [comment] 2015-11-10 23:09
![2015-11-11 00_08_57-clipboard](https://cloud.githubusercontent.com/assets/93181/11078805/6cadb216-8808-11e5-8eb1-5169a42d8ddf.png)
Dark is fine

Can confirm for Lite one

**Comment by DGMurdockIII** [comment] 2015-11-12 05:05
i cant see it

**Comment by funkydude** [comment] 2015-11-12 18:57
This is a duplicate of https://github.com/mumble-voip/mumble/issues/1748 from July which I can confirm is still an issue on a fresh Windows install.

**Comment by Kissaki** [comment] 2015-11-13 01:42
Thanks, thought that we already had one on that.
Closing this as duplicate.

**Closed by Kissaki** 2015-11-13 01:42 UTC
Labels: mumble
