### ISSUE TITLE
I got the source code. How can I compile it

### ISSUE THREAD

**Issue by donggua2096** [mumble-voip/mumble#4469] opened 2020-09-08 18:28 UTC
I got the source code. How can I compile it

**Comment by Krzmbrzl** [comment] 2020-09-08 19:39
Which OS are you using?

If you have all dependencies installed, you simply have to execute the following commands:
```
mkdir build
cd build
cmake ..
cmake --build .
```

Depending on your OS you might want to use a special cmake generator.
Note also that for Windows you have to use thw procedure described at https://github.com/mumble-voip/mumble-releng-vcpkg

**Comment by donggua2096** [comment] 2020-09-08 19:41
I'm win10. I'm a rookie

**Comment by ZeroAbility** [comment] 2020-09-08 19:45
> ... you have to use the procedure described at https://github.com/mumble-voip/mumble-releng-vcpkg
You may also want to join our chat to get these questions answered. You can find links that here:

https://www.mumble.info/contribute/

**Comment by donggua2096** [comment] 2020-09-08 20:16
I have this problem:
./ get-mumbledeps.ps1: The "./ get-mumbledeps.ps1 "TAB cannot be identified as the name of a cmdlet, function, script file, or runnable program. Please check the spelling of the name
Write, if the path is included, make sure the path is correct, and then try again.
Line :1 character :1
+ ./Get-MumbleDeps.ps1
+ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
+ CategoryInfo          : ObjectNotFound: (./Get-MumbleDeps.ps1:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by ZeroAbility** [comment] 2020-09-08 20:19
Did you clone https://github.com/mumble-voip/mumble-releng-vcpkg? You have to `cd` into the directory of the cloned repo.

**Comment by donggua2096** [comment] 2020-09-08 20:25
Thank you. I know why

**Comment by ZeroAbility** [comment] 2020-09-08 20:27
You're welcome. Depending on your system specifications, it could take a while to finish and might appear to be slow or hanging especially on the `qt` components.

**Comment by donggua2096** [comment] 2020-09-08 20:33
I'm sorry to disturb you again. I have another problem:
Failure to read file for hashing: 12152
vcpkg_install : Failed at installing package mdnsresponder (x64-windows-static-md)
 G:\mumble-releng-vcpkg-master\Get-MumbleDeps.ps1:68 字符: 3
+         vcpkg_install -package mdnsresponder -targetTriplet $triplet
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,vcpkg_install

**Comment by ZeroAbility** [comment] 2020-09-08 20:36
That appears to be a permissions issue. Did you modify the output path in the script? Do you have the proper permissions set for `G:\mumble-releng-vcpkg-master\`?

**Comment by donggua2096** [comment] 2020-09-08 20:37
I haven't modified any files. How can I do it

**Comment by ZeroAbility** [comment] 2020-09-08 20:38
Are you an administrator on your PC? Have you tried the script more than once?

**Comment by donggua2096** [comment] 2020-09-08 20:40
I'm trying to run it as an administrator

**Comment by ZeroAbility** [comment] 2020-09-08 20:42
There should be no need to run it as an administrator if you did the `Set-ExecutionPolicy` step in the README. I would recommend moving the `mumble-releng-vcpkg-master` folder to your `Downloads` folder and see if the issue occurs again.

**Comment by donggua2096** [comment] 2020-09-08 20:48
This is still the problem

**Comment by donggua2096** [comment] 2020-09-08 20:49
Could not download https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip. Failed to open file C:\Users\王睿\vcpkg\downloads\cmake-3.17.2-win32-x86.zip.part. Error code was 13
vcpkg_install : Failed at installing package mdnsresponder (x64-windows-static-md)
所在位置 C:\Users\王睿\Downloads\mumble-releng-vcpkg-master\Get-MumbleDeps.ps1:68 字符: 3
+         vcpkg_install -package mdnsresponder -targetTriplet $triplet
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,vcpkg_install

**Comment by ZeroAbility** [comment] 2020-09-08 20:50
Are you able to access this site in a web browser?
https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip

**Comment by donggua2096** [comment] 2020-09-08 20:50
yes

**Comment by donggua2096** [comment] 2020-09-08 20:50
I downloaded him

**Comment by ZeroAbility** [comment] 2020-09-08 20:51
Do you have any Antimalware/virus software that may be blocking scripts that run on your PC?

**Comment by donggua2096** [comment] 2020-09-08 20:52
I'm all closed

**Comment by donggua2096** [comment] 2020-09-08 20:54
I can change the source code to you, you help compile, I only change the icon

**Comment by ZeroAbility** [comment] 2020-09-08 20:56
If you are using a third party Antivirus you may need to check for any blocks it may have made while trying to run `vcpkg`. I would suggest creating exceptions for both the `mumble-releng-vcpkg-master` and `C:\%userprofile%\vcpkg` folders.

**Comment by donggua2096** [comment] 2020-09-08 20:57
I don't have any third-party anti-virus software on my computer now, but I still report an error

**Comment by ZeroAbility** [comment] 2020-09-08 21:00
Which version of Windows 10 and Visual Studio/Build Tools are you using?

**Comment by donggua2096** [comment] 2020-09-08 21:02
Windows 10 home edition

**Comment by donggua2096** [comment] 2020-09-08 21:03
Visual Studio2019

**Comment by ZeroAbility** [comment] 2020-09-08 21:05
Please provide the version number of Windows 10 using the following instructions:

https://support.microsoft.com/en-us/help/13443/windows-which-version-am-i-running

Is Windows up to date and do you have a consistent network connection?

**Comment by donggua2096** [comment] 2020-09-08 21:07
2004         OS internal version 19041.338

**Comment by donggua2096** [comment] 2020-09-08 21:08
I don't seem to have Build Tools installed

**Comment by ZeroAbility** [comment] 2020-09-08 21:10
You only need Visual Studio Community or the Build Tools. Both are not necessary as Community includes the Build Tools. Was this an upgrade to 2004 or did you purchase a new PC with 2004? Is Windows Update working and up to date? Do you have a consistent network connection?

**Comment by donggua2096** [comment] 2020-09-08 21:12
Windows Update has been suspended by me. I am the updated 2004 version

**Comment by donggua2096** [comment] 2020-09-08 21:12
I guarantee that the system is the latest version

**Comment by ZeroAbility** [comment] 2020-09-08 21:14
Make sure Windows Firewall is not disabled, I suggest setting it to Private. Make sure you have a stable connection by running a speedtest. Lastly, from the powershell window in the `mumble-releng-vcpkg-master` directory type the following:

```
./vcpkg install mdnsresponder
```

If it produces the same error, let me know.

**Comment by donggua2096** [comment] 2020-09-08 21:15
ok

**Comment by donggua2096** [comment] 2020-09-08 21:18
Computing installation plan...
A suitable version of cmake was not found (required v3.17.2). Downloading portable cmake v3.17.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip -> C:\Users\王睿\vcpkg\downloads\cmake-3.17.2-win32-x86.zip
Could not download https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip. Failed to open file C:\Users\王睿\vcpkg\downloads\cmake-3.17.2-win32-x86.zip.part. Error code was 13

**Comment by donggua2096** [comment] 2020-09-08 21:20
The same problem arises

**Comment by ZeroAbility** [comment] 2020-09-08 21:20
Please check the contents of `C:\Users\王睿\vcpkg\downloads\` for the file it says it can't open. I have a feeling it is probably a language issue. Did you install the English language pack in Visual Studio?

**Comment by donggua2096** [comment] 2020-09-08 21:24
I installed the English language package，Besides, I didn't find the downloads folder under "C:\Users\ 王睿\ VCPKG"

**Comment by donggua2096** [comment] 2020-09-08 21:25
![RAEZY7TY)VZ4TX@LJUM5CJ0](https://user-images.githubusercontent.com/63895372/92529312-de607d80-f25c-11ea-89d9-efce25ecf22e.png)

**Comment by ZeroAbility** [comment] 2020-09-08 21:26
Try to create a folder called `downloads` in the directory.

**Comment by donggua2096** [comment] 2020-09-08 21:26
You can create

**Comment by ZeroAbility** [comment] 2020-09-08 21:27
Good, now try to run `./Get-MumbleDeps.ps1` in `mumble-releng-vcpkg-master` again.

**Comment by donggua2096** [comment] 2020-09-08 21:32
It's the same problem，I think this is a bug. Can I manually install cmake-3.17.2-win32-x86.zip

**Comment by donggua2096** [comment] 2020-09-08 21:32
Can I manually install cvK-3.17.2-win32-x86.zip?

**Comment by ZeroAbility** [comment] 2020-09-08 21:37
The problem is that every other package that will be installed will use the path you specify and I believe the issue is the characters in the path. I don't think vcpkg has full support for region specific languages. I would modify this:

https://github.com/mumble-voip/mumble-releng-vcpkg/blob/13787533f191c034f6c7e730adffda93de4fab48/Get-MumbleDeps.ps1#L2

To this:

`$vcpkgDir = C:\vcpkg`

You will need 30 GB of free space, so you could also set it to `G:\vcpkg` if that has more space. Once you have done that, feel free to delete the `vcpkg` directory in your `%userprofile%` and then run the script again.

**Comment by ZeroAbility** [comment] 2020-09-08 21:41
> Computing installation plan...
> A suitable version of cmake was not found (required v3.17.2). Downloading portable cmake v3.17.2...
> Downloading cmake...
> https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip -> C:\Users\王睿\vcpkg\downloads\cmake-3.17.2-win32-x86.zip
> Could not download https://github.com/Kitware/CMake/releases/download/v3.17.2/cmake-3.17.2-win32-x86.zip. Failed to open file C:\Users\王睿\vcpkg\downloads\cmake-3.17.2-win32-x86.zip.part. Error code was 13

You should also open an Issue that contains the information above with the `vcpkg` team here:

https://github.com/microsoft/vcpkg/issues

**Comment by donggua2096** [comment] 2020-09-08 21:42
I'm trying，ok

**Comment by donggua2096** [comment] 2020-09-08 21:52
PS G:\mumble-releng-vcpkg-master> ./Get-MumbleDeps.ps1
G:\ VCPKG: The "G:\ VCPKG" item cannot be identified as the name of a cMDlet, function, script file, or runnable program. Please check the spelling of the name and ensure that the path is included
The path is correct, and then try again.
G:\mumble-releng-vcpkg-master\ get-Mumbledeps.PS1:2 Character: 14
+ $vcpkgdir  = G:\vcpkg
+ ~ ~ ~ ~ ~ ~ ~ ~
+ CategoryInfo          : ObjectNotFound: (G:\vcpkg:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

Setting triplets for AMD64
Checking for ...
Test-path: The parameter cannot be bound to the parameter "Path" because it is null.
G:\mumble-releng-vcpkg-master\ get-Mumbledeps.PS1:51 characters: 22
+     if (-not (Test-Path $vcpkgdir)) {
+ ~ ~ ~ ~ ~ ~ ~ ~ ~
+ CategoryInfo: InvalidData: (:)/Test - Path, ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCom
mand

**Comment by donggua2096** [comment] 2020-09-08 21:52
![$XT3JL4%BX_D)R @HQEWHPT](https://user-images.githubusercontent.com/63895372/92531355-b2df9200-f260-11ea-8f44-1d8a1c78535f.png)

**Comment by donggua2096** [comment] 2020-09-08 21:53
![BQ$0@WA}0PECLIAQ7N8WZOO](https://user-images.githubusercontent.com/63895372/92531410-cb4fac80-f260-11ea-8382-270face674a9.png)

**Comment by ZeroAbility** [comment] 2020-09-08 21:53
> Can I manually install cmake-3.17.2-win32-x86.zip?

If you are running a 64 bit version of Windows this would not be ideal. `vcpkg` uses that for specific tooling when CMake is not installed. We recommend installing the latest release of CMake 64 bit from here:

https://cmake.org/download/

**Comment by ZeroAbility** [comment] 2020-09-08 21:54
`$vcpkgdir = "G:\vcpkg"` Or C: if you prefer.

**Comment by donggua2096** [comment] 2020-09-08 21:56
> > 我可以手动安装cmake-3.17.2-win32-x86.zip吗？
> 
> 如果您正在运行64位版本的Windows，那将不是理想的选择。`vcpkg`未安装CMake时将其用于特定工具。我们建议从此处安装最新版本的CMake 64位：
> 
> https://cmake.org/download/

I've installed it

**Comment by donggua2096** [comment] 2020-09-08 21:58
> 问题在于，将要安装的所有其他软件包都将使用您指定的路径，并且我相信问题在于路径中的字符。我认为vcpkg不完全支持特定于区域的语言。我将对此进行修改：
> 
> https://github.com/mumble-voip/mumble-releng-vcpkg/blob/13787533f191c034f6c7e730adffda93de4fab48/Get-MumbleDeps.ps1#L2
> 
> 对此：
> 
> `$vcpkgdir = C:\vcpkg`
> 
> 您将需要30 GB的可用空间，因此也可以将其设置为`G:\vcpkg`具有更多的空间。完成此操作后，请随时删除`vcpkg`您目录中的目录`%userprofile%`，然后再次运行脚本。

It's easy to use. I made it

**Comment by donggua2096** [comment] 2020-09-08 21:58
![image](https://user-images.githubusercontent.com/63895372/92531714-72344880-f261-11ea-981c-0d96afc290af.png)

**Comment by donggua2096** [comment] 2020-09-08 21:59
Thank you for helping me solve the problem successfully

**Comment by ZeroAbility** [comment] 2020-09-08 22:02
You're welcome. Please let us know if you need anything else.

**Closed by ZeroAbility** 2020-09-08 22:02 UTC
Labels: support
