### ISSUE TITLE
F-keys over F12 show 'K:Unknown'

### ISSUE THREAD

**Issue by knight2142** [mumble-voip/mumble#4513] opened 2020-09-30 13:04 UTC
**Describe the bug**
Trying to map F-keys as my PTT hotkey and it does not represent button accurately

**Steps to Reproduce**
I have a QMK enabled keyboard with higher level F-keys mapped. I have tried F13, F14, F15, and F16, when trying to set any of those as a hotkey Mumble shows the shortcut as 'K:Unknown'.

**Expected behavior**
I expect, when I set F16 as my PTT shortcut, it would show as 'K:F16'.
To note, the hotkey does work as expected: even though F16 is showing as 'K:Unknown', F16 still activates PTT.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version: Mumble 1.3.2

**Comment by davidebeatrici** [comment] 2020-10-01 00:04
Duplicate of #4467.

**Closed by davidebeatrici** 2020-10-01 00:04 UTC
