### ISSUE TITLE
Autoscroll does not work properly

### ISSUE THREAD

**Issue by ranomier** [mumble-voip/mumble#3601] opened 2019-02-17 19:02 UTC
If you have a long channel name the chat text input field will break lines. If you click inside the text field it will change to one line. If you click outside again (without typing) the scroll history will be a little bit up and does not auto scroll anymore.

![mumble_scroll_issue](https://user-images.githubusercontent.com/7649949/52917687-b57d3e00-32ee-11e9-8d4b-ea007d4ff937.jpg)

For me this is low prio, please release 1.3 as soon as possible :)

Your awesome!

**Comment by ranomier** [comment] 2019-10-07 22:48
Maybe now that 1.3 is out a little more attention? Sometimes it scrools waaaay up in the chat.

:)

**Comment by davidebeatrici** [comment] 2019-10-07 23:13
What desktop environment are you using? Qt version?

On KDE with Qt 5.11.3 the scroll history goes a little up, but the autoscroll never stops working.

**Comment by ranomier** [comment] 2019-10-08 23:00
OS: Arch Linux
qt: 5.13.1
DE: KDE

Once its a little bit up it actually goes more up when someone posts a picture.

I try to make a Video.

**Comment by promi** [comment] 2020-02-23 11:59
This is a duplicate of #2504

**Comment by Krzmbrzl** [comment] 2020-02-23 13:56
Indeed it appears like it.

**Closed by Krzmbrzl** 2020-02-23 13:56 UTC
Labels: mumble, priority/P4 - Low, ui
