### ISSUE TITLE
When sending links to other people, they're styled according to the sender's theme

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2445] opened 2016-07-18 19:27 UTC
Topic.

**Comment by MoKe12g** [comment] 2020-10-12 16:50
Isn't this a duplicate of Issue #1773?

**Comment by Krzmbrzl** [comment] 2020-10-12 18:41
Indeed it is. Thank you for finding that out! :) 

Closing as a duplicate of #1773

**Closed by Krzmbrzl** 2020-10-12 18:41 UTC
Labels: client, priority/P3 - Somewhat important, theme
