### ISSUE TITLE
Cannot assign shortcut key press to mumble as standard user Fedora 34 - Gnome 40 - Wayland 

### ISSUE THREAD

**Issue by joncartee** [mumble-voip/mumble#4907] opened 2021-04-04 20:32 UTC
**Describe the bug**
Cannot assign shortcut key press to mumble as standard user

While executing as a user in Fedora 34 with Gnome 40, when attempting to assign a keyboard shortcut the terminal responds 
"Wayland does not support QWindow::requestActivate()"

When executing as root the key is assigned with no message. 

**Expected behavior**
Expected user to be able to assign a push to talk key. 

**Screenshots**
![Screenshot from 2021-04-04 13-27-57](https://user-images.githubusercontent.com/38994215/113520683-b6fb3600-9549-11eb-9874-275fc031c33a.png)

**Desktop (please complete the following information):**
Fedora 34 Gnome 40
Mumble 1.3.4
Wayland

**Additional context**

**Comment by Krzmbrzl** [comment] 2021-04-05 06:04
Duplicate of #3243.

In short: Wayland prevents global shortcuts as used by Mumble from working.
The linked issue does give a workaround for setting up at least PTT keys.

**Closed** 2021-04-05 06:17 UTC
