### ISSUE TITLE
Support 320kbps Audio

### ISSUE THREAD

**Issue by grravity** [mumble-voip/mumble#4294] opened 2020-06-14 16:38 UTC
**Describe the feature you have in mind**
I understand this may debatable considered overkill, and if it is accepted I don't expect it to be a high priority, but depending on how difficult of an implementation it would be, I think it would be nice to just support up to at least 320kbps audio for users who wish for it. Of course, servers would still be able to set the limit, so if they don't want to worry about extra strain they can keep it how it is. But if they want it, and can support it no issues, they would have the option to go up essentially double what we have now.

I _believe_ Discord does support 320kbps now behind their Nitro subscription, so it would be nice for us to have it.

**Comment by Krzmbrzl** [comment] 2020-06-14 19:16
Duplicate of #3895

**Closed** 2020-06-14 19:17 UTC
