### ISSUE TITLE
wrong rendering after restart in Win7

### ISSUE THREAD

**Issue by dafoxia** [mumble-voip/mumble#1534] opened 2015-01-20 16:37 UTC
When Mumble closed in Fullscreen Mode, then opened again (next day or a minute lader), Rendering of UI goes wrong.
Occured 1.3.0~511~ge469bd6~snapshot.
![screen1](http://soa.chickenkiller.com/daten/dafoxia_Screen1.png)
When opened Menue
![screen3](http://soa.chickenkiller.com/daten/dafoxia_Screen2.png)

**Comment by mkrautz** [comment] 2015-01-21 20:13
Thanks for the report. But it's a duplicate of #1510.  Closing.

**Closed by mkrautz** 2015-01-21 20:13 UTC
