### ISSUE TITLE
App doesn’t work with Mac OSx 10.14

### ISSUE THREAD

**Issue by ajinkyaghorpade** [mumble-voip/mumble#3531] opened 2018-10-08 15:25 UTC
I downloaded the latest version of mumble from 
[here](
https://github.com/mumble-voip/mumble/releases/tag/1.2.19). I’m running mac osx 10.14. The installed mumble app won’t open on this version. It is also not able to upload the error report (I think it was error report 299).

**Comment by Kas-tle** [comment] 2018-10-09 03:35
I am having the same issue with OSX 10.14. I have attached my error log as plain text.
[ErrorLog.txt](https://github.com/mumble-voip/mumble/files/2458753/ErrorLog.txt)

**Comment by Kas-tle** [comment] 2018-10-09 03:43
I was having the same issue. Since you didn't post an error log, I am unsure if this is the case, but I would check the solution given by amaranth in #3529 (https://github.com/mumble-voip/mumble/issues/3471#issuecomment-410490926).

**Comment by davidebeatrici** [comment] 2019-02-20 19:07
Duplicate of #3471.

**Closed by davidebeatrici** 2019-02-20 19:07 UTC
Labels: macOS, mumble
