### ISSUE TITLE
Mumble Client causes certain applications to become unresponsive or laggy

### ISSUE THREAD

**Issue by Bradley-Schneider** [mumble-voip/mumble#6171] opened 2023-07-10 08:18 UTC
### Description

I run Mumble Server and Client on the same Windows 10 machine and don't have any issues with Mumbles functionality itself outside of my own configuration troubles unrelated to this issue.

However, the Mumble _Client_ causes strange slowdowns in other applications simply by being open. It does not seem to matter if I am connected to a server, disconnected or trying to connect. The affected programs I noted are:

- Dolphin
- Citra
- Yuzu
- Ryujinx
- CEMU
- Foobar2000 (sometimes, not always)

This likely also affects other software outside of this but these are the programs I most commonly use at the same time as Mumble. The most obvious and annoying problem is while the Mumble client is open, launching any of the programs I listed will take 10-12 seconds as opposed to it being instantaneous when it is not running. In addition these programs will be much less responsive in general when running as opposed to normal.

The issues are always fully resolved by simply closing the Mumble Client (and restarting the other application to be safe) 
Note, Mumble Server has no effect on this only the Mumble Client. 

I am wondering if it could also be one of my connected devices as well. DAC, Wireless Microphone, Gamepads as I see there are some open issues related to some of these but they don't describe the issues I am encountering.

I will provide any requested logs or other information, and am willing to attempt troubleshooting if anybody has suggestions. 
Love Mumble otherwise!

### Steps to reproduce

1. Launch Mumble (State of Mumble does not matter: Connected/Disconnected/Failed to Connect all cause the issue.)
2. Launch any of the following programs Dolphin / CEMU / Yuzu / Ryujinx / Citra or Foobar2000.
3. The launched program will be significantly delayed in starting, and is likely to be detected as unresponsive. Program will eventually launch but may be less responsive overall and sometimes have degraded performance.

### Mumble version

1.4.287 and 1.5.517

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

**Relevant System Information**
Windows 10 22H2 19045.3155
Ryzen 7950X3D
Asus X670 ProArt (Not using any of the onboard audio though)

**Relevant Connected Devices**
Topping D30 Pro (External DAC, could be a source of problems? #3224 )
AntLion ModMic Wireless Adapter
XBOX 2.4Ghz Adapter  (Issue #6054 ?)
Switch Pro Controller (Issue #6054 ?)

**Relevant Software**
VB-Cable (Never had issues with this and Mumble, but not impossible that there is a weird interaction)
Peace + APO EQ

### Relevant log output

Log upon launching Mumble, launching other programs afterwards didn't provide anything useful from what I gathered.

[19844] Args: /detect
[19844] Detect mode!
[19844] Unable to initialize Logitech LCD library. (Error: 1722)
[2096] <W>2023-07-10 04:27:39.294 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
[2096] <D>2023-07-10 04:27:39.296 libopus 1.3.1-97-g6b6035ae from C:/Program Files/Mumble/client/opus.dll
[2096] <W>2023-07-10 04:27:39.300 CELT bitstream 8000000b from C:/Program Files/Mumble/client/celt0.0.7.0.dll
[2096] <W>2023-07-10 04:27:39.303 Theme: "Mumble"
[2096] <W>2023-07-10 04:27:39.303 Style: "Dark"
[2096] <W>2023-07-10 04:27:39.303 --> qss: ":themes/Mumble/Dark.qss"
[2096] <W>2023-07-10 04:27:39.303 Locale is "en_US" (System: "en_US")
[2096] <W>2023-07-10 04:27:39.476 Database SQLite: "3.35.5"
[2096] <W>2023-07-10 04:27:39.497 Updating application palette
[2096] <W>2023-07-10 04:27:39.585 QMetaObject::connectSlotsByName: No matching signal for on_qtvUsers_customContextMenuRequested(QPoint,bool)
[2096] <W>2023-07-10 04:27:39.766 AudioInput: Opus encoder set for low delay
[2096] <W>2023-07-10 04:27:39.766 AudioInput: 64022 bits/s, 48000 hz, 480 sample
[2096] <W>2023-07-10 04:27:39.767 Public list disabled
[2096] <W>2023-07-10 04:27:39.770 WASAPIInput: Latencies 100000 30000 => 100000
[20432] 04:27:39.770 21   AudioDeviceSessionCollection OnSessionCreated 
[20432] 04:27:39.771 21   DesktopAppInfo DisplayName read failed mumble 0x80070490 
[2096] <W>2023-07-10 04:27:39.777 WASAPIOutput: Latencies 100000 30000 => 100000
[20432] 04:27:39.781 21   AudioDeviceSession Create mumble {0.0.0.00000000}.{b58dd1e6-0a1f-4443-bc93-b36713b148ab}|\Device\HarddiskVolume3\Program Files\Mumble\client\mumble.exe%b{00000000-0000-0000-0000-000000000000}|1%b2096 
[20432] 04:27:39.782 UI AudioDeviceSessionCollection AddSession mumble {0.0.0.00000000}.{b58dd1e6-0a1f-4443-bc93-b36713b148ab}|\Device\HarddiskVolume3\Program Files\Mumble\client\mumble.exe%b{00000000-0000-0000-0000-000000000000}|1%b2096 
[2096] <W>2023-07-10 04:27:39.782 WASAPIInput: Mic Stream format 1
[2096] <W>2023-07-10 04:27:39.782 WASAPIInput: Stream Latency 0 (1056)
[2096] <W>2023-07-10 04:27:39.792 WASAPIOutput: Output stream format 1
[2096] <W>2023-07-10 04:27:39.792 WASAPIOutput: Stream Latency 0 (1056)
[2096] <W>2023-07-10 04:27:39.793 WASAPIInput: Echo Stream format 1
[20432] 04:27:39.793 21   AudioDeviceSession OnStateChanged Active mumble {0.0.0.00000000}.{b58dd1e6-0a1f-4443-bc93-b36713b148ab}|\Device\HarddiskVolume3\Program Files\Mumble\client\mumble.exe%b{00000000-0000-0000-0000-000000000000}|1%b2096 
[2096] <W>2023-07-10 04:27:39.795 WASAPIOutput: Periods 10000us 3000us (latency 0us)
[2096] <W>2023-07-10 04:27:39.795 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 2 channel 48000 hz echo
[2096] <W>2023-07-10 04:27:39.795 WASAPIOutput: Buffer is 22000us (1)
[2096] <W>2023-07-10 04:27:39.796 AudioOutput: Initialized 2 channel 48000 hz mixer
[2096] <W>2023-07-10 04:27:39.832 AudioInput: Noise canceller disabled
[2096] <W>2023-07-10 04:27:39.832 AudioInput: ECHO CANCELLER ACTIVE
[2096] <W>2023-07-10 04:27:39.847 Database SQLite: "3.35.5"
[2096] <W>2023-07-10 04:27:39.847 OpenSSL Support: 1 (OpenSSL 1.1.1k  25 Mar 2021)
[2096] <W>2023-07-10 04:27:39.851 SSL: CA certificate filter applied. Filtered size: 104, original size: 104
[2096] <W>2023-07-10 04:27:39.851 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
[2096] <W>2023-07-10 04:27:39.853 ServerHandler: QOS2 loaded
[2700] Suspending

**Comment by Krzmbrzl** [comment] 2023-07-10 11:04
Do you have positional audio enabled in Mumble? If so, could you try turning off `Link to Game` in the settings and see if the issue persists (after a restart of Mumble)?

**Comment by Hartmnt** [comment] 2023-07-11 14:31
> So I take it you are on Linux, not Windows, correct? (Your initial comment states Windows)

No, there is also a XInput for Windows which succeeded DirectInput (?) Something like that. The logs and system information OP posted also say Windows 10

**Comment by Hartmnt** [comment] 2023-07-11 15:20
> "Enable Shortcuts in privileged applications" is disabled (Saw another issue that was vaguely related, regarding global hotkeys)

@Bradley-Schneider Have you tried disabling "Global Shortcuts" in the Mumble shortcut settings tab? That should **probably**  tell us, if any of your peripheral devices is causing the issue.

**Comment by davidebeatrici** [comment] 2023-07-11 17:44
> No, there is also a XInput for Windows which succeeded DirectInput (?) Something like that.

XInput is actually poorly designed, which led to DirectInput being used for many years despite Microsoft declaring it legacy. From the Wikipedia page you linked:

![](https://github.com/mumble-voip/mumble/assets/5897523/fa312d93-fd3b-4c8a-b655-d8d7fcaa1fe0)

Raw input is the proper replacement for both.

**Comment by Krzmbrzl** [comment] 2023-07-12 04:42
> No, there is also a XInput for Windows which succeeded DirectInput (?) Something like that

Ah okay. Didn't know that.

> Best guess is "Enable GKey" is the one

Nah - GKeys are keys on Logitech devices, which are usually called G1, G2, etc.

I'm not even sure if we have an option to disable shortcuts on Windows (in 1.4) :thinking:

**Comment by Hartmnt** [comment] 2023-07-12 16:21
> I'm not even sure if we have an option to disable shortcuts on Windows (in 1.4)

I see.

@Bradley-Schneider In that case could you please try to unplug your peripheral devices and test again? I think we are pretty stumped here as there is nothing special in the logs and we will have a hard time reproducing the issue (due to a lack of hardware and operating systems).

If you could somehow narrow down what exactly causes the problem, hardware or software, that would be of great help.

**Comment by Krzmbrzl** [comment] 2023-07-13 04:47
> In that case could you please try to unplug your peripheral devices and test again?

Ah. Now that you mention it: there have been reports where analog input devices (e.g. a Joystick) can drive up the CPU usage through the shortcut system. -> #6054

**Comment by davidebeatrici** [comment] 2023-07-13 09:16
No worries and thank you very much for the extensive testing!

How's the Mumble log now?

**Comment by Hartmnt** [comment] 2023-07-13 09:52
@Bradley-Schneider Wait, but the issue (be it a BIOS issue or not) did originally only occur when Mumble was running, right?

So both the USB 2.0 connection AND Mumble had to be active to trigger this?

That would suggest something fishy is still going on, no?

**Comment by Hartmnt** [comment] 2023-07-13 10:19
So using your DAC as AudioOutput device is causing the issue, correct?

**Comment by davidebeatrici** [comment] 2023-07-13 14:59
I actually spotted something weird in your log, that's why I asked for an up-to-date one (confirming my suspicion):

```
[23184] 2023-07-13 06:11:18.305 WASAPIInput: Mic Stream format 1
[23184] 2023-07-13 06:11:18.305 WASAPIInput: Stream Latency 0 (1056)
[23184] 2023-07-13 06:11:18.308 WASAPIOutput: Output stream format 1
[23184] 2023-07-13 06:11:18.308 WASAPIOutput: Stream Latency 0 (1056)
[23184] 2023-07-13 06:11:18.308 WASAPIOutput: Periods 10000us 3000us (latency 0us)
[23184] 2023-07-13 06:11:18.308 WASAPIOutput: Buffer is 22000us (1)
```

The latency cannot be 0...

**Comment by Hartmnt** [comment] 2023-07-14 10:25
> Not sure if this is super helpful but there are 3 other open issues on Mumble that contain that same 0 latency log.

I think this search query will work just fine: https://github.com/mumble-voip/mumble/issues?q=is%3Aissue+%22latency+0us%22

**Comment by Krzmbrzl** [comment] 2023-07-27 09:15
Thanks for sharing your insights :+1:
Under these circumstances, I will indeed close the issue.

**Closed by Krzmbrzl** 2023-07-27 09:15 UTC
Labels: client, windows, audio, bug
