### ISSUE TITLE
Forward Tabbing Does not Take Screenreader Users to the First Available Setting

### ISSUE THREAD

**Issue by hjozwiak** [mumble-voip/mumble#6108] opened 2023-04-18 21:16 UTC
### Description

When going into the various panels in the settings UI, pressing tab will take you past all the options accept for the categories.

### Steps to reproduce

1. Head to settings.
2. Select a category; in this case I chose the input category.
3. Try pressing tab, and observe it goes directly to the OK, cancel, and apply buttons.

### Mumble version

1.6.0 at commit 9c492fe0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Interestingly, shift+tab to go backward through the dialog allows one to edit the settings, though this can be somewhat of a pain if the setting of interest is closer to the front of the dialog. This has been tested with the latest master of Orca screenreader under the Sway window manager.

**Comment by Hartmnt** [comment] 2023-04-18 21:56
This is more or less a duplicate of #2972 or even #5811 
Progress on this is tracked in the merge request #5984

**Closed by Hartmnt** 2023-04-18 21:56 UTC
Labels: bug, triage
