### ISSUE TITLE
Mumble at flathub.org

### ISSUE THREAD

**Issue by Peque** [mumble-voip/mumble#3556] opened 2018-12-06 00:05 UTC
It would be great if Mumble could be distributed as a Flatpak package through [flathub.org](https://flathub.org).

**Comment by JBBgameich** [comment] 2019-01-12 19:01
I created a flatpak manifest for Mumble nightly builds. You can find it on GitLab: https://gitlab.com/snippets/1733216

Flathub only accepts release builds though, which means that mumble would have to release a new tag until it can be accepted into Flathub.

**Comment by Peque** [comment] 2019-01-12 20:38
@mkrautz Friendly ping. :innocent:

**Comment by anarcat** [comment] 2019-01-16 22:09
i guess this is related to #2728 - a new release needs to be made :)

**Comment by veridiam** [comment] 2019-04-07 06:33
@JBBgameich i believe flatpak-beta repo would accept your build now

**Comment by JBBgameich** [comment] 2019-04-07 07:11
Okay, I'll try submitting it. I'm not completely sure whether they accept rc releases though.

**Comment by d10sfan** [comment] 2019-04-07 21:44
I tried the version the build bot created with flatpak and ran into an issue when connecting to servers. The message was "Unable to find matching CELT codecs with other clients. You will not be able to talk to all users.".

I've included a copy of running the app via command line below if that helps:

` flatpak run info.mumble.Mumble
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
<W>2019-04-07 16:43:20.155 ALSAInit: No cards found, not initializing
<D>2019-04-07 16:43:20.155 libopus 1.3 from libopus.so.0
<W>2019-04-07 16:43:20.157 Theme: "Mumble"
<W>2019-04-07 16:43:20.157 Style: "Dark"
<W>2019-04-07 16:43:20.157 --> qss: ":themes/Mumble/Dark.qss"
<W>2019-04-07 16:43:20.157 Locale is "en_US" (System: "en_US")
<W>2019-04-07 16:43:20.158 TextToSpeech: Compiled without support for speech-dispatcher
<W>2019-04-07 16:43:20.167 Database SQLite: "3.27.2"
<W>2019-04-07 16:43:20.168 Overlay: Listening on "/run/user/1000/MumbleOverlayPipe"
<W>2019-04-07 16:43:20.170 Updating application palette
<W>2019-04-07 16:43:20.179 GlobalShortcutX: Using XI2 2.3
<W>2019-04-07 16:43:20.182 failed to register service "org.kde.StatusNotifierItem-2-2"
<W>2019-04-07 16:43:20.256 AudioInput: Opus encoder set for VOIP
<W>2019-04-07 16:43:20.256 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2019-04-07 16:43:20.256 PulseAudio: Starting input alsa_input.usb-Logitech_USB_Headset_Logitech_USB_Headset-00.analog-mono
<W>2019-04-07 16:43:20.256 PulseAudio: Starting output: alsa_output.usb-Logitech_USB_Headset_Logitech_USB_Headset-00.analog-stereo
<W>2019-04-07 16:43:20.323 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2019-04-07 16:43:20.324 AudioInput: Initialized mixer for 1 channel 44100 hz mic and 0 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2019-04-07 16:43:22.618 Database SQLite: "3.27.2"
<W>2019-04-07 16:43:22.618 OpenSSL Support: 1 (OpenSSL 1.1.1b  26 Feb 2019)
<W>2019-04-07 16:43:22.636 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2019-04-07 16:43:22.909 OSInfo: Failed to execute lsb_release`

**Comment by JBBgameich** [comment] 2019-04-08 04:49
I could connect to servers and speak to others although it complained about the celt codec. Afaik mumble nowadays uses different codecs anyway.

**Comment by veridiam** [comment] 2019-04-08 04:51
Works well for me, I haven't run into the celt issue. There's no appindicator support though (sni-qt?) or espeak-ng

**Comment by JBBgameich** [comment] 2019-04-08 05:22
We can still extentend the functionality after mumble is accepted on flathub. I think I had problems compiling the original espeak, but maybe easpeak-ng is easier.

**Comment by barthalion** [comment] 2019-04-09 12:37
We're good with using RC for stable channel on Flathub as well, given it brings Qt5.

**Comment by barthalion** [comment] 2019-04-15 08:55
If anyone from upstream team would like to get write access to [the Flathub repo](https://github.com/flathub/info.mumble.Mumble), please mention me on GitHub.

**Comment by Procsiab** [comment] 2020-03-31 18:41
I ran into the same warning as d10sfan (https://github.com/mumble-voip/mumble/issues/3556#issuecomment-480632501), and quickly enough after I connected to a not so crowded server I lost the audio from the whole channel when another client joined; apparently, the server force an all-client fail over to CELT codec if a client without Opus support joins. By the way, I tried to connect on the same channel with only some other clients, and I did not have the same issue.
In this second case, I stillgot the following warning (however being able to listen and be heard):
"Unable to find matching CELT codecs with other clients. You will not be able to talk to all users"

**Comment by adnub** [comment] 2020-10-10 23:05
> I ran into the same warning as d10sfan ([#3556 (comment)](https://github.com/mumble-voip/mumble/issues/3556#issuecomment-480632501)), and quickly enough after I connected to a not so crowded server I lost the audio from the whole channel when another client joined; apparently, the server force an all-client fail over to CELT codec if a client without Opus support joins. By the way, I tried to connect on the same channel with only some other clients, and I did not have the same issue.
> In this second case, I stillgot the following warning (however being able to listen and be heard):
> "Unable to find matching CELT codecs with other clients. You will not be able to talk to all users"

I'm noticing the same thing. I installed an older version via apt, copied /usr/lib/mumble/libcelt0.so.0.7.0 from it.
Then removed the older version, installed the flatpak version and put libcelt0.so.0.7.0 in the folder ~/.local/share/flatpak/app/info.mumble.Mumble/current/active/files/bin

Can you guys please add libcelt0.so.0.7.0 to the flatpak version?

**Comment by Krzmbrzl** [comment] 2020-10-11 09:32
Given that Mumble is now available at flathub, I'll close this issue as resolved.

If you are having issues that are specific to the flatpak version of Mumble, please report them at https://github.com/flathub/info.mumble.Mumble.
If you think the issue is a more general one, please feel free to create a new issue.

**Closed by Krzmbrzl** 2020-10-11 09:32 UTC
Labels: release-management
