### ISSUE TITLE
Support runtime injection of the overlay on Linux and other Unix-like systems

### ISSUE THREAD

**Issue by mkrautz** [mumble-voip/mumble#2129] opened 2016-02-23 18:52 UTC
Currently, we use the "mumble-overlay" script, which is a glorified wrapper for LD_PRELOAD.

We could potentially add a "mumble-overlay -p <pid>" feature by piggy-backing on gdb.

Depending on gdb feels wrong, so initially the script could simply check if gdb is installed, and if not, prompt you to install it.

In time, we could also move the functionality into Mumble itself: Just use gdb to inject an overlay payload into the processes your current "overlay rules" specify. In this case, a sane default could be "parent is Desura or Steam?", or something along those lines...

Right now libmumble.so only works when it is loaded with LD_PRELOAD.  We would need to modify to also do runtime injection, like it does on Windows and OS X.

**Comment by davidebeatrici** [comment] 2020-10-14 03:05
https://github.com/kubo/injector

**Comment by ZeroAbility** [comment] 2023-02-14 02:37
Duplicate of https://github.com/mumble-voip/mumble/issues/1273

**Closed** 2023-02-14 06:16 UTC
Labels: overlay, help wanted
