### ISSUE TITLE
Connect with different usernames even if one is registered

### ISSUE THREAD

**Issue by meaz** [mumble-voip/mumble#4012] opened 2020-03-27 09:09 UTC
Hi,

if I register my username ("meaz") on my mumble server, then, if I add another connexion to the same server with a different username ("testuser"), mumble connects me with the registered username, so "meaz" in this example.

I would love to be able to have several usernames attached to my certificate so that I could decide to log with one username or with another one, or, if it is not possible, to have the possibility to log in with a different username without using the registered username certificate.

Thanks a lot!

**Comment by Krzmbrzl** [comment] 2020-03-27 09:27
My understanding is that registration has the very purpose of fixing a user to a single UserName to be recognized throughout sessions.

What I am certain though is that this is intended behavior, so I take it that this is a feature-request?

**Comment by meaz** [comment] 2020-03-27 10:30
> My understanding is that registration has the very purpose of fixing a user to a single UserName to be recognized throughout sessions.

Yes you're right. But when you add another server with the same address (so the same server) and add a different username, you're still connected to the user that you registered with. So it is confusing I think.

> What I am certain though is that this is intended behavior, so I take it that this is a feature-request?

Yes, that would be great to be able to switch between different usernames.

**Comment by Krzmbrzl** [comment] 2020-03-27 10:35
What is a use-case for adding in another server with the same address as another one? Apart from changing the nickname that is.

The identification of a user is based on the client certificate and thus as far as the serve is concerned, it doesn't matter how you connected to it. As long as you have that certificate, it'll assign you the specific name you had when registering on that server.

> Yes, that would be great to be able to switch between different usernames.
If that is all this issue is about, I think it is a duplicate of #3779

**Comment by meaz** [comment] 2020-03-27 10:49
the use case is this one. I'm registered onto a server as meaz. That is my "online" username.

I am a teacher and I would like to have my pupils to join the server so that I can have audio conferences with them (because of the coronavirus). So, I would like to change my username to something that they could recognize, for example, 'Teacher" and at the same time, I don't want them to know my online username. I would then change my username to "Teacher" when we have a meeting, and get back to "meaz" the rest of the time. 

I have another idea: could it be possible to have a different username in a channel? Because then , I could just appear as "Teacher" in the channel I created for my pupils, and when I get out of this channel, be seen as "meaz".

**Comment by Krzmbrzl** [comment] 2020-03-27 10:54
I don't assume you have admin rights on that server, do you? As it is now only admins can change the names of registered users.

> could it be possible to have a different username in a channel?

Possible - probably. But I don't think it'd be a good idea to have this. Just imagine the confusion if you see that XY is on your server, you blink in which time XY changes channel and now XY is gone and you only see a YZ in another channel.

Your use-case (although absolutely valid) seems to be solved by #3779 (once it is implemented) which is why I will close this issue as a duplicate.
If you feel that the linked issue would not solve your situation, please elaborate why this is so :)

**Closed by Krzmbrzl** 2020-03-27 10:54 UTC

**Comment by meaz** [comment] 2020-03-27 11:01
thanks a lot, it does indeed look the same...
