### ISSUE TITLE
Feature Request: Listen Permission

### ISSUE THREAD

**Issue by nocmonkey** [mumble-voip/mumble#1352] opened 2014-08-15 07:31 UTC
Add a listen permission in order to allow admins the ability to control deafening via ACLs.

**Comment by ZeroAbility** [comment] 2023-02-13 00:16
Does this provide the requested feature?

https://wiki.mumble.info/wiki/ACL_and_Groups/English#Mute_.2F_Deafen

**Comment by Hartmnt** [comment] 2023-02-13 09:58
> Does this provide the requested feature?
> 
> https://wiki.mumble.info/wiki/ACL_and_Groups/English#Mute_.2F_Deafen

No, I think this is more or less a duplicate of #1257

**Comment by Krzmbrzl** [comment] 2023-02-14 12:26
I agree. Let's close this as a duplicate

**Closed by Krzmbrzl** 2023-02-14 12:26 UTC
Labels: acl, feature-request
