### ISSUE TITLE
64 bit Mumble doesn't work with 32 bit Steam games on Linux

### ISSUE THREAD

**Issue by NothingMuchHereToSay** [mumble-voip/mumble#1274] opened 2014-05-30 05:47 UTC
Ubuntu 14.04 64 bit

Command output:

ERROR: ld.so: object '/usr/lib/mumble/libmumble.so.1' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.

**Comment by Thrash-td** [comment] 2016-02-25 10:35
The problem is still exist. Attempt to run Team Fortress 2 with overlay:
`$ LD_PRELOAD=/usr/lib/mumble/libmumble.so steam steam://run/440`
`Running Steam on manjarolinux 15.12 64-bit`
`STEAM_RUNTIME is enabled automatically`
`ERROR: ld.so: object '/usr/lib/mumble/libmumble.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.`

Mumble (1.3.0~941~gcffa565~snapshot)

I was using [this](https://www.reddit.com/r/truetf2/comments/393t7l/how_to_enable_mumble_overlay_on_linux_with_tf2/) workaround for a while. But looks like it's doesn't work now.

**Comment by mkrautz** [comment] 2016-02-25 10:49
@Thrash-td 

There are a number of possible problems here:

Either the error is from Steam itself. This could happen if the Steam binary itself is 32-bit.
In this case, the assumption is that Steam will keep its environment around in programs it launches, such that any games launched through steam also have LD_PRELOAD=/path/to/libmumble.so set.
Since the overlay doesn't appear in the game, this probably isn't it.

Another possibility is that the error is from the game itself. In this case, the game is of a different architecture than the libmumble.so that you're using. Since you're on a 64-bit x86_64 OS, you'd need a libmumble.so built for i386 instead. Then it would probably work.

Right now, we can't easily provide a 32-bit libmumble.so with our PPA inside the 64-bit package. And Linux distributions don't do that either, since an x86_64 package shouldn't contain i386 binaries.

Either you build libmumble.so yourself.
Or you download a i386 build of Mumble and extract its libmumble.so.
Or you install the x86_64 and i386 packages of Mumble side-by-side, if your distro suports that.

**Comment by mkrautz** [comment] 2016-02-25 11:00
@NothingMuchHereToSay We want to provide automatic injection on Linux as well. But it's already quite fragile on the other platforms (which is why we want to make it only injection into known game launcers by default on Windows, for example: https://github.com/mumble-voip/mumble/issues/2059).

The feature is tracked here:
https://github.com/mumble-voip/mumble/issues/2129

Obviously, if you want to inject it into everything -- that has been possible since the start.

Simply set a global environment variable, LD_PRELOAD=/path/to/libmumble.so, and you'll automatically have the overlay in all processes.

**Comment by msva** [comment] 2016-07-27 08:31
@davidebeatrici I'd say it is not only ubuntu problem. I having segfaults on gentoo too. Even when (just to test) trying to preload overlay to glxgears

**Comment by mkrautz** [comment] 2016-07-27 08:44
@msva Hm. But this thread isn't about segfaults, it's about binary distros not shipping both 64-bit and 32-bit overlay libraries.

Can you open a new issue for what you're seeing -- or at least clarify in here?

Thanks.

**Comment by msva** [comment] 2016-07-27 08:55
I just meant that I have all the same behaviour as @Weegee mentioned in [second comment](#issuecomment-46064581)
// Although, maybe really it is not that clear as he described and right now I can't say in which cases it causes segfault, and in which just warns about wrong elf class.

**Comment by ZeroAbility** [comment] 2023-02-12 03:29
This appears to be a duplicate of https://github.com/mumble-voip/mumble/issues/1274 just with more info.

**Comment by Krzmbrzl** [comment] 2023-02-12 06:56
There are mutlitple issues addressed in here and as such this is not a particularly useful ticket. But for the most part it really seems to be a duplicate of the linked issue.

**Closed** 2023-02-12 06:57 UTC
Labels: overlay, linux, ubuntu, bug
