### ISSUE TITLE
Certain special characters are not shown on Windows

### ISSUE THREAD

**Issue by davidebeatrici** [mumble-voip/mumble#4939] opened 2021-04-21 22:42 UTC
Reported by @Natenom.

Example string: `ᎭᎪᎢᎬᎭᎾᎷ`

All characters are shown as empty space.

**Comment by Krzmbrzl** [comment] 2021-04-22 06:17
It seems that it can happen that the used font does not contain the used characters. See https://forum.qt.io/topic/82243/some-unicode-characters-not-displayed-on-ui/3

There it is suggested that this can be checked with the following snippet:
```cpp
QFont f("DejaVu sans");
QFontMetrics fm(f);
qDebug() << fm.inFont(QChar(2399)) << fm.inFont(QChar(2386));
```
I guess we'd instead want to use the font from our main application instead of providing the font name explicitly... (And obviously we'll have to use different character codes)

@davidebeatrici you said you can reproduce - could you try to verify that these characters are contained in the used font

**Comment by davidebeatrici** [comment] 2021-04-22 06:38
```cpp
QFontMetrics fm(qApp->font());
qDebug() << fm.inFont(QChar(0x13AD)) << fm.inFont(QChar(0x13AA)) << fm.inFont(QChar(0x13A2))
		 << fm.inFont(QChar(0x13AC)) << fm.inFont(QChar(0x13AD)) << fm.inFont(QChar(0x13BE))
		 << fm.inFont(QChar(0x13B7));
```

```
true true true true true true true
```

**Comment by Krzmbrzl** [comment] 2021-04-22 08:46
Hm okay.

Btw.: Why did you label this issue as `upstream-bug`? Do you already have evidence that this is not our fault? And if so: Why is this ticket still open? :thinking:

**Comment by davidebeatrici** [comment] 2021-04-22 17:23
I'm pretty sure it's an upstream bug because Windows has no issues showing those characters.

The ticket is still open because we have to either find a workaround or fix the issue in Qt.

**Comment by Krzmbrzl** [comment] 2021-04-23 06:56
I guess in order to verify that this is an upstream Bug, we'd have to create a minimal example that also fails to display this String.
I think a simple label with this text should be sufficient. Plus it should probably include the check for whether these characters are contained in the used font. And if we have verified this in this way, we can file a report against Qt and close this issue here as an upstream issue.

Should that minimal example be capable of displaying this String, then the issue is probably on our side somewhere :thinking:

**Comment by davidebeatrici** [comment] 2021-04-23 18:55
Done: https://github.com/mumble-voip/qt_unicode_test

![](https://user-images.githubusercontent.com/5897523/115916614-52ab0280-a475-11eb-880c-f5e6df01be3c.png)

```
String: "ᎭᎪᎢᎬᎭᎾᎷ"
Character '\u13ad' in font: true
Character '\u13aa' in font: true
Character '\u13a2' in font: true
Character '\u13ac' in font: true
Character '\u13ad' in font: true
Character '\u13be' in font: true
Character '\u13b7' in font: true
```

**Comment by Krzmbrzl** [comment] 2021-04-26 17:06
Upstream report: https://bugreports.qt.io/browse/QTBUG-93183

Until proven otherwise I'll close this as an upstream bug

**Closed by Krzmbrzl** 2021-04-26 17:06 UTC
Labels: qt, upstream-bug, windows

**Comment by Kissaki** [comment] 2021-05-02 21:00
@Krzmbrzl Shouldn’t this be listed as a known issue in our release notes then? Or is this specific to master rather than our stable too?

**Comment by Krzmbrzl** [comment] 2021-05-03 05:54
It seems to only be an issue with 1.4.0 snapshots.
But I guess for them we should probably add it...

**Comment by davidebeatrici** [comment] 2021-05-03 06:31
No, it's an issue in 1.3.x too.

I didn't try to reproduce in 1.2.x.

**Comment by Krzmbrzl** [comment] 2021-05-03 07:58
> No, it's an issue in 1.3.x too.

Did you verify that? 'cause if I remember correctly @Natenom mentioned that this was only observed since 1.4.0 snapshots :thinking:

**Comment by davidebeatrici** [comment] 2021-05-03 17:51
> A user reports he cannot see some special characters with 1.3.4. Neither in the public server nor when connecting to the server.

**Comment by Krzmbrzl** [comment] 2021-05-03 18:23
Ah I missed that one... I'll add it to the list of known issues

**Comment by Kissaki** [comment] 2021-05-08 11:24
Looks like it was added to the release notes (on GitHub) 👍

**Comment by Snowknight26** [comment] 2022-09-15 01:06
The example string provided in the first post, `ᎭᎪᎢᎬᎭᎾᎷ`, is rendered correctly on Windows 10 using 1.4.287. Noting this since this issue is listed as a known issue for 1.4.287.

![image](https://user-images.githubusercontent.com/5608270/190289335-e11919c9-cc99-4862-acff-177054d47ccc.png)

**Comment by Krzmbrzl** [comment] 2022-09-15 07:14
I removed the note, thanks

**Comment by davidebeatrici** [comment] 2022-09-15 17:12
@Snowknight26 Was the string rendered correctly in 1.4.274 as well?

**Comment by Snowknight26** [comment] 2022-09-15 22:31
> @Snowknight26 Was the string rendered correctly in 1.4.274 as well?

It was, was.

![image](https://user-images.githubusercontent.com/5608270/190519989-9ae45cbe-a2af-404b-bbd2-ec2fd46bcadd.png)
