### ISSUE TITLE
Retain spaces on chat messages

### ISSUE THREAD

**Issue by Ape** [mumble-voip/mumble#1838] opened 2015-10-10 09:58 UTC
Currently any sequences of spaces in chat messages are collapsed to just one and leading spaces are trimmed. For example

```
"    a             b" => "a b"
```

This makes it hard to communicate source code snippets. Consider a scenario where an user wants to send this Python code:

``` python
while True:
    if error:
         print('There was an error!')
         break
```

It currently appear as:

```
while True:
if error:
print('There was an error!')
break
```

I don't see any reason for trimming the white space. It just seems to cause issues in some cases. Spaces are only trimmed on the client UI, so there is no need to change any server side things.

**Comment by hacst** [comment] 2015-10-10 12:56
That's due to the html nature of the display area we are using. Would be great if we could get rid of that behavior as I myself am bugged by that from time to time when trying to send code. Overall I don't consider this to be a big issue though. Most normal users using chat won't notice.

Usually we should be able to easily fix this by wrapping things from the chat bar in
```html
<div style="white-space: pre-wrap">...</div>
```
but unfortunately Qt doesn't seem to properly process it.
```html
<div style="white-space: pre">...</div>
```
works but that obviously disables line wrapping and we don't want that.

**Comment by Ape** [comment] 2015-10-10 14:15
Hmm, according to Qt documentation ```pre-wrap``` should be supported. [[1]](http://doc.qt.io/qt-4.8/richtext-html-subset.html)

**Comment by hacst** [comment] 2015-10-11 11:32
Yeah. I know it should be. Doesn't work though. Will have to write a small reproducer and figure out what exactly is broken there.

**Comment by u6bkep** [comment] 2021-06-06 07:25
any chance we could get preservation of spacing as an option or checkbox in the send message dialog? just a checkbox that wraps all the text in <pre> tags or something else to preserve white space. In my group we send text that needs white space almost more often then we send messages that are ok to strip.

**Comment by Krzmbrzl** [comment] 2021-06-06 13:58
@u6bkep with Mumble 1.4.0 there is now markdown support that includes sending source code.

Use e.g. as
```
\`\`\`
   Your code
\`\`\`
```

That should do what you need. In fact that should resolve this issue altogether and thus I'll close this issue as resolved.

**Closed** 2021-06-06 14:00 UTC
Labels: client, enhancement, ui
