### ISSUE TITLE
Echo cancellation causes a memory leak

### ISSUE THREAD

**Issue by wchristian** [mumble-voip/mumble#3379] opened 2018-03-24 10:32 UTC
Dump file: [mumble.exe.11080.dmp.zip](https://github.com/mumble-voip/mumble/files/1844269/mumble.exe.11080.dmp.zip)

Steps:

- run Mumble 1.2.19 on Win10Pro with a Focusrite Scarlett Solo Mk1 (usb soundcard)
- open "Self > Audio Statistics" window
- confirm input is picked up
- wait until input gets stuck, i.e. speech detection bar and all values stop updating. recording tab in windows sound device window also doesn't indicate input anymore. (hardware volume meter on soundcard indicates pickup tho)
- let it sit, don't touch audio things (playing music or games is ok tho)
- eventually Mumble crashes

**Comment by mkrautz** [comment] 2018-03-24 10:37
Thanks!

**Comment by wchristian** [comment] 2018-03-24 11:24
Cheers.

I forgot to mention: It can take a long time for this to happen. I usually have a crash due to this maybe once a week.

Happy to provide more data too if i can, or test builds, etc.

**Comment by mkrautz** [comment] 2018-03-24 21:26
The crash itself happens when trying to send a Ping packet. A malloc inside QSslSocket::writeData (...due to a realloc on a QRingBuffer's QByteArray) seems to exhaust the virtual memory space of the process.

It's hard to say where WASAPIInput is stuck. It seems to be in the call to GetNextPacketSize.

I'd recommend you try to see if you can reproduce this in the latest 1.3.x snapshot, available from https://www.mumble.info/. 

However, if you run into this on 1.2.x again, could you check the memory usage -- before it crashes?
If it is indeed a leak somewhere causing this problem, a full dump would be more helpful. (Right click Mumble in Task Manager -> Create dump file...). However, beware of posting this publicly, as it could contain sensitive material, such as the private key of your client cert, etc.

...Anyway, I'd try 1.3.x first.

**Comment by wchristian** [comment] 2018-03-25 07:41
To minimize hopping around between versions i'm trying to get data on the memory issue first, and upon watching the usage found that it seemed to be leaking indeed and did this over the course of 20 minutes:
![image](https://user-images.githubusercontent.com/175467/37872859-781bf182-3010-11e8-8135-81ed23ee79b1.png)
Failed to get a dump because some of the steps necessary to get there reset the memory usage, but i should have something soon.

Then i'll try with 1.3 and see if i can replicate the behavior. (I'm not urgently needing to fix this and would rather provide as much useful info for fixing as i can.)

**Comment by wchristian** [comment] 2018-03-25 08:15
Alright, i got the same behavior to reoccur by having it open while a youtube video was playing on the loudspeakers that the mic could pick up. (Interestingly i saw a lot more CPU usage by mumble when the environment was quiet.

Here's a set of dumps and minidumps at various times in the process. Please let me know where i should send the password, or you can ping me on telegram under @mithaldu

https://www.dropbox.com/s/yiez7hx85d95t7y/mumble1.2_dumps.zip?dl=1 (Upload in process, ETA 8 minutes from this post.)

Trying with the latest snapshot now. (Would be good if i could copypaste the snapshot version out of the program.)

**Comment by wchristian** [comment] 2018-03-25 08:32
Alright, same behavior occurs under 1.3 and even better: The sound input stopped working this time, which immediately sent mumble into memory gobbling mode. About 10 mb per minute.

![image](https://user-images.githubusercontent.com/175467/37873163-d0632a94-3016-11e8-8aa7-21433650eee6.png)

Dumps: https://www.dropbox.com/s/xgnzm5p4pcc2z6q/mumble1.3_dumps.zip?dl=1 (Upload in process, ETA 8 minutes from this post.)

Going into the options menu and clicking "apply" reset the memory usage back to baseline, but it immediately started rising again. Switching to ASIO, letting it sit a while, and back to WASAPI reset the memory usage and also reenabled input, but i'm not sure how much that is incidental.

**Comment by mkrautz** [comment] 2018-03-25 08:48
Haven't looked at the dump yet, but:

The problem seems to be that addMic() doesn't get called any longer, but addEcho() does.

Based on this:

We added a "leak guard" a while back, for a PulseAudio bug that causes Pulse to produce extra echo frames:
https://github.com/mkrautz/mumble/commit/a5c45550ae8e0d1ccdbf047823e0472a040ca668

That guard only clears qlEchoFrames when adding new audio via addMic().

The interesting question is: how can addMic() not be called if addEcho() is? They're running inside the same thread. That must mean that we're improperly handling some error condition for getting mic data from WASAPI.

**Comment by mkrautz** [comment] 2018-03-25 08:49
Ah, actually... That PR wasn't landed: https://github.com/mumble-voip/mumble/pull/2786

**Comment by mkrautz** [comment] 2018-03-25 08:53
@wchristian To send me the passphrase, could you PGP encrypt it, via https://keybase.io/encrypt#mkrautz and send it to mikkel@krautz.dk... or here, I guess.

**Comment by wchristian** [comment] 2018-03-25 09:20
Here you go:

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.76
Comment: https://keybase.io/crypto

wcFMA+EGJbyHJEqCAQ//aV2n7bZwH3a5OyFu1kGRsDjE3mN3EqRq6PfA3PY5PRq1
DJvmYLLI5pbvA0nH6MNPD7PGRRXWoPiwdaG2t1xSXolADh21pscnL1EFTgWKQ0wE
iYDUeknMJvoaXTVDfCK7I6OcddnAKgnYJfwXxttnQ47Mv/L7dpOPkbQOeKF7nb9s
2DGDoYPPWBbvOWhbJVR017HZoqGwPRCjphMtVnxcwiEkNO/xdgrgReb53ELCKRAF
OtUYpHdVR02ov5D3sRjUQZBjRqsyLRozjtw6M5bcsxIH+mGkJHKLU7jYrifiu+11
wzMkrkjDsJGmDidgiQXRzLnLA0czFh1lBbmm5Xwvi8Mzxci0tzD24+mLOQlfw5RE
GqW53VWYZnqb5c3FEW/a969kUqsTRheg7qWmhvlRUf+actn3TiLMVYrrdMTIcqvR
BOz2yDedV5jeLSLAACat0qC+//Rta53V+8T7MPgslAaSv7U9PxmjF06KX22W9Fmo
Jo4bXlseCe69+enCXaO1Nx+eKLlozLT0crt3ySlD1E5d6gOozYf+AMDuaWKM+nTk
QvShWY9/4oR//JfEOOoP86e7WWUWQiPiJxg9rlEJFx6XP4cAi7wCqXYZUZmxc4wf
GDK3JzmX0vKOa1y8HhJa5v3X+UqQqktPqwaP4llJ3YBt6gBwJVZ4u39cHGjMvJvS
RAFItzyTM/6GiUJIUrKSTBaIp0TD/IGsp7htfy3COnVEIql/JboWQPZ9Wa1tElfR
TLpEPNGOrL1CVV2qiLtElCgA8539
=z4Tl
-----END PGP MESSAGE-----

**Comment by wchristian** [comment] 2018-03-25 09:25
I should note: The leak ALSO happens while the mic is still open and working, just more slowly. (Or maybe that's a second leak.)

**Comment by wchristian** [comment] 2018-03-25 09:52
Disabling echo cancellation seems to have stopped the leaks. Still observing. (Of course not great for usability.)

**Comment by mkrautz** [comment] 2018-03-25 10:41
@wchristian I have downloaded the file, feel free to remove it from your Dropbox.

**Comment by wchristian** [comment] 2018-03-25 10:45
Thanks. I'll hold off on deleting them for a while, just in case. :)
And 👍 on the extra ticket.

**Comment by mkrautz** [comment] 2018-03-27 21:21
Well, the memory leak is because addMic() is never called. Thus, all the extra echo frames generated are never cleaned up.

The real question is: why is the audio stuck?

Could you check the Mumble log to see if there's anything useful in there?

%APPDATA%\Mumble\Console.txt

**Comment by wchristian** [comment] 2018-03-27 22:59
Might be an issue with the hardware or its driver. I've also been in contact with the manufacturer, but decided to try and see if the crashes of mumble might be related.

Does this help?

https://www.dropbox.com/s/q0a7s32o5n8lhvz/Console.txt?dl=0

**Comment by wchristian** [comment] 2018-04-03 07:42
Any update on the leak itself? I'm not sure if your last post ties the leaking to the getting stuck or not, as the two seem to happen without connection to one another.

**Comment by mkrautz** [comment] 2018-04-03 08:57
AFAICS, it should only leak when addMic() is not called (which means it isn't getting mic data).
If you see it without it getting stuck, that would be an interseting tidbit, and I'd take another look.

**Comment by mkrautz** [comment] 2018-04-03 08:59
Also, the Console.txt has this:

	<W>2018-03-27 23:39:04.511 WASAPINotificationClient: Device state changed newState= 1 device= "{0.0.1.00000000}.{df96399a-ccd8-4886-97a3-1824407d3464}"
	<W>2018-03-27 23:39:04.512 WASAPINotificationClient: Default device changed flow= 1 role= 0 device "{0.0.1.00000000}.{df96399a-ccd8-4886-97a3-1824407d3464}"
	<W>2018-03-27 23:39:04.513 WASAPINotificationClient: Default device changed flow= 1 role= 1 device "{0.0.1.00000000}.{df96399a-ccd8-4886-97a3-1824407d3464}"
	<W>2018-03-27 23:39:04.514 WASAPINotificationClient: Default device changed flow= 1 role= 2 device "{0.0.1.00000000}.{df96399a-ccd8-4886-97a3-1824407d3464}"
	<W>2018-03-27 23:39:04.514 WASAPINotificationClient: Triggering audio reset
	<W>2018-03-27 23:39:04.515 MainWindow: Start audio reset
	<W>2018-03-27 23:39:04.515 WASAPINotificationClient: Default device changed flow= 1 role= 3 device "{0.0.1.00000000}.{df96399a-ccd8-4886-97a3-1824407d3464}"
	<W>2018-03-27 23:39:04.522 AudioInput: Opus encoder set for VOIP
	<W>2018-03-27 23:39:04.523 AudioInput: 96000 bits/s, 48000 hz, 480 sample
	<W>2018-03-27 23:39:04.523 MainWindow: Audio reset complete

which would typically be from you unplugging and re-plugging the audio device, or something like that. Do you do that?

**Comment by wchristian** [comment] 2018-04-03 09:40
> If you see it without it getting stuck, that would be an interseting tidbit, and I'd take another look.

I absolutely see the memory leak in normal use too, the mic drop just makes it go faster. See: https://github.com/mumble-voip/mumble/issues/3379#issuecomment-375954115

> which would typically be from you unplugging and re-plugging the audio device, or something like that. Do you do that?

I do that occasionally (it's a usb sound card, so that sometimes helps), but i have confirmed by checking this morning's log that i get that type of set of messages also at times when i *know* i didn't disconnect it.

**Comment by wchristian** [comment] 2018-04-03 10:20
Here's another more clear example of the leak:

![image](https://user-images.githubusercontent.com/175467/38243653-7d0e2abe-3738-11e8-8ca6-c7821b1cc13f.png)

> <W>2018-04-03 11:41:59.202 AudioInput: ECHO CANCELLER ACTIVE
> <W>2018-04-03 12:12:41.560 AudioInput: Opus encoder set for VOIP


The IO spike is at 11:41, when i activate the canceller. The first measurable blip of memory use rise happens at 11:51, then it remains flat for a while, and rises in earnest at 11:53, until 12:12 when i disable the echo canceller. The log, as shown above, shows zero activity between my two actions there.

**Comment by wchristian** [comment] 2018-04-12 03:54
Just woke up to this. :D

![image](https://user-images.githubusercontent.com/175467/38655554-b697d990-3e15-11e8-9ce7-79bcfc7ada1f.png)

Only log contents before this: https://gist.github.com/wchristian/8da130fe0c8c10e58f861b993a70eba5

(It is now 0554 local time.)

**Comment by mkrautz** [comment] 2018-04-15 18:59
Unfortunately, I wasn't able to hook into the memory I wanted from your memory dumps. :(

Not sure why. WinDBG complained that the memory wasn't available in the dump.

So unfortunately, I haven't been able to debug further.

**Comment by wchristian** [comment] 2018-04-17 15:12
Is there anything i can do on my end to help get you useful data?

**Comment by crknadle** [comment] 2019-02-13 01:16
It appears that this bug is related to Debian bug #921617:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=921617

So I think this issue is affecting other OSes than Windows

**Comment by streaps** [comment] 2020-05-09 14:45
Is this still happening with 1.3.0?

**Comment by Krzmbrzl** [comment] 2020-05-10 09:16
Good question. I didn't experience it, but then again I haven't used Mumble for really long sessions yet...

**Closed** 2020-06-09 10:15 UTC
Labels: audio, client, needs-more-input, priority/P2 - Important
