### ISSUE TITLE
FR: Global shortcuts for peers local volume adjustment

### ISSUE THREAD

**Issue by AtmanActive** [mumble-voip/mumble#6216] opened 2023-10-02 10:34 UTC
### Context

client

### Description

In a 4 player co-op session I frequently get into a situation where some of my peers are too loud while some are too soft to understand them. This is not a simple matter of individual input compressors, but a matter of various factors, like for example, how loud the game gets, how breathless the speaker gets, and so on. I already have various knobs and streamdecks on my desk and would like to use them to adjust my local volume level for each of the participants in a channel. Alas, as of this writing, Mumble doesn't provide global shortcuts for this.

Thanks.

### Mumble component

Client

### OS-specific?

No

### Additional information

Mumble rocks!

**Comment by Hartmnt** [comment] 2023-10-02 10:55
Duplicate of #3932

**Closed by Hartmnt** 2023-10-02 10:55 UTC
Labels: feature-request, triage
