### ISSUE TITLE
Headless Certificate Accepting

### ISSUE THREAD

**Issue by Frettarix** [mumble-voip/mumble#5037] opened 2021-05-24 16:26 UTC
**Context**
_In which context would you expect your suggested feature to be useful?_ 
LAN Voice assistants.

**Describe the feature you have in mind**
_A clear and concise description of what you want to happen._
Currently a headless client works if you copy the configuration files (no need for a GUI to accept options), the only thing you can't do is accept the certificate it seems. Full headless support would make it easy to use Mumble together with a home-assistant for LAN voice commands.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
I tried the GUI method, but my Raspberry won't support that.

**Additional context**
_Add any other context or screenshots about the feature request here._
Currently bypassing the GUI via:
Xvfb :1 &
export DISPLAY=:1

**Comment by Krzmbrzl** [comment] 2021-05-26 10:35
Duplicate of #3877 and/or of #3913

**Closed by Krzmbrzl** 2021-05-26 10:35 UTC

**Comment by Krzmbrzl** [comment] 2021-05-26 10:38
As a (temporary) workaround, you can abuse that the certificate is currently stored in Mumble's settings. On Linux they are stored in `~/.config/Mumble/Mumble.conf`.
The tricky part would be to get Qt's QByteArray serialization format right.

The line you are looking for looks something like this:
```
[net]
certificate="@QByteArray(<contents>)"
```

**Comment by siddhpant** [comment] 2021-11-15 15:15
Is there any way to allow any certificate? Because it doesn't join the channel unless accepted from GUI.

The use case (https://github.com/siddhpant/broo) runs on a local server so I don't really have to worry about authentication.

**Comment by Krzmbrzl** [comment] 2021-11-15 18:24
@siddhpant where do you want to allow any certificate? On the server?

**Comment by siddhpant** [comment] 2021-11-16 11:32
I want to skip the warning.

**Comment by Krzmbrzl** [comment] 2021-11-16 12:40
I'm not aware of a way to do this :thinking:
