### ISSUE TITLE
Autoscroll doesn't always work (correctly) on latest master

### ISSUE THREAD

**Issue by Gert-dev** [mumble-voip/mumble#4638] opened 2020-12-16 16:34 UTC
**Describe the bug**
Several of my fellow Mumblers updated to an unstable build a few days ago to get access to stereo support and apparently some bugfixes related to image pasting, and we noticed that _sometimes_ autoscrolling doesn't behave well when images are pasted.

Usually, if A pastes an image, and whether B's scrollbar is scrolled down as much as possible or not, B's chat view will scroll further down (to the bottom), bringing the image into view. However, _sometimes_, B's chat view will scroll to a (seemingly) arbitrary point in the chat view. This "abitrary" point always seems to be the same point, once this starts happening.

**Steps to Reproduce**
1. Join a server with two clients.
2. Start pasting images (e.g. by copying them from a browser and pasting them in the chat box input using Ctrl-V) and observe the behavior.

Because this doesn't always happen, I understand this may not be easily reproducible. It seems to happen about half of the time. Sometimes it randomly fixes itself and several pastes will work fine, and it might break again at some other point.

I've (unsuccessfully) tried pinpointing the exact thing that makes this occur:

* Images of various widths and heights, but nope.
* Clearing the chat view when this starts happening, also nope.

**Expected behavior**
When someone says something or pastes an image:

* Was it you? Then always jump to the bottom.
* Was it someone else?
    * Is your scrollbar already at the bottom? Move further to the bottom after inserting the text or image.
    * Is your scrollbar not at the bottom? Maintain it in such a way that your viewport stays the same and you can keep reading what you were reading and are not forced down every time.

**Desktop (please complete the following information):**
 - OS: Arch Linux 64-bit for me, Windows 10 for my fellow Mumblers.
 - Version: `master` at commit c5b5c123d (1.4.0 dev). This also still appears to happen on commits of a couple of days ago.

**Additional context**
May be related to or a regression of https://github.com/mumble-voip/mumble/issues/1258 or https://github.com/mumble-voip/mumble/issues/1969.

**Comment by Krzmbrzl** [comment] 2020-12-18 07:52
> However, sometimes, B's chat view will scroll to a (seemingly) arbitrary point in the chat view. This "abitrary" point always seems to be the same point, once this starts happening.

Is this arbitrary position really arbitrary or is it e.g. always lower or equal to the current scroll position?

Does this only happen if B is scrolled down to the bottom at the time the image arrives or does this also happen regardless of B's current scroll position?

----

When having a quick look at the code that is probably responsible for the scrolling behavior, it seems that it pretty much uses the exact same logic you just described:
https://github.com/mumble-voip/mumble/blob/d408deb2463211c37df02ae13bbafa7450761ec4/src/mumble/Log.cpp#L661-L707

**Comment by Gert-dev** [comment] 2020-12-18 14:15
> Is this arbitrary position really arbitrary or is it e.g. always lower or equal to the current scroll position?

The position is always upwards, i.e. backwards in chat history, looking at older logs. A pasting an image will make B jump up to some older chat logs he isn't interested in or wasn't even looking at, as if some random point in the chat history is locked/chosen sometimes, and then that point is scrolled to instead of scrolling to the end of the chat log (if B was already at the end).

> Does this only happen if B is scrolled down to the bottom at the time the image arrives or does this also happen regardless of B's current scroll position?

It happens when B is scrolled down to the bottom at the time the image arrives. When B is not, I only noticed Mumble forcing B's view down to the end (which is annoying, but currently perhaps still intended behavior); it may yet also happen here, but I've not (yet) noticed it, but I'll keep an eye out to see if it also happens there.

**Comment by Gert-dev** [comment] 2020-12-27 22:21
> ... but I've not (yet) noticed it, but I'll keep an eye out to see if it also happens there.

Had some more time to test, and it also happens when scrolled up; you are then forced down back to that specific position, rather than the end.

**Comment by Krzmbrzl** [comment] 2020-12-28 15:23
Hm okay. That's weird :eyes: 

I guess in order to find out what's going on, we'd have to do a `git bisect` to find out where the problem was introduced...

**Comment by Argetlami** [comment] 2021-03-05 07:36
Can confirm, the automatic-scroll-to-bottom does not seem to work on any linux distribution I've used in past years. Our mumble community heavily utilizes posting images into the mumble chat with a [mumo chatimg-module](https://github.com/aselus-hub/chatimg-mumo). With that, this is very visible bug in our use scenario. This does not seem to happen on Windows-clients.

However, this might be an upstream bug as this issue is probably relevant to https://github.com/mumble-voip/mumble/issues/2504
An upstream bug report was created from that issue https://bugreports.qt.io/browse/QTBUG-83622

**Comment by Krzmbrzl** [comment] 2021-03-05 10:29
@Argetlami thanks for the info. This does indeed look very related :thinking: 

In fact after checking the code again this seems to be the exact same issue. Inside `Log.cpp` we are using
https://github.com/mumble-voip/mumble/blob/95d51828acaffc841cfba0b63a279081babd1008/src/mumble/Log.cpp#L695-L696
and this function is defined as
https://github.com/mumble-voip/mumble/blob/cdbc4058874f623b7b5404a6502cf2bc426abbb6/src/mumble/CustomElements.cpp#L52-L54
which is the exact same semantics as reported in that bug report.

Thus I am closing this issue as an upstream bug and as a duplicate of #2504

**Closed by Krzmbrzl** 2021-03-05 10:29 UTC
Labels: bug, client, ui

**Comment by Kissaki** [comment] 2021-03-05 18:18
We may want to track this as a known-issue then? (Release notes or wherever we collect those.)

**Comment by Krzmbrzl** [comment] 2021-03-06 13:30
Yes indeed :+1:

**Comment by Kissaki** [comment] 2021-03-06 18:04
Will you add it @Krzmbrzl ?

**Comment by Krzmbrzl** [comment] 2021-03-06 18:05
Already done

**Comment by Gert-dev** [comment] 2021-05-22 19:58
Just wanted to follow up and mention that this happens to a friend on Windows, too, in case anyone is wondering.
