### ISSUE TITLE
Launch shortcuts lost after upgrade to 1.4

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5023] opened 2021-05-22 10:06 UTC
**Describe the bug**

Start menu context menu no longer shows jump shortcuts to immediately connect to a (recent) server.

**Steps to Reproduce**
1. Pin program to start menu
2. Open context menu

**Expected behavior**
List of servers shows up like it does in 1.3, like it still seems to in the context menu of the task bar

**Screenshots**

![image](https://user-images.githubusercontent.com/93181/119222719-0693c200-baf6-11eb-9337-b1dccf64ab11.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.4 snapshot

**Comment by ZeroAbility** [comment] 2021-05-22 17:46
Is the issue specifically for our shortcuts or for any shortcuts? Please review this and make sure your system is not affected:

https://answers.microsoft.com/en-us/windows/forum/windows_10-start-winpc/jump-lists-not-working-in-windows-10/f03cd014-6784-4d81-8735-3beb9877db5a

**Comment by Kissaki** [comment] 2021-05-22 18:09
Others still work fine, show up from the start menu.

**Comment by Kissaki** [comment] 2021-05-22 18:11
Not sure what specifically you want to point to on that 11 page forum topic.

**Comment by ZeroAbility** [comment] 2021-05-22 18:25
> Not sure what specifically you want to point to on that 11 page forum topic.

Just that there were issues posted regarding jump lists in Windows 10. Starting with the simple things first. My suspicion is the lists may need to be migrated since the installer changed. I will look into it.

**Comment by Kissaki** [comment] 2021-05-22 18:30
Given that the jump list is still there in the taskbar, I’m first suspecting some manifest differences. 🤷‍♂️

**Comment by ZeroAbility** [comment] 2021-05-22 18:33
Just to try something else simple, if you logoff and login do they show up? PuTTY had a similar issue with one of their installers and it appeared to clear up on its own:

https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/win-jumplist-trouble.html

**Comment by Krzmbrzl** [comment] 2021-05-23 08:44
Where are these "jump lists" defined in the first place? You mentioned some manifest - does that mean it is somewhere in the installer? :thinking:

**Comment by davidebeatrici** [comment] 2021-05-23 17:20
Relevant code lives in https://github.com/mumble-voip/mumble/blob/master/src/mumble/TaskList.cpp.

**Comment by Krzmbrzl** [comment] 2021-05-26 11:00
Well then this seems very odd that this would not work anymore since there were no changes to the way things are added to the TaskList.
It even gets weirder that apparently for the task bar it still works as expected while for the start menu it does not.
To me this kinda seems as if there was some sort of change on Windows's side but I assume @Kissaki used 1.3.x on that very same machine with the same Windows version and it was still working?

**Comment by Kissaki** [comment] 2021-05-29 09:03
I uninstalled both installers.

Installing 1.3.4 the jump lists show up fine in start menu, pinned start, and task bar.

Installing 1.4 snap it does not show up in any of those.

**Comment by Kissaki** [comment] 2021-05-29 09:15
Reading the linked code above, I see the jump list is stored windows-side.

And it looks like we pass program executable path as a key for the storage.

The 1.4 installer changed the installation path of Mumble client, using a client subfolder.

We should implement a migration path that takes over previous stored information.

**Comment by Krzmbrzl** [comment] 2021-05-29 10:32
Ahso the issue is that only the old entries don't show up anymore? I was thinking they don't work at all

**Comment by Kissaki** [comment] 2021-05-31 19:22
If anyone wants to look into this:

I would like to know what that DefaultIcon logic is about, where the app path is the fallback of.

The implementation should be quite simple: The resource/registory is being opened already, then the previous values have to be read, and copied to the new location. This should only be done if the new stuff is empty, and the old is not. Preferably we would only check this once, which would require some kind of migration flag. I think checking every time if empty is fine though. A single server connect will add something to the list.

**Comment by Krzmbrzl** [comment] 2021-05-31 19:32
> Ah so the issue is that only the old entries don't show up anymore? I was thinking they don't work at all

@Kissaki so?

**Comment by Kissaki** [comment] 2021-05-31 19:37
What?

**Comment by Kissaki** [comment] 2021-05-31 19:37
Yes

**Comment by Krzmbrzl** [comment] 2021-06-01 05:42
I want you to answer the question that I posed. Is the problem that the old launch shortcuts don't are not shown anymore or is the problem that these don't work at all?

**Comment by Kissaki** [comment] 2021-06-01 20:56
Upon launch the previous ones are no longer there.

**Comment by Krzmbrzl** [comment] 2021-06-02 06:14
Upon every launch or upon the first launch of 1.4.x after having used 1.3.x before?

**Comment by Kissaki** [comment] 2021-06-02 21:03
Unknown

But it seems pretty obvious to me what the expected behavior is from the code linked above, so I really don't get why we have to go back and forth here. The shortcuts are not moved, but the logic for adding new items upon connecting is still there.

Whether that expectation holds is something to test out when tackling this issue, when working on it.

If I had tested extensively I would have documented my findings. If you're asking if I know or verified, I don’t.

**Comment by Eviltechie** [comment] 2021-09-22 23:38
Mumble (1.4.0~2021-09-04~g37ee677~snapshot)

I have the launch shortcuts on the taskbar, but not within the start menu.

![image](https://user-images.githubusercontent.com/796982/134435663-3922ed07-0965-4b3f-8f4c-dc76c3824167.png)

![image](https://user-images.githubusercontent.com/796982/134435719-7710f379-52c9-477d-8ddf-c2c664c68d27.png)

For kicks, I tried deleting and re-adding the saved server I had. Didn't seem to affect anything.

**Comment by Krzmbrzl** [comment] 2024-12-30 16:00
Closing this as no longer relevant (1.4 has already been superseded by 1.5 by now) as the issue seems to only affect upgrading from pre-1.4 to 1.4 or newer. If someone experiences this with an upgrade from e.g. 1.4 to 1.5, please let me know.

**Closed by Krzmbrzl** 2024-12-30 16:00 UTC
Labels: client, windows, bug
