### ISSUE TITLE
Installer does not uninstall/replace 1.3 installs

### ISSUE THREAD

**Issue by Kissaki** [mumble-voip/mumble#5076] opened 2021-05-31 19:17 UTC
_I am migrating this from the Road to 1.4 project note so it is trackable and extendable as a ticket_

**Fix installer to uninstall/replace 1.3 installs correctly**

Currently, if 1.3 is installed it has to be uninstalled manually to be replaced by 1.4.

We expect the vast majority of users will want to replace any 1.3 installation.
Installing 1.4 in a different folder than 1.3 works fine.
Installing 1.4 into the same folder as 1.3 will cause issues (mixup; partial replace but still installation metadata).

With the switch to CMake we also changed the installer creation process leading to this change.
It does not seem to be a simple product/installer GUID mismatch.

The efforts we put into trying to fix the (new) installer to work as we intended could not resolve this up to now.
For the snapshots we currently warn users about this.

We may look into this again, with more/other eyes on it, but will not consider this a blocker.
We would be very thankful to other people checking this out too, and trying to come up with a solution.

**Comment by Kissaki** [comment] 2021-05-31 19:18
Installing 1.4 then 1.3, or 1.4 then 1.4, both installations work just fine because in 1.4 we install into client and server subfolders. So the old and new installations are separate.

The installers however do replace the previous shortcuts in the start menu, because they are the same file name and location.

**Comment by ZeroAbility** [comment] 2021-05-31 21:10
Work done thus far leading up to the current implementation:

Something in the WiX toolset version 3 binaries broke the Upgrade feature in our old WiX projects. We had an open issue for it and mentioned devs from WiX and they did not provide any feedback to us. This necessitated the need to test a new project using either CPack or WixSharp. WixSharp was decided on as we could more easily script it with CI.

The Upgrade GUID was changed in the old WiX projects to handle differences in architecture (x86, x64 etc). Since the client and server are individual installers now, we use the same GUID for both architectures per installer and different GUID's for client and server. Since we only package 32 and 64 bit libraries with the x64 version, it would make sense that those on a 64 bit OS should use x64 specifically. 

The larger reason why the 1.4.x packages cannot be used with our previous GUID is they would be tied to a possible installer that included both client and server components and they may be installed on a given PC. The manual process both accomplishes the new install/upgrade process that was tested and worked, and provides for the user to back up any needed config files prior to manually uninstalling 1.3.x versions and older that may also be running a server install.

**Comment by Krzmbrzl** [comment] 2021-06-01 05:46
From that I kinda read that it is impossible that the automatic upgrade from 1.3.x will work. If that is true then I think the issue can be closed :thinking:

**Comment by Kissaki** [comment] 2021-06-01 21:00
While it is true that we have an inherent split between client and server that was one installer before I don’t think there is nothing we can do, and that we can clean up better, create a normal upgrade path that does not leave behind stuff that may cause confusion and support effort down the line.

**Comment by ZeroAbility** [comment] 2021-06-01 22:05
My initial suggestion was to provide a disclaimer when downloading the snapshots and the version 1.4.x and newer that versions 1.3.x and older would need to be manually uninstalled. The client and server each install to their own program directory independent from the 1.3.x install to help reduce the support effort in the likelihood that this disclaimer would be overlooked or ignored. The ability to change paths during the install was also not modified so there wouldn't be an issue during the transition. I would argue that the size of Mumble (client or server) are not significant enough that the install path being set makes it a deal-breaker. It is based on Microsoft's best practices and other packages for other OS follow a similar guidance.

I had considered the possibility of including a script in the installer to determine the ProductID(?) of Mumble <= 1.3.x and calling `msiexec` to remove it. It seemed like that would be more error prone than manually uninstalling first. There didn't appear to be a straightforward way to unpack the script into a temp folder and then clean it up after. Depending on the antimalware software, it may also trigger a threat false positive.

The idea I heard in a previous "discussion" was to pin an Issue in Github along with the disclaimer on the download page so most bases are covered. I would welcome some new ideas about it as I have exhausted my knowledge on this and went through the WiX documentation, the WixSharp project sources, and several searches and forum posts.

**Comment by Krzmbrzl** [comment] 2021-06-02 06:14
If the cleanup of such a script was the problem I think we could just extract it into the temp directory and then leave it there to be cleaned up by the OS eventually.

Could we perhaps bundle such a script and then add a page into our installer that explicitly states that 1.3.x or earlier has to be removed and then add a button in there that - when pressed - attempts to run that script?
That seems to given a potential false-positive alarm of an anti-malware system clear context (e.g. it's not the installer per se, it's the attempted removal of previous Mumble installation that the user explicitly triggered) and even if the script fails or is not executed we have a warning directly in the installer as well :thinking:

**Comment by ZeroAbility** [comment] 2021-06-02 23:41
>That seems to given a potential false-positive alarm of an anti-malware system clear context (e.g. it's not the installer per se, it's the attempted removal of previous Mumble installation that the user explicitly triggered)...

There are some antimalware solutions that trigger a threat or actively block scripts that are triggered from processes. I have seen that behavior on Windows Defender and Comodo specifically. I think Microsoft gets around that by executing as TrustedInstaller. 

On top of it being over-engineered when compared to manually uninstalling, it seems like the manual uninstall is less error prone and less maintenance. If we add a script like that it will be in the installer project seemingly forever. That is the only way to guarantee the old version will be uninstalled if there are any holdouts.

**Comment by Krzmbrzl** [comment] 2021-06-03 06:24
I see your point there. 

Can we create a warning page in the installer nonetheless? Just a text-only warning that 1.3.x or earlier needs to be uninstalled manually before proceeding?

**Comment by ZeroAbility** [comment] 2021-06-07 22:28
I think a better way to handle that would be to add a disclaimer to the website until the next stable release after 1.4.x so we don't have to add more to the installer project than is necessary. This way, someone downloading 1.4.x can check their version beforehand and do that maintenance before opening the installer.

**Comment by ppfeufer** [comment] 2021-06-07 23:45
From my experience, no one reads that ...

**Comment by ZeroAbility** [comment] 2021-06-07 23:49
> From my experience, no one reads that ...

The same could be said of things that pop up when the installer runs, like the EULA. 

To be fair, it's not detrimental to accidentally install 1.4 without removing 1.3. The shortcuts will still point to the new version. If 1.3 is removed you just need to run the 1.4 `msi` again and choose "Repair" because the uninstall removes the menu entries and the shortcuts.

**Comment by Krzmbrzl** [comment] 2021-06-08 05:22
I also think that a disclaimer on the webpage will not really catch people's attention whereas a note in the installer might at least catch a few more folks.

I have no idea how complex it would be to add such a warning to the installer though. If it is easy then I think we should do it and remove it again for installers after the 1.4.x series. If it is complicated it's probably not worth it.

**Comment by ZeroAbility** [comment] 2021-06-11 21:59
I reflected on this a bit more. There is a possibility of opening a dialog box when the `msi` is executed and I have tested that with the installer project previously. However, I don't think that the dialog box will open or even prevent an install from occurring in a silent install context. It would have to open in some OK/Cancel scenario without opening the welcome screen of the installer. From what I can tell, it's not flexible enough to make the installer continue based on this condition. It would also defeat the purpose of a silent installer. I will see if I can find more information about that, but I wouldn't hold up a release over it.

**Comment by Krzmbrzl** [comment] 2021-06-12 08:16
Silent installer? Is that basically an automated installation?
If so, I think not stopping the installation in this scenario is fine as I assume most users will install it in the "regular way".

**Comment by ProjectPatatoe** [comment] 2021-08-15 01:12
After a quick skim, I don't think anyone has mentioned that it actually leaves the old 1.3.4 exe as the first available mumble if you were to go there, and not 1.4.0. If you were to leave both installed, Someone might still run the old one. Also, copied/custom shortcuts of course will not get updated. Although not really detrimental, it can be pretty confusing to someone unaware that both are installed.

**Comment by Krzmbrzl** [comment] 2021-08-15 12:15
Yeah that's why we say users will have to uninstall any prior version before installing 1.4.0.

And it's not that we _want_ this behavior. It just does not seem to work in any other way 🤷

**Comment by ProjectPatatoe** [comment] 2021-08-15 18:17
Why can't we just call `C:\WINDOWS\system32\msiexec.exe /qb /x "{F01AE994-B03B-46EC-87BD-65682C2968F4}"`? This is what windows does. It's a non-interactive uninstall even though it still graphically shows.

**Comment by ZeroAbility** [comment] 2021-08-15 18:57
We discussed it in a meeting and decided that sealing that into the installer project for all time wasn't productive. Going forward from 1.4.x, it should work as intended.

**Comment by JuniorJPDJ** [comment] 2021-08-15 20:46
Warning in installer itself is IMO must-have.
People often hold installers, give them to other using direct links or directly sending the files etc.
Not everyone is accessing the page to download installer.

**Comment by ZeroAbility** [comment] 2021-08-15 21:08
> Warning in installer itself is IMO must-have.
> People often hold installers, give them to other using direct links or directly sending the files etc.
> Not everyone is accessing the page to download installer.

This is why we have support resources for the community. We can't cover every single edge case like that where someone didn't properly assist someone else. If the 1.3.x or older version is not removed before install, it can be removed after so long as you run the 1.4.x and newer install again and choose "Repair." 

> I would prefer to kill myself than telling all my friends they need to remove old version before installation of new one when I'm telling them to update. It would be loads of work to make sure they did it and making sure they did it as they should.

I don't think this response is at all appropriate.

**Comment by Kissaki** [comment] 2021-08-19 20:49
@JuniorJPDJ Please invest some time in implementing an adequate solution then.

We do not currently have the resources to do so, evidently. We prioritize a release to move forward more than indefinitely postponing a release that we would never reach. If you can resolve the issue by then that’d be great. Thanks.

**Comment by Krzmbrzl** [comment] 2021-11-28 16:49
As we have no clue as to where the problem may be and we are preparing for the 1.4.0 stable release, we will consider this issue to be unfixable.
Note however that this should only apply to the transition to 1.4. All versions after that are expected to upgrade just fine.

**Closed by Krzmbrzl** 2021-11-28 16:49 UTC
Labels: installer

**Comment by tonyvg2013** [comment] 2024-03-03 20:03
sys.pointoperations.ABDABE
