### ISSUE TITLE
Connecting to a server freezes if Pulseaudio sink cannot be found

### ISSUE THREAD

**Issue by letharion** [mumble-voip/mumble#1672] opened 2015-05-18 08:22 UTC
Steps to reproduce:
1. Connect a USB headset.
2. Start mumble, use it enough to get some audio output.
3. Tell pulseaudio to use the headset as sink for mumble.
4. Close mumble.
5. Disconnect headset, and replace it with a different headset.
6. Start mumble.
7. Try to connect to a server.
8. Mumble freezes.

Opening Mumble.conf and removing the referenes to the old headset under [pulseaudio], and restarting mumble, resolves the problem.

I'm using Mumble 1.2.8, pulseaudio 5.0 and a up to date gentoo install.

**Comment by mkrautz** [comment] 2015-05-20 08:33
Thanks.

Fix seems obvious: detect if the chosen device is actually there, still.

Any takers? :-)

**Comment by bontibon** [comment] 2015-05-20 17:08
Duplicate #1143?

**Comment by mkrautz** [comment] 2015-05-20 17:37
I think so, yes.

**Comment by Krzmbrzl** [comment] 2020-01-15 19:10
@davidebeatrici I'll add this to the 1.4 milestone as this really seems rather trivial to fix and I guess this kind of stuff can get pretty annoying.

**Comment by Popkornium18** [comment] 2020-07-01 21:19
I can't reproduce this. Whenever I remove my USB headset and start Mumble again, the Output device is reset to "Default Output". If I remove my headset, the speakers will be used. If I disable the speakers too, PulseAudio creates a "Dummy Output" and Mumble uses that.

I have not tried to connect another headset, because I don't have one but that shouldn't be the reason why I can't reproduce this.

Maybe PulseAudio couldn't migrate clients to other sinks if the one that is in use goes missing?

**Comment by Krzmbrzl** [comment] 2020-07-02 05:46
@Popkornium18 thanks for testing. In that case I'd say we can assume the best and close this issue until someone experiences the problem again :D

**Closed by Krzmbrzl** 2020-07-02 05:46 UTC
Labels: bug, client, linux
