### ISSUE TITLE
reinsert usb sound card doesn't start input

### ISSUE THREAD

**Issue by patmu** [mumble-voip/mumble#4749] opened 2021-02-11 20:35 UTC
**Describe the bug**
If I remove the USB sound card and insert it again, only the PulseAudio output is started (I can hear other users). But the PulseAudio input is not. So my mic is not working anymore. It happens with different usb sound cards.

**Steps to Reproduce**
1. Remove USB sound card
2. Insert USB sound card
3. You can hear other users
4. You can't talk anymore to users

**Expected behavior**
I expect that also the mic is working after reinsert the USB sound card.

**Log application start**
<W>2021-02-11 21:12:44.465 Style: "Lite"
<W>2021-02-11 21:12:44.465 --> qss: ":themes/Mumble/Lite.qss"
<W>2021-02-11 21:12:44.468 Locale is "en_US" (System: "en_US")
<W>2021-02-11 21:12:44.567 Database SQLite: "3.22.0"
<W>2021-02-11 21:12:44.587 Updating application palette
<W>2021-02-11 21:12:44.636 GlobalShortcutX: Using XI2 2.3
<W>2021-02-11 21:12:45.623 SocketRPC: Listen failed
<W>2021-02-11 21:12:45.641 AudioInput: Opus encoder set for VOIP
<W>2021-02-11 21:12:45.641 AudioInput: 19000 bits/s, 48000 hz, 480 sample
<W>2021-02-11 21:12:45.642 PulseAudio: Starting input alsa_input.usb-GeneralPlus_USB_Audio_Device-00.analog-mono
<W>2021-02-11 21:12:45.649 PulseAudio: Starting output: alsa_output.usb-GeneralPlus_USB_Audio_Device-00.analog-stereo
<W>2021-02-11 21:12:45.657 AudioOutput: Initialized 1 channel 48000 hz mixer
<W>2021-02-11 21:12:45.665 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo

**log remove...**
<W>2021-02-11 21:12:47.776 OSInfo: Failed to execute lsb_release
<W>2021-02-11 21:13:01.330 PulseAudio: Stream error: Entity killed
<W>2021-02-11 21:13:01.330 PulseAudio: Sinks or inputs changed (inserted or removed sound card)
<W>2021-02-11 21:13:01.332 PulseAudio: Stopping output
<W>2021-02-11 21:13:01.344 PulseAudio: Starting output: alsa_output.platform-bcm2835_audio.analog-stereo

**...and insert USB soundcard**
<W>2021-02-11 21:13:12.711 PulseAudio: Sinks or inputs changed (inserted or removed sound card)
<W>2021-02-11 21:13:12.713 PulseAudio: Stopping output
<W>2021-02-11 21:13:12.718 PulseAudio: Starting output: alsa_output.usb-GeneralPlus_USB_Audio_Device-00.analog-stereo
no more log entries
-->> The microphone is listed as an Input Device in PulseAudio Volume Control .

**Desktop (please complete the following information):**
 - OS: Rasperry Pi OS (latest)
 - Version: Mumble 1.3.4
 - Audio Input and Output via System=PulseAudio and Device=Default Device

**Comment by Krzmbrzl** [comment] 2021-02-12 07:25
Seems like the issue is somewhere in 
https://github.com/mumble-voip/mumble/blob/4821df353d1dba8f3cb1e10e2c6fc838e34839f0/src/mumble/PulseAudio.cpp#L270-L308

But @davidebeatrici probably has a better idea on what might be going on :point_up:

**Comment by davidebeatrici** [comment] 2021-02-12 07:32
The Raspberry Pi does not have built-in audio input, which leads me to think that `PulseAudioInput` does not recover.

**Comment by Krzmbrzl** [comment] 2021-02-12 07:35
Okay so then the question would be: Are other applications still able to grab input from the mic after this has happened?
If it is available, you could try that out with e.g. Audacity.

**Comment by patmu** [comment] 2021-02-12 11:51
I did a test with Audacity on Pi.

Audacity behaves a little differently than Mumble. After application start there are no PulseAudio connections established. The connections are done when the Play or Record button is pressed and closed when the Stop button is pressed. That's what I see in PulseAudio Volume control. 

If I remove the USB sound card during a record session, the recording stops.

When I plug the usb sound card back in, nothing happens in audacity. only when I press record again, the pulse audio connection is re-established and the recording works again.

**Comment by patmu** [comment] 2021-02-12 12:42
> The Raspberry Pi does not have built-in audio input, which leads me to think that `PulseAudioInput` does not recover.

Another test with a second usb sound card as fallback. So the Pi as a now a built-in mic.

**unplug primary usb sound card and switch to fallback device...**
<W>2021-02-12 13:30:09.147 PulseAudio: Sinks or inputs changed (inserted or removed sound card)
<W>2021-02-12 13:30:09.161 PulseAudio: Stopping output
<W>2021-02-12 13:30:09.161 PulseAudio: Stopping input
<W>2021-02-12 13:30:09.165 PulseAudio: Starting output: alsa_output.usb-Samson_Technologies_Samson_G Track_Pro_53FE38171F183B00-00.analog-stereo
<W>2021-02-12 13:30:09.165 PulseAudio: Starting input alsa_input.usb-Samson_Technologies_Samson_G-Track_Pro_53FE38171F183B00-00.analog-stereo

-> "Stopping input" is here but missing in the log in the bug description

**...and reinsert the primary usb sound card**
<W>2021-02-12 13:31:19.291 PulseAudio: Sinks or inputs changed (inserted or removed sound card)
<W>2021-02-12 13:31:19.370 PulseAudio: Stopping output
<W>2021-02-12 13:31:19.370 PulseAudio: Stopping input
<W>2021-02-12 13:31:19.372 PulseAudio: Starting output: alsa_output.usb-GeneralPlus_USB_Audio_Device-00.analog-stereo
<W>2021-02-12 13:31:19.373 PulseAudio: Starting input alsa_input.usb-GeneralPlus_USB_Audio_Device-00.analog-mono

-> The input is also started.

Looks like @davidebeatrici is right.

**Comment by davidebeatrici** [comment] 2021-02-12 18:37
Thank you very much for confirming my hypothesis!

Right now we have an action for shortcuts called `Reset Audio Processor`, but it only resets SpeexDSP.

I propose to add a new one that restarts the entire audio system.

**Comment by patmu** [comment] 2021-02-15 09:35
Your proposal looks to me more like a workaround.

But for a final solution, I guess the whole PulseAudio code has to be refactored. I don't understand all of the code. But it looks like if there is no "raw_ai" device, the whole start/stop code is never executed again.

**Comment by davidebeatrici** [comment] 2021-02-15 19:09
Correct.

**Comment by Hartmnt** [comment] 2024-04-10 08:36
@davidebeatrici This should be fixed with #6371 right?

**Closed** 2024-04-10 18:00 UTC
Labels: client, audio, bug
