### ISSUE TITLE
Server disconnects random client on telnet to murmurd port

### ISSUE THREAD

**Issue by house-of-vanity** [mumble-voip/mumble#6120] opened 2023-05-01 02:01 UTC
### Description

If someone do `telnet myserver.com 64738` I got warnings in log and random client may be disconnected. 

### Steps to reproduce

1. Start server
2. `telnet myserver.com 64738`
3. just press Enter a few times.
4. Clients may be disconnected.

### Mumble version

1.3.0

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Relevant log output

```shell
May 01 04:52:24 msk murmurd[146331]: <W>2023-05-01 04:52:24.928 1 => <98:(-1)> New connection: 109.105.249.191:55050
May 01 04:52:25 msk murmurd[146331]: <W>2023-05-01 04:52:25.844 1 => <98:(-1)> Connection closed: Error during SSL handshake: error:1408F10B:SSL routines:ssl3_get_record:wrong version number [13]
May 01 04:52:26 msk murmurd[146331]: <W>2023-05-01 04:52:26.026 1 => <94:LINUX_USER(17)> Connection closed: Error while reading: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init [20]


May 01 04:52:34 msk murmurd[146331]: <W>2023-05-01 04:52:34.236 1 => <99:(-1)> New connection: 109.105.249.191:53668
May 01 04:52:34 msk murmurd[146331]: <W>2023-05-01 04:52:34.344 1 => <99:(-1)> Client version 1.5.255 (Linux: 1.5.517)
May 01 04:52:34 msk murmurd[146331]: <W>2023-05-01 04:52:34.350 1 => <99:LINUX_USER(17)> Authenticated
```

**Comment by davidebeatrici** [comment] 2023-05-01 02:14
Probably a duplicate of #3679.

**Comment by Krzmbrzl** [comment] 2023-05-01 05:51
Could you try to upgrade your server to at least 1.4 and check whether the issue persists? If it is indeed the same issues as the one Davide linked, then that should fix it.

**Comment by house-of-vanity** [comment] 2023-05-01 15:46
Finally upgrading to 1.4.287 resolve the problem. Thanks.

**Closed** 2023-05-01 16:19 UTC
Labels: needs-more-input, bug, triage
