### ISSUE TITLE
Mumble url does not work

### ISSUE THREAD

**Issue by Natenom** [mumble-voip/mumble#4684] opened 2021-01-13 06:27 UTC
When starting Mumble with: mumble "mumble://user@server.tld" it does not connect to the server and says "This version of Mumble can't handle URLs for Mumble version 1.2.0"

"mumble://user@server.tld?version=1.4.0" also doesn't work.

Works in a new instance if another Mumble instance is already running.

**Comment by Krzmbrzl** [comment] 2021-01-13 09:20
The relevant code part:
https://github.com/mumble-voip/mumble/blob/ffb2b70b32558c4db0619ea22a7c6865fba58dc2/src/mumble/MainWindow.cpp#L938-L959

I think that this can only happen if the client thinks that it is a version < 1.2.0. I suspect that this could be due to the broken `getVersion` call that uses the new build number as a forth part in the versioning and thus it fails and pretends that we're at version `0.0.0` which would of course make the client think that the URL is referring to a newer version of Mumble.

**Comment by Kissaki** [comment] 2021-01-15 14:59
Is this a regression in 1.4/master [only]?

**Comment by Krzmbrzl** [comment] 2021-02-21 19:18
@Natenom could you verify that the issue is fixed with #4778, please?
I can't reproduce any of the described issues with the changes of that PR.

**Closed** 2021-02-23 16:52 UTC
Labels: bug, client, good first issue
