### ISSUE TITLE
Channel main menu items do not operate on selected channel

### ISSUE THREAD

**Issue by bontibon** [mumble-voip/mumble#3090] opened 2017-05-11 10:15 UTC
All of the channel main menu items operate on the last channel that was right-clicked on, not the currently selected channel.

To reproduce:
1. Join a channel's root server
2. Right click on some other channel in the server
3. Close the popup menu without doing anything
4. Click once on the root channel so it is selected
5. Click Channel -> Edit...

You expect to edit the ACL of the root channel, since it is currently selected, but actually you are editing the channel that you right clicked on in step 2.

**Comment by bontibon** [comment] 2017-05-11 10:31
Just noticed that the User menu is the same.

If this behaviour is to be fixed, the "Use the selected item as the chat bar target" setting may have to be considered.

**Comment by mkrautz** [comment] 2017-05-12 07:57
Ouch, this is pretty bad.

**Comment by Calves95** [comment] 2017-11-28 17:14
Hello, I'm having trouble reproducing this bug, has it been fixed in the recent 1.3.0 snapshot?

When I edit channel on step 5 (my root channel), it opens the edit channel window for my root channel. not the previously right clicked channel in step 2.

Also for the selected item as chat bar target. When I right-click or left-click channels while I'm doing steps 1-5, the chat box for "type message to channel" states the correct channel.

Thanks!

**Comment by reelsense** [comment] 2017-11-28 18:53
I can't reproduce on `1.2.19`. Sounds like @Calves95 is right.

**Comment by bontibon** [comment] 2017-11-28 21:28
Reproduced on 312543974048d832e5d430aa9b49cd32984188e8 by:

1. Connect to a server
2. Note the channel you initially joined, but do not right click any channels
3. Switch to another channel by double clicking a channel in the tree
4. Click **Channel** -> **Edit**
5. The Edit window is for the channel you initially joined

**Comment by Hartmnt** [comment] 2022-08-07 20:51
This bug was introduced in this commit 4f5089fe30 in 2010. It is because of an oversight in the ``aboutToShow`` code paths:
```
if (Global::get().uiSession != 0) {
	QModelIndex idx;
	if (!qpContextPosition.isNull())
		idx = qtvUsers->indexAt(qpContextPosition);

	if (!idx.isValid())
		idx = qtvUsers->currentIndex();

	p = pmModel->getUser(idx);

	if (cuContextUser)
		p = cuContextUser.data();
}
```
This code is supposed to check whether this ``qpContextPosition`` is valid and, if not, fall back to the currently selected user in the tree view (same code is copied in aboutToShow functions for channel and possibly listener).

Furthermore, it is **supposed** to fall back to ``cuContextUser``, if and only if the query ``getUser`` fails to retrieve a user. (e.g. when the selected user disconnected... at least that is what the commit message reads)

However, the last ``if`` in the above code does not check whether or not the query was successful, but rather only whether or not the ``cuContextUser`` is set. Which means that this code will ALWAYS prefer the ``cuContextUser`` over everything else. And this variable is updated outside of this scope only when a context menu is created (right-click).

So the fix is to change the last ``if`` to:
```
	if(p == nullptr && cuContextUser)
		p = cuContextUser.data();
```
Additionally, the code regarding context menus could possibly be refactored to reduce copy&paste areas...

**Closed** 2022-08-10 16:33 UTC
Labels: client, help wanted, bug, priority/P1 - Critical
