### ISSUE TITLE
Mumble server reports it loaded settings from non-existing INI file 

### ISSUE THREAD

**Issue by Krzmbrzl** [mumble-voip/mumble#6077] opened 2023-03-07 11:40 UTC
### Description

See https://user-images.githubusercontent.com/69093516/223404904-550e3685-adb5-45e7-b39b-740e5fd2667a.png

Essentially, the server always claims that it loaded settings from an INI file, even if it didn't and is therefore using the defaults.

### Steps to reproduce

Start a server that won't find an existing INI file

### Mumble version

many

### Mumble component

Server

### OS

Linux

### Reproducible?

Yes

### Additional information

See https://github.com/mumble-voip/mumble/issues/5848#issuecomment-1457977455

**Comment by Postman67** [comment] 2023-03-24 03:18
Having the same issue. Cant find the ini file. Where even is it getting it from?

**Comment by davidebeatrici** [comment] 2023-03-24 03:27
From nowhere: it simply relies on the default settings.

You can find the file at https://github.com/mumble-voip/mumble/blob/master/auxiliary_files/mumble-server.ini.

**Comment by WOLFI3654** [comment] 2023-10-05 12:11
Hey, If this issue is still relevant, I'd like trying to fix it during this hacktoberfest!
Could I get assigned to the issue? Looking forward to it!

**Comment by Hartmnt** [comment] 2023-10-05 15:51
> Hey, If this issue is still relevant, I'd like trying to fix it during this hacktoberfest! Could I get assigned to the issue? Looking forward to it!

Sure thing! Check the last 3 or so messages of #5848 for additional context.

**Comment by WOLFI3654** [comment] 2023-10-07 19:13
I was able to reproduce the issue on my end. The issue arises from QSettings not caring if the read / synced file actually exists. Therefore, the read settings do not contain any keys. I think there are two options that could be feasible in this situation. 
1. Just checking if the file exists and if not just print that we are initializing with default options
2. Checking if there were actually any keys synced into the settings. This way, an empty file would result in the same behavior as no file – the log would print something like "No or empty file found". So you could comment out all settings in your current file and it would correctly say that you loaded the defaults.

Please let me know what you think would fit the best in this situation.

------------

I also noticed that this line https://github.com/mumble-voip/mumble/blob/5cef9f6f62ecf445a0478902906a08255610aaaa/src/murmur/Meta.cpp#L202C37-L202C37
does in fact not make much sense from the things happening during debugging. If no datapaths exist at all this will just create the folder the exe is currently in. Is this the intended behavior? It looks odd to me since after creation the target paths are altered to the default (0) datapath which is not created and the application lives in a folder that does not exist. Please let me know if this is in fact odd.

**Comment by Krzmbrzl** [comment] 2023-10-08 05:44
I think option 1 is probably the most straight forward. Plus, it is taken for granted that all options not specified in the INI are set to their defaults and thus an empty file seems just an extreme case of that.

**Comment by Krzmbrzl** [comment] 2023-10-08 05:46
About creating that directory, I would have think on this some more. Maybe there was a case in which this was indeed needed... Did you check whether girl blame reveals anything useful?

**Comment by WOLFI3654** [comment] 2023-10-08 11:08
> About creating that directory, I would have think on this some more. Maybe there was a case in which this was indeed needed... Did you check whether girl blame reveals anything useful?

Sadly haven't found anything useful yet, the line was introduced in 0779a0f9 with no specification why this was needed.
_qdBasePath_ has not been initialized until this line is reached, which means it results in https://doc.qt.io/qt-5/qdir.html#currentPath which makes it even more odd because `QDir::setCurrent` is only called _after_ the load from ini happened and there are no other places where this path is set.

**Comment by Krzmbrzl** [comment] 2023-10-11 06:26
Alright. Thanks for taking a look.

> the line was introduced in https://github.com/mumble-voip/mumble/commit/0779a0f986d8ea1a1875fd0472400a0a599817e3 with no specification why this was needed.

Yeah, unfortunately commit messages were not equipped with reasoning or explaining back then.

I had a closer look at the code myself now and indeed: in all code paths in which `qsAbsSettingsFilePath` ends up empty, `qdBasePath` will be empty as well. Therefore, I think we can indeed remove
https://github.com/mumble-voip/mumble/blob/f989f22d28732d9743fe82e36ec999027d53c29a/src/murmur/Meta.cpp#L202
from the code as it doesn't do anything (I expect this function call to return `false` indicating that creating the given (empty!) path has failed).
Could you add a separate `MAINT(server)` commit to #6231 that removes this line?

**Closed** 2023-10-12 07:06 UTC
Labels: server, bug, good first issue
