### ISSUE TITLE
mumble:// straight up not registering

### ISSUE THREAD

**Issue by Hedwig7s** [mumble-voip/mumble#5680] opened 2022-05-14 13:47 UTC
### Description

Trying to open a mumble:// link just results in Windows asking what app to open it with (only option MS store)

### Steps to reproduce

1. Got a mumble link
2. Opened it with Ctrl+R (got nothing using a browser)

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment] 2022-05-14 19:38
Duplicate of #5567

**Closed by Krzmbrzl** 2022-05-14 19:38 UTC
Labels: bug, triage
