### ISSUE TITLE
Possible Mumble has Livestream screenshare  as new feature like Discord?

### ISSUE THREAD

**Issue by rock2rap** [mumble-voip/mumble#6347] opened 2024-02-26 07:24 UTC
### Description

I hope Mumble dev. can do.

### Mumble component

Client

### OS-specific?

Yes

**Comment by Krzmbrzl** [comment] 2024-02-26 08:41
For practical purposes, this is a duplicate of https://github.com/mumble-voip/mumble/issues/4150

**Closed by Krzmbrzl** 2024-02-26 08:41 UTC
Labels: feature-request, triage
