### ISSUE TITLE
Direct user notification

### ISSUE THREAD

**Issue by nilsh** [mumble-voip/mumble#1425] opened 2014-10-06 07:56 UTC
It would be really helpful to have a function that allows notifying/call a user. In my use case, there is a channel where people hang around while doing concentrated work alone. So they put their headset off, but want to stay available for occasional talking. Not really AFK, but also not 100% present. I believe this could be a common scenario.

A whipser function that can be dynamically set (maybe via context menu) could do the trick, or a kind of nudge function that raises a popup message and/or sound on the other user's end.

Current whisper function via preconfigured hotkeys is not suitable, also text messages do not help as they are easily overlooked.

**Comment by Foolson** [comment] 2015-01-21 16:29
If I understand this right then this feature would work like the poke funktion in TeamSpeak?
Then I would request it too!
That is the only feature I miss in Mumble.

**Comment by Kissaki** [comment] 2017-04-06 22:10
How would a separate "poking" notification differ from the standard text message notification, which can be configured with playing a sound as well?

**Comment by nilsh** [comment] 2017-04-07 09:01
I think most people wouldn't want a sound for every text message in a conversation, and as this setting is the default, experience tells that only very few will ever change it anyway.
For the notification, something more persistent would be nice, so you can notify a user that you want to talk to them even if they're afk short or not paying attention at the moment, but will see the request when they're back. Like a persistent popup window. Optionally with sound, sure.

**Comment by Krzmbrzl** [comment] 2020-01-19 12:28
I'll close this as a duplicate of #2997

**Closed by Krzmbrzl** 2020-01-19 12:28 UTC
Labels: feature-request
