### ISSUE TITLE
Allow user to select install directory or drive

### ISSUE THREAD

**Issue by crius-al** [mumble-voip/mumble#5901] opened 2022-09-27 22:57 UTC
### Context

Installing mumble

### Description

When I installed mumble, it forced itself onto my C: system drive which is an ssd exclusively for the operating system. Applications need to go on my D: drive.
Older mumble installs allowed alternative install locations. The newest mumble does not.

### Mumble component

Client

### OS-specific?

Yes

**Comment by davidebeatrici** [comment] 2022-09-27 23:29
Duplicate of #4702.

**Closed by davidebeatrici** 2022-09-27 23:29 UTC
Labels: feature-request, triage
