### ISSUE TITLE
Parameter to start Mumble with a different configuration file

### ISSUE THREAD

**Issue by R4PS** [mumble-voip/mumble#4010] opened 2020-03-25 15:47 UTC
Hi,

currently i started streaming, and to capture the voice chat, i start a second mumble instace which is connected to a single soundcard which i can "Import" to OBS. - Works great so far:) 

but unfortunately i need to readjust the Sound Output / Certificate / Username every time i start streaming.

My request: 
a simple parameter like -ini would also be very usable for the mumble client in this case

yes i could create a chroot / lxc / docker container, but i think this is a little bit overkill

**Comment by Krzmbrzl** [comment] 2020-03-25 16:08
I think this is a duplicate of #3953, isn't it?

As such I'll close it for now. If you disagree, feel free to comment and I'll check again :)

**Closed by Krzmbrzl** 2020-03-25 16:08 UTC
