### ISSUE TITLE
Audio quality of other applications drop if mumble is active and used with jabra evolve 65 / wlan headset

### ISSUE THREAD

**Issue by felixprick** [mumble-voip/mumble#5134] opened 2021-06-17 07:57 UTC
**Describe the bug**
somehow it seems like every audio signal goes through mumble if a headset with usb tongle is used. (example jabra evolve65) this causes an massive drop in audio quality. 

**Steps to Reproduce**
1. open mumble
2. use jabra evolve 65s or similar
3. go to browser and start a youtube song
4. close and open mumble to hear the quality  difference 

**Expected behavior**
the quality should not drop 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: mumble 1.3.4

**Comment by Krzmbrzl** [comment] 2021-06-17 08:49
This sounds remarkably like the same issue that was reported for Bluetooth headsets already in #3491.

Did you try to reproduce this with other voice communication software on that machine? E.g. Discord, TeamSpeak, Zoom, Webex, ...

**Comment by JuniorJPDJ** [comment] 2021-06-25 17:29
It's not mumble's problem.
That's how BT works.
Headset working in A2DP mode have high quality output and most of times no input.
To provide input (mic) it needs to change mode to HFP or HSP where quality of audio is much worse than on A2DP.

**Comment by felixprick** [comment] 2021-06-28 06:40
@JuniorJPDJ thanks! You´re probably right. But other programs (tried with gotomeeting) handle to deliver the sound in high quality when the mic is muted. So this should be possible for mumble too i think.

**Comment by Krzmbrzl** [comment] 2021-06-28 07:40
> handle to deliver the sound in high quality when the mic is muted. So this should be possible for mumble too i think.

While in principle I assume this was possible, I would consider it not worth the effort. The core issue lies within the Bluetooth protocol and thus they should be the ones fixing that.
Mumble's main purpose is to be used as a communication software and as such sitting around with muted mic while listening to music should not be the norm (at least from my perspective).

The problem with this is that I assume (but didn't verify) that handling this requires platform-specific code that needs to be developed, tested and maintained. And that (in my eyes) is not worth it :thinking:

@davidebeatrici @ZeroAbility @Kissaki what are your thoughts on this?

**Comment by Kissaki** [comment] 2021-06-28 21:00
I’m not familiar with the problem specifics, but if the driver is the one switching modes and stuff, that’s what should to so according to use and to the desire of the user.

If we are pointed to how to solve this on Mumble side and it’s simple enough we may consider it. Like, for QoS networking we label packets as VoIP, so networking can handle them adequately.

But I assume that is not standardized; not designed, available or simple (standardized) for such bluetooth drivers, if at all possible. I wouldn't be surprised if we had no influence over this, as it is driver level adjustments from what I understood here?

And if that's the case, there is nothing we can do. It's a workaround on the driver level for the technological limitations the hardware device has. We use it as a device without any knowledge or control over that.

This is my understanding and assumptions on this.

**Comment by Krzmbrzl** [comment] 2021-06-30 06:30
In any case this is a duplicate of #3491. I just re-read parts of the discussion there and it seems that Qt does provide some sort of API for interacting with Bluetooth. Maybe that also features what we'd need to switch codecs when the mic is muted...

**Closed by Krzmbrzl** 2021-06-30 06:30 UTC
Labels: needs-more-input

**Comment by JuniorJPDJ** [comment] 2021-07-06 15:23
Mumble should probably just disconnect from microphone when it's muted and it would be all it needs.

**Comment by Kissaki** [comment] 2021-07-16 15:42
Related to this and possible improvements with Windows 11, quoting a Discord message from Esablaka (unrelated to this ticket or Mumble):

> I just noticed a GREAT thing. Windows 11 fixed the terrible Bluetooth audio. 
It apparently now properly supports the AAC (Advanced Audio Coding) Codec. 
That support initially appeared in a windows 10 insider build earlier this year but never made it to stable. It IS in Windows 11. 
> 
> Bluetooth headphones now show up as one device (no more weird "stereo" and one "mic" device appearing in the device settings) and automatically switch between the "mic mode" and the "music/listening mode". In the past if one wanted to use a mic on a bluetooth headset on windows 10 it caused the audio to be absolutely atrocious due to it using the mic device channel (and not automatically switching back but just permanently being there.) , if one wanted proper audio one couldn't use the bluetooth headphone mic at all. 
> 
> Now Windows 11 supports proper AAC and also automatically switches between the "music" channel and the "mic" channel  thus one has great audio and it only switches to the mic channel when one is actually actively talking and it automatically switches back. 
> 
> I haven't seen any change notes mentioning this but I remembered the AAC support in the W10 insider build so I just tested it on W11. Works like a charm, sounds noticeably better (at least in direct comparison to my ears).

> Also I didn't look for any online sources etc. confirming my suspicions. I just tried it with a couple of different pairs of headphones on 2 different devices (one running W10 and one running W11 Insider build on the Developer Channel. ) and the behaviour fits with the AAC support that was in insider W10 earlier this year.
