### ISSUE TITLE
Messages with multiple lines send on one line instead

### ISSUE THREAD

**Issue by benhwebster** [mumble-voip/mumble#5445] opened 2022-01-17 16:17 UTC
### Description

When sending a message with multiple lines, everything sends on one line. This was not the case on 1.3.x, and I can't see any mention of this behavior in the release notes of 1.4.x

### Steps to reproduce

Attempt to send a message with multiple lines
ex:
```
a
b
c
```
see that it instead sends as
```
abc
```

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Additional information

Server version is 1.2.18-1+deb9u2, users sending messages from older client versions can still send multi line messages, so I doubt this is related to the server.

let me know if you need any other information.

### Screenshots

![image](https://user-images.githubusercontent.com/14381460/149805995-e7610c92-5717-4b2d-b690-36178a87b8a4.png)

**Comment by Krzmbrzl** [comment] 2022-01-17 16:48
I assume you are referring to typing directly in the chat box as opposed to using the rich text editor, right? If so, could you check whether actually leaving a blank line between your paragraphs gets you the desired result? Aka
```
a

b

c
```

What I think is happening here is that your message is interpreted as Markdown (new feature in 1.4) and in Markdown you have to use two consecutive newlines in order to produce a new paragraph. If that's how it works, then everything is working as intended :)

**Comment by benhwebster** [comment] 2022-01-17 17:22
Ah, I suppose that's the case then: 
![image](https://user-images.githubusercontent.com/14381460/149810663-ef6222db-98d9-4cfa-8530-05d734e1435b.png)
I find it interesting that other users messages don't display in a similar fashion for me, and vice versa with them on earlier versions.

**Comment by Krzmbrzl** [comment] 2022-01-17 18:09
The markdown parsing only happens locally and only upon sending the message. Essentially your Markdown plaintext message is converted to the corresponding HTML once you hit send. What's sent out is then only the HTML. And if you are receiving text messages, they are rendered as-is, without any markdown parsing :)

I'll close this as _working as intended_ :point_up:

**Closed by Krzmbrzl** 2022-01-17 18:09 UTC
Labels: bug, triage
