### ISSUE TITLE
chat message entry field is hidden by default

### ISSUE THREAD

**Issue by rkoe** [mumble-voip/mumble#4093] opened 2020-04-22 11:03 UTC
**Describe the bug**
The field for entering chat messages is hidden by default, so it's not possible to type any text messages by default.
The only way to type messages, is to move the mouse to the bottom left until a up-down-arrow-mousepointer appears and then drag upwards to make the chat-entry-field appear. If you don't know that (and don't accidentally stumble over it), you're not able to use the text chat.

**Steps to Reproduce**
1. start Mumble
2. No chat-entry-field there.

**Screenshots**
![mumble-missing-chatentry](https://user-images.githubusercontent.com/2507744/79974409-97ceda00-8499-11ea-8b5c-ad144b17d74b.png)

**Desktop (please complete the following information):**
 - OS: Linux (NixOS)
 - Version: Mumble 1.3.0

**Comment by Krzmbrzl** [comment] 2020-04-22 11:13
Duplicate of #3701

**Closed by Krzmbrzl** 2020-04-22 11:13 UTC
