### ISSUE TITLE
Server group icons

### ISSUE THREAD

**Issue by preterive** [mumble-voip/mumble#3261] opened 2017-11-10 16:37 UTC
Hello,
i wish Server group icons because a normal user don't know the rank of another user.

**Comment by bendem** [comment] 2017-11-10 17:31
Duplicate of https://github.com/mumble-voip/mumble/issues/1632

**Comment by davidebeatrici** [comment] 2017-11-10 17:38
Hello, @preterive!

As pointed out by @bendem, there's already an open issue requesting the same feature.
Please write in #1632 if you want to give input on how the feature should be.

**Closed by davidebeatrici** 2017-11-10 17:38 UTC
Labels: mumble, ui
