### ISSUE TITLE
Window display picture

### ISSUE THREAD

**Issue by HHBP** [mumble-voip/mumble#6062] opened 2023-02-16 00:43 UTC
### Context

Hope to add new functions
View picture Double click to display in the window

### Description

View picture Double click to display in the window

### Mumble component

Client

### OS-specific?

Yes

**Comment by Hartmnt** [comment] 2023-02-16 08:49
Probably a duplicate of #3282 or #4830

**Comment by Krzmbrzl** [comment] 2023-02-16 11:12
Yeah, I also consider this a duplicate of #3282

**Closed by Krzmbrzl** 2023-02-16 11:12 UTC
Labels: feature-request, triage
