### ISSUE TITLE
Adjust sound notification volume 

### ISSUE THREAD

**Issue by Mati20187** [mumble-voip/mumble#3963] opened 2020-02-08 12:37 UTC
**Context** 
Currently, I don't see an option that would allow users to change the volume of their sound notifications. They're very useful but I can't really use them because the volume is too high and hurts my ears.

**Describe the feature you have in mind**
It would be nice to have a volume slider for Sound Notifications in Settings, Messages just like Text to Speech has.

**Comment by Krzmbrzl** [comment] 2020-02-08 12:46
I almost closed this as a duplicate of #3954 but I think we'll keep this one instead as it is more general.

I agree though that this would be a good feature.

**Comment by Hartmnt** [comment] 2022-06-21 09:33
I want this feature and I am willing to implement it myself. In fact, I have already implemented a naive version of this functionality [here](https://github.com/Hartmnt/mumble/tree/feat_notification_volume).

However, the naive implementation lacks the ability to change the volume of "Audio on/off/mute cues" independent of regular notification sounds. I would like to also implement that, but it will be more complex. Furthermore, I need some feedback regarding the implementation and will therefore open a draft pull request for this feature now.

**Comment by Krzmbrzl** [comment] 2022-06-21 10:28
That sounds great. I'm looking forward to your PR :+1:

**Closed** 2022-08-01 13:51 UTC
Labels: client, feature-request, help wanted

**Comment by Hartmnt** [comment] 2022-08-01 14:02
Automation moved this into "Discarded", but rest assured this feature is actually implemented as of 03c9fc7a1157decf631fb605526113227a409abd

**Comment by Krzmbrzl** [comment] 2022-08-01 14:03
Meh - that automation kinda sucks :eyes:
