### ISSUE TITLE
Can't set shortcut

### ISSUE THREAD

**Issue by omnigenous** [mumble-voip/mumble#6627] opened 2024-11-11 19:23 UTC
### Description

```
wayland 1.23.1-1
wayland-protocols 1.38-1
xorg-xwayland 24.1.4-1
linux 6.11.6.artix1-1
hyprland 0.44.1-4
```
Can't assign any key to shortcut, pretty much https://github.com/mumble-voip/mumble/issues/4460 https://github.com/mumble-voip/mumble/issues/4133

I tried to copy "shortcuts" section from config I use in windows but that just added `'Unknown'` shortcut

### Steps to reproduce

1. Open Settings > Shortcut
2. Choose any function
3. Try to assign keybind
4. mumble doesn't accept any key besides space, enter, esc, tab, etc (they can't be assign obviously)

### Mumble version

1.5.634-6

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Screenshots

![image](https://github.com/user-attachments/assets/d08fed3b-1472-45ed-bcc5-bf386f5629b6)

**Comment by Hartmnt** [comment] 2024-11-12 08:53
Duplicate of #5257
Please look at that issue for possible workarounds

**Closed by Hartmnt** 2024-11-12 08:53 UTC
Labels: bug, triage

**Comment by omnigenous** [comment] 2024-11-12 09:03
I was able to set shortcut keys in KDE but still can't use them in hyprland even after adding bind pass: https://wiki.hyprland.org/Configuring/Binds/#global-keybinds

https://github.com/hyprwm/Hyprland/discussions/8432
