### ISSUE TITLE
Recognize Right/Left Modifiers independently (for PTT)

### ISSUE THREAD

**Issue by Vorror** [mumble-voip/mumble#4889] opened 2021-03-28 01:03 UTC
Currently, mumble only recognizes left and right modifiers(ctrl, cmd, option, etc, shift) as a single key.

Could we add an option to mumble accurately discriminate between right/left versions of a key? I prefer to use the _right_-option key for talking but I don't want it to activate when I press _left_-option.

Since I don't want to break the current PTT/shortcuts for anyone who relies on the current behavior — how about we add an checkbox option to settings to enable right/left discrimination?

**Comment by davidebeatrici** [comment] 2021-03-28 01:11
Operating system?

**Comment by Vorror** [comment] 2021-03-28 01:16
OSX

**Comment by Krzmbrzl** [comment] 2021-03-28 07:47
Duplicate of #4529

**Closed by Krzmbrzl** 2021-03-28 07:47 UTC
Labels: GlobalShortcuts, macOS
