### ISSUE TITLE
Questions regarding plugin compilation and install dir

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#4477] opened 2020-09-09 21:11 UTC
Mumble (latest Git version) compiled / installed on Linux with CMake includes all plugins,
while version 1.3.0 (using QMake) includes only three (l4d, link and rl). [1] [2]

What is the reason for this? And is this behavior intended?
I see no sense in compiling plugins for Windows games on Linux.

The linked package lists also indicate that both distributions install these files to `/usr/lib/mumble/`.
But `make install` with CMake omits the `mumble` directory. Is there any way to configure this?
Otherwise this can lead to file conflicts (e. g. `/usr/lib/libcelt0.so`) if CELT is installed globally.

My current workaround for the Arch Linux AUR package is to specify `PLUGIN_PATH` in the CXXFLAGS and move the files manually. See also the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mumble-git) file (line 60 and 83).
Is there a cleaner way like passing the path as a CMake parameter which then affects the `make install` target?

Thanks for the support.

[1] https://www.archlinux.org/packages/community/x86_64/mumble/files/
[2] https://packages.debian.org/buster/amd64/mumble/filelist

**Comment by radioactiveman** [comment] 2020-09-09 21:30
Regarding the install dir I have tried using `-DCMAKE_INSTALL_LIBDIR='lib/mumble'` but it had no effect unfortunately.

**Comment by davidebeatrici** [comment] 2020-09-09 22:20
> What is the reason for this? And is this behavior intended?
I see no sense in compiling plugins for Windows games on Linux.

Plugins support games running through Wine since 1.4.0.

> The linked package lists also indicate that both distributions install these files to `/usr/lib/mumble/`.

Indeed. However, they should probably be installed to `/usr/lib/mumble/plugins/` instead.

> Is there a cleaner way like passing the path as a CMake parameter which then affects the `make install` target?

We should probably add some options to allow granular control over the install paths.

**Comment by Krzmbrzl** [comment] 2020-09-11 15:20
@radioactiveman could you check whether this issue is fixed by #4481 please?

**Closed** 2020-09-11 18:09 UTC
Labels: build

**Comment by radioactiveman** [comment] 2020-09-11 19:42
@Krzmbrzl: Not completely yet, but we are getting there. :+1:

The installation to `/usr/lib/mumble` works as expected now.
To tell Mumble where to find the libraries I use `CXXFLAGS+=" -DPLUGIN_PATH=/usr/lib/mumble"`.
But since the plugins are now in a separate plugins directory, they are not found anymore.

This code here probably needs to be adjusted.
https://github.com/mumble-voip/mumble/blob/af7dac72f4063dd8d4dac71973ea51c25896089a/src/mumble/Plugins.cpp#L240

**Comment by Krzmbrzl** [comment] 2020-09-14 09:54
@radioactiveman could you check whether it is working when applying the changes from #4485 and then setting the plugin path to the actual plugin directory (in your case I think this'd be `CXXFLAGS+=" -DPLUGIN_PATH=/usr/lib/mumble/plugins"`)?

I am also thinking about de-coupling the Opus and CELT codecs from the `PLUGIN_PATH` macro entirely as imo these are not plugins and should therefore not be affected by this setting.
If anything I'd introduce a new preprocessor macro `CODEC_PATH` or something similar that will allow custom locations for the codecs. I'm not really sure if this is needed at all though :thinking: 
Thoughts?

**Comment by radioactiveman** [comment] 2020-09-14 10:56
The plugins are now found obviously, but the CELT / Opus library is not.

1. attempt: /usr/bin/libcelt.so.0.7.0
2. attempt: /usr/bin/lib/libcelt.so.0.7.0 (after adding the missing slash)
3. attempt: /usr/lib/mumble/plugins/libcelt.so.0.7.0
4. attempt: mumble/libcelt.so.0.7.0
5. attempt: libcelt.so.0.7.0

But the file is installed at `/usr/lib/mumble/libcelt0.so.0.7.0`.
See also my review comments in the pull request.

**Comment by Krzmbrzl** [comment] 2020-09-14 11:51
Then it seems that the issue is that it doesn't check for the proper name for the CELT library 🤔

**Comment by radioactiveman** [comment] 2020-09-14 12:04
No, this is not true. Multiple file names are checked:
`libcelt0.so.0.7.0`, `libcelt.so.0.7.0`, `celt.so.0.7.0`, `libcelt0.so.0.0.0`, `libcelt.so.0.0.0` and `celt.so.0.0.0`

The issue is that the directory where they are installed is not searched at all.
Which line of code would you expect to find the file in `/usr/lib/mumble/`?

**Comment by Krzmbrzl** [comment] 2020-09-14 13:16
See https://github.com/mumble-voip/mumble/pull/4485#issuecomment-692042830
