### ISSUE TITLE
Attenuate not working with Amazon Music Desktop App

### ISSUE THREAD

**Issue by daviderickson** [mumble-voip/mumble#2077] opened 2016-01-20 04:23 UTC
As the subject says, attenuate works fine with all other audio producing apps on my computer, but for some reason does not correctly attenuate Amazon Music at all.  You can download this program here: http://www.amazon.com/gp/feature.html/?ie=UTF8&docId=1001067901

**Comment by mkrautz** [comment] 2016-01-20 17:49
I can reproduce (but I can't really get into the app -- but I made it play music by using the Play multimedia key on my keyboard!).

An interesting observation: the volume *is* in fact changed if you look in the volume mixer. I wonder why it has no effect?

**Comment by mkrautz** [comment] 2016-01-20 17:50
Marking as up-for-grabs because I am not actively looking at it at the moment, if someone else wants to take a peek!

**Comment by daviderickson** [comment] 2016-01-21 15:40
@mkrautz I saw the exact same behavior with the mixer, and even more weird is if you drag the Amazon Music slider up and down by hand on the mixer, that works fine.  Maybe there is some event or something not being sent by Mumble?

**Comment by Krzmbrzl** [comment] 2020-03-02 17:04
Does this happen with Mumble 1.3 as well?

This really sounds like some sort of bug in the Amazon Music app... Do you have other applications that can successfully attenuate the Amazon music app?

**Closed** 2020-04-01 17:19 UTC
Labels: help wanted, mumble, needs-more-input, windows
