### ISSUE TITLE
[1.4.230] [Minor] "Non-plugin found in plugin directory" warnings upon launch

### ISSUE THREAD

**Issue by mikebdp2** [mumble-voip/mumble#5494] opened 2022-01-21 15:42 UTC
### Description

Upon each Mumble client launch, I'm getting a set of warnings visible above the "Welcome to Mumble" message:
```
Non-plugin found in plugin directory: "/usr/lib/mumble/libcelt0.so"
Non-plugin found in plugin directory: "/usr/lib/mumble/libcelt0.so.0.7.0"
Non-plugin found in plugin directory: "/usr/lib/mumble/libmumbleoverlay.so"
Non-plugin found in plugin directory: "/usr/lib/mumble/libmumbleoverlay.so.1"
Non-plugin found in plugin directory: "/usr/lib/mumble/libmumbleoverlay.so.1.4"
Non-plugin found in plugin directory: "/usr/lib/mumble/libmumbleoverlay.so.1.4.0"
```
This doesn't seem to affect the program operation

### Steps to reproduce

launch Mumble and look at its' chat window

### Mumble version & environment

1.4.230 Client at Alpine Linux - based PostmarketOS on Pinephone

**Comment by Krzmbrzl** [comment] 2022-01-21 17:27
How did you obtain this version of Mumble? Did you self-compile?
I remember having had a similar issue at some point which I fixed, but maybe I forgot to backport that particular commit :eyes:

**Comment by Krzmbrzl** [comment] 2022-01-21 17:29
I think the PR I remembered was https://github.com/mumble-voip/mumble/pull/5339 but that one has been backported: https://github.com/mumble-voip/mumble/pull/5340

**Comment by mikebdp2** [comment] 2022-01-22 08:53
@Krzmbrzl 
> How did you obtain this version of Mumble?

a Mumble package got updated at Alpine Linux repository and I installed it. [Here are the build scripts](https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/community/mumble) - together with three patches: `libgen`, `no-rnnoise` and `poll` _(I don't know their origin)_

**Comment by Krzmbrzl** [comment] 2022-01-22 13:36
Hm, given the reported paths this might be related to some installation dir mess-up (or rather thst the general library location seems to wrongly be included in the plugin path. I'll have to check that 👀

**Comment by Krzmbrzl** [comment] 2022-09-07 17:07
This is a packaging issue caused by this line: https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/mumble/APKBUILD#L67
It should not be pointed to `/usr/lib/mumble` but instead to `/usr/lib/mumble/plugins`. As it stands, the plugin path is the same as the library path, which is why e.g. the CELT library will appear in the "plugin directory" producing the observed warning.

I will create a PR against the GitLab repo, but in any case, this is not an issue of mainline Mumble itself -> Closing this

**Closed by Krzmbrzl** 2022-09-07 17:07 UTC
Labels: client, bug

**Comment by Krzmbrzl** [comment] 2022-09-07 17:15
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/38740
