### ISSUE TITLE
Deafen self with Push to Talk

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#5804] opened 2022-08-15 22:50 UTC
### Context

I'm unable to resolve a sound feedback issue due to our room's shape, speaker + mic placement, etc.

### Description

Can we add a option, near the Attenuate options, to deafen self on Push-to-Talk (or something more broadly applicable?)

Attenuate 100% does not reduce others' sound to zero.

### Mumble component

Client

### OS-specific?

No

**Comment by Hartmnt** [comment] 2022-08-16 07:51
This is a duplicate of #5320

**Comment by Krzmbrzl** [comment] 2022-08-16 07:53
Indeed - I was just about to write the same ^^

**Closed by Krzmbrzl** 2022-08-16 07:53 UTC
Labels: feature-request, triage
