### ISSUE TITLE
captures sound from the game overpowering my voice 1.3.4-1~ppa~focal

### ISSUE THREAD

**Issue by orkanaye** [mumble-voip/mumble#5221] opened 2021-08-04 10:40 UTC
**Describe the bug**
since 1.3 starting mumble produces crackling and echo on connect for a while. after few clicks the crackling disappears but mumble captures the game music/audio/sounds and volume is higher than my voice so others can't understand me.
tried different inputs but it does not seem to make any difference.
Edit: should add I use a headset with a mic, not speakers

**Steps to Reproduce**
1. start mumble - when game is running, hear crackling for a while
2. push to talk also transmits game sound

**Expected behavior**
Expect just my voice to transmit via push to talk no game audio

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Version: mumble 1.3.4-1~ppa~focal
 - server back end runs 1.3

**Additional context**
this seems to be a new thing that started happening in 1.3 as 1.2.x worked as expected.

**Comment by Krzmbrzl** [comment] 2021-08-04 13:27
Did you use 1.2.x on the same hardware as you are currently using?
Do you have echo and/or noise cancellation enabled?

**Comment by orkanaye** [comment] 2021-08-05 22:25
Yes. same hardware. Only thing that changed was upgrade from 18.04 lts -> 20.04 lts (that's when mumble version also got bumped) weirdly though this behaviour started recently and I struggle to figure out what was the reason as it seems even after upgrade to 20.04 was ok? Could be something with later package updates.

the echo cancellation is on, noise suppression is at -40 dB
As I mentioned I use headphones so there should not be any game output sound audible to the mic

**Comment by Krzmbrzl** [comment] 2021-08-06 05:44
What happens if you deactivate echo cancellation? This feature is kinda broken in 1.3.x anyway xD

If you are still getting the audio to spill over then you might be seeing the same issue that I am getting as well. I always thought that due to lousy hardware the cables for input and output would be too close together inducing current in one another, therefore causing the output to "spill over" into the input. 
However if the issue did not exist in 1.2.x then this clearly can't be the (main) issue :thinking:

**Comment by Kissaki** [comment] 2021-08-06 09:21
Do you use a headset with cable? On bad insulation played audio can bleed into the mic input through induction.

If you put the audio volume on 0%, the issue disappears?

Given that the crackling disappears, are you using the RNNoise noise suppression?

**Comment by orkanaye** [comment] 2021-08-06 12:06
so nothing changed with echo cancellation on or off. hardware didn't change since upgrade to 1.3. cabling didn't change either...
headset is with a cable, with separate mic and output jack, plugged at the back.

Weirdly enough after trying few things via alsamixer and pulseaudio volume control yesterday I accidentally muted the mic in pulseaudio late at night so couldn't record anything. after increasing boost the issue disappeared for now (tested with recording via mumble just now). I have a feeling it will be back. I will update in few days

It's possible something got messed up in recent audio driver updates in the OS. although the crackling issue comes and goes only in 1.3 (no rnnnoise). crackling affects the output audio too. with weird echo too if I click mute, deafen, unmute undeafen

**Comment by Krzmbrzl** [comment] 2021-08-06 14:27
@orkanaye I think another way to make sure the issue lies within Mumble would be to e.g. install Audacity and then use that to record your microphone to see if that too picks up the audio output. If it does, the issue lies outside of Mumble but if it does not, the issue is most likely somewhere within Mumble.

**Comment by Green-Sky** [comment] 2021-08-11 17:06
I installed PipeWire (ppa) today and compiled a fresh mumble build (unrelated) today, and i now have a similar issue? But it does not seem to be caused by mumble! I did a audacity recording of it.

[pw_mumble_klicky_audacity.zip](https://github.com/mumble-voip/mumble/files/6970160/pw_mumble_klicky_audacity.zip)
![image](https://user-images.githubusercontent.com/2938071/129072484-4acc6a0a-7ef5-4b60-ab61-f6355c399ccb.png)

**Comment by orkanaye** [comment] 2021-08-11 21:52
yeah. it something weird. I suspect it;s something in pulseaudio as when I record via built in recorder I can hear the issue. For now I force it via alsa with the loopback mixing disabled (as seems pulseaudio ignores that setting...)

The weird crackling noise seems to be mumble related. It starts when I start mumble and audio is playing

**Comment by Krzmbrzl** [comment] 2021-08-12 13:45
In that case I think we can conclude that this issue does not seem to be Mumble's fault.
As such I'll close this issue.

As for the crackling: I also get it immediately after Mumble starts but iirc I also get it for other applications (not all though and I can't remember which).
If this continues to be a problem, please create a separate issue for it :)

**Closed by Krzmbrzl** 2021-08-12 13:45 UTC
