### ISSUE TITLE
Unable to create ban

### ISSUE THREAD

**Issue by wfjsw** [mumble-voip/mumble#3986] opened 2020-03-04 10:09 UTC
**Describe the bug**
App does nothing when press `Add` button on ban list.

**Steps to Reproduce**
1. Go to 'Ban list'
2. Fill a IP address and its mask
3. Click 'Add'
4. Nothing happens

**Expected behavior**
A new ban item appear on the ban list.

**Screenshots**
![image](https://user-images.githubusercontent.com/2220320/75868640-4ca62c80-5e43-11ea-98c0-41dcbca1aa75.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.3

**Comment by Krzmbrzl** [comment] 2020-03-04 10:29
I can replicate this on Linux

**Comment by wfjsw** [comment] 2020-06-12 00:14
Looks like it is fixed in 1.3.1. Can anyone confirm?

**Comment by Krzmbrzl** [comment] 2020-06-12 06:59
It seems to work, yes. The question would be: why? I can't seem to find a change related to this xD

But I guess as long as it's fixed, it doesn't really matter :shrug: 

Thanks for reporting back on this :)

**Comment by wfjsw** [comment] 2022-01-07 11:56
Well this breaks again in 1.4.0-rc1. What happened?

**Comment by Krzmbrzl** [comment] 2022-01-07 15:52
> What happened?

No idea - I guess the "magical fix" lost its magic xD

**Comment by Krzmbrzl** [comment] 2022-01-07 17:04
Okay so I think I know what the problem is from a technical point of view:
When adding a ban, without changing the default value for the mask, the mask will be set to `128` (see your screenshot). Now we run
https://github.com/mumble-voip/mumble/blob/5598fe82c7369c816ddac3cf51e1c5332351f71a/src/mumble/BanEditor.cpp#L101-L103
which will add `96` to the mask, if we have not entered an IPv6 address. At the bottom, we check whether the created ban is valid
https://github.com/mumble-voip/mumble/blob/5598fe82c7369c816ddac3cf51e1c5332351f71a/src/mumble/BanEditor.cpp#L115
which equates to
https://github.com/mumble-voip/mumble/blob/5598fe82c7369c816ddac3cf51e1c5332351f71a/src/Ban.cpp#L28
and since our mask is now `128 + 96 = 224`, this check fails. And since Mumble doesn't add bans to the list that it considers to be invalid, nothing happens when clicking the ban button.

Thus, bans should be addable once you are using IPv6 addresses or if you use a mask in the range between 8 and 32.

----

Now the open questions are
1. Why did this appear to have worked before? The related code is ancient and hasn't been touched in any meaningful way in quite a while
2. Where on earth is that `96` value coming from? Maybe someone with deeper insights into the whole IP-address + masks topic can enlighten me?

**Comment by Krzmbrzl** [comment] 2022-01-07 17:30
Okay so it seems like the maximum valud subnet mask for IPv4 addresses is 32 whereas for IPv6 it's 128 :thinking:

**Comment by Krzmbrzl** [comment] 2022-01-07 18:10
So in the end, I think this is not really a bug but rather a strange user experience in case an invalid mask is entered.

**Comment by Krzmbrzl** [comment] 2022-01-07 18:19
This is going to be fixed by https://github.com/mumble-voip/mumble/pull/5406

**Closed** 2022-01-07 19:04 UTC
Labels: client, ui, bug
