### ISSUE TITLE
'Channel user count' is displayed incorrectly at RTL language

### ISSUE THREAD

**Issue by MiskyWhixer** [mumble-voip/mumble#2713] opened 2016-12-20 18:11 UTC
![mumble_screenshot_arabic](https://cloud.githubusercontent.com/assets/8101397/21361852/21e602b0-c6e6-11e6-9097-6e8ea609a664.png)

As you can see in the screenshot the normally displayed channel user count
' **...channel name... (3)** '
is displayed as
' **3) ...channel name... )** '
at RTL language (in this case arabic).

**Comment by mkrautz** [comment] 2016-12-20 18:42
Here's where the string is created:

https://github.com/mumble-voip/mumble/blob/master/src/mumble/UserModel.cpp#L423

Not sure why that'd be wrong for RTL languages...

**Comment by Kissaki** [comment] 2017-01-20 09:40
You seem to be using a German language, so it is not a client setting.

So I guess you are using unicode glyphs to make that specific channel name RTL? (Not sure how writing RTL text within LTL text works.)

**Comment by MiskyWhixer** [comment] 2017-01-20 13:48
The channel name in the screenshot was given by a user.
Now I have created a permanent channel also with arabic channel name.
Same problem.
The name is a copy / paste from Google translator. In this case:

أهلا و سهلاً

Translated it means 'Welcome'.

**Comment by MiskyWhixer** [comment] 2017-01-20 14:05
Huh...
I have changed the Client language to arabic and the problem is vice versa (see screenshot).

![arabic_mumble](https://cloud.githubusercontent.com/assets/8101397/22152164/c87a07ae-df21-11e6-8f4e-4629cbd6ad63.png)

**Comment by Hartmnt** [comment] 2024-07-17 09:25
I tried to reproduce this with the latest Mumble version (on Linux), but the issue seems to be gone.
So this is either a Windows only problem, or it was fixed by a later version of Qt

![mumble1](https://github.com/user-attachments/assets/1c283b82-51a1-4ad9-aed4-4c37bbec73a2)
(client is set to LTR)

**Comment by Krzmbrzl** [comment] 2024-07-17 10:02
In that case, let's close this until we get a report of this still being an issue.

**Closed by Krzmbrzl** 2024-07-17 10:02 UTC
Labels: client, ui, needs-more-input, bug, needs-ckeck-with-latest-version
