### ISSUE TITLE
Mumble client crash on OSX[Reproducible]

### ISSUE THREAD

**Issue by Vorror** [mumble-voip/mumble#3253] opened 2017-10-21 03:18 UTC
OSX Version: 10.12.1 (16B2657)
Mumble Version: Mumble-1.3.0-2569-gd196a4b-snapshot

Issue:
Mumble client hard crashes when you attempt to open preferences when connected to an external monitor via hdmi. Can be reproduced 100% of the time. Preferences work when I unplug the monitor. 

Crashing when opening preferences aside, audio seems to work fine. ~~But because of the issue I can't change my audio output devices~~(see update).

OSX crash file attached:
[Mumble_2017-10-20-231454.crash.zip](https://github.com/mumble-voip/mumble/files/1403726/Mumble_2017-10-20-231454.crash.zip)

I sent a memory dump using the window mumble displays after a crash. I used the fake email "16B2657-vorror@gmail.com", I'm assuming you can do a search for crashdumps from that email. This ticket is also mentioned in the crash description.

Update: 
After some more testing, the Audio Wizard page actually works(so I can now change audio output). My initial assumption was maybe mumble had an issue getting the audio device name. Other than listing the audio devices, I'm not sure what part of preferences could be affected by a specific audio device.

**Comment by ancarda** [comment] 2020-11-14 19:14
I'm unable to reproduce this (Mumble 1.3.3 on macOS 10.15.7). I'm not directly attached to HDMI, but going through [the USB-C/Thunderbolt adapter](https://www.apple.com/shop/product/MUF82AM/A/usb-c-digital-av-multiport-adapter). I tried with both mirroring and extending the desktop. In both circumstances, I can open and close Preferences.

@Vorror, @razum2um: Is this still an issue for you? I can try to look into a fix for you if it is, but I will need a way to reproduce the problem on my end.

**Comment by Krzmbrzl** [comment] 2020-11-15 15:03
@ancarda thank you very much for looking into this! :)

**Comment by razum2um** [comment] 2020-11-17 02:20
@Krzmbrzl hm, after 2yrs I hardly remember details :)

Right now retried my own reproduction steps with mumble 1.3.3
- and (mbp15@mojave with another hdmi monitor)
- and (mbp13@bigsur with hdmi-via-usbc)

Both are ok ¯\_(ツ)_/¯

**Comment by Krzmbrzl** [comment] 2020-11-17 07:30
Thanks for the update :+1:

In that case I suggest us being optimistic in assuming that the issue has been resolved at some point.

Thus I'll close this issue as resolved and if someone encounters this bug again, then we can have a new report or reopen this one.

**Closed by Krzmbrzl** 2020-11-17 07:30 UTC
Labels: client, macOS, needs-more-input
