### ISSUE TITLE
opusthreshold set to 0 still fallbacks to CELT

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#992] opened 2013-06-03 02:49 UTC
Setting "opusthreshold = 0" will not force server to run only Opus, but still falls back to CELT if any older clients connects to the server.

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/992/ ._

**Comment by Krzmbrzl** [comment] 2020-01-15 17:58
@davidebeatrici do you know, if this has been changed/fixed?

**Comment by davidebeatrici** [comment] 2020-01-15 19:19
Unfortunately not, we should check whether it can be reproduced in 1.3.

**Comment by streaps** [comment] 2020-04-21 14:02
I checked with Mumla and the "Disable Opus Codec" checked. With "opusthreshold=0" in murmur.ini it crashes immediately after connecting to the server.  With "opusthreshold=100" it works fine and CELT is used.

I'm not sure if this is the best test, but it seems like it is working as intended (besides the bug in Mumla).

**Comment by Krzmbrzl** [comment] 2020-04-21 14:21
@streaps thanks for testing. Let's assume the best and close this issue for now :)

**Closed by Krzmbrzl** 2020-04-21 14:21 UTC
Labels: needs-ckeck-with-latest-version, server
