### ISSUE TITLE
[Linux] Links notification showing as HTML in the notifications

### ISSUE THREAD

**Issue by lmao-emerald** [mumble-voip/mumble#2211] opened 2016-04-22 13:30 UTC
Instead getting "A link" I get `<a href="http://a-link.com">A link</a>` when someone sends me a link.

This doesn't happen in Windows 7, didn't test in more distros

I'm using Elementary OS Freya, specs: http://i.imgur.com/IjIPqT4.png

Mumble Version: http://i.imgur.com/C6SZI7B.png

Bug screens:
 Notification: http://i.imgur.com/JNnIN0p.png
 Link on the channel: http://i.imgur.com/qBG96bR.png

If I need to provide more info just tell me what I'm missing and I will gladly add it.

**Comment by mkrautz** [comment] 2016-04-23 18:05
Technically, per the desktop notification spec, this is a violation:

https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html states that:
> The following tags should be supported by the notification server. Though it is optional, it is recommended. Notification servers that do not support these tags should filter them out.
>   \<b> ... \</b>	Bold
>    \<i> ... \</i>	Italic
>    \<u> ... \</u>	Underline
>    \<a href="..."> ... </a>	Hyperlink
>    \<img src="..." alt="..."/>	Image

...So, the expected behavior would be to filter the tags away.

I'm preparing a patch to just use plain text instead, since many notification daemons do not seem to be spec compliant in practice.

**Comment by mkrautz** [comment] 2016-04-23 18:07
Also, dupe of https://github.com/mumble-voip/mumble/issues/1535.

**Comment by mkrautz** [comment] 2016-04-23 18:10
Not a dupe. OP tried to send an HTTP-link.

**Comment by lmao-emerald** [comment] 2016-04-23 18:17
Hi, I don't know if this helps but, what's the point of having link in notifications if we can't click them? I will wait the patch, thanks for the support.

**Comment by mkrautz** [comment] 2016-04-23 18:20
There's not much we can do about it. I recommend you file a bug a against ElementaryOS. We send the messages with HTML in them. According to the spec [1], it should work (or degrade back to plain text automatically). But it doesn't.

ElementaryOS isn't alone in this. See for example https://github.com/mumble-voip/mumble/issues/1535.

[1] https://developer.gnome.org/notification-spec/

**Comment by mkrautz** [comment] 2016-04-23 18:25
Actually, reading your bug report, it seems like it isn't regular <a> tags that are affected.

In your screenshots, it seems like this *is* a dupe of #1535: because, in your screenshots, Mumble is sending \<a>-tags with non-HTTP/HTTPS URL schemes, like `clientid://`, etc.

Reading the spec, I would expect these to be stripped by the notification daemon. But that doesn't seem to happen.

**Comment by mkrautz** [comment] 2016-04-23 18:27
One interesting thing to test would be to send a text message with the following content:

    \<a href="http://www.google.com>A working link?</a>
    \<a href="mumble://example.com">A broken link?</a>

**Comment by lmao-emerald** [comment] 2016-04-23 18:31
Images with Html and a link here: http://imgur.com/a/FDHJF

They images are large since I'm lazy to cut them, sorry lol

**Comment by mkrautz** [comment] 2016-04-23 18:36
Thanks.

I think the HTML from our own log view is confusing the notification daemon...

We'll need to test it some more before taking action...

**Closed** 2016-04-28 11:11 UTC
