### ISSUE TITLE
Mumble says there are users in an empty private server.

### ISSUE THREAD

**Issue by ZingBlue** [mumble-voip/mumble#3854] opened 2019-10-17 04:49 UTC
I am running a Mumble server on Azure and sometimes Mumble randomly claims that there is 3 or 4 people on the server, when I go on to check, no one is. This also shows up in Plumble. No one knows the password besides me and a few friends.

**Comment by davidebeatrici** [comment] 2019-10-17 04:51
By "go on to check" you mean that you connect to the server, right?

What happens to the users counter when you do that?

**Comment by ZingBlue** [comment] 2019-10-17 04:54
It seems to fix itself afterwards(or after a few minutes), once I can repeat the issue, I'll let you know which one it is.

**Comment by azlux** [comment] 2019-10-18 09:30
If you can reproduce it, you can check with this script also : https://gist.github.com/azlux/315c924af4800ffbc2c91db3ab8a59bc
It ask with UDP ping the numbers of connected users in real time.

**Comment by Krzmbrzl** [comment] 2021-03-25 09:29
I think this is a duplicate of #4277 and as such this should be fixed in the current development snapshot of Mumble (available on our website).

**Closed by Krzmbrzl** 2021-03-25 09:29 UTC
Labels: server
