### ISSUE TITLE
Mumble crashes after starting

### ISSUE THREAD

**Issue by frontendschlampe** [mumble-voip/mumble#3609] opened 2019-02-25 10:15 UTC
After updating from ```1.3.0~2729~g2126495~snapshot``` to ```1.3.0~2942~g755c290~snapshot``` on MacOS 10.14.3 (18D109) Mumble crashes directly after starting. I can send a crash report, but nothing more.

**Comment by hemna** [comment] 2019-02-25 16:04
same for me.   Just installed 1.2.19 and it crashes instantly on start.  
Mac OSX 10.14.3

**Comment by davidebeatrici** [comment] 2019-02-25 18:13
Workaround: https://github.com/mumble-voip/mumble/issues/3471#issuecomment-410490926

**Comment by frontendschlampe** [comment] 2019-02-25 19:50
> Workaround: [#3471 (comment)](https://github.com/mumble-voip/mumble/issues/3471#issuecomment-410490926)

thx :-)

**Comment by davidebeatrici** [comment] 2019-02-25 20:20
You're welcome!

Closing this as duplicate of #3471.

**Closed by davidebeatrici** 2019-02-25 20:20 UTC
Labels: macOS, mumble
