### ISSUE TITLE
Linking failures due to undefined Protobuf references

### ISSUE THREAD

**Issue by radioactiveman** [mumble-voip/mumble#4577] opened 2020-11-11 17:31 UTC
**Describe the bug**
Linking fails on Linux due to undefined Protobuf references when compiling Mumble with Clang.

**Steps to Reproduce**
1. Clone latest master branch
2. Configure Clang as default compiler (export CC=clang && export CXX=clang++)
3. Build Mumble

**Expected behavior**
Linking should work also with Clang, not only GCC.

**Desktop**
 - OS: Arch Linux
 - Version: Mumble (Git), Master branch
 - Clang 11.0.0
 - Protobuf 3.12.4

**Additional context**
```
[100%] Linking CXX executable ../../mumble
/usr/bin/ld: ../libshared.a(Mumble.pb.cc.o): in function `MumbleProto::Authenticate::Authenticate(MumbleProto::Authenticate const&)':
Mumble.pb.cc:(.text+0x29c3): undefined reference to `google::protobuf::RepeatedField<int>::RepeatedField(google::protobuf::RepeatedField<int> const&)'
/usr/bin/ld: ../libshared.a(Mumble.pb.cc.o): in function `MumbleProto::ChannelState::ChannelState(MumbleProto::ChannelState const&)':
Mumble.pb.cc:(.text+0x703c): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x7050): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x7060): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: ../libshared.a(Mumble.pb.cc.o): in function `MumbleProto::UserState::UserState(MumbleProto::UserState const&)':
Mumble.pb.cc:(.text+0x9ac7): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x9ad7): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: ../libshared.a(Mumble.pb.cc.o):Mumble.pb.cc:(.text+0xecec): more undefined references to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)' follow
/usr/bin/ld: ../libshared.a(Mumble.pb.cc.o): in function `MumbleProto::UserStats::UserStats(MumbleProto::UserStats const&)':
Mumble.pb.cc:(.text+0x1d22a): undefined reference to `google::protobuf::RepeatedField<int>::RepeatedField(google::protobuf::RepeatedField<int> const&)'
/usr/bin/ld: ../libshared.a(Mumble.pb.cc.o): in function `MumbleProto::RequestBlob::RequestBlob(MumbleProto::RequestBlob const&)':
Mumble.pb.cc:(.text+0x1f6bd): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x1f6cd): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x1f6dd): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/mumble/CMakeFiles/mumble.dir/build.make:2520: mumble] Error 1
make[2]: Leaving directory '/tmp/makepkg/mumble-git/src/mumble/build'
make[1]: *** [CMakeFiles/Makefile2:1366: src/mumble/CMakeFiles/mumble.dir/all] Error 2
make[1]: Leaving directory '/tmp/makepkg/mumble-git/src/mumble/build'
make: *** [Makefile:149: all] Error 2
make: Leaving directory '/tmp/makepkg/mumble-git/src/mumble/build'
```

**Comment by Krzmbrzl** [comment] 2020-11-11 17:36
But everything works find with gcc?

Afaik we don't do any gcc/clang differentiation so the problem is probably being created by clang handling something in a different way than gcc or it having a bug :thinking:

**Comment by radioactiveman** [comment] 2020-11-11 18:22
Yes, linking works when Mumble is compiled with GCC.

I will check if it works here when downgrading Clang.
The recent update to 11.0.0 was the reason why I have tried it with Mumble. :wink:

**Comment by TredwellGit** [comment] 2020-11-12 09:24
Use cmake instead of qmake.
```
cd mumble
mkdir -p build
cd build
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
```

**Comment by Krzmbrzl** [comment] 2020-11-12 12:59
If he's using current master, there is basically no way he can use qmake. All necessary files have been removed ^^

**Comment by TredwellGit** [comment] 2020-11-12 15:51
Sorry, I meant ninja instead of make. If I recall correctly, that is what fixed this for me back when I used Arch Linux. Cannot reproduce on NixOS, however.

**Comment by radioactiveman** [comment] 2020-11-12 16:57
Still the same errors when using Ninja.

```
[369/369] Linking CXX executable mumble
FAILED: mumble 
: && /usr/bin/clang++ -D_FORTIFY_SOURCE=2 -march=native -O2 -pipe -fno-plt -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now    -Wl,-z,relro -Wl,-z,now src/mumble/CMakeFiles/mumble.dir/mumble_autogen/mocs_compilation.cpp.o src/mumble/CMakeFiles/mumble.dir/main.cpp.o src/mumble/CMakeFiles/mumble.dir/About.cpp.o src/mumble/CMakeFiles/mumble.dir/ACLEditor.cpp.o src/mumble/CMakeFiles/mumble.dir/AudioConfigDialog.cpp.o src/mumble/CMakeFiles/mumble.dir/Audio.cpp.o src/mumble/CMakeFiles/mumble.dir/AudioInput.cpp.o src/mumble/CMakeFiles/mumble.dir/AudioOutput.cpp.o src/mumble/CMakeFiles/mumble.dir/AudioOutputSample.cpp.o src/mumble/CMakeFiles/mumble.dir/AudioOutputSpeech.cpp.o src/mumble/CMakeFiles/mumble.dir/AudioOutputUser.cpp.o src/mumble/CMakeFiles/mumble.dir/AudioStats.cpp.o src/mumble/CMakeFiles/mumble.dir/AudioWizard.cpp.o src/mumble/CMakeFiles/mumble.dir/BanEditor.cpp.o src/mumble/CMakeFiles/mumble.dir/CELTCodec.cpp.o src/mumble/CMakeFiles/mumble.dir/Cert.cpp.o src/mumble/CMakeFiles/mumble.dir/ClientUser.cpp.o src/mumble/CMakeFiles/mumble.dir/ConfigDialog.cpp.o src/mumble/CMakeFiles/mumble.dir/ConfigWidget.cpp.o src/mumble/CMakeFiles/mumble.dir/ConnectDialog.cpp.o src/mumble/CMakeFiles/mumble.dir/CustomElements.cpp.o src/mumble/CMakeFiles/mumble.dir/Database.cpp.o src/mumble/CMakeFiles/mumble.dir/DeveloperConsole.cpp.o src/mumble/CMakeFiles/mumble.dir/Global.cpp.o src/mumble/CMakeFiles/mumble.dir/GlobalShortcut.cpp.o src/mumble/CMakeFiles/mumble.dir/LCD.cpp.o src/mumble/CMakeFiles/mumble.dir/ListenerLocalVolumeDialog.cpp.o src/mumble/CMakeFiles/mumble.dir/Log.cpp.o src/mumble/CMakeFiles/mumble.dir/LookConfig.cpp.o src/mumble/CMakeFiles/mumble.dir/MainWindow.cpp.o src/mumble/CMakeFiles/mumble.dir/Markdown.cpp.o src/mumble/CMakeFiles/mumble.dir/Messages.cpp.o src/mumble/CMakeFiles/mumble.dir/MumbleApplication.cpp.o src/mumble/CMakeFiles/mumble.dir/NetworkConfig.cpp.o src/mumble/CMakeFiles/mumble.dir/OpusCodec.cpp.o src/mumble/CMakeFiles/mumble.dir/Plugins.cpp.o src/mumble/CMakeFiles/mumble.dir/PTTButtonWidget.cpp.o src/mumble/CMakeFiles/mumble.dir/RichTextEditor.cpp.o src/mumble/CMakeFiles/mumble.dir/Screen.cpp.o src/mumble/CMakeFiles/mumble.dir/ServerHandler.cpp.o src/mumble/CMakeFiles/mumble.dir/Settings.cpp.o src/mumble/CMakeFiles/mumble.dir/SharedMemory.cpp.o src/mumble/CMakeFiles/mumble.dir/SocketRPC.cpp.o src/mumble/CMakeFiles/mumble.dir/SvgIcon.cpp.o src/mumble/CMakeFiles/mumble.dir/TalkingUI.cpp.o src/mumble/CMakeFiles/mumble.dir/TalkingUIContainer.cpp.o src/mumble/CMakeFiles/mumble.dir/TalkingUIEntry.cpp.o src/mumble/CMakeFiles/mumble.dir/TalkingUISelection.cpp.o src/mumble/CMakeFiles/mumble.dir/TextMessage.cpp.o src/mumble/CMakeFiles/mumble.dir/ThemeInfo.cpp.o src/mumble/CMakeFiles/mumble.dir/Themes.cpp.o src/mumble/CMakeFiles/mumble.dir/Tokens.cpp.o src/mumble/CMakeFiles/mumble.dir/Usage.cpp.o src/mumble/CMakeFiles/mumble.dir/UserEdit.cpp.o src/mumble/CMakeFiles/mumble.dir/UserInformation.cpp.o src/mumble/CMakeFiles/mumble.dir/UserListModel.cpp.o src/mumble/CMakeFiles/mumble.dir/UserLocalVolumeDialog.cpp.o src/mumble/CMakeFiles/mumble.dir/UserModel.cpp.o src/mumble/CMakeFiles/mumble.dir/UserView.cpp.o src/mumble/CMakeFiles/mumble.dir/VersionCheck.cpp.o src/mumble/CMakeFiles/mumble.dir/ViewCert.cpp.o src/mumble/CMakeFiles/mumble.dir/VoiceRecorder.cpp.o src/mumble/CMakeFiles/mumble.dir/VoiceRecorderDialog.cpp.o src/mumble/CMakeFiles/mumble.dir/WebFetch.cpp.o src/mumble/CMakeFiles/mumble.dir/XMLTools.cpp.o src/mumble/CMakeFiles/mumble.dir/widgets/MUComboBox.cpp.o src/mumble/CMakeFiles/mumble.dir/__/ACL.cpp.o src/mumble/CMakeFiles/mumble.dir/__/Channel.cpp.o src/mumble/CMakeFiles/mumble.dir/__/ChannelListener.cpp.o src/mumble/CMakeFiles/mumble.dir/__/Connection.cpp.o src/mumble/CMakeFiles/mumble.dir/__/Group.cpp.o src/mumble/CMakeFiles/mumble.dir/__/__/3rdparty/smallft/smallft.cpp.o src/mumble/CMakeFiles/mumble.dir/SharedMemory_unix.cpp.o src/mumble/CMakeFiles/mumble.dir/GlobalShortcut_unix.cpp.o src/mumble/CMakeFiles/mumble.dir/Log_unix.cpp.o src/mumble/CMakeFiles/mumble.dir/os_unix.cpp.o src/mumble/CMakeFiles/mumble.dir/TextToSpeech_unix.cpp.o src/mumble/CMakeFiles/mumble.dir/ManualPlugin.cpp.o src/mumble/CMakeFiles/mumble.dir/DBus.cpp.o src/mumble/CMakeFiles/mumble.dir/Overlay.cpp.o src/mumble/CMakeFiles/mumble.dir/OverlayClient.cpp.o src/mumble/CMakeFiles/mumble.dir/OverlayConfig.cpp.o src/mumble/CMakeFiles/mumble.dir/OverlayEditor.cpp.o src/mumble/CMakeFiles/mumble.dir/OverlayEditorScene.cpp.o src/mumble/CMakeFiles/mumble.dir/OverlayPositionableItem.cpp.o src/mumble/CMakeFiles/mumble.dir/OverlayText.cpp.o src/mumble/CMakeFiles/mumble.dir/OverlayUser.cpp.o src/mumble/CMakeFiles/mumble.dir/OverlayUserGroup.cpp.o src/mumble/CMakeFiles/mumble.dir/PathListWidget.cpp.o src/mumble/CMakeFiles/mumble.dir/Overlay_unix.cpp.o src/mumble/CMakeFiles/mumble.dir/Zeroconf.cpp.o src/mumble/CMakeFiles/mumble.dir/__/__/3rdparty/qqbonjour/BonjourServiceBrowser.cpp.o src/mumble/CMakeFiles/mumble.dir/__/__/3rdparty/qqbonjour/BonjourServiceResolver.cpp.o src/mumble/CMakeFiles/mumble.dir/ALSAAudio.cpp.o src/mumble/CMakeFiles/mumble.dir/JackAudio.cpp.o src/mumble/CMakeFiles/mumble.dir/PAAudio.cpp.o src/mumble/CMakeFiles/mumble.dir/PulseAudio.cpp.o src/mumble/CMakeFiles/mumble.dir/mumble_autogen/EWIEGA46WW/qrc_mumble.cpp.o src/mumble/CMakeFiles/mumble.dir/mumble_autogen/2IKLLRAJFH/qrc_mumble_flags_0.cpp.o src/mumble/CMakeFiles/mumble.dir/mumble_autogen/6RJHKKPRHE/qrc_MumbleTheme.cpp.o src/mumble/CMakeFiles/mumble.dir/mumble_autogen/EJRQKI7XPS/qrc_translations.cpp.o src/mumble/CMakeFiles/mumble.dir/mumble_autogen/6RJHKKPRHE/qrc_ClassicTheme.cpp.o -o mumble  /usr/lib/libsndfile.so  src/libshared.a  /usr/lib/libQt5Concurrent.so.5.15.1  /usr/lib/libQt5Sql.so.5.15.1  /usr/lib/libQt5Svg.so.5.15.1  /usr/lib/libQt5Widgets.so.5.15.1  /usr/lib/libXi.so  /usr/lib/librt.so  /usr/lib/libXext.so  /usr/lib/libspeex.so  /usr/lib/libspeexdsp.so  src/mumble/rnnoise/librnnoise.a  /usr/lib/libspeechd.so  /usr/lib/libglib-2.0.so  /usr/lib/libQt5DBus.so.5.15.1  /usr/lib/libdns_sd.so  /usr/lib/libasound.so  /usr/lib/libprotobuf.so  -lpthread  /usr/lib/libssl.so  /usr/lib/libcrypto.so  /usr/lib/libQt5Network.so.5.15.1  /usr/lib/libQt5Xml.so.5.15.1  /usr/lib/libQt5Gui.so.5.15.1  /usr/lib/libX11.so  /usr/lib/libQt5Core.so.5.15.1 && :
/usr/bin/ld: src/libshared.a(Mumble.pb.cc.o): in function `MumbleProto::Authenticate::Authenticate(MumbleProto::Authenticate const&)':
Mumble.pb.cc:(.text+0x29c3): undefined reference to `google::protobuf::RepeatedField<int>::RepeatedField(google::protobuf::RepeatedField<int> const&)'
/usr/bin/ld: src/libshared.a(Mumble.pb.cc.o): in function `MumbleProto::ChannelState::ChannelState(MumbleProto::ChannelState const&)':
Mumble.pb.cc:(.text+0x703c): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x7050): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x7060): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: src/libshared.a(Mumble.pb.cc.o): in function `MumbleProto::UserState::UserState(MumbleProto::UserState const&)':
Mumble.pb.cc:(.text+0x9ac7): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x9ad7): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: src/libshared.a(Mumble.pb.cc.o):Mumble.pb.cc:(.text+0xecec): more undefined references to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)' follow
/usr/bin/ld: src/libshared.a(Mumble.pb.cc.o): in function `MumbleProto::UserStats::UserStats(MumbleProto::UserStats const&)':
Mumble.pb.cc:(.text+0x1d22a): undefined reference to `google::protobuf::RepeatedField<int>::RepeatedField(google::protobuf::RepeatedField<int> const&)'
/usr/bin/ld: src/libshared.a(Mumble.pb.cc.o): in function `MumbleProto::RequestBlob::RequestBlob(MumbleProto::RequestBlob const&)':
Mumble.pb.cc:(.text+0x1f6bd): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x1f6cd): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
/usr/bin/ld: Mumble.pb.cc:(.text+0x1f6dd): undefined reference to `google::protobuf::RepeatedField<unsigned int>::RepeatedField(google::protobuf::RepeatedField<unsigned int> const&)'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by Krzmbrzl** [comment] 2020-11-12 17:42
Did you perhaps recently upgrade protobuf? Could that cause the issue?

**Comment by radioactiveman** [comment] 2020-11-12 19:59
I have downgraded protobuf to 3.11.4 (Arch uses 3.12.4) by compiling it manually with Clang. Then linking the Mumble executable worked. Afterwards I compiled 3.12.4 manually. Interestingly linking still worked.

So the assumption is:
- If protobuf is compiled with GCC, Mumble cannot be linked when compiled with Clang, but with GCC
- If protobuf is compiled with Clang, Mumble can be linked when compiled with Clang and GCC

Using `CMAKE_BUILD_TYPE=Release` also makes the linking work, even when using Clang and protobuf 3.12.4 from Arch repositories. Before I have used buildy type `None` to use the default distribution compiler flags.

All in all this seems to be a rare corner case and no bug in Mumble. So feel free to close this issue.

**Comment by Krzmbrzl** [comment] 2020-11-13 06:47
Thanks for the update.

This is very curious... Maybe this should be reported as a problem to protobuf? Perhaps they are doing something different when compiled with clang? :eyes: 

I agree though that this is probably not an issue in Mumble and therefore I'll indeed close this issue :)

**Closed by Krzmbrzl** 2020-11-13 06:47 UTC
Labels: build
