### ISSUE TITLE
Speech-Dispatcher Causes Static Noise

### ISSUE THREAD

**Issue by naortega** [mumble-voip/mumble#2872] opened 2017-02-25 10:25 UTC
I am unsure as to the reason why speech-dispatcher is used, especially since every time I run mumble I obligatorily run `pkill speech-dispatch` to stop static noise from killing my ears with the sounds coming from every application (it makes the output of Mumble static as well as sounds coming from other applications).

I don't see how it can have that much importance if I'm killing it and nothing happens (except the improvement of sound quality).

I would also like to ask if this is related to Mumble silencing other applications (like my music player, `cmus`) upon startup **by default** (which means every time I reinstall I need to search around for a half hour on how to change this setting).

The only warnings I get are: `warning: The VAD has been replaced by a hack pending a complete rewrite`. The version I'm running is `1.2.19` on GNU/Linux (but this also happens on Windows from my experience), but this has been happening throughout various versions of the software.

**Comment by mkrautz** [comment] 2017-02-25 10:37
> I am unsure as to the reason why speech-dispatcher is used, especially since every time I run mumble I obligatorily run pkill speech-dispatch to stop static noise from killing my ears with the sounds coming from every application (it makes the output of Mumble static as well as sounds coming from other applications).
>
> I don't see how it can have that much importance if I'm killing it and nothing happens (except the improvement of sound quality).

speech-dispatcher is used on Unix-like systems for speaking notification sounds aloud. "User joined", "User left", "Connected to server", etc.

We've previously diagnosed these static noise issues to be a bug in speech-dispatcher, and asked people kindly to report the bug to the speech-dispatcher project. The problem was reproducible without even running Mumble -- just by running the CLI tool `spd-say`.

Which distro are you on? I'd like to try and reproduce the static noise issue again, so it can be properly reported upstream.

> I would also like to ask if this is related to Mumble silencing other applications (like my music player, cmus) upon startup by default (which means every time I reinstall I need to search around for a half hour on how to change this setting).

No. The issue you are seeing is because Mumble 1.2.x registers itself with PulseAudio as a "phone".
At some point, after Mumble started using "phone", PulseAudio implemented a "ducking" feature, where other program's volumes will be lowered automatically when a "phone" program is in use.

I thought the fix for this was backported to 1.2.x, but it seems like I was mistaken -- it's still there:
https://github.com/mumble-voip/mumble/blob/1.2.x/src/mumble/PulseAudio.cpp#L119

**Comment by Deathsbreed** [comment] 2017-02-25 11:01
Well then, it seems like I went to the wrong place. Sorry for that.

>Which distro are you on? I'd like to try and reproduce the static noise issue again, so it can be properly reported upstream.

I'm running Parabola GNU/Linux-libre, but I've also seen it in Debian Stretch.

>No. This issue is because Mumble 1.2.x registers itself with PulseAudio as a "phone".
At some point, after Mumble started using "phone", PulseAudio implemented a "ducking" feature, where other program's volumes will be lowered automatically when a "phone" program is in use.

Alright, I'll take a look into that.

**Comment by mkrautz** [comment] 2017-02-25 11:07
> Well then, it seems like I went to the wrong place. Sorry for that.

No, don't be sorry. :-)

The bug is affecting us, so we can't just leave users hanging.

For example, a quality-of-life improvement we can add until this is fixed is to simply not initialize speech-dispatcher if the user has disabled text-to-speech via Configure -> Text-to-Speech.

**Comment by DarkArc** [comment] 2017-04-21 22:27
@Deathsbreed I stumbled across this issue, about your muting problem, disabling the pulse audio cork module solved that for me. https://github.com/mpv-player/mpv/issues/1173#issuecomment-59243470

@mkrautz I would really appreciate it if you guys could implement something so that speech dispatcher doesn't start if text to speech is disabled, that would be a quite welcome change.

**Closed** 2020-03-15 11:22 UTC
Labels: audio, linux
