### ISSUE TITLE
Unpin from taskbar after update

### ISSUE THREAD

**Issue by SvenNus** [mumble-voip/mumble#1845] opened 2015-10-15 21:07 UTC
I have mumble pinned to my taskbar and after some updates it just unpins itself from the taskbar. I don't know when this happened for the first time but 6 months ago this wasn't an issue.
-Using snapshot client
-occurred on win 8.1 and 10
-happened with latest update and several times before.

**Comment by JoelTroch** [comment] 2015-11-05 15:08
This might help (or not)

https://www.mail-archive.com/wix-users@lists.sourceforge.net/msg41250.html

**Comment by mkrautz** [comment] 2015-11-05 15:27
I don't think it will.

The problem is that we changed the way the installer works. Previously, it wouldn't properly uninstall the old files. We changed it to do a full uninstall, and install the new files freshly.

This seems to remove the pin to the task bar, seemingly because the shortcut is removed for a short while between the uninstall and the fresh install.

It also is problematic when you use Murmur and murmur.ini in the Program Files directory. The installer overwrites your murmur.ini every time you upgrade your installation.

**Comment by mkrautz** [comment] 2015-11-05 18:57
@SvenNus Is this with snapshots, or release builds? I assume it is snapshots...

**Comment by SvenNus** [comment] 2015-11-05 21:08
@mkrautz yes I use snapshots.

**Comment by Enigma0** [comment] 2016-06-27 01:07
Same issue. With snapshots.

**Comment by mkrautz** [comment] 2017-07-20 12:28
This should be fixed in the latest snapshot: mumble-1.3.0~2505~g346702f.

If it isn't, please re-open.

**Closed by mkrautz** 2017-07-20 12:28 UTC
Labels: installer, windows
