### ISSUE TITLE
Integrated Comment Viewer

### ISSUE THREAD

**Issue by Xylemon** [mumble-voip/mumble#1998] opened 2015-12-20 11:39 UTC
There's quite a few people, including myself, who seem to dislike the way Mumble handles user and channel comments. Even the "view comment" window feels lacking. It would be nice if a comment viewer with possible information about the user (avatar and so on) that is actually in the GUI itself could be added to the client and could be moved around like the chat log or channel browser. This could be nice for viewing larger descriptions without the need of "view comment" and perhaps some image re-sizing could be applied. Just some general ideas on how a feature like this could be useful.

**Comment by dannycolin89** [comment] 2016-06-12 23:43
Any progress on that feature request?

**Comment by Krzmbrzl** [comment] 2019-12-31 08:36
This seems like a duplicate of #3386 at least when considering https://github.com/mumble-voip/mumble/issues/3386#issuecomment-569888486

Although given that this issue is older, the kinked issue is possibly a duplicate of this one. 

Maybe you (or one of the maintainers) could change the issue to also include the channel description (in the title)

**Closed** 2020-03-02 16:29 UTC
Labels: feature-request, ui
