### ISSUE TITLE
Could not create AF_NETLINK socket

### ISSUE THREAD

**Issue by roughnecks** [mumble-voip/mumble#6180] opened 2023-07-16 17:33 UTC
### The issue

Hello, I've got this "issue", a log repeating warn/err:

`mumble-server[277214]: <C>2023-07-16 19:27:08.838 Could not create AF_NETLINK socket (Address family not supported by protocol)`

I don't have IPv6 on this host, or.. better, it's completely disabled.

In my config I have `host=0.0.0.0`
What's the best alternative to only listen to IPv4? I tried with my public IP but then I cannot connect bots via localhost anymore.

Thanks

### Mumble version

1.5.517

### Mumble component

Server

### OS

Linux

### Additional information

Debian 12, manually compiled binary.

**Comment by Krzmbrzl** [comment] 2023-07-16 18:27
@davidebeatrici

**Comment by davidebeatrici** [comment] 2023-07-16 22:25
It's not rare to see modern software failing on hosts without IPv6, usually because relying on `AF_INET6` for IPv4 as well ([mapped to IPv6](https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses)). Fixing the issue is not too hard: SoftEtherVPN/SoftEtherVPN#1510

Right now we're relying on Qt for networking; we have to check whether the issue is on our side or upstream.

**Comment by roughnecks** [comment] 2023-12-08 20:53
I've got a new host which has IPv6 and mumble is actually listening to it:

`tcp6       0      0 :::64738                :::*                    LISTEN      380387/mumble-serve`

but I still have the error message, how comes?

**Comment by Krzmbrzl** [comment] 2023-12-12 19:17
@davidebeatrici ^

**Comment by Krzmbrzl** [comment] 2024-01-07 10:07
To my understanding this has been resolved via Matrix check thanks to a reference to https://forum.manjaro.org/t/murmur-mumble-server-systemd-unit-log-errors/103593

Based on the information there this seems to be related to a kernel issue and adding
```
[Service]
RestrictAddressFamilies=
```
to the systemd service file.

**Closed by Krzmbrzl** 2024-01-07 10:07 UTC
Labels: server, bug

**Comment by atomGit** [comment] 2024-03-10 07:59
log is getting spammed by these ...

`<C>2024-03-10 07:55:16.150 Could not create AF_NETLINK socket (Address family not supported by protocol)`

i tried the following but it didn't work...

[Murmur (mumble server) systemd unit log errors - Technical Assistance - Manjaro Linux Forum](https://forum.manjaro.org/t/murmur-mumble-server-systemd-unit-log-errors/103593)

**Comment by Sailing74** [comment] 2024-11-20 16:45
The solution mentioned in the Manjaro forum (adding an override.conf to systemd for murmur) helped here to stop the spam. The service is called mumble-server.service here, not murmur. But the actual solution worked for me.

**Comment by Kissaki** [comment] 2025-01-12 14:03
@Krzmbrzl I'm a bit confused as to why this was closed as completed.

Did you not only link a workaround while our systemd file remains as-is with the issue?

From what I can see, [our systemd service file still has the filled `RestrictAddressFamilies` defined](https://github.com/mumble-voip/mumble/blob/29ca4f0f36a0a7d68d7175a1e39d5e1f1477e3d8/auxiliary_files/config_files/mumble-server.service.in#L25). Should that file not be updated with that declaration removed or emptied to fix the issue?

---

The key was added in cd068fe3eec4713916257295626e2aebf6c6ed7f. Sourced from https://github.com/archlinux/svntogit-community/commit/d609d479160961b69f16c65f011be9f59310e991 which seems to describe it as general hardening. That repo has since been archived.

* https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RestrictAddressFamilies=
* https://en.wikipedia.org/wiki/Netlink#Netlink_socket_families
* https://manpages.org/af_packet/7

Dropping the `AF_NETLINK` from it resolves the logged errors for me. (Ubuntu server)

**Comment by Kissaki** [comment] 2025-01-12 14:09
oops, I wanted to create a PR, but the GitHub UI committed directly to master by default...

@Krzmbrzl if you could please take a look if that's fine https://github.com/mumble-voip/mumble/commit/ba3a32d736cbd30146e11287a755f4b599d393c7

**Comment by Krzmbrzl** [comment] 2025-01-12 14:13
> I'm a bit confused as to why this was closed as completed.

Because this is not a Mumble issue, but a Kernel bug.

I have no idea what the implications of removing `AF_NETLINK` from the service file are. Hence, I can't really comment on whether or not this is a good thing.
If it didn't serve any purpose before, then removing it as a workaround to a Kernel bug seems fine. However, if it did in fact serve a purpose, it would depend on what that purpose is. Generally speaking, I am a bit hesitant with including workarounds for non-Mumble bugs into Mumble itself :shrug:

**Comment by Kissaki** [comment] 2025-01-12 14:15
The assumption that it is a kernel big stems only from the last comment in that thread?

> The ARM is not changed (config wise) compared to the x64 package, so I think it would likely be a kernel issue instead, if the think needs something specific from the kernel.

I'm not on an ARM system and see this issue.

**Comment by Kissaki** [comment] 2025-01-12 14:19
Maybe I'm not understanding what is referenced and happening here.

My interpretation of the stuff I linked is:

* That's a service config declaration for disallowing (`~`) socket address families.
* Given the error logs a not supported family, it must try to reference the disallowed family despite it not being supported on the system, which would not be necessary for a disallow on something that does not exist.
