### ISSUE TITLE
Crackling/Sound quality loss intermittently 

### ISSUE THREAD

**Issue by rembomy** [mumble-voip/mumble#3950] opened 2020-01-23 10:53 UTC
Occasionally people hear crackles/sound quality loss from my microphone. 

My input does not have boost option and signal coming in is around 50% on the mumble voice activation bar. In comparison, I do not have a single issue when talking with microphone using other comms software or OBS. 

I have tried playing with the sound bandwidth on server side, on client side, reconfigured my microphone on the mixer and on windows. Even added compression on mixer side to reduce input volume, but it did not change anything. Mic is not clipping and just occasionally messes up sound on Mumble.

Server and my client are running 08 Sept stable x64 1.3.0 for Windows.

Tested with 2 microphones:
Main (2 channels, 24bit 48000Hz) has issues.
Second (1 channel, 16bit, 44100 Hz) no issues. 

Interesting is that on Second volume levels spiked much higher than on the Main. Neither of them had any issues with OBS at the time being when it happened in Mumble so I can confirm its not a hardware fault. It doesn't happen all the time, occurs randomly. 

I will try to get someone recording when this happens so I could share what they are hearing.

**Comment by Krzmbrzl** [comment] 2020-01-23 15:36
I asked on our IRC channel and there have been others using multi-channel microphones who don't have this problem. Thus it appears as if it is not a problem with multi-channel-mics (per se).

Which audio interface are you using? (Can be found out under Configure -> audio input -> Interface -> System)
Maybe it'd be best if you could provide a screenshot of your Audio-input settings screen :)

**Comment by rembomy** [comment] 2020-01-23 16:24
I am using Berhinger X18 that is connected via USB, on top of that I am using ASIO Link Pro that is routed from 16th channel to 01 Mic using ASIOVADPRO driver. In the ASIO Link Pro there is unfortunately no option to single channel it as all WDM devices are created 2 channel. In most cases I would suspect the software (ASIO Link Pro) immediately, but it does not happen in other software Like OBS and all of my sound is routed through there...  

I'll try to get a recording done today should it break down again so I can give you better examples of what happens. I suspect is something to do with the sound format and how its passed between Windows and Mumble. 

![Capture](https://user-images.githubusercontent.com/20752675/73002525-df978400-3e0c-11ea-938a-86cf754eb3b6.PNG)

**Comment by Krzmbrzl** [comment] 2020-01-23 16:41
Wow that appears like a really fancy audio setup :+1:

I was referring to the audio settings in Mumble though. If you'd be so kind as to share a screensjot of that as well... 
Though from what you have written so far, I suspect you're using the ASIO interface. Let's see though before making premature assumptions :)

**Comment by rembomy** [comment] 2020-01-23 18:41
On mumble, no I'm not using ASIO interface. Pics below. 

![Capture2](https://user-images.githubusercontent.com/20752675/73013206-89ccd700-3e20-11ea-8e2a-30e43c72f982.PNG)
![Capture1](https://user-images.githubusercontent.com/20752675/73013207-8a656d80-3e20-11ea-8904-6a0b69eefaef.PNG)

**Comment by Krzmbrzl** [comment] 2020-01-23 20:35
Okay then... Have you tried whether not ticking exclusive (directly under the sound system selection) changes anything in regards to that bug?

**Comment by rembomy** [comment] 2020-01-23 21:53
Yeah, that didn't change anything. I suspect that since the signal is originally mono and I change it to stereo then since they are identical maybe mumble gets confused somehow from that?

**Comment by Krzmbrzl** [comment] 2020-01-24 06:34
> I suspect that since the signal is originally mono and I change it to stereo

I thought the microphone causing the trouble was stereo? Or are you inputting via a mono-microphone and create something like a "virtual microphone" that upgrades the input to stereo?

> since they are identical maybe mumble gets confused somehow from that?

That'd depend on how Mumble handles stereo input... I'm not quite sure right now, but I have been told that Mumble reduces the input to mono anyways (through whichever method). I'll have to look at the code in order to get some more insights into this.
In the meantime maybe @davidebeatrici could think of something, as he is way more familiar with the whole audio-backend than I am :)

**Comment by Krzmbrzl** [comment] 2020-01-24 06:42
Could you start Mumble via console and copy the log-messages it emits during startup to here? There should be a line from 
https://github.com/mumble-voip/mumble/blob/72e1f47b7b13d2ffd2a98cb2fd79c10674376698/src/mumble/AudioInput.cpp#L424
containing information how many channels Mumble sets up for your mic...

**Comment by rembomy** [comment] 2020-01-24 08:17
[14300] <W>2020-01-24 10:13:07.455 AudioInput: Opus encoder set for VOIP
[14300] <W>2020-01-24 10:13:07.456 AudioInput: 96000 bits/s, 48000 hz, 480 sample
[14300] <W>2020-01-24 10:13:07.473 WASAPIInput: Latencies 100000 30000 => 100000
[14300] <W>2020-01-24 10:13:07.473 Adding device {6f1d2b60-d5a0-11cf-bfc7-444553540000} Mouse Mouse:8 type 0x00000112 guid product {6f1d2b60-d5a0-11cf-bfc7-444553540000}
[14300] <W>2020-01-24 10:13:07.475 WASAPIOutput: Latencies 100000 30000 => 100000
[14300] <W>2020-01-24 10:13:07.476 Adding device {6f1d2b61-d5a0-11cf-bfc7-444553540000} Keyboard Keyboard:127 type 0x00000413 guid product {6f1d2b61-d5a0-11cf-bfc7-444553540000}
[14300] <W>2020-01-24 10:13:07.479 WASAPIInput: Mic Stream format 1
[14300] <W>2020-01-24 10:13:07.479 WASAPIInput: Stream Latency 0 (1056)
[14300] <W>2020-01-24 10:13:07.483 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 0 channel 48000 hz echo
[14300] <W>2020-01-24 10:13:07.492 WASAPIOutput: Output stream format 1
[14300] <W>2020-01-24 10:13:07.492 WASAPIOutput: Stream Latency 0 (1056)
[14300] <W>2020-01-24 10:13:07.492 WASAPIOutput: Periods 10000us 3000us (latency 0us)
[14300] <W>2020-01-24 10:13:07.492 WASAPIOutput: Buffer is 22000us (1)
[14300] <W>2020-01-24 10:13:07.492 AudioOutput: Initialized 2 channel 48000 hz mixer

**Comment by rembomy** [comment] 2020-01-24 11:17
After some more troubleshooting I am suspecting that the issue is the driver I am using on windows side and since it has not been updated for the past 5 years then mumble just may not like it that much. I found some newer alternative, drivers and I will give it another go of testing today to see if it happens again.

**Comment by Krzmbrzl** [comment] 2020-01-24 15:17
> 480 sample? If that's buffer rate then I'm using 256 and can use 512, but not 480

No this appears to be the frame-size (the naming in the log seems to be a bit confusing)
https://github.com/mumble-voip/mumble/blob/72e1f47b7b13d2ffd2a98cb2fd79c10674376698/src/mumble/AudioInput.cpp#L116
And the frame-size is defind as
https://github.com/mumble-voip/mumble/blob/72e1f47b7b13d2ffd2a98cb2fd79c10674376698/src/mumble/AudioInput.cpp#L92
and finally `SAMPLE_RATE` is defined as
https://github.com/mumble-voip/mumble/blob/c2469ac29cc9761b8d90de958ab37573858db272/src/mumble/Audio.h#L18
( which you can also find in the respective log-message)

> After some more troubleshooting I am suspecting that the issue is the driver I am using on windows side

Did you get any specific result that led you to this suspicion or is it just a feeling? After having seen your setup, I do share the suspicion that the problem is connected to the intermediary software (driver) between the mic and Mumble.
On the other hand you said that you didn't have any problems in other applications which in turn suggests that the fault is indeed somewhere to be found on Mumble's side. Having said that though, I have the feeling that we'll have a hard time debugging this as we'd have to replicate the issue before. Do you know whether the driver you are using also works for other microphones? And does it happen to be freely available so I could try and replicate the problem (a quick search on the internet didn't yield much).

> I found some newer alternative drivers and I will give it another go of testing today to see if it happens again.

It would of course be neat, if that fixed the problem. Good luck! :)

**Comment by rembomy** [comment] 2020-01-26 08:47
I can confirm alternative drivers worked, and that that case mic sound is actually one channel. 

What I was using: ASIOVADPRO drivers + ASIO Link Pro software for routing. Those both are actually installed together. Those drivers also are limited to spiting Mic into 2 channels like I showed above on the screenshots. With these drivers issue was only on mumble side for me though.

What I am using: Synchronous Audio Router drivers + ASIO Link Pro for routing the audio. In this case I could put mic on once channel like it should be and nobody has complained in Mumble that I crackle or cut out. 

I agree that testing this on your side can be pretty complicated as for starters you will need a digital USB mixer that has more than 2 channels as everything runs over USB for me. 

For me the case is closed, but I guess its good knowledge should someone actually run into something like this again that ASIOVADPRO drivers are not compatible with Mumble. Unfortunately guy who was developing those has passed away so there will be no updates coming from that side.

**Comment by Krzmbrzl** [comment] 2020-01-26 09:00
Thank you for testing this and I'm glad that the issue has been resolved for you.

Given that it appears to be indeed very complicated to try and reproduce this case on my machine (which would be needed to investigate the underlying cause of the bug), I'd say it is unrealistic that this will ever happen. Especially now that there seems to be a more or less easy fix to this. 
Thus I'll close this issue. Thanks to you however we'd have a lot of input should an issue like this one ever occur again :)

**Closed by Krzmbrzl** 2020-01-26 09:00 UTC
Labels: audio, bug
