### ISSUE TITLE
Chat log not properly terminating lists (and possibly other tags)

### ISSUE THREAD

**Issue by dexgs** [mumble-voip/mumble#5430] opened 2022-01-17 05:53 UTC
### Description

If you send a message which ends in a list, it does not get properly terminated and future chat log entries will be displayed as list items.

### Steps to reproduce

1. Join a server
2. Write the following in a message (using the "source text" tab in the send message dialogue so that you can use HTML tags): `<ul><li>list</li></ul>`
3. send more messages, notice that they display as list items.

### Mumble version

1.4.0

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

Clearing the chat or receiving a message containing a block-level element, such as `<h1>` will reset the effects of this bug.
I am running Linux, but received confirmation from someone using Windows that the same effect is visible.

### Screenshots

![image](https://user-images.githubusercontent.com/93449583/149714370-5edbdc81-02b3-4c85-902f-ba3046174fb3.png)
![image](https://user-images.githubusercontent.com/93449583/149714940-5f665d7f-540e-4f2f-bfe5-d69a62803ee4.png)

**Comment by Krzmbrzl** [comment] 2022-01-17 07:08
Probably (yet again) related to the Markdown parsing in some way :eyes:

**Comment by TerryGeng** [comment] 2022-01-17 19:53
I can confirm this problem has been here for a long time... I did some preliminary troubleshooting long long time ago but wasn't very successful.

**Comment by Krzmbrzl** [comment] 2022-01-17 20:00
"Long long" as in "before 1.4 was a thing" or as in "sometime during 1.4 development"?

**Comment by Krzmbrzl** [comment] 2022-01-17 20:02
That brings me to https://github.com/mumble-voip/mumble/issues/4491 which I think this issue here is a duplicate of... Does that sound about right?

**Comment by TerryGeng** [comment] 2022-01-17 20:06
During 1.4.0 development, for which I'm pretty sure.

1.4.x:
![image](https://user-images.githubusercontent.com/2306637/149831276-57c80bf8-5292-435b-9632-e23a77be2bce.png)

1.3.x:
![image](https://user-images.githubusercontent.com/2306637/149831287-54ec54fa-74b2-4a4b-b209-18adec54b5d2.png)

**Comment by dexgs** [comment] 2022-01-17 20:07
@Krzmbrzl , That issue seems to describe the same problem. I'm just guessing here, but I noticed that in mumble 1.3.x, if your message contains any block-level elements, it gets enclosed in a box. This doesn't happen in 1.4.x. Is it possible that this has always been a problem, but was previously avoided by enclosing messages that cause this problem in 1.4.x in a block-level element (the box)?

**Comment by TerryGeng** [comment] 2022-01-17 20:07
> That brings me to #4491 which I think this issue here is a duplicate of... Does that sound about right?

Ahh... you are right. Even the examples are the same :).

**Comment by Krzmbrzl** [comment] 2022-01-17 20:09
Yes the block thingy has been changed in 1.4 and iirc the linked issue did indeed appear after that change - so it's likely that you hypothesis is correct. 

In any case, I'll close this issue as a duplicate then. Thanks for reporting anyway, though!

**Comment by dexgs** [comment] 2022-01-17 20:09
> Is it possible that this has always been a problem, but was previously avoided by enclosing messages that cause this problem in 1.4.x in a block-level element (the box)?

To clarify, I think it's worth it to look beyond the Markdown parsing for the cause of this, as I think the problem has possibly been around for a lot longer (just invisibly)

**Closed** 2022-01-17 20:10 UTC
Labels: client, bug
