### ISSUE TITLE
Shortcuts -> Set Hotkey - does not support taskbar on the top.

### ISSUE THREAD

**Issue by DesktopMasters** [mumble-voip/mumble#5544] opened 2022-02-02 22:15 UTC
### Description

My taskbar is on the top of the screen.  When I got to add a hotkey the (new) box that pops up to configure the hotkey goes right up to the top of the screen under my taskbar.

### Steps to reproduce

0. Move taskbar to top of screen
1. Open the settings window
2. Add shortcut
3. Set hotkey

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

### Screenshots

![Example](https://user-images.githubusercontent.com/58863524/152246515-01e7e1d0-fb28-46a2-81ba-397561008d40.png)

**Comment by Hartmnt** [comment] 2024-05-31 13:05
Ok I am closing this anyway as duplicate of #5024

**Closed by Hartmnt** 2024-05-31 13:05 UTC
Labels: client, ui, bug
