### ISSUE TITLE
Really slow to load server info at launch

### ISSUE THREAD

**Issue by iJaack** [mumble-voip/mumble#4894] opened 2021-03-29 08:18 UTC
**Describe the bug**
The Mumble application takes almost 30 seconds to load server information and log in.

**Steps to Reproduce**
1. Open the app

**Expected behavior**
I expect the app to load information in a few seconds on a fast connection.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3 on Mac Mini M1
 - Version: Mumble 1.3.3

**Additional context**
I've got fast 200 Mbps connection, and it works fine on another macOS computer (MacBook) in the same network, so I don't think it's a network issue.

**Comment by Krzmbrzl** [comment] 2021-03-29 13:16
What do you mean by "log in"?

And what do you mean by "server information"? Do you mean servers appearing in the public server list or saved servers showing a ping?
Or are you actually talking about connecting to a server?

**Comment by iJaack** [comment] 2021-03-29 13:37
By 'log in' I mean connection to a server.

By 'server information' I mean saved servers showing a ping.

I'm talking about both loading and connection: it's slow either way. Very slow.

**Comment by Krzmbrzl** [comment] 2021-03-29 19:39
Yeah I experienced that from time to time as well. I did not yet have the time to look into this though...

**Comment by iJaack** [comment] 2021-03-29 22:11
I don’t know if this needs a separate issue, but the **whole** computer really slows down. It’s not like it’s blocked, but it’s tremendously lagging whenever Mumble is open. For example, typing a single letter takes about 3-4 seconds, that’s crazy.

The only way I’ve solved this is I downloaded the iPhone build and ran it natively on M1. That seems to work fine for now, but I don’t get all the flexibility of the desktop app..

**Comment by davidebeatrici** [comment] 2021-03-29 22:23
Try to disable the public server list.

**Comment by iJaack** [comment] 2021-03-30 08:35
> Try to disable the public server list.

How do I do that? However, I reinstalled v1.3.3. now and it seems to work almost fine, except for the long waiting to fetch server info.

**Comment by Krzmbrzl** [comment] 2021-03-30 13:16
> How do I do that?

In 1.4.0 there is a setting under (I think) settings -> network.

I'm not sure whether this option is present in 1.3.3 as well though :thinking:

**Comment by iJaack** [comment] 2021-03-30 19:38
> > How do I do that?
> 
> In 1.4.0 there is a setting under (I think) settings -> network.
> 
> I'm not sure whether this option is present in 1.3.3 as well though 🤔

I don't see it on 1.3.3

**Comment by davidebeatrici** [comment] 2021-03-30 20:24
Sorry, the option was introduced in 1.4.0.

As a workaround, you can block incoming packets from `https://publist.mumble.info`.

**Comment by iJaack** [comment] 2021-03-31 09:57
I removed it and re-compiled it (1.4.0), I get this error:
> CMake Error at cmake/pkg-utils.cmake:87 (message):
>   OpenSSL component not found: Crypto
> Call Stack (most recent call first):
>   src/CMakeLists.txt:25 (find_pkg)

I already changed OpenSSL's path with `echo 'export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc`, what else should I do?

**Comment by iJaack** [comment] 2021-04-26 10:07
OK, something strange happened, maybe this can help someone else.

I recently moved the Mac Mini M1 to my new house, where I have a broadband 1 Gbps connections with another operator (I'm in Italy, I had TIM in the old house and I have Fastweb in the new one) with a 4-6 ms ping (compared to 20-30 ms with the previous operator), and now I get blazing fast start up time using v1.3.3.

I don't know exactly what caused the tremendous lag in my old house, specifically on the Mac Mini M1, also because the MacBook Pro (with Intel chipset) had no problem at all.

**Comment by skybella** [comment] 2021-05-18 12:46
I've had problems with some DNS Servers that cause mumble to be very slow to ping each of the servers in my list. Switching DNS servers from the default given to me by my internet provider fixed it for me.

**Comment by trudnorx** [comment] 2021-05-27 03:48
> I don’t know if this needs a separate issue, but the whole computer really slows down. It’s not like it’s blocked, but it’s tremendously lagging whenever Mumble is open. For example, typing a single letter takes about 3-4 seconds, that’s crazy.

Why Mumble causes these computer lags should be investigated even if it only happens in the context of some issues like the one you fixed. I have experienced lags like that too (with old versions - not sure if it happens with new version), and I wonder what Mumble is doing to cause such things.

**Comment by davidebeatrici** [comment] 2021-05-27 04:15
The input issue was fixed by #4941.

**Comment by trudnorx** [comment] 2021-05-28 00:22
Should this be closed?

**Comment by Krzmbrzl** [comment] 2021-05-28 05:52
I guess so, yes :+1:

**Comment by davidebeatrici** [comment] 2021-05-31 07:51
I just realized the report is strictly about macOS, as such the cause is still unknown.

**Comment by iJaack** [comment] 2021-05-31 08:03
It seems the issue is solved for me, but I don't know how. Recently, the only change I've made is I've switched to a 2400 Mbps connection, and I've got less than 5 ms ping, so it's impossible for it to load slowly.

So I guess the problem is that for not-ultrafast or low-latency (<5 ms) connections, data is loaded exponentially slower. I don't know if I explained that clearly, but **I** don't even know what happened exactly, just trying to make a sense of it.

**Comment by Krzmbrzl** [comment] 2021-05-31 08:20
> I just realized the report is strictly about macOS, as such the cause is still unknown.

But there is also no information that would help us fix this or track this down and as such this issue is not actionable by us.

We can reopen this once someone can actually reproduce this.

**Closed by Krzmbrzl** 2021-05-31 08:20 UTC
Labels: bug, client
