### ISSUE TITLE
When connect to AFK channel, can´t write text into chat

### ISSUE THREAD

**Issue by Vasekdvor** [mumble-voip/mumble#1799] opened 2015-09-03 14:45 UTC
Hi i´ve got a problem. When i connect to mumble , enter to AFK channel which is muted, and then disconnect from server (directly from AFK channel) then again reconnect, i can´t write text into textbox (chat) [well i am at AFK], even after entering another channel which is for comunicating. But when i am at communicating channel (standart, not AFK) and disconnect from server and then reconnect i can write to textbox normally. This issue is here for a several releases. I´ve got the 1.2.10 version.

**Comment by Tarun80** [comment] 2015-09-04 19:45
I've noticed that people on my server have had this issue as well. I assume it's a strange permission bug.

If Text Message is set to Deny for ```@all```, it seems to happen to everyone except admins.

**Comment by jagodragon** [comment] 2015-09-09 04:29
it's not a bug in that case. you have removed their permission to use text chat in the acl options. i did this intentionally because the read er will read the text for some one who is, perhaps, trying to get a moment of silence.
the only reason admins can still chat is because their powers override the @all group in the acl

**Comment by Tarun80** [comment] 2015-09-09 04:50
Reproduce (based on feedback and observations):

* Connect automatically into AFK (Text Message disabled)
* Move to any other channel.
* Try to send message, does not work.

**Comment by wrycu** [comment] 2015-09-12 15:14
Can confirm, this impacts me as well.  It's been happening since at least 1.2.7.  The TextMessage permission is denied within AFK, but allowed everywhere else.  After leaving AFK, users are still unable to use the input box to send messages until they right click any channel, in which case the input box re-enables itself.

**Comment by Hartmnt** [comment] 2022-10-07 12:25
The bug here is a combination of two separate issues:

First, the target selection of the chat bar introduced in be7ad39fd756083 is not working correctly. This is suffering from the exact same issue as described in #3090. This can be fixed by using the unified target selection which prefers tree items introduced in #5773.

The second problem is that when the "Use selected item as the chat bar target" option was introduced in 441d06f6d1ae7f0, the ``updateMenuPermission`` code was not updated to take the new option into account. That means, when the new option was disabled, that the chat bar would correctly display the current channel in its label, but the client-side ``enabled`` state was always pulled from the "selected" user or channel.
The second bug can be reproduced by joining a channel with ``Text Message`` as well as the "Use selected item as the chat bar target" disabled and clicking between a ``Text Message`` allowed channel and the current channel. The chat bar will become enabled/disabled with the target channel correctly staying the same.

I am currently preparing a fix for both of these problems.

**Closed** 2022-10-18 06:14 UTC
Labels: client, acl, bug
