### ISSUE TITLE
Eve online overlay stopped displaying

### ISSUE THREAD

**Issue by promitheas17j** [mumble-voip/mumble#4332] opened 2020-07-01 13:17 UTC
After updating to 1.3.1 the overlay stopped displaying in the eve client. It is enabled in settings, and I have also added the <b><i>bin64\exefile.exe</i></b> to the allowed programs list. It may be irrelevant, but if it can help, I also tried ticking the <b><i>Show FPS counter</i></b> box and that wouldn't display either. I always run mumble before running the game client. Thanks.

**Comment by Krzmbrzl** [comment] 2020-07-01 13:53
Duplicate of #4281

**Closed by Krzmbrzl** 2020-07-01 13:53 UTC
