### ISSUE TITLE
Add video support for Mumble!

### ISSUE THREAD

**Issue by TechGuyOnTGB** [mumble-voip/mumble#5213] opened 2021-07-28 10:51 UTC
**Context**
In which context would you expect your suggested feature to be useful? 
Many users have switched to online communication, and video is a key component. Mumble is awesome for its powerful role system, low latency, and doing one thing and do it well: to be a voice platform. But I would like Mumble to be more extensible :)
**Describe the feature you have in mind**
This feature may be considered controversial because Mumble is a platform dedicated to voice chat, and adding video may be a bit far cry for the entire project. I acknowledge that. But I also think mumble is appealing to gamers. Video will allow users to share their screens while they're playing, showcase themselves, their setups, etc. 
As far as implementation goes, I was thinking to implement ffmpeg and an embedded mpv instance or some sort to see users' video stream. This may be dirty, but this is the simplest way to video stream I can think of.
**Describe alternatives you've considered**
If I wanna showcase something on video, I leave my mumble instance and wsitch to a jitsi instance, where I communicate with others. This is pretty inconvenient imo.
**Additional context**
As I stated in the beginning, this is a controversial feature request, this may or may not be viable. I am open to any criticism or aditional opinions.

Have a nice day!

**Comment by JuniorJPDJ** [comment] 2021-07-28 11:05
IMO bad idea.

**Comment by Krzmbrzl** [comment] 2021-07-28 11:34
Duplicate of #4150

That being said I personally don't consider this a great idea either. Mumble is not a conferencing system and if it tried to be one, it would probably not work out well...

**Closed by Krzmbrzl** 2021-07-28 11:34 UTC

**Comment by TechGuyOnTGB** [comment] 2021-07-28 12:52
I didn't see that thread, sorry!

**Comment by Krzmbrzl** [comment] 2021-07-28 13:40
No worries :)
