### ISSUE TITLE
Compatibility with Murmur servers running versions prior to 1.2.19 is broken as of 1.3.4..

### ISSUE THREAD

**Issue by SC1040-TS2** [mumble-voip/mumble#4780] opened 2021-02-22 05:30 UTC
**Describe the bug**
Following the Mumble 1.3.4 Client update, all unmaintained Murmur servers that were running versions 1.2.16 to 1.2.18(e.g. Schwarzspiele, HopelessDemocracy, and so on) are no longer visible in the server list. This is likely due to changes made in this update breaking compatibility with those versions.

**Steps to Reproduce**
1. Open Mumble.
2. Open the Server Connect List.
3. Open a region where you knew very old servers were hosted, such as the ones named for the US region.
4. Notice how listings for those are no longer available.

**Expected behavior**
This may be expected behavior considering what changes were made to the Mumble client version as of 1.3.4, but if it is not, seeing those ancient servers is warranted.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 2009(20H2) 19042.804
 - Version: Mumble 1.3.4

**Additional context**
This is not exactly an issue given the nature of it, but may be worth documenting so it is a known thing.

**Comment by Krzmbrzl** [comment] 2021-02-22 06:35
Afaik we did not change anything related to this in the client's code.

We did however rewrite the public server backend script (unrelated to the update).

@davidebeatrici do you have an idea why these old servers are not showing up anymore? 
Iirc you once mentioned that the older binaries were using a different endpoint on our website. Could that be the issue?

**Comment by davidebeatrici** [comment] 2021-02-22 07:15
Correct: https://github.com/mumble-voip/mumble/blob/cf8eaa20d9ba36a7877f01a83ac1036aebf18631/src/murmur/Register.cpp#L117

The endpoint appears to be working just fine though, I only see `200` responses for it in the web server's logs.

**Comment by SC1040-TS2** [comment] 2021-02-22 07:53
1.2.19 servers seem to be unaffected by this from what I have seen, as was mentioned in the title. It is those few servers that use versions before 1.2.19 which are no longer seen, such as the two to three remaining 1.2.16, one 1.2.17, and one or two 1.2.18 servers as of the US region.

Though, I thought there were more servers than 6 running 1.2.19 as of currently, with two in the US region and two or three in New Zealand, and maybe some more lurking around here and there.

**Comment by Krzmbrzl** [comment] 2021-02-22 10:20
I found 
https://github.com/mumble-voip/mumble/blob/045953c1b9d0c12fd5e4f408ac5cba9161619f39/src/murmur/Register.cpp#L117

that only got updated to use `mumble.info` instead via 6d376041ef73d350b519dacdda9d836f7eba2014.

@davidebeatrici do you think that these old versions are so old that they might be using this endpoint? But if so, how did that ever work until recently. This site does not seem to exist (anymore) :eyes:

**Comment by davidebeatrici** [comment] 2021-02-22 19:46
`mumble.hive.no` disappeared years ago, thus servers older than 1.2.18 (which introduced 6d376041ef73d350b519dacdda9d836f7eba2014) cannot register anymore.

A possible explanation for the servers appearing anyway until now is our old script not cleaning up the database properly.

**Comment by Krzmbrzl** [comment] 2021-02-23 06:45
That would be a funny artifact xD

That'd mean though that these servers should have disappeared from the list a long time ago already.

@SC1040-TS2 mentionwd however that these servers were using a version between 1.2.16 and 1.2.18 (inclusive).
Thus they must be using the correct `mumble.info` domain.

@davidebeatrici it is now possible to use CNAME records as well. Do you think that this change could affect their registration? :thinking:

**Comment by davidebeatrici** [comment] 2021-02-23 08:17
> @SC1040-TS2 mentionwd however that these servers were using a version between 1.2.16 and 1.2.18 (inclusive).
Thus they must be using the correct `mumble.info` domain.

Yeah, I initially thought the commit was introduced in 1.2.18. I updated the message afterwards.

> @davidebeatrici it is now possible to use CNAME records as well. Do you think that this change could affect their registration? :thinking:

I'm pretty sure the reason why those servers don't appear anymore is because the OpenSSL version they're using don't support TLSv1.2, which is the minimum protocol version accepted on `mumble.info` since we upgraded from Ubuntu 16.04 to 20.04.

**Comment by Krzmbrzl** [comment] 2021-02-23 08:27
> I'm pretty sure the reason why those servers don't appear anymore is because the OpenSSL version they're using doesn't support TLSv1.2, which is the minimum protocol version accepted on mumble.info since we upgraded from Ubuntu 16.04 to 20.04.

That sounds plausible. When did we perform the upgrade? Not too long ago iirc, right?

**Comment by davidebeatrici** [comment] 2021-02-23 18:15
15th November.

**Comment by Krzmbrzl** [comment] 2021-02-23 18:21
@SC1040-TS2 any chance this was about the same time the servers disappeared?

**Comment by SC1040-TS2** [comment] 2021-02-26 19:38
Unfortunately, I do not know if the servers were already missing as of November 15th. I only just noticed the removal following the 1.3.4 client update.

Whether it is a case of user perception or the client version update taking the changes into account is something I do not know of at this time. As far as I know, I could still access those servers in roughly December last year, but that may be a false memory.

I will follow up this in the event users still using Mumble 1.3.3 can still see them.

**Comment by Krzmbrzl** [comment] 2021-02-27 07:26
Alright. If you find anything in that regards, please let us know. Until then I'll close this issue assuming that the issue is not the updated client but rather the outdated TLS version of the servers.

**Closed by Krzmbrzl** 2021-02-27 07:26 UTC
Labels: public-server-registration

**Comment by SC1040-TS2** [comment] 2021-04-11 20:30
Seems that this was likely tied to the outdated TLS version or other backend whatnot, based on one other time where I had tested it.

Oh well, eventually those servers will either have to upgrade if the original owner remembers it, or cease operation.
