### ISSUE TITLE
EVE: Overlay doesn't work anymore

### ISSUE THREAD

**Issue by Attoy** [mumble-voip/mumble#1560] opened 2015-02-08 15:37 UTC
I upgraded today to the latest snapshot and the overlay with Eve Online doesn't work anymore. I'm on Win 8.1 Pro 64bit.

I tried the following configuration:
Mumble 32bit - Eve DX9
Mumble 32bit - Eve DX11
Mumble 64bit - Eve DX9
Mumble 64bit - Eve DX11

**Comment by Attoy** [comment] 2015-02-08 15:50
It seems I missed a snapshot; so I add a further test results:
version 1.3.0~532~g818e4c9~ , overlay doesn't work
version 1.3.0~511~ge469bd6~ , overlay doesn't work
version 1.3.0~509~g3b507d5~ , overlay works (Eve DX9 , Mumble 32bit)

**Comment by AxMi-24** [comment] 2015-02-08 20:05
That's probably because it was crashing the client before. Not working is preferred I would say.

**Comment by Attoy** [comment] 2015-02-09 17:32
What's crashing exactly? As it seems there's nothing crashing based on the task manager.

**Comment by AxMi-24** [comment] 2015-02-09 21:28
EVE game client was crashing when using DX 11 overlay.

**Comment by Attoy** [comment] 2015-02-10 14:30
My bad , as I just logged in , check if the overlay works and then close the client. Waiting a bit longer indeed the exefile.exe is going to crash.

**Comment by Attoy** [comment] 2015-02-22 10:53
Updated , tested with 1.3.0~540~gedd5509~ and it still doesn't work

**Comment by Kissaki** [comment] 2015-02-27 23:27
Overlay displays fine for me in the main menu.
Mumble 1.3.0~540. Eve 8.52.865562 DX11.

**Comment by minshayla** [comment] 2015-02-28 06:36
I didn't see this thread before sorry for duplicating.  I have tested with both 64bit and 32 bit on my system and my results are as follows:

1.  64 bit Mumble 1.3.0~540 & Eve 8.52.865562 DX 11 - overlay does not work
2.  64 bit Mumble 1.3.0~540 & Eve 8.52.865562 DX 9 - overlay does work
3.  32 bit Mumble 1.3.0~540 & Eve 8.52.865562 DX 11 - overlay does not work
4.  32 bit Mumble 1.3.0~540 & Eve 8.52.865562 DX 9 - overlay does work

These are the results from my system.  In all cases all settings remained the same and were not changed.

System:
OS Name	Microsoft Windows 8.1 Pro
Version	6.3.9600 Build 9600
System Manufacturer	Dell Inc.
System Model	Dell System XPS L702X
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-2720QM CPU @ 2.20GHz, 2201 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	Dell Inc. A19, 09/07/2012
Installed Physical Memory (RAM)	16.0 GB
Adapter Description	NVIDIA GeForce GT 555M
Driver Version	9.18.13.4752

**Comment by rndmerle** [comment] 2015-04-01 16:08
EVE using DX11.
Using Mumble 1.3.0~567 **64bits** : NOT working
Using Mumble 1.3.0~567 **32bits** : working

**Comment by Attoy** [comment] 2015-04-02 10:46
Using EVE in DX11 and Mumble 1.3.0~567 32bits overlay indeed is working but it randomly crashes the Eve client. It doesn't happen if I disable the overlay in Mumble and it doesn't happen if I run the Eve client in DX9

**Comment by rndmerle** [comment] 2015-04-07 11:34
Here is the DebugView logs when it crashes: 
https://dl.dropboxusercontent.com/u/265403/EveCrash.LOG

Not sure if it helps.

**Comment by andrewpmartinez** [comment] 2015-12-06 03:57
Mumble 1.3.0~867~g197f13e~snapshot 64bit, on Windows 10 64bit, the mumble overlay will crash Eve after a period of time.

**Comment by AxMi-24** [comment] 2015-12-08 06:40
Not sure where the previous discussion went but the issue with crashing seems to be a bad memory leak that is reset every time the overlay is actually displayed. That means that if there is a lot of chatter going on it will be fine for ever but if there is not you will eventually crash the eve client (once it reaches memory limit for 32bit).

I use it with win7 64bit and DX11 eve all the time and it's rock stable if you just turn on "show FPS". That way overlay is constantly active and there is no memory leak. I've run 3 clients during fleet fights lasting several hours without a single issue.

It's not perfect but at least it works until devs figure out how to prevent the memory leak from occurring in the first place.

**Comment by rndmerle** [comment] 2015-12-08 07:16
Thanks much AxMi-24 :)

**Comment by mkrautz** [comment] 2015-12-08 07:58
Thanks @AxMi-24. Those kind of reproducible instructions always help.

**Comment by AxMi-24** [comment] 2015-12-08 08:52
I finally found the discussion I was referring to https://github.com/mumble-voip/mumble/issues/1123#issuecomment-111254510

**Comment by Kissaki** [comment] 2015-12-15 10:45
Where do I switch between DX9 and 11? There is no such graphics setting.

So the conclusion here is that DX9 works, but DX11 does not?

If this is different for you @rndmerle could you try a more recent snapshot?
Because those inject into x86 and x64 processes no matter what Mumble client version you use.

**Comment by andrewpmartinez** [comment] 2015-12-15 12:46
The DX setting is in the launcher. Open it, click on the gear in the top right; choose the "Game" tab.

**Comment by Kissaki** [comment] 2015-12-15 18:27
It shows fine for me in the main menu (login screen, not launcher) in DX11 with borderless fullscreen.
So I can not reproduce the overlay not showing up…
Dx9 works fine as well.
Mumble 1.3.0~868, eve 13.11.991576

**Comment by mkrautz** [comment] 2016-07-03 20:46
Fixed via https://github.com/mumble-voip/mumble/issues/1123.

**Closed by mkrautz** 2016-07-03 20:46 UTC
Labels: overlay
