### ISSUE TITLE
mumble client from cmd line

### ISSUE THREAD

**Issue by s1090017** [mumble-voip/mumble#3964] opened 2020-02-11 14:00 UTC
On Linux machines there is a need for starting the mumble client from cmd line. Please consider adding cmd line options so that the client can be started and run without x server or manual interaction.

**Comment by Krzmbrzl** [comment] 2020-02-11 23:06
Closing this as a duplicate of #3877. If you disagree, please let me know :)

**Closed by Krzmbrzl** 2020-02-11 23:06 UTC
