### ISSUE TITLE
Positional audio crashes Battlefield 1

### ISSUE THREAD

**Issue by xenadmin** [mumble-voip/mumble#2643] opened 2016-11-16 20:03 UTC
Hello,
when you try to use Positional audio in `1.3.0~1685~g491363e~snapshot` with Battlefield 1, the game crashes as soon as you try to join a Multiplayer server.
Happens for me and two of my friends on three different Windows PCs.
What further information do you need from me?

**Comment by Kissaki** [comment] 2016-11-17 13:40
Thank you for reporting.

We were able to reproduce this and identified the issue.
I reverted the culprit change e2ad9c05f0cff73defe5083e6728ab9b1af63ab9 for now.
After they are built and after updating the plugins, they should be fine again.

**Comment by mkrautz** [comment] 2016-11-18 00:23
Hi,

A new snapshot is out now. The problem should be fixed.

**Comment by xenadmin** [comment] 2016-11-20 20:43
I can verify, that BF1 doesn't crash anymore. Thank you very much for the fast fix. 
Although, the positional audio for BF1 does **not** work. Should I open a new issue for that problem?

**Comment by davidebeatrici** [comment] 2016-11-20 21:08
Hi,

You're welcome, thank you for the report. :smile: 
If the positional audio is not working anymore it's because with the latest update the memory offsets changed. I will update the plugin once I have access to the game. :wink:

**Comment by mkrautz** [comment] 2016-11-25 23:48
Yes, let's open a new BF1 plugin issue.

**Closed** 2016-11-25 23:49 UTC
Labels: positional audio
