### ISSUE TITLE
Cannot accept autogenerated certificates

### ISSUE THREAD

**Issue by Sollybird** [mumble-voip/mumble#3414] opened 2018-05-30 00:04 UTC
This is a very recent problem that I've been having. Whenever I try to join a server that has an autogenerated certificate, the client states that the server presented a different certificate from the stored one. This is not true - they are identical, as the UI shows.

Screenshots provided below
https://i.imgur.com/gktwICU.png
https://i.imgur.com/j4AFjt8.png
https://i.imgur.com/3r0cOmF.png

If I click "Yes", the same menu pops up again and again, in an infinite loop.

This error has made it impossible for me to connect to my own mumble server, and a few Public servers that aren't using SSL - I have tried a few.

Platform: Arch Linux
Version: 1.3.0

I have not had this issue on previous versions of mumble.

**Comment by MindfulProtons** [comment] 2018-05-30 00:06
I have the same issue on self-signed certificates.

**Comment by Natenom** [comment] 2018-05-30 07:16
This is a duplicate of #3411

**Closed by Natenom** 2018-05-30 07:16 UTC

**Comment by ErikKalkoken** [comment] 2020-07-31 21:15
If anyone else stumbles over this. I had the same issue with one of my users and this solution works: https://sourceforge.net/p/mumble/discussion/492607/thread/f5ae21aa/

The issue is caused by a problem wth writing to the SQLite DB on the users's Windows machine.
The solution is 
1. Close Mumble client
2. Navigate to: `https://sourceforge.net/p/mumble/discussion/492607/thread/f5ae21aa/` and then remove `mumble.sqlite`. 
3. Restart Mumble client. (It will create a new one on startup)
