### ISSUE TITLE
Missing audio for wireless headset (mumble only fault)

### ISSUE THREAD

**Issue by mumble-voip** [mumble-voip/mumble#984] opened 2013-05-03 03:34 UTC
There is an issue with audio support for my wireless headset (noname).

No audio is transmitted in either direction.

I have the following details available:

Unit-manager info:
    USB\VID_0451&PID_16BB&REV_0001&MI_00
(Listed as General USB audio)

I believe it is a Texas instruments (VID_0451) SoC device, probably a PurePath device:
http://www.ti.com/paramsearch/docs/parametricsearch.tsp?family=wireless&familyId=936&sectionId=646&tabId=2736&uiTemplateId=WLS_PRDSRCH_T

Also the following probably points to the problem:

```
<W>2013-05-02 21:51:21.553 AudioInput: 40000 bits/s, 48000 hz, 480 sample 
<W>2013-05-02 21:51:21.555 WASAPIInput: Latencies 100000 30000 => 100000
<W>2013-05-02 21:51:21.555 WASAPIInput: Mic Subformat is not IEEE Float: hr=0x00000000
<W>2013-05-02 21:51:21.557 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2013-05-02 21:51:21.557 WASAPIOutput: Subformat is not IEEE Float: hr=0x00000000
<W>2013-05-02 21:51:27.159 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2013-05-02 21:51:27.160 WASAPIInput: Latencies 100000 30000 => 100000
<W>2013-05-02 21:51:27.160 WASAPIInput: Mic Subformat is not IEEE Float: hr=0x00000000
<W>2013-05-02 21:51:27.161 WASAPIOutput: Latencies 101587 30000 => 100000
<W>2013-05-02 21:51:27.171 WASAPIOutput: Stream Latency 116100 (2646)
<W>2013-05-02 21:51:27.171 WASAPIOutput: Periods 10158us 3000us (latency 11610us)
<W>2013-05-02 21:51:27.171 WASAPIOutput: Buffer is 60000us (5)
<W>2013-05-02 21:51:27.172 AudioOutput: Initialized 2 channel 44100 hz mixer
```

The device works for other sources (battlefield: bad company 2, system sounds etc.)

_This ticket has been migrated from sourceforge. It is thus missing some details like original creator etc.
The original is at https://sourceforge.net/p/mumble/bugs/984/ ._

**Comment by Krzmbrzl** [comment] 2020-01-15 17:52
If they worked with "Vista compatibility", I assume the problem is either fixed by now or is simply outdated.
If this isn't the case, feel free to reopen this issue

**Closed by Krzmbrzl** 2020-01-15 17:52 UTC
Labels: mumble, windows
