### ISSUE TITLE
1.4 appimage not working??

### ISSUE THREAD

**Issue by huizichin** [mumble-voip/mumble#4341] opened 2020-07-03 05:56 UTC
```
huizichin@huizichin-Latitude-E4310:~/Downloads/AppImage$ ./Mumble-5e65ac56-x86_64.AppImage
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function SSLeay
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
<W>2020-07-03 14:19:08.322 QSslSocket: cannot call unresolved function SSLv23_client_method
<W>2020-07-03 14:19:08.323 QSslSocket: cannot call unresolved function sk_num
Segmentation fault (core dumped)
```

i am using xubuntu

**Comment by TerryGeng** [comment] 2020-07-03 06:15
I think you'd better post the version (the commit id) of the app image you downloaded from Azure and the version of your Linux distro.

**Comment by huizichin** [comment] 2020-07-03 06:21
i tried multiple release 
this is the one i am using: https://dev.azure.com/Mumble-VoIP/Mumble/_build/results?buildId=2131&view=results
linux version: Xubuntu 20.04 LTS

**Comment by Krzmbrzl** [comment] 2020-07-03 06:55
Duplicate of #3959

**Closed by Krzmbrzl** 2020-07-03 06:55 UTC
