### ISSUE TITLE
Setting minimum volume to 0% doesn't seem to work

### ISSUE THREAD

**Issue by dustydesigner** [mumble-voip/mumble#6149] opened 2023-06-15 00:59 UTC
### Description

When setting minimum volume to 0, I can still hear people very slightly no matter where I'm at. I've tried restarting Mumble, reinstalling Mumble and changing headphones. I know proximity sound works as people get quieter when I get further away, but I can still hear them no matter how far. Everyone else using Mumble seems to work just fine

For reference I'm testing this with 7 Days to Die and the link plugin.

### Steps to reproduce

This bug just happens no matter what I do.

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by rish1602** [comment] 2023-06-21 09:09
hi @dustydesigner 
Im new to open source and want to contribute by resolving this isssue. 
I can have a look at the issue and will update you if its resolved.

**Comment by Hartmnt** [comment] 2023-06-21 10:22
@rish1602 Hi, thanks for your interest in contributing to Mumble.

Before starting to work on a fix, could you try to reproduce the issue first and report back to us?
It would be nice to know how to trigger this bug and under what conditions.
I would be sad, if you wasted time on this and it turns out the issue is not reproducible :)

**Comment by rish1602** [comment] 2023-06-21 10:36
sure let me check and I will get back :)

**Comment by Krzmbrzl** [comment] 2023-10-06 06:56
After having dug around in the code a bit, I am almost certain that this is caused by #5094 as the code introduced there limits the minimal volume to a minimum of 0.05 while computing the gain:
https://github.com/mumble-voip/mumble/blob/0310159a93e64b1bc0573d52fe2c90d7d40902b2/src/mumble/AudioOutput.cpp#L121-L123
and additionally, the computed gain is again limited to a minimum value of 0.05 here:
https://github.com/mumble-voip/mumble/blob/0310159a93e64b1bc0573d52fe2c90d7d40902b2/src/mumble/AudioOutput.cpp#L668-L673

**Comment by Hartmnt** [comment] 2023-10-06 08:35
> After having dug around in the code a bit, I am almost certain that this is caused by #5094 as the code introduced there limits the minimal volume to a minimum of 0.05 while computing the gain:
> 
> https://github.com/mumble-voip/mumble/blob/0310159a93e64b1bc0573d52fe2c90d7d40902b2/src/mumble/AudioOutput.cpp#L121-L123

Mhh, the first code snipped sets a minimum for the **maximum distance volume**. I think ``calcGain()`` is not broken and reaches ``0`` in the right conditions.

> and additionally, the computed gain is again limited to a minimum value of 0.05 here:
> 
> https://github.com/mumble-voip/mumble/blob/0310159a93e64b1bc0573d52fe2c90d7d40902b2/src/mumble/AudioOutput.cpp#L668-L673

This seems to be the real culprit. But the intention is probably still desirable for cases where the minimum distance volume is **NOT** set to ``0`` by the user. So I would say, we add a conditional path: We keep the line as is for the minVol > 0 case, and calculate ``svol[s] * calcGain(dot, len) * volumeAdjustment;`` for the minVol == 0 case.

**Comment by Krzmbrzl** [comment] 2023-10-06 08:41
> Mhh, the first code snipped sets a minimum for the maximum distance volume. I think calcGain() is not broken and reaches 0 in the right conditions.

Which what should be able to be zero. However, due to the exponential fadeoff it can get very close to zero, but not quite (except dud to numerical imprecision)

> But the intention is probably still desirable for cases where the minimum distance volume is NOT set to 0 by the user.

Indeed. Or more generally: in all cases in which the gain is not zero. If it is zero, it should be zero, I think :thinking:

**Comment by Hartmnt** [comment] 2023-10-06 08:43
Arrgh im getting confused by (minimum|maximum) distance vs volume...

**Comment by Krzmbrzl** [comment] 2023-10-06 12:15
Haha, yeah that always trips me as well ^^

**Comment by Hartmnt** [comment] 2023-10-06 22:48
In ``calcGain`` I think this is the relevant code path that is used if the distance >= maxDistance
https://github.com/mumble-voip/mumble/blob/0310159a93e64b1bc0573d52fe2c90d7d40902b2/src/mumble/AudioOutput.cpp#L118-L120

While the quoted code path is used if distance < maxDistance
https://github.com/mumble-voip/mumble/blob/0310159a93e64b1bc0573d52fe2c90d7d40902b2/src/mumble/AudioOutput.cpp#L120-L128

So calcGain should work and return ``0`` after all, no?

The calcGain function was also not touched by #5094

**Comment by Hartmnt** [comment] 2023-10-06 23:16
I am still puzzled by this comment
https://github.com/mumble-voip/mumble/blob/0310159a93e64b1bc0573d52fe2c90d7d40902b2/src/mumble/AudioOutput.cpp#L668-L669
It sounds like a good idea, but it seems to be incorrectly implemented (as in causing our bug)
I would say the intention is good, but you would have to pre-compute the gain for all channels, and only apply the ``1/20`` part if the gain for any channel (ear) is larger than 0, right?
With the current implementation I do not see how this code does take different channels (ears) into account.

**Comment by Krzmbrzl** [comment] 2023-10-07 06:58
> So calcGain should work and return 0 after all, no?
> The calcGain function was also not touched by https://github.com/mumble-voip/mumble/pull/5094

Oh. Yes, you are correct.

>  It sounds like a good idea, but it seems to be incorrectly implemented (as in causing our bug)

I think the implementation matches the comment exactly, but the comment doesn't take into account that there is the possibility that the incoming audio has a gain of zero on all channels and should therefore indeed not be heard at all.

> I would say the intention is good, but you would have to pre-compute the gain for all channels, and only apply the 1/20 part if the gain for any channel (ear) is larger than 0, right?
With the current implementation I do not see how this code does take different channels (ears) into account.

Yes, I think that should to the trick. However, I think  we could probably get away with doing the distance check first and if the distance > maxDistance and the minVolume for maxDistance == 0, then we can apply the 1/20 trick. Otherwise, we can essentially skip the entire audio packet as its volume will be zero.

Another thing that might be worth to take into account is that in cases where the distance-reduced volume is <= 1/20, simply adding 1/20 is probably not what we want either as this seems to boost the volume above the desired levels. I think the constant part being added should probably be a fraction of the maximum possible volume (taking into account the distance, but not the direction to the audio source).

**Comment by Hartmnt** [comment] 2023-10-09 22:05
> Another thing that might be worth to take into account is that in cases where the distance-reduced volume is <= 1/20, simply adding 1/20 is probably not what we want either as this seems to boost the volume above the desired levels. I think the constant part being added should probably be a fraction of the maximum possible volume (taking into account the distance, but not the direction to the audio source).

I am pondering about the second part and I am trying to visualize ``calcGain`` in my head. What confuses me right now is the normalization:
https://github.com/mumble-voip/mumble/blob/master/src/mumble/AudioOutput.cpp#L96-L102
Why is it done this way?
Naively, I would have expected to have a positive dotfactor for a dotproduct of 1 (coming straight from the right side) and also for a dotproduct of -1 (coming staight from the left side), while having no dotfactor for a dotproduct of 0 (coming straight from front or back)
However, the normalization forces the conversion ``-1 (left) -> 0`` ``1 (right) -> 1`` and ``0 (front/back) -> 0.5``. This seems... wrong? Should the normalization not be ``abs(dotproduct)``? We are using the coordinates of the "listener" and the "sender" here, right? Am I missing something?

**Comment by Krzmbrzl** [comment] 2023-10-11 11:15
I think the normalization logic is that if the sound comes from a source completely opposite the speaker's position, then letting that audio play through that speaker would play the audio from the wrong direction.
So if you have something like
|speaker ->|    |player|   <-----   | audio source |
where `->` indicates the direction into which the speaker will emit audio and `<------` indicates the direction of audio from the source to the player
then playing the audio through that speaker would make the audio come from the wrong direction. This situation is characterized by the direction of the speaker and the direction of sound being antiparallel, meaning their dot product equals -1.

Note however, that this is just a theory that would make sense (imo) for explaining the code and not an actual "that's why it _has to be_ that way" argument. Aka: it should probably be tested that this indeed correct.

On another note though: Shifting the dot product by a constant amount after renormalization would automatically deal with the "let all ears hear at least some volume" feature in a much more elegant way than that 1/20 + 19/20 approach in the current code, wouldn't it?

**Closed** 2023-10-25 06:55 UTC
Labels: client, positional audio, bug, good first issue
