### ISSUE TITLE
Phonetic Nickname option

### ISSUE THREAD

**Issue by arukaen** [mumble-voip/mumble#2210] opened 2016-04-21 15:52 UTC
## Feature Request

It would be nice for users who have "complicated," or "funny," nicknames to be able to setup the TTS engine to pronounce it correctly.

**Comment by Enigma0** [comment] 2016-04-21 19:19
This would be amazing.

**Comment by Tarun80** [comment] 2016-04-21 19:21
Been wanting this ever since we changed from Ventrilo many years ago.

**Comment by Kissaki** [comment] 2016-05-01 12:48
What do you think the implications for trolls misusing it would be?
What prevents anyone from specifying the phonetic name of a different user?
That could become very confusing.

**Comment by Kissaki** [comment] 2016-05-01 12:51
See also previous feature request tickets:
* [SF FR 630](https://sourceforge.net/p/mumble/feature-requests/630/)
* [SF FR 79](https://sourceforge.net/p/mumble/feature-requests/79/)

**Comment by mkrautz** [comment] 2016-05-01 12:51
@Kissaki That's just people being jerks. You could already do that now, by picking a name that sounds like someone else's.

The problem with phonetic names is that we support various different platforms, but we use different TTS engines on each of them. And our users have different language settings.

So, even if we did add a phonetic nickname, that nickname wouldn't be pronounced the same across the board either way.

So I don't see it as being particularly useful.

I'd like to hear people's thoughts on these issues.

**Comment by Kissaki** [comment] 2016-05-01 18:13
But, isn’t that the TTS engines being wrong then?
The phonetic name is there to declare how it is pronounced. If the TTS differs, are they/some wrong? Or is it that phonetic is not clear enough?

**Comment by mkrautz** [comment] 2016-05-01 19:02
I believe most of these feature requests are for a feature like "phonetic nickname" like in Ventrilo.
In Ventrilo, you give it a "phonetic nickname", which just means "replace my name with this when you say it via PTT". (At least that's my understanding of the feature -- I might be wrong!)

So there's nothing really "phonetic" about it. It's just that PTT engines are too stupid to pronunce "1337h4x0r", so you'd use "leet hacksaw" as your phonetic nickname. (Which would definitely be pronunced differently in en_US vs. de_DE, for example.)

**Comment by mkrautz** [comment] 2016-05-01 19:05
...But maybe that's good enough (this is, as of this writing, our most +1'd feature request). :-)

Any thoughts from onlookers?

**Comment by hacst** [comment] 2016-05-01 19:12
I argued against this in the previous SF FRs: It's technically unclean (as you said it works around quirks of a single TTS engine/voice and is a prime trolling target) and yet another setting in the UI. However seing as it keeps coming up and people on a single server being pretty likely to use the same TTS engine anyways I wouldn't try to prevent anyone from adding it now. Can't say I'm thrilled about "yet another mysterious setting" and the trolling potential though.

**Comment by synapse84** [comment] 2016-05-03 10:06
Since the main issue seems to be trolling, could this be added as a server set thing instead?

In my opinion it should work something like this:
1. Users would NOT be able to set their own phonetic. This is simply too easy to troll servers with.
2. Admins set the user's phonetic in the Registered Users list. It's out of the way and could be added to the context menu next to 'Rename' and 'Delete'.
3. Users should be able to _locally_ override the server set ones. Just an entry in the right click context menu when users right click on other users.

I use a different name for my testing, but I feel it fits this well. "Raefon".

**Comment by synapse84** [comment] 2016-05-03 10:18
Since the main issue seems to be trolling, could this be added as a server set thing instead?

In my opinion it should work something like this:
1. Users would NOT be able to set their own phonetic. This is simply too easy to troll servers with.
2. Admins set the user's phonetic in the Registered Users list. It's out of the way and could be added to the context menu next to 'Rename' and 'Delete'.
3. Users should be able to _locally_ override the server set ones. Just an entry in the right click context menu when users right click on other users.

Unfortunately TTS engines are different, so consistency is improbable. I use a different name for my testing, but I feel it fits this well. "Raefon".
Windows: "Reefon".
Linux (espeak): "Reefon"
Both are wrong. Usually Windows has the majority of users, so a Windows admin would likely set it to 'Rayphon'. This would likely fix it for most people, but say a Linux or Mac user connects, they may want to override it to match espeak/whatever mac uses.

**Comment by Tarun80** [comment] 2016-05-04 17:55
I believe a user could be allowed to set their own phonetic. Have it so they cannot change it once they've been registered, an admin has to change it. Having to seek out an admin to change the phonetic puts a lot of work onto the admins which seems unnecessary. Additionally, servers can control it by having a regex as well to help prevent abuse.

**Comment by hacst** [comment] 2016-05-04 20:33
The usual precautions would be similar to what we already have for tts I think:

- User (and maybe server) side length limit
- User-side (and server-side) option to completely switch off phonetic nicknames

Additionally admins should be able to:

- edit and reset
- block someone from using them (either personally or via ACL)

As I said. This feature if implemented properly won't make the UI any simpler ;)

**Comment by Tarun80** [comment] 2016-05-04 22:47
@hacst - would a regex in the murmur.ini also be added to allow for server control of what is and is not allowed?

I would find it a welcome addition. The reason is because on my server I made a regex to limit names to one uppercase or lowercase, and then lowercase letters, and then again, one upper and a few lowercase. That means JohnSmith, johnSmith, and Johnsmith would all be accepted

**Comment by synapse84** [comment] 2016-05-05 13:45
@Tarun80 In an ideal world I would agree with letting users set their phonetic. But I feel regular users either wouldn't set it, wouldn't set it correctly, or would set it to useless things (trying to be witty or clever, referencing memes, using other peoples names, etc..). This would result in more admin work.

Instead with the way I mentioned above.. It would simply default to the user's name like it currently is and if the TTS engine says it wrong the admin could simply overwrite it. No complicated and useless regex required, just a competent admin. The benefits of this is you could allow users like "1337h4x0r" to keep his name that he uses for everything else, while at the same time telling TTS to say "leet hacks or" instead.

**Comment by hacst** [comment] 2016-05-06 19:24
@Tarun80 Maybe we would add one just because we'll want some basic limitations anyways. Not sure changing it would be useful though. Phonetic nicks by design can look crazy to get the TTS engine to do what you want.

@synapse84 If the users can't choose them themselves that would severly limit their usefulness. I doubt admins on big servers can be bothered to tweak tons of users phonetic name just right (TM). Then again what do I know about big servers so if someone dealing with those has an opinion I would be quite interested ;)

**Comment by mkrautz** [comment] 2016-05-11 08:56
From mumble-voip/mumble#2254, I said:

> I suppose if we implemented phonetic nicknames (#2210) we would implement a phonetic serve name as well.
> Also phonetic channel names?

**Comment by synapse84** [comment] 2016-05-11 13:09
@hacst I've thought about this a bit over the past few days and I agree. It would limit their usefulness. (Though I could debate for days on just how "_useful_" they are in the first place.)

So, I propose a setting to allow/deny client phonetics entirely.

Something like this:

**Allow**: Users would be allowed to set their phonetic, set phonetics could however still be overwritten/edited/reset by an admin if needed.

**Deny**: Users could still set a phonetic, but it would act more as a 'suggestion' until it's accepted by an admin. Until then the default behavior would be to read off the user's name. The benefit of this is it allows a user to suggest their own phonetic, while letting the admin decide if it's a good phonetic replacement. (e.g. "1337h4x0r" connects with a suggested phonetic of "leet hacks or", an admin hears it pronouncing it wrong and thus can see there's already a suggested phonetic and could simply accept it.)

Just something I was thinking about. Maybe I still missed the point, but I'd prefer if server admins have control over things like this.

**Comment by eligrey** [comment] 2016-05-11 13:24
I'm completely for this idea, with server admins in control, as long as we also get phonetics for channels (including the root channel).

**Comment by arukaen** [comment] 2016-05-11 15:48
I think having server admins approve things is much more work than is really needed for any server admin. Any options that impede on the user's ability to spam the phonetic should be handled via server config.

**Comment by synapse84** [comment] 2016-05-11 22:05
smh.Does nobody remember Ventrilo? I can't believe I even have to 

@arukaen Considering most servers I've connected to are ~5-30 members, I don't consider it that much extra work.

**Comment by DGMurdockIII** [comment] 2017-05-22 19:19
This would be very useful

**Comment by Tobeus** [comment] 2019-01-17 23:48
I know this is really old, but I would think the solution would be client-side phonetics individualized to each user for OTHER users.  So as a user, I would set a phonetic nickname for each person on my server that I wanted to clarify so I know who each person is logging in.  This should not be set on the server side.  This should not be set on the user side for everyone else.  I need to set what I want to hear when someone else logs in.  Then no spoofing, no trolls, etc.  Just clarity for me. -Cheers!

**Comment by Krzmbrzl** [comment] 2020-03-03 09:24
Closing this one in favor of the more general request in #3974

**Closed by Krzmbrzl** 2020-03-03 09:24 UTC
Labels: feature-request
