### ISSUE TITLE
URLs aren't properly decoded

### ISSUE THREAD

**Issue by paxswill** [mumble-voip/mumble#1275] opened 2014-05-30 06:07 UTC
When clicking a url like [mumble://mumble.braveineve.com/BRAVE%20Public%20Comms%20%5BOPEN%5D/HERO%20Addresses/Speakers?title=Brave%20Collective&version=1.2.0](mumble://mumble.braveineve.com/BRAVE%20Public%20Comms%20%5BOPEN%5D/HERO%20Addresses/Speakers?title=Brave%20Collective&version=1.2.0) with encoded [ or ] characters, the log seems to indicate that Mumble isn't decoding them properly:

    [2:02] Opening URL mumble://mumble.braveineve.com/BRAVE Public Comms %5BOPEN%5D/BRAVE - Lobby %5BEVE%5D?title=Brave Collective&version=1.2.0

Note only the brackets remain encoded.

I've verified that if I create a URL (via the contextual menu) to a channel whose path doesn't include special characters, the URL works as expected. Others have told me that  special characters work on their systems, so it seems to point to an OS X specific problem. I'm running 10.9.2 (will upgrade to 10.9.3 eventually), and am normally running  Mumble 1.2.6. I also tested against the gf91386b snapshot and the problem is present there as well.

**Comment by mkrautz** [comment] 2016-07-08 16:32
Can't reproduce with latest snapshots on OS X.

1.2.16 still does not work.

**Comment by mkrautz** [comment] 2016-07-08 16:33
Re-assigned to 1.2.17... I believe this was a Qt bug, and was fixed by upgrading Qt.

It works in recent snapshots.

**Comment by mkrautz** [comment] 2016-07-09 12:20
If anyone is still listening in on this, I'd like to know if anyone still has issues with this with the latest snapshot?

As I said yesterday, I haven't been able to reproduce.

Snapshot:
http://mumble.info/snapshot/Mumble-1.3.0~1434~g6a78217~snapshot.dmg

**Comment by mkrautz** [comment] 2016-09-21 19:26
From what I can tell, this is simply a display bug.

The URL shown in the log in 1.2.x is wrong on OS X.
But the values returned by QUrl::path() (for example) are correctly unescaped.

Closing...

**Closed by mkrautz** 2016-09-21 19:26 UTC
Labels: macOS, mumble
