### ISSUE TITLE
windows 10 anniversary update (x64) PTT not working with Xbox Controllers

### ISSUE THREAD

**Issue by andrew166** [mumble-voip/mumble#2483] opened 2016-08-03 22:58 UTC
Hi,

I have installed a clean copy of Windows 10 Anniversary Update x64 (aka Version 1607) and installed Mumble 1.2.16 the Push-to-talk function works fine with mouse and keyboard bindings, but the Xbox One Controller using both Wireless and USB only works while mumble has focus. As soon as mumble is minimised or another application opened (i.e. a game, word, notepad etc) the binding from the Xbox controller no longer registers the PTT button binding, only by re-selecting mumble will the PTT work.

Things i have done:

Run Mumble as administrator - does not work 
Clean installation of Windows 10 Version 1607 x64 only installing mumble - does not work 
Tested on my laptop with a clean Windows 10 Version 1607 x64 installation - does not work 
Tested mumble-1.3.0-1492-g2f88605-snapshot - does not work (also tested using admin)

Note: The game-pad binding worked fine under Windows 10 November Update (aka Version 1151)

**Comment by mkrautz** [comment] 2016-08-03 23:27
Seems like our DirectInput filtering doesn't work in 1607:

	<W>2016-08-04 01:25:07.649 XboxInput: using XInput DLL 'XInput1_4.dll'
	<W>2016-08-04 01:25:07.649 XboxInput: using XInputGetStateEx() as querying function.
	<W>2016-08-04 01:25:07.649 GlobalShortcutWin: XboxInput initialized, isValid: 1
	[...]
	<W>2016-08-04 01:25:07.908 Adding device {251a19c0-59e1-11e6-8001-444553540000} Controller (Xbox One For Windows) Controller (Xbox One For Windows):11 type 0x00010215

The controller is using DirectInput instead of XInput.

**Comment by andrew166** [comment] 2016-08-03 23:34
It works fine when mumble has focus (not sure if this helps). If you need any diag data from my machine please let me know.

**Comment by mkrautz** [comment] 2016-08-04 00:37
Hi,

A workaround for this is available at https://github.com/mumble-voip/mumble/pull/2484, pending code review.

No known workaround for 1.2.16 for now, I'm afraid.

**Comment by Tarun80** [comment] 2016-08-04 04:57
What button did you assign on the XBox controller? I have XBox1:LeftShoulder and it works fine.

**Comment by mkrautz** [comment] 2016-08-04 06:36
@Tarun80 Interesting.

The problem for me, and presumably @andrew166 is that our code that filters XInput devices from being picked up by the DirectInput backend didn't work.

@Tarun80

Are you by any chance using a 360 pad, and *not* a One pad? 360 pads are hardcoded in the detection logic, and work as before. So, the issue as @andrew166 reports, is only visible on non-360 XInput devices.

...and of course, you are on the Annversary Update, correct @Tarun80?

Thanks!

**Comment by mkrautz** [comment] 2016-08-04 07:18
(Yours is correctly uses via XInput because the button name is XboxN:????)

**Comment by Tarun80** [comment] 2016-08-04 19:34
Yes, running Windows 10 Pro x64 Anniversary Update. Controller is Xbox 360 Controller. It's also wired, not wireless.

**Comment by mkrautz** [comment] 2016-08-04 19:57
OK, cool. That *should* indeed still work, since the GUIDs for Xbox 360 controllers are well known in the XInputCheck library.

**Comment by andrew166** [comment] 2016-08-04 20:45
Why is the issue been closed? (is it because the bug is known elsewhere?) or has a fix been issued

**Comment by mkrautz** [comment] 2016-08-04 20:46
I pushed a fix to Git.

**Comment by andrew166** [comment] 2016-08-04 20:47
can this be complied and downloaded as an exe?

**Comment by mkrautz** [comment] 2016-08-04 20:47
Yes, I'll trigger a snapshot soon!

**Comment by andrew166** [comment] 2016-08-04 20:48
can you please post a comment here when you do?

Many Thanks

**Comment by mkrautz** [comment] 2016-08-04 21:32
Yep, will do.

**Comment by mkrautz** [comment] 2016-08-05 00:11
@andrew166 New snapshots that include the workaround for this are available on the front page of mumble.info: http://wiki.mumble.info/wiki/Main_Page

1.3.0~1500~g8bdfd7d~snapshot

**Comment by andrew166** [comment] 2016-08-05 18:21
sadly mumble-1.3.0-1500-g8bdfd7d-snapshot did not fix the issue. As before the control works when the application has focus but as soon as it looses focus the PTT button on the Xbox one controller no longer works

**Comment by mkrautz** [comment] 2016-08-06 10:15
Hi, I'm re-testing this on my end.

Meanwhile, could you perhaps provide a Mumble log of a session where you run Mumble with the controller connected? You can get your to your full log at %APPDATA%\Mumble\Console.txt. You can look at the timestamps to find the lines that represent the Mumble session you're submitting a log for, and copy/paste the log output to a gist (gist.github.com) or a pastebin somewhere. Feel free to remove any content in there that contains personal information, if any.

Also, is it a wireless, wired or Bluetooth controller? Is it an official Microsoft controller, or a third-party Xbox One controller? Thanks.

**Comment by mkrautz** [comment] 2016-08-06 10:21
The 1.3.0~1500~g8bdfd7d~snapshot fixes it for me with official Xbox One controllers, wireless/wired/bluetooth.

The way we worked around the issue was to hard-code the Xbox One controller line as well-known controllers to a part of the code that detects whether the controllers are XInput devices.
The low-level check doesn't work on Windows 10 Anniversary, so it's falling back to just checking the list of well-known devices.

So if your device isn't an official controller, it might not be detected by the well-known list.

**Comment by andrew166** [comment] 2016-08-06 10:52
Hi,

I am using an official Xbox controller (came with my Xbox) with the official Xbox wireless adapter

http://www.xbox.com/en-GB/xbox-one/accessories/controllers/windows-10-wireless-adapter

**NOTE: the controller is the Xbox Elite Wireless Controller (not sure if this makes a difference

Do i need to manual delete any files when installing the 1.3.0~1500~g8bdfd7d~snapshot as i simply uninstalled using control panel and then installed the  1.3.0~1500~g8bdfd7d~snapshot

**Comment by mkrautz** [comment] 2016-08-06 10:58
No, no need to do that. I'll test with an Elite controller, hold on.

Please submit a log of a session where you run Mumble with the controller connected as described above. Thanks!

**Comment by andrew166** [comment] 2016-08-06 10:59
Okay the i have tested using the USB connection, and this works but the Xbox wireless adapter does not work.

Interestingly when i am using the controller via USB the shortcut column displays Xbox1:Back but with the Wireless adapter it displays Controller (Xbox One For Windows);.....

**Comment by mkrautz** [comment] 2016-08-06 10:59
Yes, it seems like the Elite has a different GUID in wireless mode.

**Comment by mkrautz** [comment] 2016-08-06 11:00
BTW, no need to submit your log -- I can reproduce on my end. :-)

**Comment by andrew166** [comment] 2016-08-06 11:01
OK, thanks for your help with this

**Comment by mkrautz** [comment] 2016-08-06 12:39
PR is available here: https://github.com/mumble-voip/mumble/pull/2489

I'll update the issue once we have a snapshot with a fix released. :-)

**Comment by mkrautz** [comment] 2016-08-06 20:17
@andrew166 1.3.0~1508~ge7ff17b~snapshot now available.

**Comment by andrew166** [comment] 2016-08-06 20:59
Great job :) that has fixed the issue. Many Thanks

**Comment by mkrautz** [comment] 2016-08-07 09:41
Excellent, will close now.

It seems like this is indeed a bigger issue:

Windows 10 Feedback Hub thread:
feedback-hub:?contextid=341&feedbackid=d4d0b4e9-35c2-4e7b-aa7a-513a81cd6f6a&form=1&src=2

Xbox Support thread:http://forums.xbox.com/xbox_support/xbox_on_windows_support/f/5412/p/2195680/5717060.aspx

So presumably Microsoft will fix it soon...

**Closed by mkrautz** 2016-08-07 09:41 UTC
Labels: mumble, windows

**Comment by WesCook** [comment] 2016-08-18 04:46
Thanks so much for the fix, @mkrautz.  And you for reporting it, @andrew166.  I've been trying black magic like installing hacky playstation drivers to try to fix this issue.  Using the snapshot now and everything is a dream.  Thanks!
