### ISSUE TITLE
No system tray icon on KDE when connected to a server

### ISSUE THREAD

**Issue by tgurr** [mumble-voip/mumble#3124] opened 2017-06-07 19:07 UTC
Mumble 1.3 (git master) doesn't show the mouth systray icons (or any icon at all) after connecting to a server when running under KDE Plasma 5.10.1, please see the attached screenshots.

Before connecting to a server:
![mumble-gitmaster-disconnected](https://user-images.githubusercontent.com/414984/26896447-15ac2e70-4bc5-11e7-8365-9638e5e36556.png)

After connecting to a server:
![mumble-gitmaster-connected](https://user-images.githubusercontent.com/414984/26896445-13256ab8-4bc5-11e7-8438-36eab19353be.png)

**Comment by davidebeatrici** [comment] 2017-06-07 19:11
What operating system are you using? Qt version?

I have encountered the same issue, on Debian Stretch with KDE Plasma 5.8.6 and Qt 5.7.1.
It seems like a Qt bug, because using QPixmap instead of QIcon fixes it.

**Comment by tgurr** [comment] 2017-06-07 19:17
Currently I've Qt 5.8.0 installed, Exherbo Linux 64bit.

**Comment by mkrautz** [comment] 2017-06-12 07:12
The problem is that Plasma uses the DBus system tray spec, with ARGB images inline.
I'm not sure what GNOME3 uses, but Unity also uses the system tray spec -- but Qt uses temporary files for the images for Unity.

Anyway, the problem is that Qt's DBus marshalling for SVG images is broken.

See https://bugreports.qt.io/browse/QTBUG-53550

Basically, since SVGs return an empty list for availableSizes, no icons will be shown in the tray for SVGs.

I'm currently preparing a patch that I can submit to upstream Qt to fix this, but you could probably do something like

  if (sizes.isEmpty()) {
      sizes << QSize(64, 64);
  }

as a hack for now in your .ebuild if you want a workaround?

**Comment by mkrautz** [comment] 2017-06-12 07:20
Actually, scratch that... I don't think that's correct...

The code already has similar fallbacks:
https://github.com/qt/qtbase/blob/71264bae08d81bdeceb96133fdb01c370504dfcc/src/platformsupport/themes/genericunix/dbustray/qdbustraytypes.cpp#L87-L90

So I don't think it's that...

(Yeah, I still hadn't gotten to testing this... Oops!)

**Comment by peylight** [comment] 2017-06-13 12:13
Hi Guys,
I have no system try icon in the [kubuntu 17.04](http://www.kubuntu.org/) when i use [Mumble Snapshot PPA](https://launchpad.net/~mumble/+archive/snapshot) (1.3.0~2424~gd66eeeb~snapshot-1~ppa1~zesty1)
The problem is only in mumble 1.3.0 not in mumble 1.2.x

**Comment by mkrautz** [comment] 2017-06-13 19:51
Turns out this is already fixed in Qt 5.10... Let's diff...

**Comment by kpande** [comment] 2017-11-01 21:01
qt 5.9 has this issue with both the 1.2.19 release or the qt5 build

**Comment by davidebeatrici** [comment] 2017-11-12 20:29
Also Qt 5.9.1, the workaround is to use QPixmap instead of QIcon.

**Comment by davidebeatrici** [comment] 2017-11-29 17:02
It's probably this bug: https://bugreports.qt.io/browse/QTBUG-53550

**Comment by mkrautz** [comment] 2018-03-03 00:59
Removing upstream-bug-reported. We didn't report an upstream bug for this.

**Closed** 2018-03-18 16:19 UTC
Labels: Qt, linux, mumble, priority/P1 - Critical, ui, upstream-bug
