### ISSUE TITLE
Mumble macOS keeps asking for access to control apps

### ISSUE THREAD

**Issue by iammeat** [mumble-voip/mumble#3917] opened 2019-12-18 18:42 UTC
Mumble 1.3.0 on macOS Mojave 10.14.6 continually asks me to grant permission to allow it control of many of my normal apps.  Most of the apps in question have nothing to do with Mumble, so this is pretty irritating when it does this 40 or 50 times a day.

![image](https://user-images.githubusercontent.com/6379227/71113626-e6a3f480-21c5-11ea-9f64-45be7b0b0aee.png)

**Comment by davidebeatrici** [comment] 2019-12-18 18:44
Duplicate of #3552.

**Closed by davidebeatrici** 2019-12-18 18:44 UTC
