### ISSUE TITLE
Release portable versions for Linux

### ISSUE THREAD

**Issue by trymeouteh** [mumble-voip/mumble#5792] opened 2022-08-12 05:05 UTC
### Context

Releasing a portable version of client and server for Linux.

### Description

Please release portable builds of Mumble client and Mumble server for Linux. An AppImage for the Mumble client would be ideal and a portable tarball or zip version for the Mumble server (Murmur).

### Mumble component

Both

### OS-specific?

Yes

### Additional information

Windows users have the ability to download the installers for Mumble client and server which allows them to download the EXE installer and install the client and server offline and backup the EXE installers. Mumble makes for a good communication app and service over mesh networks and having the ability to backup the client and server is essential if the internet goes down to deploy Mumble.

**Comment by Krzmbrzl** [comment] 2022-08-12 08:04
Duplicate of #4659 and #5693

To summarize: We used to have an AppImage but it broke and we didn't figure out how to fix it. And for the static server binary: we no longer have the infrastructure to create those and with the new build system nobody has yet figured out how to do a static build.
As an alternative, we suggest using the official Docker image.

**Closed by Krzmbrzl** 2022-08-12 08:04 UTC
Labels: feature-request, triage
