### ISSUE TITLE
1.3 client hangs on start

### ISSUE THREAD

**Issue by colcrunch** [mumble-voip/mumble#3700] opened 2019-06-03 04:15 UTC
OS: Windows 10 Build 1809

When the client starts, it will hang on the first interaction with the connection window. If you close the connection window it will hang on the first interaction with the main client window. This behavior usually lasts 30 seconds to two minutes, after which time I have experienced no issues what so ever with the client.

Here is the output from the debugger: https://pastebin.com/wX0deSiu

Edit: New pastebin link provided

**Comment by colcrunch** [comment] 2019-06-04 06:08
I have been having hangs in normal operation of the client now.

**Comment by davidebeatrici** [comment] 2019-06-04 06:10
Could you paste the console's log, please?

**Comment by Krzmbrzl** [comment] 2020-06-06 16:21
I think this is a duplicate of #3789

**Closed by Krzmbrzl** 2020-06-06 16:21 UTC
Labels: client, windows
