### ISSUE TITLE
Shortcut for a separate "Deafen self (no self-mute)" or "(momentary)"

### ISSUE THREAD

**Issue by jaggzh** [mumble-voip/mumble#5851] opened 2022-09-01 23:26 UTC
### Context

I've been working a lot trying to resolve the echo/feedback I get between our systems.
My recent attempt was just to assign one global shortcut to Deafen self, and one to Push to Talk.
Unfortunately this returns to an earlier issue, that it was decided that Deafen self inherently must also mute oneself to prevent from being disturbing, making this a useless approach for me as well.

### Description

I think we have a generally more technical userbase, but how about either an internal shortcut-mappable function for "Deafen Self (without mute)", or making it only momentary during the key-press (automatically toggling deafen on, then off when the key is released)?  This would resolve the issue of it being left on but the person being heard by others without knowing.

(I haven't yet returned to coding in the "[X] Push to talk deafens self" feature)

### Mumble component

Client

### OS-specific?

No

**Comment by Krzmbrzl** [comment] 2022-09-02 06:29
To my this seems superfluous as we already have #5320. Essentially what you are describing appears to be a manual version of that. I currently don't see a value in having both and when choosing, I'd favor the automatic approach... 👀

**Comment by Krzmbrzl** [comment] 2022-09-16 17:34
Given that there was no objection to my comment, I'll close this as a duplicate of #5320

**Closed by Krzmbrzl** 2022-09-16 17:34 UTC
Labels: feature-request, triage
