### ISSUE TITLE
no audio output after applying settings

### ISSUE THREAD

**Issue by kolAflash** [mumble-voip/mumble#4883] opened 2021-03-24 21:13 UTC
After applying the settings I get no more audio output. Others still hear me.

I don't even get a "speaking" symbol on the others. Except someone is speaking while I'm applying the settings, which results in the speaking symbol getting stuck (but I can't hear that person speaking anymore).

**Steps to Reproduce**
1. Connect to a server.
2. Open the settings.
3. Click "Apply" or "OK" (don't actually change a setting)

&nbsp;

What didn't help:
- disabling echo cancellation
- disabling positional audio
- restarting pulseaudio (`pulseaudio -k`)

&nbsp;

**Desktop (please complete the following information):**
 - OS: Debian 11/Bullseye (Testing / Beta)
 - Version: Mumble and Murmur 1.3.4-1 (by Debian package manager)
   - Also tested Mumble from [FlatHub](https://www.flathub.org/apps/details/info.mumble.Mumble) (same problem)

&nbsp;

Maybe related:
- #3278 _Output cuts out on my end/Input still works_
- #3345 _Mumble freezes audio after settings change under FreeBSD_
- #4679 _Audio isn't working when opening Mumble_

&nbsp;

<details>
<summary>screenshots and logs</summary>

![grafik](https://user-images.githubusercontent.com/3355089/112383793-dd210a80-8ced-11eb-85ed-aebf87825795.png)

![grafik](https://user-images.githubusercontent.com/3355089/112383808-e0b49180-8ced-11eb-8fbf-7734e13d8186.png)

```
$ LANG=C.UTF-8 mumble
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
<W>2021-03-24 21:47:48.373 JackAudioSystem: unable to open client due to 2 errors:
<W>2021-03-24 21:47:48.373 JackAudioSystem: JackFailure - overall operation failed
<W>2021-03-24 21:47:48.373 JackAudioSystem: JackServerFailed - unable to connect to the JACK server
<D>2021-03-24 21:47:49.476 libopus 1.3.1 from libopus.so.0
<W>2021-03-24 21:47:49.477 CELT bitstream 8000000b from /usr/lib/mumble/libcelt0.so.0.7.0
<W>2021-03-24 21:47:49.479 Theme: "Classic"
<W>2021-03-24 21:47:49.479 Style: "Old Style"
<W>2021-03-24 21:47:49.479 --> qss: ":themes/Classic/Classic.qss"
<W>2021-03-24 21:47:49.481 Locale is "C" (System: "C")
<W>2021-03-24 21:47:49.636 Database SQLite: "3.34.1"
<W>2021-03-24 21:47:49.658 Updating application palette
<W>2021-03-24 21:47:49.719 GlobalShortcutX: Using XI2 2.3
<W>2021-03-24 21:47:50.182 AudioInput: Opus encoder set for VOIP
<W>2021-03-24 21:47:50.182 AudioInput: 45000 bits/s, 48000 hz, 480 sample
<W>2021-03-24 21:47:50.183 PulseAudio: Starting input alsa_input.pci-0000_00_14.2.analog-stereo
<W>2021-03-24 21:47:50.183 PulseAudio: Starting echo: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
<W>2021-03-24 21:47:50.184 PulseAudio: Starting output: alsa_output.pci-0000_00_14.2.analog-stereo
<W>2021-03-24 21:47:50.184 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-24 21:47:50.184 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2021-03-24 21:47:50.203 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 1 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-24 21:47:50.204 AudioInput: ECHO CANCELLER ACTIVE
<W>2021-03-24 21:47:51.943 Database SQLite: "3.34.1"
<W>2021-03-24 21:47:51.943 OpenSSL Support: 1 (OpenSSL 1.1.1j  16 Feb 2021)
<W>2021-03-24 21:47:51.982 ServerHandler: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<W>2021-03-24 21:48:02.810 AudioInput: Opus encoder set for VOIP
<W>2021-03-24 21:48:02.810 AudioInput: 45000 bits/s, 48000 hz, 480 sample
<W>2021-03-24 21:48:02.813 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
<W>2021-03-24 21:48:02.816 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 1 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-24 21:48:02.819 AudioInput: ECHO CANCELLER ACTIVE
<W>2021-03-24 21:48:11.092 PulseAudio: Forcibly disconnected from PulseAudio
```
</details>

**Comment by Krzmbrzl** [comment] 2021-03-25 09:22
I _know_ there already is an issue about this. But I just can't seem to find it :/

**Comment by Krzmbrzl** [comment] 2021-03-25 09:32
I am pretty sure this is due to the fact that the audio system is completely stopped and restarted when applying the settings and that this process gets stuck when attempting to doing that.

**Comment by kolAflash** [comment] 2021-03-30 20:31
I've done some tests with my notebook which is running exactly the same Debian system. But I couldn't reproduce the bug on that system. So I guess this might be something related to my hardware setup.
I've tried using an USB sound card on my PC where the bug happens. But that didn't solve the the problem.

&nbsp;

---

&nbsp;

In rare occasions the bug doesn't happen. This is the console output if everything goes fine when applying the settings.
```
<W>2021-03-30 22:09:14.953 AudioInput: Opus encoder set for VOIP
<W>2021-03-30 22:09:14.953 AudioInput: 45000 bits/s, 48000 hz, 480 sample
<W>2021-03-30 22:09:14.954 AudioInput: Initialized mixer for 0 channel 48000 hz mic and 1 channel 48000 hz echo
<W>2021-03-30 22:09:14.957 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 1 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-30 22:09:14.964 AudioInput: ECHO CANCELLER ACTIVE
<W>2021-03-30 22:09:15.173 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2021-03-30 22:09:15.321 QXcbConnection: XCB error: 3 (BadWindow), sequence: 2798, resource id: 16778381, major code: 40 (TranslateCoords), minor code: 0
```

&nbsp;

In constrast, this is the console output when the bug happens.
```
<W>2021-03-30 22:11:10.269 AudioInput: Opus encoder set for VOIP
<W>2021-03-30 22:11:10.269 AudioInput: 45000 bits/s, 48000 hz, 480 sample
<W>2021-03-30 22:11:10.270 AudioInput: Initialized mixer for 0 channel 48000 hz mic and 1 channel 48000 hz echo
<W>2021-03-30 22:11:10.272 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 1 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-30 22:11:10.278 AudioInput: ECHO CANCELLER ACTIVE
<W>2021-03-30 22:11:14.584 Sound file ":/PermissionDenied.ogg" is not a valid audio file, fallback to TTS.
```
The `":/PermissionDenied.ogg" is not a valid audio file` error is triggered when I try to switch to an invalid channel more than twice in direct succession.

Interestingly while audio is working this clicking on an invalid channel twice doesn't trigger that message. But the PermissionDenied sound nevertheless played just once.

**Comment by kolAflash** [comment] 2021-03-30 20:32
Found a **workaround**.
`Mumble -> Configure -> Settings... -> Audio Output -> System`
Switching from `PulseAudio` to `ALSA` (`Device -> [default] ...`) workarounds the problem.

It's even possible to use this to "undo" the bug while it already appeared without restarting Mumble.

And after switching to ALSA (don't forget to `Apply`) it's also possible to switch back to Pulseaudio and the bug doesn't come back. At least until you apply the settings for the next time...
Returning from ALSA to Pulseaudio looks like this on the console:
```
<W>2021-03-30 22:11:39.042 ALSAAudioOutput: Destroyed
<W>2021-03-30 22:11:39.142 AudioInput: Opus encoder set for VOIP
<W>2021-03-30 22:11:39.142 AudioInput: 45000 bits/s, 48000 hz, 480 sample
<W>2021-03-30 22:11:39.142 PulseAudio: Starting echo: alsa_output.pci-0000_00_14.2.analog-stereo.monitor
<W>2021-03-30 22:11:39.142 PulseAudio: Starting output: alsa_output.pci-0000_00_14.2.analog-stereo
<W>2021-03-30 22:11:39.146 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2021-03-30 22:11:39.148 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 0 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-30 22:11:39.438 QXcbConnection: XCB error: 3 (BadWindow), sequence: 32764, resource id: 16778482, major code: 40 (TranslateCoords), minor code: 0
<W>2021-03-30 22:11:40.984 AudioInput: Initialized mixer for 1 channel 48000 hz mic and 1 channel 48000 hz echo
warning: The VAD has been replaced by a hack pending a complete rewrite
<W>2021-03-30 22:11:40.993 AudioInput: ECHO CANCELLER ACTIVE
```

**Comment by Krzmbrzl** [comment] 2021-03-31 08:59
I also saw this happening on my laptop whereas on my desktop the bug does not show. So I am onboard with the hardware-dependency thesis..

So this seems to be related to PulseAdudio. Intersting :thinking: 

> And after switching to ALSA (don't forget to Apply) it's also possible to switch back to Pulseaudio and the bug doesn't come back. At least until you apply the settings for the next time...

So you performed the following steps?
1. Start Mumble (audio system is at PulseAudio)
2. Open Settings
3. Click `Apply` (or `Ok`?)
4. Sound is gone
5. (Open settings again)
6. switch to ALSA
7. Click `Apply` (or `ok`?)
8. Sound is back
9. (Open settings again)
10. Switch back to PulseAudio
11. Click `Apply` (or `Ok`?)
12. Sound is still there
13. (Open settings again)
14. Hit `Apply` (`Ok`?) again
15. Sound is gone again

Is this correct?

**Comment by kolAflash** [comment] 2021-04-24 11:49
@Krzmbrzl Yes, that is exactly correct.

**Comment by WGH-** [comment] 2021-09-19 00:58
I can reproduce this bug on Mumble 1.3.4 / PulseAudio 13.0. Clicking either "Apply" or "OK" breaks the audio _most_ of the time completely until Mumble is restarted. Very rarely it doesn't break, and very rarely it comes back after a second.

**Comment by WGH-** [comment] 2021-09-19 01:08
I've tried increasing PulseAudio logging level (`-v`).

PulseAudio logs new connection when Mumble is started, but it doesn't logs anything when "Apply" is pressed, suggesting that Mumble doesn't reopen PulseAudio connection.

When audio does come back after a while, the following warning is printed:
```
I: [alsa-sink-ALC3232 Analog] alsa-sink.c: Scheduling delay of 1.76 ms > 1.00 ms, you might want to investigate this to improve latency...
I: [alsa-sink-ALC3232 Analog] alsa-sink.c: Underrun!
I: [alsa-sink-ALC3232 Analog] alsa-sink.c: Increasing minimal latency to 4.00 ms
```

But it's hard to tell whether this info is useful in any way.

**Comment by Krzmbrzl** [comment] 2021-09-19 14:55
Yeah this seems to support my suspicion that Mumble's audio thread hangs up while performing the restart which means the reconnect never happens

**Comment by WGH-** [comment] 2021-09-23 19:04
I think I kinda figured it out.

There's is a scenario when `write_callback` is called, `PulseAudioOutput` object is not not present, and `write_callback` returns without writing anything. This indeed might happen when settings are applied. Apparently, the write callback is edge-triggered rather than level-triggered, and it won't be called again if you fail to write enough data to fill the buffer.

This is apparently a known issue (I'm not saying "bug", because this might be working as intended):
* https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/1132
* https://lists.freedesktop.org/archives/pulseaudio-discuss/2015-April/023605.html

i tried this bullshit fix, and it works:
```diff
diff --git a/src/mumble/PulseAudio.cpp b/src/mumble/PulseAudio.cpp
index 521ea1e73..a99f5c510 100644
--- a/src/mumble/PulseAudio.cpp
+++ b/src/mumble/PulseAudio.cpp
@@ -566,15 +566,17 @@ void PulseAudioSystem::write_callback(pa_stream *s, size_t bytes, void *userdata
 	PulseAudioSystem *pas = reinterpret_cast< PulseAudioSystem * >(userdata);
 	Q_ASSERT(s == pas->pasOutput);
 
+	const auto &pa = pas->m_pulseAudio;
+
 	AudioOutputPtr ao     = Global::get().ao;
 	PulseAudioOutput *pao = dynamic_cast< PulseAudioOutput * >(ao.get());
 
 	if (!pao) {
+		unsigned char buffer[bytes] = {};
+		pa.stream_write(s, buffer, bytes, nullptr, 0, PA_SEEK_RELATIVE);
 		return;
 	}
 
-	const auto &pa = pas->m_pulseAudio;
-
 	const pa_sample_spec *pss = pa.stream_get_sample_spec(s);
 	const pa_channel_map *pcm = pa.stream_get_channel_map(pas->pasOutput);
 	if (!pa.sample_spec_equal(pss, &pao->pss) || !pa.channel_map_equal(pcm, &pao->pcm)) {
```

I know almost nothing about computer audio and audio APIs, so i don't think this is the proper fix. Maybe the proper fix is somehow restart the "callback loop" once `PulseAudioOutput` is back again?

**Comment by WGH-** [comment] 2021-09-23 19:07
Maybe the bug is that the PulseAudio connection and streams are preserved during audio restart, leading to some weird edge cases, and they should've been recreated instead.

**Comment by Krzmbrzl** [comment] 2021-09-23 19:22
Oh that is interesting. Thanks for sharing! I'll  have to look into this once I have some more time again - I can test it on my laptop where this problem occurs quite often

**Comment by tati1454** [comment] 2022-01-19 08:34
I'm having the same issue, also when I try to do the workaround of changing the backend to ALSA mumble just freezes and even after waiting for 5 minutes it still doesn't come back.

**Comment by stickman89** [comment] 2022-05-07 13:55
Same issue for me to. As soon as you apply settings audio is lost. Other person can still hear your mic though. No idea if this will ever get solved, or if it has already been resolved in latter versions... 1.3.4-1 seems to be the only version available for Ubuntu 21.10 .  I did begin to build, but the dependency qt5-default isn't available on Ubuntu. So, kinda lost interest at the first hurdle.

**Comment by Krzmbrzl** [comment] 2022-05-07 14:15
>  if it has already been resolved in latter versions

It wasn't

**Comment by stickman89** [comment] 2022-05-07 14:32
> > if it has already been resolved in latter versions
> 
> It wasn't

T'is for me. Just built it. No more loss of audio after changing setting(s).

**Comment by Krzmbrzl** [comment] 2022-05-07 14:37
Very interesting :eyes: 
We certainly didn't add any explicit fix though - guess you were lucky :sweat_smile:

**Comment by stickman89** [comment] 2022-05-07 14:46
> Very interesting eyes We certainly didn't add any explicit fix though - guess you were lucky sweat_smile

Proof is in the pudding: https://youtu.be/OHogOLaVNcU

**Comment by Hartmnt** [comment] 2023-01-24 19:43
This is definitely still happening in 1.5 RC albeit maybe less frequently.

**Comment by Krzmbrzl** [comment] 2023-01-25 18:25
For me this issue was hardware/system dependent. On my old laptop, this would happen almost always whereas on my current system this has yet to happen to me :shrug:

**Comment by Hartmnt** [comment] 2023-01-26 17:47
> For me this issue was hardware/system dependent. On my old laptop, this would happen almost always whereas on my current system this has yet to happen to me shrug

This is most likely a PulseAudio issue. Are you maybe running Pipewire on your new system? Anyway I think the user WGH- was probably onto something there. I might try this and see, if it fixes the problem for me.

**Comment by Hartmnt** [comment] 2023-01-30 20:28
So I tried the fix @WGH- provided, and it seems to work for me. (I have yet to encounter the bug while repeatedly pressing apply in the settings).

I have opened #6051 for this.

**Closed** 2023-02-02 20:40 UTC
Labels: client, audio, bug
