### ISSUE TITLE
Mumble needs a config switch.

### ISSUE THREAD

**Issue by zBeeble42** [mumble-voip/mumble#4343] opened 2020-07-03 19:50 UTC
**Context**
Anyone wanting to run different mumbles for different purposes.

**Describe the feature you have in mind**
Either "mumble --config foo.ini" OR "mumble --cfgdir=C:\foo"

**Describe alternatives you've considered**
I've looked at available bots, I'm currently starting mumble with -m and -n for the 2nd and 3rd instance.  This is imperfect because there are about 10 parameters that change between the instances.  Changing configurations or quitting out-of-order leads to forgotten or missed settings changes.

**Additional context**
What am I doing?  I'm a DM for several D&D campaigns.  I have music, audio soundscapes, sound effects ... and of course my voice.  I have players with all kinds of challenges from ear-and-perception problems to abhorrently bad internet.  I produce a very custom soundscape, but I also value their ability to set their own level (in mumble) for each of these classes of audio --- to suit their own abilities (both physical an technical).

I dropped in IRC and someone immediately suggested a music bot.  Cool-ish, but doesn't really apply.  Only one of my three or four audio streams could be encapsulated as a playlist.  But all of my problems (W.R.T. mumble) would be solved by being able to start mumble with a given config file.

It would also be cool _if_...
- mumble would also save to the given file or directory so that adjustments in-interface would rewrite the file.
- one of the arguments could start mumble without GUI.
- (extra credit) ... if someone could poke a running mumble to reopen it's GUI (this could be done with a tray icon on winblows)

**Comment by Popkornium18** [comment] 2020-07-03 20:03
> mumble would also save to the given file or directory so that adjustments in-interface would rewrite the file.

That would not only be cool, but necessary. I would expect an application to save to the specified config, if I specify one.
It would also be necessary to use a different sqlite database. I don't know if that should be a seperate flag, because it would make little to no sense to use a different config but the same database.

Maybe we could make `--configfile`  require that a separate sqlite DB is specified with `--db` and vice versa.

**Comment by toby63** [comment] 2020-07-04 16:03
I am quite sure this is a duplicate.

**Comment by Krzmbrzl** [comment] 2020-07-04 17:07
It is indeed a duplicate of #3953 - thanks for pointing that out :+1:

**Closed by Krzmbrzl** 2020-07-04 17:07 UTC
