### ISSUE TITLE
[Bug] Minimizing Mumble in a call can effectively crash mumble

### ISSUE THREAD

**Issue by delvh** [mumble-voip/mumble#4862] opened 2021-03-16 13:59 UTC
**Describe the bug**
After "de-minimizing" mumble using either the tray icon or the taskbar on Kubuntu 20.04, mumble can no longer be controlled at all, not even to be closed.
The only way to kill it is using the bash/ task manager and killing it manually (kill signal 15 suffices).
By uncontrollable I mean that no mouse events seem to be fired anymore resulting in an effectively deadlocked program that does not respond to any input.
Additionally, this error does not seem to occur consistently: the only way where this could be reproduced was when being in a voice chat room muted.
There is a possibility that mumble does not get disabled completely but rather for a limited time:
When attempting to reproduce this issue, I think I could reproduce it once for a small time frame (1s) where any mouse events were impossible. Afterwards however, de-minimizing would always perform the expected action. 

**Steps to (hopefully) Reproduce**
1. Open mumble on Kubuntu 20.04
1.1. (Connect to a server and join a voicechat room)
1.2. (Stay Muted)
4. Minimize mumble (either using the minimize button in the top bar or by clicking on the tray icon)
5. Maximize mumble (either using the taskbar or the tray icon)
6. Enjoy no control over mumble anymore ;)
(that were at least the steps taken when encountering this error, I've tried many variations to reproduce it, but it doesn't appear to be reproducible outside of calls)

**Expected behavior**
Mumble should not get disabled.

**Desktop**
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.8.0-44-generic
OS Type: 64-bit

**Comment by Krzmbrzl** [comment] 2021-03-16 16:53
This looks like a duplicate of #3977 to me.

Do you have "minimize to tray" enabled? And when Mumble gets "disabled" does your CPU load go up?

**Comment by delvh** [comment] 2021-03-16 20:51
Yes, minimize to tray is enabled, but unfortunately I do not know whether CPU load went up.

**Comment by Krzmbrzl** [comment] 2021-03-17 08:15
I am pretty sure it does, since all other symptoms match the ones described in #3977.

In there we have noted that having Mumble maximized seems to be a way to reproduce this issue somewhat reliably.

In any case though: Until there is a fix, I recommend disabling "minimize to tray" for the time being. That should work around the issue.

I will close this issue as a duplicate until there are information indicating otherwise :point_up:

**Closed by Krzmbrzl** 2021-03-17 08:15 UTC
