### ISSUE TITLE
Chat messages are no longer received

### ISSUE THREAD

**Issue by DominikTV** [mumble-voip/mumble#3610] opened 2019-02-25 17:38 UTC
Since the latest mumble-server update (debian), messages are no longer sent or received from users. If the user reconnects, everything will work again for some time. 
The same phenomenon occurs with muting: Sometimes a user is mutet although he has unmuted himself.
Happens to all users, so it's not a single-user phenomenon, so I thing it has to do something with the update.
No errors what so ever came up (DebugView)

**Comment by davidebeatrici** [comment] 2019-02-25 18:15
Could you try to tune the `messageburst` and `messagelimit` settings in Murmur's configuration, please?

**Comment by DominikTV** [comment] 2019-02-25 18:25
We've doubled the values (burst: 10 and limit: 5).
We're testing it out tonight.

**Comment by DominikTV** [comment] 2019-02-25 20:10
Update: Nope, still same issue

**Comment by DuckBoss** [comment] 2019-02-26 11:08
What mumble-server version are you using? I had identical issues. 
My setup is running version 1.2.8-2+deb8u1 armhf debian-based build for raspberry pi. Reverting the package to 1.2.8 fixed the issue (pre-rate limiting update). The issues did not persist on 1.2.19 though.

I hope this information might be useful.

**Comment by DominikTV** [comment] 2019-02-26 17:19
@DuckBoss We use 1.2.8-2+deb8u1 too, so we gonna try reverting back to 1.2.8. I hope this will fix the issue, I'll report :)

**Comment by DuckBoss** [comment] 2019-02-27 10:05
I made a post about this in this issue: https://github.com/mumble-voip/mumble/issues/3605
because that update didn't have a reconfigurable ini file. Please check my issue for more information from the mumble developers!

**Comment by DominikTV** [comment] 2019-02-27 10:50
Yeah, the version version 1.2.8-2+deb8u1 was the issue, after reverting back to 1.2.8, we had no issues the whole evening.

**Comment by davidebeatrici** [comment] 2019-02-28 18:16
Closing as duplicate of #3605.

**Closed by davidebeatrici** 2019-02-28 18:16 UTC
Labels: bug, debian, linux, murmur
