### ISSUE TITLE
probably broken on aarch64

### ISSUE THREAD

**Issue by boletus-edulis** [mumble-voip/mumble#5943] opened 2022-10-27 22:00 UTC
### Description

TestPacketDataStream::space() fails on aarch64, due to the fact that by default 'char' is unsigned on arm unlike i386 where 'char' is signed.

Using gcc's '-fsigned-char' makes the test work.

FWIW this is enough to run the server. The client does not seem to work, it can not connect to any server, "Invalid Server" appears on the shell.

### Steps to reproduce

1. login to your aarch64 machine or vm
2. follow the procedure to build mumble
3. make test

### Mumble component

Both

### OS

Linux

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment] 2022-10-28 05:54
Duplicate of https://github.com/mumble-voip/mumble/issues/3845

**Closed by Krzmbrzl** 2022-10-28 05:54 UTC
Labels: bug, triage
