### ISSUE TITLE
Key reservation isn't available under Linux

### ISSUE THREAD

**Issue by suprovsky** [mumble-voip/mumble#3707] opened 2019-06-11 06:35 UTC
Platform: Gentoo Linux x64
Version: Mumble 1.3.0-rc1
Issue: as mentioned in the title, Mumble on Linux doesn't allow users to reserve certain button used for example as push-to-talk button system-wide which means if the button is usable in multiple applications, it gets used in both of them (for instance I use Back button on my mouse which allows application to go to the previous window (in file/internet browsers)) to push-to-talk and it is very frustrating when I accidentally go to the previous website in the browser.

By the way, it works fine under Windows x64.
I just wanted to suggest implementing it in Mumble for Linux if possible, I appreciate your work on that application.

**Comment by Krzmbrzl** [comment] 2020-01-15 09:08
So the problem is that you can't assign a key to one of mumble's shortcuts, if it has been ssigned to a system-wide shortcut?

What desktop environment are you using? I had a similar problem with KDE and KeepassXC. I think the problem in that case is that the system swallows the keypress and thus it never reaches the application.
If this is the case here as well, then I'm afraid there's not really much, Mumble could do. It's simply how these DEs are designed (for all I know that is).

**Comment by suprovsky** [comment] 2020-01-15 23:44
I use Windows and Linux in dualboot on the same machine, so I can show you how does it look like. And I think it's much easier to understand than you think.
![config-windows](https://user-images.githubusercontent.com/13705604/72480857-06483000-37f9-11ea-98c3-ff7058a4b7bf.png)
The interface is in Polish, but it doesn't really matter. Look at the right side - there is a column named Reserwuj (that means Reserve). It allows me to reserve a button system-wide, so for instance I use a backward button on the mouse which normally turns back to a last webpage while using web browsers. When I have Mumble opened on Windows, it's only used for push-to-talk. Nothing else.
![config-linux](https://user-images.githubusercontent.com/13705604/72480856-06483000-37f9-11ea-931e-daa87dca1bd7.png)
That column doesn't exist here. That's the problem.

I use the latest version of the XFCE4 on Gentoo.

**Comment by Krzmbrzl** [comment] 2020-01-16 06:40
Okay now I think I understood :)

https://stackoverflow.com/questions/57745399/overriding-system-wide-windows-key-shortcuts-in-qt-app appears to be supporting my initial claim though that this is a non-trivial thing to implement as system-wide shortcuts usually are intercepted by the OS and don't even arrive at the application level. I could imagine that we use some magic on Windows to make this happen and probably nobody has had the time yet to also implement that for Linux (and possibly MacOS).

Thanks for providing the screenshots though. However I can't promise that we'll have the time to fix this any time soon...

**Comment by Krzmbrzl** [comment] 2022-11-27 17:58
Alright. Coming back to this one to update the info here with the snippet that this feature has been removed from Windows with the switch to a new input event backend (that does not support such stuff).
Therefore, currently only macOS has this feature still in place and given how things currently develop in Mumble, that will probably be dropped at some point to.

Therefore, I'll close this as wontfix. In general I believe that reserving shortcuts system-wide only works (well) if the shortcuts themselves are registered to the host system, which itself might not necessarily be desirable...

**Closed by Krzmbrzl** 2022-11-27 17:58 UTC
Labels: client, linux, enhancement
