### ISSUE TITLE
Can't change installation folder on WIndows

### ISSUE THREAD

**Issue by metapone** [mumble-voip/mumble#5439] opened 2022-01-17 15:04 UTC
### Description

After uninstalling Mumble, when I try to install the newest version there are no way to change the installation directory. Running the x64 install file pops up an EULA page with an `Install (A)` button and no `Advanced` or `Configure path` option.

### Steps to reproduce

Download Mumble installer for Windows x64 version 1.4.230 and run.

### Mumble version

1.4.230

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment] 2022-01-17 16:10
Duplicate of #4702

**Closed by Krzmbrzl** 2022-01-17 16:10 UTC
Labels: bug, triage
