### ISSUE TITLE
[Solved but exploring reason]Mumble server start failed due to failed opening sqlite db file

### ISSUE THREAD

**Issue by jobber2955** [mumble-voip/mumble#5618] opened 2022-04-08 09:36 UTC
### The issue

Could not start mumble server in container, says ```ServerDB: Failed initialization: unable to open database file Error opening database```, but ```-supw``` could create db file.

##### Dockerfile:
```
FROM ubuntu:latest

WORKDIR /usr/bin/mumble-server

COPY . .

RUN cp ./mumble-server.ini /etc/mumble-server && \
	apt-get update && \
	apt-get install --no-install-recommends -y \
		libcap2 \
		libzeroc-ice3.7 \
		'^libprotobuf[0-9]+$' \
		'^libgrpc[0-9]+$' \
		libgrpc++1 \
		libavahi-compat-libdnssd1 \
		libqt5core5a \
		libqt5network5 \
		libqt5sql5 \
		libqt5sql5-mysql \
		libqt5sql5-psql \
		libqt5sql5-sqlite \
		libqt5xml5 \
		libqt5dbus5 \
		ca-certificates &&\
	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \
	adduser --disabled-password --gecos "" mumble-server && \
	chown mumble-server: /usr/bin/mumble-server && \
	chown mumble-server: /usr/bin/mumble-server/*
	
USER mumble-server

CMD ["sh", "./presist_mumble_server.sh"]
```

##### ```mumble-server.ini```'s content(comments are deleted):
```
database=mumble-server.sqlite
ice="tcp -h 127.0.0.1 -p 6502"
logfile=mumble-server.log
pidfile=mumble-server.pid
welcometext="<h>Welcome</h>"
port=64738
host=example.com
serverpassword=
bandwidth=256000
timeout=30
users=1024
usersperchannel=0
messageburst=25
messagelimit=5
allowping=true
opusthreshold=100
channelnestinglimit=5
channelcountlimit=128
defaultchannel=0
rememberchannel=true
textmessagelength=10240
imagemessagelength=2048000
allowhtml=true
logdays=31
registerName=example
registerPassword=examplePassword
registerUrl=https://example.com
registerHostname=example.com
registerLocation=US
bonjour=True
sslCert=fullchain.pem
sslKey=privkey.pem
uname=mumble-server
obfuscate=false
certrequired=True
sendversion=True
suggestPositional=False
suggestPushToTalk=False
autobanAttempts=15
autobanTimeframe=60
autobanTime=30
[Ice]
Ice.Warn.UnknownProperties=1
Ice.MessageSizeMax=65536

```

##### ```presist_mumble_server.sh```'s content:
```
./mumble-server -ini "./mumble-server.ini" -supw "superuserpassword"
./mumble-server -ini "./mumble-server.ini"
while true
do
  sleep 3600
done
```

#### The issues
Behavior descrition by steps of ```presist_mumble_server.sh```
```Line #1```: mumble-server could create a sqlite db file and exit successfully.
```Line #2```: mumble-server could not be able to start the server. Error is ```ServerDB: Failed initialization: unable to open database file Error opening database```

#### File premission in ```/usr/bin/mumble-server(the WORKDIR in Dockerfile)```
```
mumble-server@7be978819e10:/usr/bin/mumble-server$ ls -la
total 2912
drwxr-xr-x 1 mumble-server mumble-server    4096 Apr  8 09:21 .
drwxr-xr-x 1 root          root             4096 Apr  8 09:20 ..
-rwxrwxr-x 1 mumble-server mumble-server     744 Apr  8 09:19 Dockerfile
-rw-rw-r-- 1 mumble-server mumble-server     231 Apr  8 07:11 build.sh
-rw------- 1 mumble-server mumble-server    5593 Apr  8 09:19 fullchain.pem
-rwxrwxr-x 1 mumble-server mumble-server 2808936 Apr  8 06:39 mumble-server
-rwxrwxr-x 1 mumble-server mumble-server   15812 Apr  8 09:13 mumble-server.ini
-rw-rw---- 1 mumble-server mumble-server     849 Apr  8 09:21 mumble-server.log
-rw-rw---- 1 mumble-server mumble-server       2 Apr  8 09:21 mumble-server.pid
-rw-r----- 1 mumble-server mumble-server  110592 Apr  8 09:21 mumble-server.sqlite
-rwxr-xr-x 1 mumble-server mumble-server     135 Apr  8 09:07 presist_mumble_server.sh
-rw------- 1 mumble-server mumble-server    1704 Apr  8 09:19 privkey.pem
```

#### ```WORKDIR``` premission
```drwxr-xr-x 1 mumble-server mumble-server    4096 Apr  8 09:21 mumble-server```

### Mumble version

1.4.230

### Mumble component

Server

### OS

Linux

**Comment by jobber2955** [comment] 2022-04-08 09:38
My guess is some kind of premission issue, but after ```exec``` into the container and manually ```chown``` all files, it still failed to open db file

**Comment by jobber2955** [comment] 2022-04-08 09:53
Digging into mumble-server's source code, i found that the error is generated at line#119~line#166 in ```mumble/src/murmur/ServerDB.CPP```, for convience, i post the code below

```
if (Meta::mp.qsDBDriver == "QSQLITE") {
		if (!Meta::mp.qsDatabase.isEmpty()) {
			db->setDatabaseName(Meta::mp.qsDatabase);
			found = db->open();
		} else {
			QStringList datapaths;
			int i;

			datapaths << Meta::mp.qdBasePath.absolutePath();
			datapaths << QDir::currentPath();
			datapaths << QCoreApplication::instance()->applicationDirPath();
			datapaths << QDir::homePath();

			for (i = 0; (i < datapaths.size()) && !found; i++) {
				if (!datapaths[i].isEmpty()) {
					QFile f(datapaths[i] + "/murmur.sqlite");
					if (f.exists()) {
						db->setDatabaseName(f.fileName());
						found = db->open();
					}
				}
			}

			if (!found) {
				for (i = 0; (i < datapaths.size()) && !found; i++) {
					if (!datapaths[i].isEmpty()) {
						QFile f(datapaths[i] + "/murmur.sqlite");
						db->setDatabaseName(f.fileName());
						found = db->open();
					}
				}
			}
		}
		if (found) {
			QFileInfo fi(db->databaseName());
			qWarning("ServerDB: Opened SQLite database %s", qPrintable(fi.absoluteFilePath()));
			if (!fi.isWritable())
				qFatal("ServerDB: Database is not writable");
		}
	} else {
		db->setDatabaseName(Meta::mp.qsDatabase);
		db->setHostName(Meta::mp.qsDBHostName);
		db->setPort(Meta::mp.iDBPort);
		db->setUserName(Meta::mp.qsDBUserName);
		db->setPassword(Meta::mp.qsDBPassword);
		db->setConnectOptions(Meta::mp.qsDBOpts);
		found = db->open();
	}
```

And in this block of code:
```
for (i = 0; (i < datapaths.size()) && !found; i++) {
				if (!datapaths[i].isEmpty()) {
					QFile f(datapaths[i] + "/murmur.sqlite");
					if (f.exists()) {
						db->setDatabaseName(f.fileName());
						found = db->open();
					}
				}
			}

			if (!found) {
				for (i = 0; (i < datapaths.size()) && !found; i++) {
					if (!datapaths[i].isEmpty()) {
						QFile f(datapaths[i] + "/murmur.sqlite");
						db->setDatabaseName(f.fileName());
						found = db->open();
					}
				}
			}
```
It seems that if mumble-server didn't found the default ```murmur.sqlite```, it will check for all possible path + ".murmur.sqlite" rather than the filename/path defined in ```mumble-server.ini```. Could be wrong, I'm not familiar with ```C```

**Comment by Krzmbrzl** [comment] 2022-04-08 09:58
When the database has been specified in the config, this code path here should be taken:
https://github.com/mumble-voip/mumble/blob/73d8a4d5dbd2c45bd141518bb8b9a2ad796fde1f/src/murmur/ServerDB.cpp#L120-L122

Could you post the full console output generated by starting the Mumble server?

**Comment by jobber2955** [comment] 2022-04-08 10:01
@Krzmbrzl Sorry for misleading comments, and here's the full output

##### with ```-supw```(only set superuser password then exit)
```
2022-04-08 09:58:53.931 SSL: OpenSSL version is 'OpenSSL 1.1.1f  31 Mar 2020'
2022-04-08 09:58:53.931 Initializing settings from /usr/bin/mumble-server/mumble-server.ini (basepath /usr/bin/mumble-server)
2022-04-08 09:58:53.939 Binding to address 124.221.31.112
2022-04-08 09:58:53.940 MetaParams: Adding 2 intermediate certificates from certificate file.
2022-04-08 09:58:54.238 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
2022-04-08 09:58:54.268 ServerDB: Opened SQLite database /usr/bin/mumble-server/murmur.sqlite
2022-04-08 09:58:54.268 ServerDB: Using SQLite's default rollback journal.
2022-04-08 09:58:55.255 Performed initial PBKDF2 benchmark. Will use 16000 iterations as default
2022-04-08 09:58:55.256 Generating new tables...
2022-04-08 09:58:55.291 Superuser password set on server 1
```

### without ```-supw```(normal start up)
```
<X>2022-04-08 09:58:55.303 SSL: OpenSSL version is 'OpenSSL 1.1.1f  31 Mar 2020'
<W>2022-04-08 09:58:55.303 Initializing settings from /usr/bin/mumble-server/mumble-server.ini (basepath /usr/bin/mumble-server)
<W>2022-04-08 09:58:55.304 Binding to address 124.221.31.112
<C>2022-04-08 09:58:55.305 MetaParams: Adding 2 intermediate certificates from certificate file.
<W>2022-04-08 09:58:55.573 MetaParams: TLS cipher preference is "TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<F>2022-04-08 09:58:55.604 ServerDB: Failed initialization: unable to open database file Error opening database
```

**Comment by Krzmbrzl** [comment] 2022-04-08 10:59
> Opened SQLite database /usr/bin/mumble-server/murmur.sqlite

It seems like the `-supw` invocation doesn't respect the database that is specified in your ini :thinking: :eyes:

**Comment by jobber2955** [comment] 2022-04-08 12:07
> > Opened SQLite database /usr/bin/mumble-server/murmur.sqlite
> 
> It seems like the `-supw` invocation doesn't respect the database that is specified in your ini 🤔 👀

Sorry, that was my testing about whether setting database to murmur.sqlite(which is written in the code). In fact it does respect the .ini config file

**Comment by jobber2955** [comment] 2022-04-08 12:24
Further more, I found that if i create a test dir(owner are the same: mumble-server) and move mumble-server to it, then just exec the mumble-server, everything works fine.

**Comment by Krzmbrzl** [comment] 2022-04-08 13:01
Have you tried removing the `uname` option from your config file? You don't Seemeilen start the server as root, so that shouldn't be needed anyway.

Another thing to try is to use the `-fg` argument when starting the server. This prevents it from forking and instead causes it to run in the foreground.

**Comment by jobber2955** [comment] 2022-04-09 06:52
@Krzmbrzl I've solved this problem. And here's my step:
1. Removing uname option
2. Removing ```while true``` option in the shell script
3. Add ```-fg``` argument
##### After doing these 3 steps, I successfully pass the ```open and load db file``` stage. But another problem came out: ```mumble-server``` could not bind the correct ```host```(I've tested, for example, specify ```host``` to ```google.com```, ```mumble-server``` will still bind to self public ip, tested on my cloud-server and local machine, both bind to self ip), So ```step 4``` is the solution(I inspect the image that pull from official docker hub and exec into it, then I check the config file and log, finally I found the solution)
4. Leave ```host``` config to empty, so that ```mumble-server``` could bind to 0.0.0.0:64738, then it will work.

But here are some question i couldn't figure out:
1.How ```mumble-server``` knows it's host machine's public ip even if it's in a container and allocated a ip only available inside the docker(172.0.0.X)? Is it request some api to get a real public ip?
2.Is this ```host``` argument issue a bug or intended?
3.It seems that ```mumble-server``` didn't respect the ```uname```'s comment ```If Murmur is started as root, which user should it switch to? This option is ignored if Murmur isn't started with root privileges.``` or something else?

For question3, Here's my thought:
IMO, I don't think ```-fg``` sovled the problem. At the ```Dockerfile``` I'm using ```USER mumble-server```, so the container won't start with user ```root```, And ```uname``` should be ignored(Maybe it's ignored, just something else goes wrong). But the result is that ```mumble-server``` could not be able to read/write db file(May be a premission issue). After I comment the ```uname``` argument, everything goes well and no issue came out, DB, SSL, Connect and all other stuff I specified in the config file are correct. So what happen here....

#### Finally, thanks for answering me this fast and providing such a great open-source software, and sorry for my lack of ```C```knowledge and could not be able to doing that much help. But if you need a test example, I could sent you all the files that included in building the image for debugging.

If nothing else, I would close this issue after 24 Hour

**Comment by Krzmbrzl** [comment] 2022-04-09 07:28
Great to hear it's working now! :+1:

1. I think it doesn't need to _know_ anything as the public IP is simply a property of Uhr machine the Docker image is running on. You just have to tell Docker which ports to forward and open and that should be about it.
2. I believe this just has to do with how Docker works. I think by default it only allows very specific connections to the outside and thus using anything else for `host` causes issues when run from within Docker
3. That is indeed interesting. I'm not entirely sure what is going on there. Did you test only changing this specific config without changing anything else? And then it would work when not using `uname` but wouldn't when using it? In that case, this appears to be a bug :thinking:

**Comment by jobber2955** [comment] 2022-04-09 07:42
I'm just curisou about how ```mumble-server``` knows the real public ip, because when I exec into the container and run ```ifconfig``` I can only see 127.0.0.1(localhost) and 172.0.0.X(Docker's internal IP). But in ```mumble-server```'s log I can see it ```Bind to XXX.XXX.XXX.XXX:64738``` which is the host machine's real public ip. Of course expose the ```64738``` port both on TCP&UDP is necessary(UDP is for udp-ping and voice transfer, but voice transfer will fallback to TCP if UDP is not available).

And yes, I've tested only ```uname``` changed will cause it un-usable. But of course, in a container. There should be more than```mumble-server```, for example, docker's ```COPY``` command will cause the files' owner to root. And it seems that ```WORKDIR``` the same. So I'm thinking this is still a premission issue.

**Comment by Krzmbrzl** [comment] 2022-04-09 07:57
Good question - No idea where it gets the actual IP from ^^

I'll have to look at the code for the uname handling. This might also end up being a bug in Mumble 👀

**Comment by Krzmbrzl** [comment] 2022-04-09 17:33
> I'll have to look at the code for the uname handling

For reference, these are the relevant code parts:

https://github.com/mumble-voip/mumble/blob/0e321ebc15f2851316df06dce992a8381e18b2f1/src/murmur/Meta.cpp#L327-L347

https://github.com/mumble-voip/mumble/blob/0e321ebc15f2851316df06dce992a8381e18b2f1/src/murmur/main.cpp#L493-L495

https://github.com/mumble-voip/mumble/blob/0e321ebc15f2851316df06dce992a8381e18b2f1/src/murmur/UnixMurmur.cpp#L267-L306

Given that you neither had the `Successfully switched to uid` message nor any of the `Failed to xy` messages in your log, it seems that the ignoring of the `uname` option did indeed work as intended. However, that makes your observation that seemingly this option affects the outcome even more confusing :thinking: 

Could you check (and post) the directory permissions of all segments in `/usr/bin/mumble-server` starting from `/`?

Btw.: Where do you get the server executable from? I don't see it being built in your Dockerfile :eyes:

**Comment by jobber2955** [comment] 2022-04-11 02:55
I build the executable myself, following the instruction from [HERE](https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md).

And I re-tested the example, found that it is the argument ```-fg``` that causing the issue.
Here's my setup:
1. ```mumble-server.ini``` has an uncommented ```uanme``` argument, and set to user ```mumber-server```
2. ```./mumble-server -ini mumble-server.ini -fg``` work all good
3. ```./mumble-server -ini mumble-server.ini``` will generate the error

**Comment by jobber2955** [comment] 2022-04-11 02:57
It's a little bit out of my expectation. Why a simple foreground argument will infect the premission?

BTW here are my premissions of all segments:
```/usr```
drwxr-xr-x   1 root root 4096 Apr  5 04:59 usr
```/usr/bin```
drwxr-xr-x 1 root root 4096 Apr 11 02:49 bin
```/usr/bin/mumble-server```
drwxr-xr-x 1 mumble-server mumble-server    4096 Apr 11 02:52 mumble-server

**Comment by Krzmbrzl** [comment] 2022-04-11 05:35
That is indeed a good question :thinking:

The permissions appear fine, btw.

**Comment by jobber2955** [comment] 2022-04-14 05:42
If there's no other things to do, I will close this issue 24 hours later

**Comment by Krzmbrzl** [comment] 2022-04-14 06:10
Yeah, idk. I still have the feeling that this is some Docker-specific weirdness we are encountering here and since we at least figure out how to prevent it, let's just close the issue for now :+1:

**Closed by Krzmbrzl** 2022-04-14 06:10 UTC
Labels: support
