### ISSUE TITLE
Echo cancellation settings not saved

### ISSUE THREAD

**Issue by fedetft** [mumble-voip/mumble#4761] opened 2021-02-14 22:26 UTC
Just downloaded and built the last development version of Mumble, and it looks like if I close and reopen it, the echo cancellation settings is lost and defaults back to "Disabled".

I tried only on Linux, don't know if it occurs on other platforms.

**Steps to Reproduce**
1. Build the latest Mumble development version
2. Open Mumble and open Configure > Settings > Audio Processing and select Mixed echo cancellation for example
3. Close and reopen Mumble
4. Check the echo cancellation settings

The expected behavior is that the setting should be preserved, the observed behavior is that it defaults back to "Disabled".

**Comment by fedetft** [comment] 2021-02-14 22:38
Seems to have been introduced by  #4694, I compiled 51c6880414173867a5d9f18146512d8def35787e and the problem is not there anymore.

Also, the first time I ran Mumble after compiling it it immediately had echo cancellation enabled. This suggests me the issue is in reading the configuration, not in writing it.

**Comment by Krzmbrzl** [comment] 2021-02-15 08:31
Yep turned out that there were a few regressions with regards to the echo cancellation settings that were introduced by that PR. They should be fixed by #4762 though.

**Comment by fedetft** [comment] 2021-02-15 21:25
Wow, that's a fast response, thanks!
I tried building the latest version, with commit message "Merge pull request #4762: Fix echo cancellation setting not saved", but the issue seems to persist though, still defaulting to disabled at every startup.

**Comment by fedetft** [comment] 2021-02-15 21:29
I looked online but it seems I can't reopen the issue as github disallows it if it was closed by a project collaborator.

**Comment by Krzmbrzl** [comment] 2021-02-16 06:37
Hm I just tested some more and it seems like this issue is specific to the mixed option. For multichannel the logic works as expected :eyes:

**Comment by Krzmbrzl** [comment] 2021-02-16 06:48
Okay I figured it out. Turns out I fixed the issue and then partially broke it again when trying to make sure the old settings were not lost by the change to the new echo cancel options :sweat_smile:

#4767 fixes that again

**Closed** 2021-02-16 08:56 UTC
Labels: bug, client

**Comment by fedetft** [comment] 2021-02-19 13:36
Works now, thanks!
