### ISSUE TITLE
PC register does not match crashing frame (0x0 vs 0x107EBFCD8) 

### ISSUE THREAD

**Issue by AmandaSenpai** [mumble-voip/mumble#6291] opened 2023-12-28 23:01 UTC
### Description

Mumble crushes on changing audio devices.  My guess is the error when it tries parsing the audio resources, causes it to list the resources twice.

### Steps to reproduce

Open Mumble and change the audio type.

### Mumble version

1.5.517

### Mumble component

Client

### OS

Linux

### Reproducible?

Yes

### Additional information

 System Version:	macOS 14.3 (23D5033f)   Kernel Version:	Darwin 23.3.0

### Relevant log output

```shell
See txt file..
```

### Screenshots

[Translated_Report.txt](https://github.com/mumble-voip/mumble/files/13789909/Translated_Report.txt)

**Comment by Krzmbrzl** [comment] 2023-12-31 12:40
Duplicate of #6041

**Closed by Krzmbrzl** 2023-12-31 12:40 UTC
Labels: bug, triage
