### ISSUE TITLE
Overlay and Eve Online

### ISSUE THREAD

**Issue by minshayla** [mumble-voip/mumble#1580] opened 2015-02-21 23:04 UTC
I have seen the issues that Eve Online wasn't working with 1.3.0~537 and the overlay for either DX9 or DX11.  I just upgraded to 1.3.0~540~gedd5509~snapshot and it is working with DX9 but not with DX11.  I have read that this should be working with DX11 am I missing something?  Win Pro 8.1 x64.

**Comment by Attoy** [comment] 2015-02-22 02:41
Sorry to hijack your issue, do you confirm overlay will work on EVE DX9 running the 1.3.0~540 version?
Thanks.

**Comment by minshayla** [comment] 2015-02-22 02:50
Yes EVE DX9 worked with 1.3.0~540 overlay for me, unfortunately I didn't have time to verify there were no crash issues.  I will check for this issue tomorrow.

**Comment by Attoy** [comment] 2015-02-22 10:52
I tried the overlay 1.3.0~540 (32bit version) on EVE DX9 with no success tho ; still doesn't show :(

**Comment by Kissaki** [comment] 2015-02-27 23:11
My test account has been disabled it seems, so I can’t test unfortunately …

**Comment by Kissaki** [comment] 2015-02-27 23:25
Actually Overlay displays fine in the main menu.
Mumble 1.3.0~540. Eve 8.52.865562.

This is a duplicate of #1560

**Comment by Attoy** [comment] 2015-02-28 12:06
I completely deleted it and reinstalled it.
Mumble 1.3.0~540 32b. Eve 8.52.865562 DX9 overlay does work
Mumble 1.3.0~540 32b. Eve 8.52.865562 DX11 overlay does NOT work
Mumble 1.3.0~540 64b. Eve 8.52.865562 DX9 overlay does NOT work
Mumble 1.3.0~540 62b. Eve 8.52.865562 DX11 overlay does NOT work

**Comment by Kissaki** [comment] 2015-03-01 22:11
Please make sure you have the overlay enabled, and use blacklist with eve not blacklisted.
To debug, place a file named `debugoverlay` (no file extension) next to the `eve.exe`, and download and run [debugview](http://technet.microsoft.com/en-us/sysinternals/bb896647.aspx) alongside.
Could you pastebin a log when running alongside the issue? Preferably filter by the `eve.exe` process.

**Comment by rndmerle** [comment] 2015-04-01 16:07
EVE using DX11.
Using Mumble 1.3.0~567 **64bits** : NOT working
Using Mumble 1.3.0~567 **32bits** : working

**Comment by Attoy** [comment] 2015-08-05 11:21
Just an update , current Eve version 13.07.918607 still closes (crash?) itself when running with Mumble 64bit with the overlay enabled.

**Comment by mkrautz** [comment] 2016-06-25 05:38
GeForce GTX 970, driver 368.39
Windows 10 Pro Insider 1511, build 14332.1001.
Mumble 1.3.0~1372 x64

EVE DX9, and DX11 work fine for me.

Anyone still having problems?

**Comment by mkrautz** [comment] 2016-07-03 20:47
I assume not.

Also, https://github.com/mumble-voip/mumble/issues/1123 was fixed.

Closing this.

If people still have EVE issues - please open a new bug. :-)

I promise an expedited response. :-)

**Closed by mkrautz** 2016-07-03 20:47 UTC
Labels: overlay, windows
