### ISSUE TITLE
Mumble on Arch Linux no longer interfacing directly with kernel input devices

### ISSUE THREAD

**Issue by cbpeckles** [mumble-voip/mumble#1726] opened 2015-06-26 21:12 UTC
As of mumble version 1.2.9, mumble no longer uses the kernel input devices even when they are set to be readable by all.  The previous fixes outlined in https://wiki.archlinux.org/index.php/Mumble#Troubleshooting no longer have any effect.  Rolling back to mumble 1.2.8 fixes this problem.  A post has been made about this on the arch linux forums here: https://bbs.archlinux.org/viewtopic.php?pid=1540013#p1540013

Thanks,

CBPeckles

**Comment by mkrautz** [comment] 2015-06-26 21:16
Caused by https://github.com/mumble-voip/mumble/commit/6edf2c6008805fce41d20e1fe929a178cca417cd

You can re-enable evdev support by adding

    [shortcut/linux/evdev]
    enable = true

to your ini. I think that'd be the syntax, at least.

(Lives in $HOME/.config/Mumble/Mumble.conf)

**Comment by mkrautz** [comment] 2015-06-26 21:17
Oh, and i'd like to add, we don't consider this a bug. You really shouldn't want to use evdev by default for keyboards, at least.

Mice and joysticks should be good.

Maybe we just need to blacklist keyboards for evdev instead?

**Comment by cbpeckles** [comment] 2015-06-26 22:15
Sorry for the bug report.  Didn't do enough research, I should have been
able to find this on my own without taking up your time.  Yes I have the
rule written for my mouse only.  Thanks for the quick response.

**Comment by mkrautz** [comment] 2015-06-27 09:53
I'll close this for now.  If any other issues with blocking evdev in this way come up, please create a new issue. Thanks!

**Closed by mkrautz** 2015-06-27 09:53 UTC

**Comment by ngollan** [comment] 2015-08-20 14:27
There's an issue with saving the setting in some client versions so it will vanish from the config every time you exit the client. If that happens to you, just put the following in your config as well:

    [shortcut/mac]
    suppresswarning = true
