### ISSUE TITLE
Mouse Pointer cannot click anymore after accidentally setting mouse movement/left-click as shortcut

### ISSUE THREAD

**Issue by simplexion-huebner** [mumble-voip/mumble#5194] opened 2021-07-15 11:19 UTC
**Describe the bug**
Mouse cannot click on anything at all once it was accidentally set as a shortcut for Push-To-Talk. Mouse still moves but it is not possible to click/select anything at all anymore. 

**Steps to Reproduce**
1. Select Add to add Shortcut.
2. While it is recording for input move the mouse and click on left mouse button (wireless logitech mouse connected via USB-Dongle).
3. Select "Apply" and "Ok"
4. Mouse pointer hovers and selects items but cannot click on anything at all. Input only possibly with keyboard. Not recommended to try out. Same is for controlling the mouse pointer with the Laptop's touchpad.

**Expected behavior**
The mouse should still be able to work normally after this.
Even moving the mouse is seen as a valid input for a shortcut. I would suggest to maybe not make left mouse click and moving the mouse as valid input.

**Desktop (please complete the following information):**
- Kubuntu 20.04.2 LTS
- Window Manager. kwin_x11
- Mumble (1.3.0+dfsg-1build1)

**Additional context**
Working on Lenovo Yoga X1. External Logitech Mouse and Keyboard connected via USB-Dongle.
When rebooting mouse works for a short time. Using "kwin_x11 --replace" makes the mouse work for a very brief time. Unplugging the USB-Dongle for the Mouse sometimes enables the Laptop's touchpad. After plugging the USB-Dongle back in the mouse works briefly, but then touchpad and mouse do not work again. 
Resetting the Settings to default, deleting the Shortcut, removing/purging Mumble does not solve the issue.

**Comment by Krzmbrzl** [comment] 2021-07-15 13:22
I am unable to reproduce this using current master on KDE Neon (based on Ubuntu 20.04) which I think also uses kwin as the Window manager.

But wait a sec. From your description it seems that you continue to have the issue of the mouse not working properly even if Mumble isn't even running? :eyes:

**Comment by simplexion-huebner** [comment] 2021-07-15 15:20
Yes, I have the issues even when the mumble is not running. Strangely enough it seems to affect only the mouse I used. I had the chance to connect a different mouse and it works. To make sure it is not the mouse itself I tested the mouse on a different computer without having any issues at all. And I can still move the pointer on the screen, only clicking is not working.
When moving the mouse the shortcut appeared as "Mouse 9" if I recall correctly. What I did do was as well use an extra mouse button (the mouse has buttons for "forward and backward") for Push-To-Talk. This worked fine, but then the clicking issues started. 
Thank you for replying so quickly. Can I provide any more information?

**Comment by Krzmbrzl** [comment] 2021-07-15 16:57
Hm... Given that the issue persists when Mumble is not running, I don't see how Mumble could be the cause of that. Our shortcut system works by polling for key events and then checking whether these match any registered shortcuts.
There is no reconfiguring of the host system involved (that I know of) that could cause any permanent changes on the system-level...

The problem must lie somewhere else. Maybe a corrupted driver for that particular mouse?

Are you 100% certain that this issue only appeared once your registered the shortcut in Mumble?

**Comment by JuniorJPDJ** [comment] 2021-07-15 16:59
Try it on mumble 1.4 and let us know if it fixes the issue

**Comment by Krzmbrzl** [comment] 2021-07-15 18:35
> Try it on mumble 1.4 and let us know if it fixes the issue

Only problem with that is that you'd have to self-compile it as you are on Linux and we currently have no working AppImage that we can provide you. Build instructions can be found at https://github.com/mumble-voip/mumble/blob/master/docs/dev/build-instructions/build_linux.md

**Comment by simplexion-huebner** [comment] 2021-07-16 09:25
I will check this soon if it works with mumble 1.4

Further testing with different devices showed that:
- Any other mouse still works flawlessly
- The mouse itself works on a windows machine flawlessly
- As soon as this mouse (Logitech MX Performance) is attached no other mouse works
- Even when booting up from a Kubuntu USB Stick the error shows with this mouse (so it becomes unlikely that is a settings fault), 
- The wireless keybour connected to the same USB Dongle works fine as long as the mouse is turned off
- Even when the mouse is connected to a different USB Dongle it shows the same error

Although I understand that it is extremely unlikely that mumble actually caused this, the error just popped up directly after setting the shortcut in mumble and no other program was running. That's why I pinpointed in this direction, but it more and more seems to be some really weird hardware issue.
So I do apologize but unless mumble has the "superpower" to change something on the mouse itself, which I doubt, this is most likely not an issue with mumble. I appreciate your help nonetheless!

**Comment by Krzmbrzl** [comment] 2021-07-16 09:56
Yeah this definitely sounds like a hardware/driver issue. Maybe Mumble polling for the events for the first time did somehow let the issue surface or something like this 🤷

Do you have Mumble installed on the image you booted from your USB? If not then I think this rules out that Mumble is responsible :thinking:

**Comment by simplexion-huebner** [comment] 2021-07-16 10:02
No, I did not have Mumble installed there. It was a fresh Kubuntu Image. So I agree, that this rules out that Mumble is responsible and it is rather related to hardware/driver issue. This will be fun to solve. :D 
Thanks anyway!!

**Comment by Krzmbrzl** [comment] 2021-07-16 13:18
Alright then I'll close this issue :+1: 

> Thanks anyway!!

No problem. And good luck with finding the root cause of this ;)

**Closed by Krzmbrzl** 2021-07-16 13:18 UTC
