### ISSUE TITLE
Ui becomes unresponsive in Linux under certain circumstances 

### ISSUE THREAD

**Issue by androos** [mumble-voip/mumble#3544] opened 2018-10-28 10:50 UTC
Install from latest git version.
Select option: hide to tray when minimized.
Open connection Dialog. Minimize to tray bei clicking on window button in task bar. 
Mumble is minimized to tray but don't reacts to right / left click. 
Tested in XFCE.

**Comment by ilu33** [comment] 2020-12-25 19:33
Same here, every misclick minimizes to tray and makes mumble unusable without a restart. Disabling "hide to tray" fixes the issue.
Debian 10, XFCE 4.12, Mumble (1.3.0~git20190125.440b173+dfsg-2) from Debian repo. Would updating to 1.3.3 from github fix the problem?

**Comment by Krzmbrzl** [comment] 2020-12-26 09:04
This is a duplicate of #3977 (or actually the other way around but since a lot of info is in #3977, I'll keep using that one as the "original" issue).

> Would updating to 1.3.3 from github fix the problem?

No unfortunately not. I looked into this issue but came to the conclusion that in order to fix it, we probably have to rewrite the entire tray logic (which currently really is a mess). For that I did not have the time though :point_up:

**Closed by Krzmbrzl** 2020-12-26 09:04 UTC
