### ISSUE TITLE
Mumble hangs on interacting with the interface at all

### ISSUE THREAD

**Issue by DoriSai** [mumble-voip/mumble#4613] opened 2020-12-06 03:39 UTC
**Describe the bug**
Every time I open Mumble recently it hangs upon clicking or tabbing in the interface at all.  Using shortcuts I am able to connect directly to a server still but if I so much as click on the client it will hang and stop responding to anything until I force quit it via the Task Manager.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Mumble 1.3.2 and 1.3.3

**Additional context**
I don't know what I can do to show more details, I just use Mumble for some chatting with friends and now I won't be able to unless I can find a fix.  I've tried uninstalling and reinstalling it a couple times and that hasn't fixed it.
Oh it also says "Mumble failed to retrieve version information from the central server."

Ripped the following from the Console file from my latest attempt to open it.

<W>2020-12-05 23:07:27.851 DirectSound: Disabled as WASAPI is available
<W>2020-12-05 23:07:27.852 ASIO: No valid devices found, disabling
<W>2020-12-05 23:07:27.901 G15LCDEngine_lglcd: Logitech LCD Manager not detected.
<D>2020-12-05 23:07:27.905 libopus v1.1.3 from C:/Program Files/Mumble/Versions/1.3.3/opus.dll
<W>2020-12-05 23:07:27.912 CELT bitstream 8000000b from C:/Program Files/Mumble/Versions/1.3.3/celt0.0.7.0.dll
<W>2020-12-05 23:07:27.918 CELT bitstream 80000010 from C:/Program Files/Mumble/Versions/1.3.3/celt0.0.11.0.dll
<W>2020-12-05 23:07:27.920 Theme: "Mumble"
<W>2020-12-05 23:07:27.920 Style: "Lite"
<W>2020-12-05 23:07:27.920 --> qss: ":themes/Mumble/Lite.qss"
<W>2020-12-05 23:07:27.920 Locale is "en_US" (System: "en_US")
<W>2020-12-05 23:07:28.140 Database SQLite: "3.18.0"
<W>2020-12-05 23:07:28.141 Bonjour: Failed to load dnssd.dll
<W>2020-12-05 23:07:28.143 Updating application palette
<W>2020-12-05 23:07:28.314 AudioInput: Opus encoder set for VOIP
<W>2020-12-05 23:07:28.314 AudioInput: 40000 bits/s, 48000 hz, 480 sample
<W>2020-12-05 23:07:28.329 WASAPIInput: Latencies 100000 30000 => 100000
<W>2020-12-05 23:07:28.332 WASAPIOutput: Latencies 100000 30000 => 100000
<W>2020-12-05 23:07:28.386 WASAPIOutput: Output stream format 1
<W>2020-12-05 23:07:28.386 WASAPIOutput: Stream Latency 0 (2880)
<W>2020-12-05 23:07:28.386 WASAPIOutput: Periods 10000us 3000us (latency 0us)
<W>2020-12-05 23:07:28.386 WASAPIOutput: Buffer is 60000us (5)
<W>2020-12-05 23:07:28.387 AudioOutput: Initialized 2 channel 48000 hz mixer
<W>2020-12-05 23:07:28.404 WASAPIInput: Mic Stream format 1
<W>2020-12-05 23:07:28.404 WASAPIInput: Stream Latency 0 (1056)
<W>2020-12-05 23:07:28.415 AudioInput: Initialized mixer for 2 channel 48000 hz mic and 0 channel 48000 hz echo

**Comment by davidebeatrici** [comment] 2020-12-06 05:10
I don't see anything related in the logs.

> Oh it also says "Mumble failed to retrieve version information from the central server."

We recently refactored our main server's configuration, but according to the web server's logs Mumble 1.3.x clients are connecting just fine.

Can you access https://update.mumble.info from your machine?

**Comment by DoriSai** [comment] 2020-12-06 16:06
That link seems to lead to a blank webpage for me.

**Comment by Krzmbrzl** [comment] 2020-12-06 17:42
Yeah that's kinda expected. As long as you don't get an error message when trying to access this site, it means that you can connect.

Is there perhaps a firewall setting that blocks Mumble from accessing this specific site (probably not, but it can't hurt to double-check)?

**Comment by DoriSai** [comment] 2020-12-07 16:11
I can't find anything like that.  Besides, I haven't changed anything major for months and Mumble worked before.  Speaking of which, I just tried it again and the version check error message was gone but the problem with clicking on the interface is still there.   After rebooting the program the error was back again.  I think it's something with the program itself not loading correctly but I can't seem to figure out what might be causing it.

**Comment by Krzmbrzl** [comment] 2020-12-08 08:44
Ah so you used an older version of Mumble that worked fine but then you upgraded and the issue showed?

Maybe you are experiencing a bug caused by a really unfortunate combination in your settings. Have you tried deleting the registry entries for Mumble's settings?
@davidebeatrici do you happen to know where Mumble stores its settings in the registry on Windows?

**Comment by davidebeatrici** [comment] 2020-12-08 18:13
`HKEY_CURRENT_USER\Software\Mumble\Mumble`

**Comment by DoriSai** [comment] 2020-12-09 23:55
The issue started up before I updated, I updated hoping it would fix the issue and the first time I attempted it wouldn't update right.

Before I messed with the registry I tried running it again and it ran smoothly so it seems this bug is intermittent.  I don't know what causes it and I don't know how to check.

**Comment by Krzmbrzl** [comment] 2020-12-11 07:14
So the bug is gone now?

In case it appears again, it would be useful to get the registry sub-tree corresponding to Mumble's settings. Maybe that's enough to reproduce this issue :thinking:

**Comment by Krzmbrzl** [comment] 2020-12-11 07:15
@radioactiveman afaik you are a maintainer of the mumble-git AUR package. Any idea on this issue?

**Comment by DoriSai** [comment] 2020-12-11 17:39
How do you get that?

**Comment by Krzmbrzl** [comment] 2020-12-13 08:52
Have a look at e.g. https://www.technipages.com/windows-10-import-export-registry-keys-from-command-line

**Comment by Krzmbrzl** [comment] 2021-03-25 08:41
Since there was no further response here, I'll close this issue as resoolved

**Closed by Krzmbrzl** 2021-03-25 08:41 UTC
