### ISSUE TITLE
Windows installer tries to close things that shouldn't be closed

### ISSUE THREAD

**Issue by trudnorx** [mumble-voip/mumble#4086] opened 2020-04-20 12:45 UTC
I didn't encounter this before:

![image](https://user-images.githubusercontent.com/42674312/79753074-9d9bb280-8315-11ea-9b6f-8386c2be6e8a.png)

**Comment by Krzmbrzl** [comment] 2020-04-20 13:57
Is this something that keeps happening (even after the computer has been restarted)?

**Comment by trudnorx** [comment] 2020-04-23 18:17
Keeps happening even after restart, it wants to close random stuff when all it should be trying to close is Mumble. Both times it happened I had Mumble github on Firefox though, maybe that confused it since it had the name "Mumble" in the window title?

Win7

**Comment by Krzmbrzl** [comment] 2020-04-23 18:31
Was it always the browser it wanted to close? If so, then I guess the logic is to look into window/application titles for "Mumble" and close the ones that match

**Comment by trudnorx** [comment] 2020-04-23 18:33
> 
> 
> Was it always the browser it wanted to close?

In both cases, it wanted to close both the browser and another unrelated app, the second app was different both times. I don't know how it would behave if the browser didn't have "Mumble" in the window name.

> If so, then I guess the logic is to look into window/application titles for "Mumble" and close the ones that match

Yeah, and such logic if exists should be eliminated, but I tried to find it with no success.

**Comment by Krzmbrzl** [comment] 2020-04-23 18:35
I think that this is not implemented by us but by the WiX framework :thinking: 

Could you try and see what happens if you don't have the browser open?

**Comment by trudnorx** [comment] 2020-04-23 18:46
@Krzmbrzl Just tried with 1.3.0 installer instead of 1.3.1 in a Win7 VM open with "Mumble" opened in browser and it didn't try to close anything

**Comment by trudnorx** [comment] 2020-04-23 18:47
Just tried with 1.3.1 installer and not happening either. Maybe this is only on some machines or certain contexts.

**Comment by Krzmbrzl** [comment] 2020-04-23 19:07
In that case I'll close this issue as to my knowledge we aren't actually responsible for this behavior...

**Comment by trudnorx** [comment] 2020-07-13 14:48
Tested on several systems with various new installer versions of Mumble, problem keeps happening. It just wants to close unrelated programs like Firefox for no reason.

**Comment by Krzmbrzl** [comment] 2020-07-13 16:09
I also researched a bit on this issue and it seems like these snippets are responsible for requesting running Mumble instances to be closed:
https://github.com/mumble-voip/mumble/blob/54e313481d2fe2fe36fbd30f55c5f055cbbee615/installer/Product.wxs#L19
https://github.com/mumble-voip/mumble/blob/54e313481d2fe2fe36fbd30f55c5f055cbbee615/installer/Product.wxs#L188

Related SO questions:
https://stackoverflow.com/questions/9822010/wix-close-application-before-uninstall-close-open-applications-message
https://stackoverflow.com/questions/2977551/wixs-utilcloseapplication-extension-doesnt-seem-to-work

And this is the doc on the close-function of WiX: https://wixtoolset.org/documentation/manual/v3/xsd/util/closeapplication.html

----

@trudnorx do the applications that the installer wants to close have `mumble.exe` somewhere in their title or process name?

**Comment by trudnorx** [comment] 2020-07-27 03:58
@Krzmbrzl No.

**Comment by Krzmbrzl** [comment] 2021-05-29 19:30
@ZeroAbility I have the feeling that this is an upstream-issue. Do you agree?

**Comment by ZeroAbility** [comment] 2021-05-29 23:20
> @ZeroAbility I have the feeling that this is an upstream-issue. Do you agree?

It's possible. I'm not sure if there is a plugin or overlay option for Firefox that would keep the mumble.exe process running in the background. That would be my guess since the exe file is defined as `Target=mumble.exe`

If there is an upstream issue with WiX 3, we have some some difficulty reporting it as they have disabled Issues:

https://github.com/wixtoolset/wix3

**Comment by trudnorx** [comment] 2021-05-30 03:13
Note it also seems to close other unrelated things, not only Firefox.

**Comment by ZeroAbility** [comment] 2021-05-30 04:35
> https://github.com/mumble-voip/mumble/blob/54e313481d2fe2fe36fbd30f55c5f055cbbee615/installer/Product.wxs#L188

This describes the action from the Windows Installer perspective:

https://docs.microsoft.com/en-us/windows/win32/msi/installvalidate-action?redirectedfrom=MSDN

Since you said this also happens after a restart, I'm wondering if you would be comfortable sharing what applications start up when you log in. Just so we can rule that out.

**Comment by trudnorx** [comment] 2021-05-30 06:20
None and it happens on multiple machines. It has nothing to do with my particular setup.

**Comment by ZeroAbility** [comment] 2021-05-30 06:59
Does it occur when nothing else is open?

**Comment by Kissaki** [comment] 2021-05-30 10:14
So, I formulated a comment here before, about Mumble overlay injecting into hardware accelerated applications, but I don’t remember why I did not post it.

Any application that is hardware accelerated may be subject to this, as Mumble may(will?) inject into them.
I don’t quite remember on which side the exceptions are evaluated. I think it injects and checks, and then unloads itself again if there is no overlay enabled/applicable for this program(?).

Going just from the list of apps in the screenshot: Firefox does use hardware acceleration, so a (Direct3D?) rendering pipeline.

A program like Process Explorer (Microsoft Sysinternals) can be used to check what DLLs are loaded into the process.

Which overlay exceptions mode are you using? Is Firefox excluded?

What is the Untitled application? Does that use use "hardware acceleration" too?

This mechanism has always been in the installers. It just does not show up if Mumble files are not loaded into other still running processes.

**Comment by Kissaki** [comment] 2021-05-30 10:18
Oh was it because this is when *installing* rather than uninstalling/updating? :P

**Comment by trudnorx** [comment] 2021-05-30 14:16
@Kissaki I don't think it works that way. The installer should only be checking if mumble.exe is open, according to the code. So it's some weird malfunction going on, and not related to the injection system, I believe. And also, Mumble wasn't open, so none of this could possibly be relevant anyway.

> Does it occur when nothing else is open?

No.

**Comment by Kissaki** [comment] 2021-05-30 22:15
Could you clarify whether this is for a fresh install, or uninstalling or updating a mumble installation?

> Can you make sure this mechanism exists in the current code and if so point out where?
> 
> And also, Mumble wasn't open, so could this still be relevant?

This is installer logic, not Mumble program logic. We do not have this logic itself in our source code.

I don't quite remember if this is correct, but I think the client hooks into process spawning/dll loading, and when that happens the overlay dlls are loaded too. So what matters is if the Mumble client was running while at some point when the process was running. If the process was started after Mumble was closed, it should not show up (caused by the Overlay injection).

**Comment by ZeroAbility** [comment] 2021-05-31 02:40
I would check Task Manager after a restart to make sure that `Mumble.exe` is not listed and try the 1.3.x upgrade again without opening anything else. This will rule out if the overlay is attaching to the other processes due to OpenGL/D3D. If it upgrades successfully, then the issue may be related to what @Kissaki is saying regarding the overlay. You could check in `Configure -> Settings -> Overlay` in the Overlay Exceptions tab and see if there are any Allowed launchers or programs that are using the overlay.

**Comment by trudnorx** [comment] 2021-05-31 08:35
I think I've seen the bug occurring with both fresh installs and updates.

I may be wrong, but I think @Kissaki's idea of why the issue occurs is mistaken. The Mumble installer code (as in, Mumble's custom part of it, as opposed to the upstream) _only_ looks for "mumble.exe", and not whether any app it has injected itself on is running. The issue here is that 1) the screen is being displayed when "mumble.exe" is not open at all, 2) the installer is identifying programs that are _not_ "mumble.exe" as the target program to be closed. @Kissaki says that the reason code that identifies injections cannot be pinpointed is that "this is installer logic", but this explanation is not plausible to me. How would the upstream installer know to look for injections, being merely given the instruction to check whether "mumble.exe" is running from the custom Mumble installer code? Is there any evidence that the upstream installer project looks for injections like that, when merely given an .exe name? And what makes the explanation most implausible of all is that I did not have Mumble running _at all_ on one of the machines when this occurred. Granting that such injections may have remained even after closing Mumble (is this really possible?), another thing that is not being explained is why would Firefox and Photoshop be targeted? @Kissaki says this may be because any apps with hardware acceleration will be injected by Mumble, but is this really the case?

In order for this explanation to become truly plausible, it would need to be explained how Wix's "WixCloseApplications" and "CloseApplication" instructions can target injections like that.

> I would check Task Manager after a restart to make sure that Mumble.exe is not listed 

Mumble.exe really was completely closed.

> try the 1.3.x upgrade again without opening anything else

The issue by definition cannot emerge at all if nothing else is open. It would be illogical to test under these conditions.

> You could check in Configure -> Settings -> Overlay in the Overlay Exceptions tab and see if there are any Allowed launchers or programs that are using the overlay.

My overlay was disabled completely. Which, again, makes @Kissaki's explanation implausible.

**Comment by Krzmbrzl** [comment] 2021-05-31 10:52
@trudnorx as far as I can tell we are currently talking about the 1.3.x installer, correct?

Have you checked whether the same still applies to the 1.4.x installer (snapshot)?
I mean after all the 1.3.x installer won't be used much longer as the new one uses a rewritten approach.

**Comment by trudnorx** [comment] 2021-05-31 11:20
It may be hard to test because I am not sure if I can reliably reproduce it. I don't know exactly how it works. So I could try 1.4.x, but if no error is encountered, that's not necessarily a guarantee the error is gone.

**Comment by Krzmbrzl** [comment] 2021-05-31 11:33
Well I would say if it is (seemingly) fixed with 1.4.0 then we can close this again and should it resurface again, we can reopen it again.
Or - and that seems more likely - open a bug report for Wix instead.

**Comment by ZeroAbility** [comment] 2021-05-31 17:45
@trudnorx the 1.4.x project doesn't use the same WiX project. We moved to WixSharp for new releases because the upgrade feature broke when we were testing it. The previous WiX project was old and had a lot of hard defined properties that we did away with. There were properties we also needed to fix that interfered with things like architecture. It was also a goal to ship separate installers for client and server. Because of that, 1.3.x and older installs will need to be uninstalled prior to installing 1.4.x and newer. 

We would be interested to know if this occurs in the new installer. If I recall correctly, we agreed that we would not be formally supporting Windows 7 for 1.4.x and newer but that we would make our best efforts to assist with it. Hopefully, in scenarios where there is an ESR established with Microsoft, or the PC is offline.

**Comment by Krzmbrzl** [comment] 2021-05-31 18:25
> as stated before, WiX has disabled Issues for v.3. We could attempt to mention them on this issue, but we didn't get much feedback from them with regard to the Upgrade process breaking despite following their guidance to enable that.

So they don't have a way to report bugs to them at all? Lol.
Anyway - my main point was: If this is appearing with 1.4.x as well and we don't do anything in our code that does the checking on its own, then this is an upstream issue and as such I'd close this issue here as that would then not be actionable by us :shrug:

**Comment by Kissaki** [comment] 2021-05-31 20:47
> in Mumble's circumstances where Wix is only told to look for "mumble.exe"? Any links to docs?

I think this is a misconception. It's not about what processes refer to mumble.exe. It's about Mumbles overlay DLLs. Those are different files that, as I described earlier, can live longer within other processes even after the Mumble client process exited.

I can’t give any source pointers where this happens though.

**Closed** 2021-06-30 12:27 UTC
Labels: installer, needs-more-input
